### ISSUE TITLE
Use threadpool->ParallelFor instead of Shard

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/addons#1000]
**Describe the feature and the current behavior/state.**
As [Shard](https://github.com/tensorflow/tensorflow/blob/e4f4579e42155801f91156a53970d54a2ba0f54f/tensorflow/core/util/work_sharder.h#L26) is marked as DEPRECATED.
The custom op implementations should use threadpool->ParallelFor instead of Shard.
For example:
``` cpp
    auto worker_threads = *(context->device()->tensorflow_cpu_worker_threads());
    Shard(worker_threads.num_threads, worker_threads.workers, oN * oH * oW,
          cost_per_pixel, work);
```
**Relevant information**
- Are you willing to contribute it (yes/no):yes
- Are you willing to maintain it going forward? (yes/no):yes
- Is there a relevant academic paper? (if so, where):
- Is there already an implementation in another framework? (if so, where):
- Was it part of tf.contrib? (if so, where):

**Which API type would this fall under (layer, metric, optimizer, etc.)**

**Who will benefit with this feature?**

**Any other info.**

**Comment by WindQAQ** [comment]
Sure, feel free to open a PR and ping me :smiley:

**Comment by PSY27** [comment]
i want to help
