### ISSUE TITLE
Update CI tests to run oldest and newest python

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#1024]
So I think this is worth discussing before implementing. We had a break last night because our CI didn't test py35:
#1023 

We can update this to test most recent and oldest python versions, but it'll ~double the CI test time for those jobs. Ultimately we'll be notified of a failure on the nightly CI builds so there's a safety net but comes at the cost of missing nightlies for the day.

**Comment by ulf1** [comment]
Is it possible to tell the sanity-check or formatter for trailing commas in lists?

**Comment by gabrieldemarmiesse** [comment]
@ulf1 running the sanity check with Python 3.5 should be enough.
