### ISSUE TITLE
Use isort in the pre-commit hook

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [tensorflow/addons#1034]
https://github.com/timothycrosley/isort

after the 5.0 release, it will be compatible with black. Do we want to use it?

**Comment by seanpmorgan** [comment]
If we fold it into the pre-commit it seems like a nice addition. Perhaps we wait a bit until black/typing is complete just to limit the amount of formatting changes going on at once. We'll need to wait for 5.0 release anyway

**Comment by seanpmorgan** [comment]
Thinking on this a little more, I'm not sure the workload for reviewing all of these PRs would be worth the effort. Happy to reconsider but closing for now.

**Comment by gabrieldemarmiesse** [comment]
@seanpmorgan isort 5 is out, we use it in my company, and it works very nicely. It's pretty cool not having to think about where you put your imports, similar to how we don't have to think about formatting anymore. 

If we do insert the the tool, it won't be like the black PR hell, I'll do one big PR, and all other contributors will have to fix conflicts themselves, which is easy since it's only ordering imports (running isort again will be enough). I you don't think it's worth the trouble, it's ok :)

**Comment by seanpmorgan** [comment]
Hmmm I lean toward holding off on this until we're able to work through some PR backlog. While it can be done in a single PR it will create conflicts on all ~43 PRs

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
