### ISSUE TITLE
Rename LazyAdamOptimizer to LazyAdam

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/addons#104]
All core optimizers in TensorFlow 2.0 dropped the "Optimizer" suffix: "Adam", "Adadelta", etc. (see the [module overview](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/optimizers)). For consistency, optimizers defined in tensorflow/addons should probably follow the same naming convention.

So I propose to rename `LazyAdamOptimizer` to `LazyAdam`.

**Comment by square-1111** [comment]
Hi @guillaumekln 
Can I work on the issue?
Thank You

**Comment by dynamicwebpaige** [comment]
+1! Would prefer to keep the terminology consistent between TensorFlow Core and addons.

**Comment by shreyashub** [comment]
if nobody is working on it, can I work on it? @seanpmorgan

**Comment by armando-fandango** [comment]
@shreyashub Seems like squadrick's pull request closed this issue.

**Comment by seanpmorgan** [comment]
Yes, but we'll be adding several more good first issues in the near term :)
