### ISSUE TITLE
Replace ops.name_scope by tf.name_scope

### ISSUE THREAD

**Issue by facaiy** [tensorflow/addons#106]
Examples:

https://github.com/tensorflow/addons/blob/8dad6d2f9b8a7d8a6c103249e960185d1f573488/tensorflow_addons/image/distort_image_ops.py#L134

https://github.com/tensorflow/addons/blob/8dad6d2f9b8a7d8a6c103249e960185d1f573488/tensorflow_addons/image/transform_ops.py#L74

We should use tf public API `tf.name_scope`.

**Comment by facaiy** [comment]
ops.convert_to_tensor is also need to be replaced by tf.convert_to_tensor

**Comment by facaiy** [comment]
By the way, it's easy to find all files by running `git grep --name-only 'ops.name_scope'`

**Comment by kyleabeauchamp** [comment]
The suggestion made above `(tf.name_scope(name))` does not work and leads to an exception due to the possibility of `name=None`:

```
/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6480, in __init__
    raise ValueError("name for name_scope must be a string.")
ValueError: name for name_scope must be a string.
```

One possible workaround would be to do ` with tf.name_scope(name):` and cast None -> string.

**Comment by facaiy** [comment]
Good question. We can give it a default value by `with tf.name_scope(name or default_name)` :-)

**Comment by shreyashub** [comment]
@facaiy I would like to work on it

**Comment by shreyashub** [comment]
Sure, I'll work on it. Any tips on how to start?

**Comment by armando-fandango** [comment]
@shreyashub You can begin by cloning the code, running in the docker container as explained on the home page, and once the code works as is, then create your branch, search for all the files with the help of grep command suggested by @facaiy, change the code, and then test it again. Let us know if that helps you start.

**Comment by facaiy** [comment]
Welcome, Shreyas :-) 
And you might want to read our guide for contributor as well: https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md

**Comment by shreyashub** [comment]
@armando-fandango @facaiy Thank you for such a kind and warm welcome.
 I'll proceed as advised and let you know if anything comes up.

**Comment by shreyashub** [comment]
https://github.com/tensorflow/tensorflow/blob/8886c844249703a0dcd79eba53a40bfbd5c11b9f/tensorflow/python/framework/ops.py#L6444
As far as I can see in the tf.name_scope(), it no longer takes default_name and values as arguments. 
To resolve default name we can use `tf.name_scope(name or default_name)` , but I'm confused as to how we can resolve the values part.

**Comment by facaiy** [comment]
@shreyashub Sorry for the delay, I afraid we don't need `values` attribute any more in tf 2.0. 
cc @karmel  Karmel, please correct me if I'm wrong.

**Comment by karmel** [comment]
@facaiy that is my understanding as well.
