### ISSUE TITLE
Got an error very recently for "layers.normalizations". Something related to the "epsilon" variable in the typeguard module.

### ISSUE THREAD

**Issue by davidweioct** [tensorflow/addons#1067]
The code was run in google colab with the following install libraries:

**!pip3 install nilearn
!pip3 install simpleITK
!pip3 install tensorflow-gpu==2.1.0
!pip3 install tensorflow-addons==0.8.1**

**ERROR info:**

File "/usr/local/lib/python3.6/dist-packages/tensorflow_addons/layers/normalizations.py", line 319, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 809, in wrapper
    check_argument_types(memo)
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 670, in check_argument_types
    raise exc from None
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 668, in check_argument_types
    check_type(description, value, expected_type, memo)
  File "/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py", line 598, in check_type
    format(argname, qualified_name(expected_type), qualified_name(value)))
TypeError: type of argument "epsilon" must be int; got float instead

Thank you so much!

**Comment by davidweioct** [comment]
It was running good previously. Not sure if this is due to a recent update.

**Comment by davidweioct** [comment]
I used a work-around solution by simply downgrading to 0.7.1

**Comment by seanpmorgan** [comment]
This is a good catch @davidweioct 
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/layers/normalizations.py#L50
https://www.tensorflow.org/api_docs/python/tf/nn/batch_normalization

Should be a float not integer.

**Comment by failure-to-thrive** [comment]
So isn't it just a change of `int` to `float`?https://github.com/tensorflow/addons/blob/343e7f3276350850f9583d0b53c6d114b6beaaeb/tensorflow_addons/layers/normalizations.py#L78 What's the catch?

**Comment by seanpmorgan** [comment]
> So isn't it just a change of `int` to `float`?
> 
> https://github.com/tensorflow/addons/blob/343e7f3276350850f9583d0b53c6d114b6beaaeb/tensorflow_addons/layers/normalizations.py#L78
> 
> What's the catch?

The catch is that we incorrectly typed it as an int. If we have casting then we can make it Union[int, float], but otherwise it should be typed as float

**Comment by failure-to-thrive** [comment]
I mean, from a workflow point of view. It's a very simple (even "stylish") modification that could be done in no time without a contributors' help. Sorry, I'm just unfamiliar with practices of this project.

**Comment by seanpmorgan** [comment]
> I mean, from a workflow point of view. It's a very simple (even "stylish") modification that could be done in no time without a contributors' help. Sorry, I'm just unfamiliar with practices of this project.

Addons only consists of volunteer contributors :smile: 

Please feel free to submit a PR, as you mentioned its an easy fix... and maintainers need to balance reviews, shepparding issues (like this one) and submitting contirbutions....

**Comment by AakashKumarNain** [comment]
`eps` should be float only and not int in any case.

**Comment by failure-to-thrive** [comment]
> and maintainers need to balance reviews, shepparding issues (like this one) and submitting contirbutions....

Got it!

**Comment by seanpmorgan** [comment]
> > and maintainers need to balance reviews, shepparding issues (like this one) and submitting contirbutions....
> 
> Got it!

Thanks for the fix!! Encouraging others to fix easy issues also helps grow our contributor base. 

Any thoughts on adding this to a 0.8.2 patch version? We could also include the fixes to CohensKappa once that merges.

**Comment by gabrieldemarmiesse** [comment]
> Any thoughts on adding this to a 0.8.2 patch version?

Yes, let's stress test our release process!

Jokes aside, it's a good way to check that the release process is as automatic as possible :)

**Comment by davidweioct** [comment]
Thank you for all the information. I understand "epsilon" should be a float simply based on it's definition. I was running in google-colab and not quite family with all those function. Thanks again!

**Comment by seanpmorgan** [comment]
@davidweioct This is fixed in the newly pushed 0.8.2 version

> Yes, let's stress test our release process! Jokes aside, it's a good way to check that the release process is as automatic as possible

@gabrieldemarmiesse Super simple :smile: it did launch 3 builds (so I canceled 2) but that's been fixed on master
