### ISSUE TITLE
Update kokoro run command

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#1068]
Apologies for moving this around on you a few times. We should have made this more configurable on our side a while ago. This should be the last time this needs to be done though.

@tomerk @karmel  Could you please update the kokoro GPU test to run `tools/run_google_cloud_tests.sh`

**Comment by seanpmorgan** [comment]
Oops @av8ramit should have been tagged.

**Comment by av8ramit** [comment]
So you want me to update `/bin/bash tools/run_docker.sh -s linux -d gpu -c 'make gpu-unit-test'` with `tools/run_google_cloud_tests.sh`?

**Comment by gabrieldemarmiesse** [comment]
Should be `/bin/bash tools/run_google_cloud_tests.sh`

**Comment by av8ramit** [comment]
Sent a change request to @karmel internally.

**Comment by seanpmorgan** [comment]
Thanks! This was completed. We have a small bug but #1081 solves it.
