### ISSUE TITLE
Bazel can't find CUDA

### ISSUE THREAD

**Issue by schnaitterm** [tensorflow/addons#1070]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7.4 x86_64
- TensorFlow version and how it was installed (source or binary): 2.1.0 from Source
- TensorFlow-Addons version and how it was installed (source or binary): 0.8.1 from source
- Python version: 3.8.0
- Is GPU used? (yes/no): yes

**Describe the bug**

When trying to build tensorflow-addons, bazel is unable to find CUDA and the build fails.  We are a cluster environment and we have CUDA installed in our `/apps` tree instead of in `/usr/local/cuda`.  `configure.py` asks for the path to the install and it is given.  configuration completes successfully, but when `bazel build` is run, it fails because it can't find CUDA.  It does not appear to actually be searching the paths it was given during configuration.

**Other info / logs**

Attached is the log from running `configure.py` and then `bazel build`:
[tfa-bazel-log.txt](https://github.com/tensorflow/addons/files/4186291/tfa-bazel-log.txt)

**Comment by seanpmorgan** [comment]
Hi @schnaitterm thanks for raising the issue. We currently only have build support for CUDA 10.1 on the master branch. See https://github.com/tensorflow/addons/issues/770

This is a high priority issue for us and will hopefully be done by then end of the month. Feel free to post comments in that issue or ask for this to be opened if you feel its a different issue.

**Comment by kennychowdhary** [comment]
Any luck on the possible solution? Also on a cluster and cannot install cuda in /use/local/cuda?
