### ISSUE TITLE
Support mask in `text/crf`

### ISSUE THREAD

**Issue by howl-anderson** [tensorflow/addons#1089]
**Describe the feature and the current behavior/state.**
support mask in  `text/crf`

**Relevant information**
- Are you willing to contribute it (yes/no): yes
- Are you willing to maintain it going forward? (yes/no): yes
- Is there a relevant academic paper? (if so, where): no
- Is there already an implementation in another framework? (if so, where): 
`https://github.com/allenai/allennlp/blob/1a8a12cd1b065d74fec3d2e80105a684736ff709/allennlp/modules/conditional_random_field.py#L318`

- Was it part of tf.contrib? (if so, where): no

**Which API type would this fall under (layer, metric, optimizer, etc.)**
text

**Who will benefit with this feature?**
CRF layer and its users

**Any other info.**

**Comment by seanpmorgan** [comment]
Closing as this is duplicated in https://github.com/tensorflow/addons/issues/1089 which had a bit more info
