### ISSUE TITLE
CorrelationCost Layer Crash with GPU 

### ISSUE THREAD

**Issue by djones** [tensorflow/addons#1092]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow version and how it was installed (source or binary): 2.1 binary
- TensorFlow-Addons version and how it was installed (source or binary): 0.8.2 binary
- Python version: 3.6
- Is GPU used? (yes/no): yes

**Describe the bug**

```python
ccl = CorrelationCost(
  kernel_size=1,
  max_displacement=10,
  stride_1=1,
  stride_2=1,
  pad=10,
  data_format='channels_last'
)

x = tf.ones([1, 100, 200, 12])
y = tf.ones([1, 100, 200, 12])

result = ccl([x,y])
```

This simple example code runs on the CPU without issue but when the `tf.device` is set to GPU it says "Your session crashed for an unknown reason"

**Code to reproduce the issue**

Reproducible nodebook here:
https://colab.research.google.com/drive/1yfa2bJ_HH8KRzNgL44Nn9uZMNreOS-YI

**Comment by failure-to-thrive** [comment]
Please make sure you are using the correct version of TFA with something like
```
import tensorflow_addons as tfa
tfa.__version__
```
They (Colab) are in their transition to Tensorflow 2.xx so the correct way to utilize `pip` under the `%tensorflow_version 2.x` magic is `!pip install -t /tensorflow-2.1.0/python3.6/ --upgrade tensorflow-addons`
I was able to reproduce your crash under the wrong TFA 0.6.0 and the correct upgrade to the 0.8.2 blew it away.

**Comment by djones** [comment]
@failure-to-thrive thanks! you're absolutely right.
