### ISSUE TITLE
AttentionWrapper incompatible with RNN

### ISSUE THREAD

**Issue by georgesterpu** [tensorflow/addons#1095]
**System information**
- OS Platform and Distribution: linux
- TensorFlow version: pypi tf-nightly 2.2.0.dev20200212
- TensorFlow-Addons version: pypi tfa-nightly 0.9.0.dev20200214
- Python version: 3.7.5

**Describe the bug**

I would like to use an attention-wrapped lstm cell with tf.keras.layers.RNN, but I receive an error message related to the state type. The `AttentionWrapperState` initial state gets internally converted to a tuple, causing a type error.

**Code to reproduce the issue**
```python
import tensorflow as tf
import tensorflow_addons as tfa


cell = tf.keras.layers.LSTMCell(8)

mechanism = tfa.seq2seq.LuongAttention(
    units=8,
    memory=tf.ones((2, 4, 8)))

cell = tfa.seq2seq.AttentionWrapper(
    cell=cell,
    attention_mechanism=mechanism)

layer = tf.keras.layers.RNN(cell)

initial_state = cell.get_initial_state(batch_size=2, dtype=tf.float32)

output = layer(
    inputs=tf.ones((2, 4, 8)),
    initial_state=initial_state,
)
```

**Other info / logs**

```python
  File "/home/john_tukey/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 864, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/john_tukey/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py", line 793, in call
    zero_output_for_mask=self.zero_output_for_mask)
  File "/home/john_tukey/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 4092, in rnn
    input_time_zero, tuple(initial_states) + tuple(constants))
  File "/home/john_tukey/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py", line 778, in step
    output, new_states = cell_call_fn(inputs, states, **kwargs)
  File "/home/john_tukey/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 864, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/john_tukey/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow_addons/seq2seq/attention_wrapper.py", line 2038, in call
    "Received type %s instead." % type(state)
TypeError: Expected state to be instance of AttentionWrapperState. Received type <class 'tuple'> instead.
```

This kind of construct used to work in TensorFlow 1.

**Comment by georgesterpu** [comment]
Hey, I think that I've fixed it by packing the state back into an `AttentionWrapperState` before the type check. To keep the change minimal, I deliberately avoided making any changes to RNN that calls a `_standardize_args` method in first place. Any thoughts, should this be submitted upstream ?

https://github.com/georgesterpu/addons/commit/2f5863abc0aff96df99223964c828a8bb13515ec

**Comment by failure-to-thrive** [comment]
> Any thoughts, should this be submitted upstream ?

The best practice is to avoid implicit casts. It would be better to explicitly extend the list of allowed inputs and maintain them appropriately. Effectively the same thing but without surprises.

**Comment by georgesterpu** [comment]
@failure-to-thrive 
Sorry for not fully understanding your message, is it correct to infer that you recommend something like: `AttentionWrapperState(cell_state=state[0], attention=state[1], ...)` ? 

I had a quick look at the documentation of [collections.namedtuple](https://docs.python.org/3.7/library/collections.html#collections.namedtuple), and it omits this aspect.
It says: `To convert a dictionary to a named tuple, use the ** operator (as described in Unpacking Argument Lists):`. Can we make an analogy and use the * operator for list to namedtuple conversions ? Since the `AttentionWrapperState` object x is converted to a list inside `keras.layers.recurrent._stardardize_args` as `list(x)`, would the * operator preserve the argument order throughout packing and unpacking ? The example in [Unpacking Argument Lists](https://docs.python.org/3.7/tutorial/controlflow.html#unpacking-argument-lists) instructs: `If they are not available separately, write the function call with the * operator to unpack the arguments out of a list or tuple; range(*args)`.

I can see instead that flake8 mentions a codestyle issue: `E722 do not use bare 'except'`. Also, namedtuple has a method `_make`for creating new instances, is this recommended over `namedtuple(iterable)` ?

**Comment by georgesterpu** [comment]
I posted a reply earlier, but soon realised that I misunderstood your advice.
What would you recommend in this specific case ?

**Comment by failure-to-thrive** [comment]
Now it is mostly a documentation job. You've already done the rest. But the code owner knows best.

**Comment by guillaumekln** [comment]
Maybe we could always call `AttentionWrapperState(*state)` and update the documentation to say something like:

> state: A tuple or list that can be packed as an `AttentionWrapperState` instance

What do you think?

**Comment by georgesterpu** [comment]
Personally I did not investigate the logic behind state flattening inside RNN, but if you are okay with this solution, I can go ahead and submit a PR with your amendments.

**Comment by guillaumekln** [comment]
Maybe @qlzh727 has an additional suggestion as he worked as this Keras code.

**Comment by qlzh727** [comment]
Thanks for reporting the issue, the issue is caused by force converting the initial_state tuple into list during input process. The reason behind that is keras need to have all the input tensors in its first argument for the __call__ (). Under the hood, we flat all the inputs, inital_state into list, and then get them back in call() body.

For now, you just need the default initial state (zeros), then you can skip the line for get_initial_state(). RNN layer will call cell.get_initial_state() if the initial state is not provide. In the case u need to provide a non-default initial state, then lets update the AttentionWrapperState to accept list as inputs during construction.

In the meantime, let me check the keras code and see if we can walk around the issue for having all the tensor inputs in the first arg. This assumption might not be needed anymore after recent rework.

**Comment by georgesterpu** [comment]
@qlzh727 thanks for looking into this.
Although I don't need a non-default case, unfortunately the call to RNN with `initial_state=None` still returns the same error.

**Comment by georgesterpu** [comment]
@qlzh727 thanks for looking into this.
Although I don't need a non-default initial state, unfortunately the call to RNN with `initial_state=None` still returns the same error.

**Comment by qlzh727** [comment]
Indeed, it seems that there are more assumptions in the keras backend RNN code that it will convert the state into tuples and pass it to the cell.call(). Changing that might require a lot of work, and could potentially break others. Let me see if we can reconstruct the AttentionWrapperState with the value from tuple.
