### ISSUE TITLE
manylinux2010 does not work with Manjaro

### ISSUE THREAD

**Issue by rnbguy** [tensorflow/addons#1097]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Manjaro
- TensorFlow version and how it was installed (source or binary): N/A
- TensorFlow-Addons version and how it was installed (source or binary): N/A
- Python version: 3.8.1
- Is GPU used? (yes/no): N/A

**Describe the bug**
Trying to install with `pip`, but it does not work.

 This is the error I get.
```
Collecting tensorflow-addons
  Could not find a version that satisfies the requirement tensorflow-addons (from versions: )
No matching distribution found for tensorflow-addons
```

**Code to reproduce the issue**
`pip install tensorflow-addons`

**Provide a reproducible test case that is the bare minimum necessary to generate the problem.**
N/A

**Other info / logs**
I first tried on my personal laptop which uses Manjaro. Then I tried with my university CentOS server and a Ubuntu docker. All of them gave the same error. I even tried manually downloading the `manylinux2010` wheel from pypi.org, but it gives the same error.

**Comment by seanpmorgan** [comment]
This is because Addons does not currently have a python3.8 wheel. We plan to as soon as TF core supports it:
https://github.com/tensorflow/addons/issues/744
https://github.com/tensorflow/tensorflow/issues/33374
