### ISSUE TITLE
Incomplete and wrong typing

### ISSUE THREAD

**Issue by n3011** [tensorflow/addons#1098]
It seems, there are many errors in the typed code. 

For examples 
1. https://github.com/tensorflow/addons/blob/master/tensorflow_addons/activations/rrelu.py#L28 (Optional[int])
2. https://github.com/tensorflow/addons/blob/master/tensorflow_addons/losses/giou_loss.py#L101 (TensorLike)

The integration of a type checker such as `mypy` can help to keep it clean if the goal is to integrate type checking.

**Comment by fsx950223** [comment]
Could you open a pull request about type checker?

**Comment by seanpmorgan** [comment]
Hi @n3011 thanks for bringing this up! We discussed static type checking, but decided that it may be too difficult to ensure that everything within the repo is typed (perhaps in the future this is an option though).

Our dynamic checker typeguard should catch these types of errors in test cases. However, there are some issues with wrapping `tf.function`  so for now we only use typeguard where we know its safe (e.g. class inits).

Typing this entire repo was a large task and reviews were large so there is likely a few mistakes like you pointed out. Please continue to raise these as you see them. Also feel free to open another issue if you would like to discuss a roadmap toward static type checking.
