### ISSUE TITLE
Clean up tutorials

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#1104]
So TFA is currently included in the TF2.x environment within colab. This is great news, but since it's an old release we'll want to upgrade the package prior to importing as @failure-to-thrive pointed out:
https://github.com/tensorflow/addons/issues/927#issuecomment-583868873

We've created an issue to see if we can get up to date installations but while we wait for that we should make sure our current tutorials work:
https://github.com/googlecolab/colabtools/issues/1005

Another thing that would improve the maintainer burden would be if we could drop the required versions from the pip upgrades. Recent addons should be more or less backwards compatible so I don't think this is still necessary. An edge case would be for a very new tutorial that was added prior to release. In that case we could install `tfa-nightly`

**Comment by abhichou4** [comment]
Hey @seanpmorgan. When tfa is installed with no dependencies, it throws a `ModuleNotFound `error for typegaurd.
https://colab.research.google.com/drive/1yrhlFadHCMsElMbBALvDKZnCKYXSXkk6

And when installed with dependencies, it gives errors for `tensorflow-federated 0.11.0` while installing. 
https://colab.research.google.com/drive/1EjkFIfhmhz1YlYqeA_XS9bwJ4F0V_2n2

Should typegaurd be installed before tfa to fix this? Any other alternatives?

**Comment by seanpmorgan** [comment]
Thanks for the find @abhichou4 !
It looks as though the reason TFA is in the environment is because of TF federated which is pinned to ~0.6.0

I'll raise an issue on TFF to see if they can pin to >= versions.

**Comment by seanpmorgan** [comment]
Just FYI 0.8.2 is now pre-installed on Colab. Going forward lets just try to use the pre-installed TFA if possible.
