### ISSUE TITLE
transform:  undefined symbol: _ZNK10tensorflow15shape_inference16InferenceContext11DebugStringEv

### ISSUE THREAD

**Issue by nscotto** [tensorflow/addons#1132]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Fedora 31
- TensorFlow version and how it was installed (source or binary): 2.1 (anaconda)
- TensorFlow-Addons version and how it was installed (source or binary): 0.8.2 (pip)
- Python version: 3.7
- Is GPU used? (yes/no): yes

**Describe the bug**
I get an error when applying a transform using `tfa.image.transform`

**Code to reproduce the issue**
```python
some_image_path = '/path/to/an/image'
with open(some_image_path, 'rb') as f:
    image = tf.io.decode_image(f.read())

ops = tfa.image.transform_ops.angles_to_projective_transforms(90, image.shape[0], image.shape[1])
image = tfa.image.transform(image, ops)
```

**Other info / logs**

```
Traceback (most recent call last):
  File "/home/nicolas/.anaconda3/envs/posenet/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-24-2e958d55097f>", line 1, in <module>
    tfa.image.transform(image, ops)
  File "/home/nicolas/.anaconda3/envs/posenet/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/nicolas/.anaconda3/envs/posenet/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/nicolas/.anaconda3/envs/posenet/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/home/nicolas/.anaconda3/envs/posenet/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/nicolas/.anaconda3/envs/posenet/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/nicolas/.anaconda3/envs/posenet/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/nicolas/.anaconda3/envs/posenet/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/nicolas/.anaconda3/envs/posenet/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/nicolas/.anaconda3/envs/posenet/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.NotFoundError: in converted code:
    /home/nicolas/.anaconda3/envs/posenet/lib/python3.7/site-packages/tensorflow_addons/image/transform_ops.py:110 transform  *
        output = _image_so.ops.addons_image_projective_transform_v2(
    /home/nicolas/.anaconda3/envs/posenet/lib/python3.7/site-packages/tensorflow_addons/utils/resource_loader.py:49 ops
        self._ops = tf.load_op_library(get_path_to_datafile(self.relative_path))
    /home/nicolas/.anaconda3/envs/posenet/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py:57 load_op_library
        lib_handle = py_tf.TF_LoadLibrary(library_filename)
    NotFoundError: /home/nicolas/.anaconda3/envs/posenet/lib/python3.7/site-packages/tensorflow_addons/custom_ops/image/_image_ops.so: undefined symbol: _ZNK10tensorflow15shape_inference16InferenceContext11DebugStringEv
```

**Comment by seanpmorgan** [comment]
Hi @nscotto! So this is a re-occuring issue we have. Please see this issue for more details:
https://github.com/tensorflow/addons/issues/987

The short of it is that until we can get ABI stable kernels (in development) you'll need to pair TF Addons with a pip installed TensorFlow.

Closing but feel free to continue this discussion if there are questions.

**Comment by DanielTakeshi** [comment]
Hi, just wondering was there any change to this? I am getting this error with `conda install tensorflow-gpu==2.1.0` and I did that because of the difficulty in pip installation (see: https://towardsdatascience.com/tensorflow-gpu-installation-made-easy-use-conda-instead-of-pip-52e5249374bc).

**Comment by seanpmorgan** [comment]
Hi @DanielTakeshi unforuntely no change yet. Still waiting on the RFC in the issue linked above:
https://github.com/tensorflow/addons/issues/987

For now you'll need to use TF that is pip installed. We'll be working to improve our support for TFA installed from source in the coming month(s)

**Comment by DanielTakeshi** [comment]
Just a quick update, this error also appears with TensorFlow 2.2 from conda:

```
conda install tensorflow-gpu==2.2
pip install tensorflow-addons-0.8.3
```

Hopefully something will happen. :) Installing from conda means the correct CUDA version is already shipped for us.

**Comment by DanielTakeshi** [comment]
Quick update: I upgrade tensorflow-addons:

```
conda install tensorflow-gpu==2.2
pip install tensorflow-addons==0.11.1
```

and now the error message disappears. @seanpmorgan  Was this expected?

**Comment by seanpmorgan** [comment]
> Quick update: I upgraded tensorflow-addons:
> 
> ```
> conda install tensorflow-gpu==2.2
> pip install tensorflow-addons==0.11.1
> ```
> 
> and now the error message disappears. @seanpmorgan Was this expected?

No not expected.... for which function did you see this disappear? Some image ops were replaced with tf.raw_ops thats the only thing I could think of. That or just by luck our gcc version is currently aligned with the one conda ships

**Comment by DanielTakeshi** [comment]
@seanpmorgan  The function https://www.tensorflow.org/addons/api_docs/python/tfa/image/transform

**Comment by seanpmorgan** [comment]
Yeah it was the first reason:
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/transform_ops.py#L108

It's calling core package functionality now
