### ISSUE TITLE
Add project description to package and pypi

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#114]
As is done here: https://github.com/tensorflow/tensorflow/blob/cfbbbe3b2e034438437cf5c9fa46756ae4d0b2d5/tensorflow/tools/pip_package/setup.py#L248

We should include the description found in the README

**Comment by Gokkulnath** [comment]
@seanpmorgan  I would like to fix this issue. Do you want me to follow the same approach as the link referenced ?

**Comment by Gokkulnath** [comment]
@seanpmorgan  I would like to fix this issue. Do you want me to follow the same approach as the link referenced ? How can i verify whether the description is getting updated without pushing the changes? Any way to verify Locally would be very helpful. Thanks in advance

**Comment by seanpmorgan** [comment]
@Gokkulnath Thanks! I would say that the way it's done in tensorflow is an acceptable way, but not required. 

Testing the description on PyPi is a little tough. You could create a package on pypt-test to make sure it works, but I think just a review by a maintainer should be enough. Great idea though,  test everything should be the general rule!
