### ISSUE TITLE
Proposal: Upload the nightlies at each commit on the master branch

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [tensorflow/addons#1144]
We already build the wheels already anyway. It's just missing the push to pypi. Yes/No?

**Comment by seanpmorgan** [comment]
Good question. It would only require a minor change to our nightly versioning to add timestamps:
https://github.com/tensorflow/addons/blob/master/setup.py#L55

Seeing as our package is only ~1MB in size I'm not overly concerned with the space it takes up on pypi. It is something to think about though if down the line we find a need to increase package size substantially.

Given that info, I think the benefits outweigh then downsides and I would be in favor of adding this.

**Comment by gabrieldemarmiesse** [comment]
Next to tensorflow and their 500MB uploaded to PyPI every day, we have some margin :laughing:
