### ISSUE TITLE
tensorflow-addons 0.6.0 have hard dependency on tensorflow-gpu 2.0.0

### ISSUE THREAD

**Issue by 372046933** [tensorflow/addons#1147]
Can tensorflow-addons 0.6.0 depend on tensorflow-gpu 2.0.1?

**Comment by seanpmorgan** [comment]
Hi @372046933! This is a fair question and I would like to say yes (well 0.6.1), however we've significantly revamped our build since that release. It's still do-able but we need to re-activate travis.

While we consider doing this.. try running without dependencies to unblock yourself:
```
pip install tensorflow-addons==0.6.0 --no-deps
```

**Comment by 372046933** [comment]
Great! Thanks a million.

**Comment by seanpmorgan** [comment]
I'm going to close this seeing as the hard dependency has since been removed and if there are user issues installing (e.g. with tensorflow-cpu) I would recommend they use the `--no-deps` option. 

Please feel free to ask to re-open if you think this isn't sufficient.
