### ISSUE TITLE
Enable SSE4.2 and AVX support during build

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#1148]
So the pip installed TF does not support these instruction sets by default, but modern-ish CPUs do. (Roughly CPUs after 2012).

We could try this and see if there are any improvements in test times and weight the benefits.  If nothing else we can add it as a flag for building from source. Currently TF-IO does this by default:
https://github.com/tensorflow/io/blob/master/.github/workflows/build.yml#L13

@perfinion do we know if this is on the roadmap for default TF installations?

**Comment by perfinion** [comment]
As far as i recall, the default wheel on pypi supports all the way up to AVX2 by default. It might only be AVX and not AVX2, but im completely sure it builds with both SSE4.2 and AVX for many versions already. AVX/2 will likely have a pretty large difference. The only one to stay away from is AVX512, that is only on the newest server xeons and not common at all.

**Comment by Leslie-Fang** [comment]
@seanpmorgan Is there anything we can do to enable it? From my knowledge, we just need to add --copt=-march=native in bazel commands. And AXV512 will be enabled if the target supports it.

**Comment by failure-to-thrive** [comment]
@Leslie-Fang _-march=native_ is useful for a local compilation only. It doesn't generate fallbacks.

**Comment by WindQAQ** [comment]
@seanpmorgan are we going to build with AVX2? TensorFlow pre-built binary is compiled with AVX2 and FMA. I think we can follow it.
