### ISSUE TITLE
Update CODEOWNERS to match documentation

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#1168]
Once #1167 merges, we'll finally have an automatic system for notifying submodule maintainers. 
We can remove the maintainers from each subpackage README so as not to duplicate work on PRs. Will also want to modify the contribution instructions.

**Comment by fsx950223** [comment]
@failure-to-thrive Are you interested in maintaining some modules?

**Comment by failure-to-thrive** [comment]
> @failure-to-thrive Are you interested in maintaining some modules?

Sure!

**Comment by fsx950223** [comment]
> > @failure-to-thrive Are you interested in maintaining some modules?
> 
> Sure!

Good! I have two modules for you.

**Comment by fsx950223** [comment]
```maxout``` and ```optical_flow```. You could submit a pull request.

**Comment by failure-to-thrive** [comment]
> `maxout` and `optical_flow`. You could submit a pull request.

Without any doubt, I'm very happy to submit pull requests! :smile:  However, as of this particular case, I'm not quite sure what and where I should modify. I think the project maintainers know the best. I'm ready to provide required info on their request.

**Comment by fsx950223** [comment]
> > `maxout` and `optical_flow`. You could submit a pull request.
> 
> Without any doubt, I'm very happy to submit pull requests! 😄 However, as of this particular case, I'm not quite sure what and where I should modify. I think the project maintainers know the best. I'm ready to provide required info on their request.

Yeah, I mean that you could submit a pull request to transfer the maintainership.
As I'm lack of time and energy. I could transfer it to you.

**Comment by failure-to-thrive** [comment]
> Yeah, I mean that you could submit a pull request to transfer the maintainership.

I meant the same. Sorry, I'm just unfamiliar with those aspects of GitHub and the project's workflow. Do you want me to update `.github/CODEOWNERS`? That's all?

**Comment by gabrieldemarmiesse** [comment]
There is a bot reading the CODEOWNERS file and dropping messages when someone is opening a pull requests that modifies the files you're responsible of.
