### ISSUE TITLE
test_utils.run_distributed fails on GPU

### ISSUE THREAD

**Issue by Squadrick** [tensorflow/addons#1171]
The error is: 

```
tensorflow.python.framework.errors_impl.UnknownError: Not enough GPUs to create virtual devices. num_gpus_to_use: 1 #virtual_devices: 2
```
This happens since number of physical GPUs != number of virtual GPUs.

The line which throws the error is here: [`gpu_device.cc`](https://github.com/tensorflow/tensorflow/blob/feacb9f25458882d1f15aec153848017ccb5c162/tensorflow/core/common_runtime/gpu/gpu_device.cc#L782). 

The [documentation for `tf.config.set_logical_device_configuration`](https://www.tensorflow.org/api_docs/python/tf/config/set_logical_device_configuration) seems to run that bit of code successfully. 

Relevant log: https://source.cloud.google.com/results/invocations/606014e4-04b9-4cd5-a907-1b7a2661375a/targets/tensorflow_addons%2Fubuntu%2Fgpu%2Fpy3%2Fpresubmit/log

**Comment by hyang0129** [comment]
@Squadrick I'm willing to take a look at this one. #969 needs to run distributed tests.

**Comment by gabrieldemarmiesse** [comment]
Closing this as it's going to be tracked in #1682
