### ISSUE TITLE
Error when using a mask in RNN + AttentionWrapper cell

### ISSUE THREAD

**Issue by georgesterpu** [tensorflow/addons#1194]
**System information**
- OS Platform and Distribution:  manjaro linux testing
- TensorFlow version: pypi tf-nightly 2.2.0.dev20200228
- TensorFlow-Addons version: pypi tfa-nightly 0.9.0.dev20200228
- Python version: 3.7.6
- Is GPU used?: no

**Describe the bug**

A ValueError is raised when using a mask in a RNN layer taking a RNN cell wrapped with an AttentionWrapper.

**Code to reproduce the issue**

```python
import tensorflow_addons as tfa
import tensorflow as tf

bs = 4
cell = tf.keras.layers.LSTMCell(3)
mechanism = tfa.seq2seq.LuongAttention(units=3)
cell = tfa.seq2seq.AttentionWrapper(cell, mechanism)
layer = tf.keras.layers.RNN(cell)


@tf.function
def test(masked=False):
    seq_len = tf.random.uniform(shape=(), minval=2, maxval=10, dtype=tf.int32)
    data = tf.ones(shape=(bs, seq_len, 3))
    mechanism.setup_memory(data)

    if masked:
        mask = tf.sequence_mask(lengths=bs * [seq_len])
    else:
        mask = None

    return layer(data, mask=mask)


test(masked=False); print('Test 1 passed')
test(masked=True); print('Test 2 passed')
```

**Other info / logs**
```python
Test 1 passed
Traceback (most recent call last):
  File "/run/media/zenbook/work/phd/work/__/pb1.py", line 26, in <module>
    test(masked=True); print('Test 2 passed')
  File "/home/zenbook/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/zenbook/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 611, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/zenbook/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2419, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/home/zenbook/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/zenbook/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/zenbook/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/zenbook/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/zenbook/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /run/media/zenbook/work/phd/work/__/pb1.py:22 test  *
        return layer(data, mask=mask)
    /home/zenbook/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py:652 __call__  **
        return super(RNN, self).__call__(inputs, **kwargs)
    /home/zenbook/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:926 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/zenbook/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py:793 call
        zero_output_for_mask=self.zero_output_for_mask)
    /home/zenbook/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4205 rnn
        **while_loop_kwargs)
    /home/zenbook/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py:2688 while_loop
        back_prop=back_prop)
    /home/zenbook/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow/python/ops/while_v2.py:229 while_loop
        len_orig_loop_vars], expand_composites=True))
    /home/zenbook/miniconda3/envs/tfn/lib/python3.7/site-packages/tensorflow/python/ops/while_v2.py:1143 _check_shapes_compat
        "specify a less-specific shape." % (input_t.name, shape, t.shape))

    ValueError: Input tensor 'rnn/AttentionWrapperZeroState/zeros_3:0' enters the loop with shape (), but has shape (4, 1) after one iteration. To allow the shape to vary across iterations, use the `shape_invariants` argument of tf.while_loop to specify a less-specific shape.


Process finished with exit code 1
```

**Comment by guillaumekln** [comment]
This is because the Keras RNN assumes that each tensor in the state has a batch dimension. However, the `time` field in `AttentionWrapperState` is just a scalar tensor.

I think we could work around not having this time field. @georgesterpu Do you want to look into that?

**Comment by georgesterpu** [comment]
Thanks, @guillaumekln.
Assuming that the problem comes from the `time` field - `AttentionWrapper` uses it to write the current alignment slice to a `TensorArray` when the `alignment_history` flag is True. I can see several possibilities, such as:
1) pass the current loop index from outside (the `time` parameter of the `_step` function declared inside `keras.backend.rnn` ?
2) manage the loop counter as a member of the `AttentionWrapper` class
3) extend the `TensorArray` class to support an `append` operation, since `AttentionWrapper` never leapfrogs over indices and only writes sequentially anyway. 

Unfortunately, as a final year student, I lack the throughput to carry on with a more detailed investigation - this is why I created the issue in the first place :relaxed:

**Comment by guillaumekln** [comment]
Thanks looking into workarounds. Actually, as `alignment_history` has a dynamic size and we only append to it, we can do something like:

```python
ta = ta.write(ta.size(), elem)
```

> Unfortunately, as a final year student, I lack the throughput to carry on with a more detailed investigation - this is why I created the issue in the first place relaxed

No worries! Thank you for finding these issues. I can make a PR as I already have a fix locally.

**Comment by georgesterpu** [comment]
Also, any chance that 
4) the `shape_invariants` parameter of the `while_loop` in keras.backend.rnn could be configured conveniently to work with an `AttentionWrapperState` ?

**Comment by guillaumekln** [comment]
If you dive into the `K.rnn` code you'll find that it applies a `tf.where` on each state tensor, including our `time` scalar. This is the issue. See the relevant code here:

https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/keras/backend.py#L4070

compared to the Addons decoder code that ignores scalar tensors:

https://github.com/tensorflow/addons/blob/fcaa672c21028c1e429ed72a7780575c2b2e86db/tensorflow_addons/seq2seq/decoder.py#L455

**Comment by georgesterpu** [comment]
@guillaumekln thanks a lot !
There is a corner case where this doesn't work: when setting `alignment_history=True` in the `AttentionWrapper` constructor. `AttributeError: 'TensorArray' object has no attribute 'shape'`. Crashing under both eager and graph modes.

**Comment by georgesterpu** [comment]
```python
import tensorflow_addons as tfa
import tensorflow as tf
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

cell = tf.keras.layers.LSTMCell(3)
mechanism = tfa.seq2seq.LuongAttention(units=3)
cell = tfa.seq2seq.AttentionWrapper(cell, mechanism, alignment_history=True)
layer = tf.keras.layers.RNN(cell)


# @tf.function
def mytest():
    var_len = tf.random.uniform(shape=(), minval=2, maxval=10, dtype=tf.int32)
    lengths = tf.random.uniform(shape=(var_len,), minval=1, maxval=var_len + 1, dtype=tf.int32)
    data = tf.ones(shape=(var_len, var_len, 3))
    mask = tf.sequence_mask(lengths, maxlen=var_len)
    mechanism.setup_memory(data, lengths)

    return layer(data, mask=mask)

mytest()

```

**Comment by guillaumekln** [comment]
It seems the Keras RNN backend does not accept TensorArray in the inputs. @qlzh727 Is there any plans for Keras to support TensorArray in cell states?
