### ISSUE TITLE
Notebooks headings are bold and H1

### ISSUE THREAD

**Issue by yashk2810** [tensorflow/addons#1210]
Hello,

I was going through this notebook: https://www.tensorflow.org/addons/tutorials/networks_seq2seq_nmt and noticed that all the headings are bold and H1.

Can you please make it not bold and H2 heading?

`# **Setup**` becomes `## Setup`

**Comment by us** [comment]
Related pr #1216 is merged, so it can be closed.

**Comment by gabrieldemarmiesse** [comment]
Thanks a lot @us !
