### ISSUE TITLE
404 in Left Sidebar of zh-cn doc

### ISSUE THREAD

**Issue by Ir1d** [tensorflow/addons#1221]
https://www.tensorflow.org/addons/api_docs/python/tfa/layers/InstanceNormalization
Check the `GELU` changed into `GeLU` if you change the language from en to zh-CN
![image](https://user-images.githubusercontent.com/10709657/75981291-2f469080-5f1f-11ea-9662-9e8145dfdb5a.png)

![image](https://user-images.githubusercontent.com/10709657/75981278-281f8280-5f1f-11ea-80a1-614aa309e3f6.png)

Because the url is case-sensitive, it only works with [GELU](https://www.tensorflow.org/addons/api_docs/python/tfa/layers/GELU), so its a 404 in zh-cn docs. I tried to bring a fix but only found the toc file in v0.7.1 branch instead of master.

**Comment by seanpmorgan** [comment]
Hi @Ir1d thanks for the issue! I'm not quite following why this hyperlink would be different for the CN version. I tried changing my language and the link looks correct?

![image](https://user-images.githubusercontent.com/18154355/76178697-9f0e8280-618e-11ea-833b-f4cd7a601330.png)

++ @MarkDaoust @lamberta to see if this makes sense to them

**Comment by Ir1d** [comment]
I believe this is somehow fixed? I can't reproduce either.

**Comment by lamberta** [comment]
I sent off a translation job for the _book.yaml files (nav) that just came back the other day. Usually translations can lag behind a bit. Should be up-to-date now.
