### ISSUE TITLE
Addons Sparsemax gets different results than Contrib sparsemax

### ISSUE THREAD

**Issue by tomerk** [tensorflow/addons#1235]
**System information**
- TensorFlow version and how it was installed (source or binary): Nightly
- TensorFlow-Addons version and how it was installed (source or binary): git commit 8bacf4d434974b8821a598aa4d1c9534a6581a5e

**Describe the bug**
We've gotten a google-internal bug report that sparsemax implementation in tensorflow addons:
https://github.com/tensorflow/addons/blob/8bacf4d434974b8821a598aa4d1c9534a6581a5e/tensorflow_addons/activations/sparsemax.py#L25

Produces different results than the sparsemax implementation that was in contrib:
https://github.com/tensorflow/tensorflow/blob/23c218785eac5bfe737eec4f8081fd0ef8e0684d/tensorflow/contrib/sparsemax/python/ops/sparsemax.py#L30

For the user's model, the contrib implementation produced better results than the addons implementation.

------------
Are these differences expected? Or is it possible that there is a bug in the addons sparsemax implementation?

**Comment by seanpmorgan** [comment]
Hi @tomerk 

Hmmm that's surprising. We have a numpy implementation that is checked against for contrib & addons that is identical:

https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/contrib/sparsemax/python/kernel_tests/sparsemax_test.py#L35-L56

https://github.com/tensorflow/addons/blob/master/tensorflow_addons/activations/sparsemax_test.py#L25-L46

Same goes for the loss testing. Is there a minimal reproducible example that shows a difference?

CC @AndreasMadsen who authored both of them to see if anything comes to mind.

**Comment by tomerk** [comment]
I've passed along the request for a reproducible example, will follow up if they manage to make one.

**Comment by tomerk** [comment]
I don't think we've been able to get a reproducible example, so I'll close this issue for now. Will reopen if we get an example.
