### ISSUE TITLE
Cleanup seq2seq API symbols

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/addons#124]
The `seq2seq` module simply exports each of its implementation file. It should export selected symbols instead for the README examples to work.

**Comment by qlzh727** [comment]
Ack, I will do some cleanup, probably later this week.

**Comment by guillaumekln** [comment]
I can also work on that if you accept contributions on this point.

**Comment by qlzh727** [comment]
That will be great. Thanks for all the contribution.
