### ISSUE TITLE
Add "Project Description" when publishing to PyPI

### ISSUE THREAD

**Issue by huan** [tensorflow/addons#127]
If we goto PyPI module page https://pypi.org/project/tensorflow-addons/, we will not see any document about this module: It's empty.

We should add a project description to this page so that the developer could be able to understand what this module is easier.

**Comment by seanpmorgan** [comment]
Thanks @huan! Just created this a few days ago though so duplicate of #114

**Comment by huan** [comment]
@seanpmorgan Great! sorry for having not noticed that old one.
