### ISSUE TITLE
Segmentation fault when using tfa.rotate in tf-nightly

### ISSUE THREAD

**Issue by bw0248** [tensorflow/addons#1277]
**System information**
- OS Platform: Linux Ubuntu 18.04.3 LTS
- TensorFlow version: tf-nightly (2.2.0-dev20200310) installed with pip
- TensorFlow-Addons version: 0.8.3 (pip) and tfa-nightly (0.9.0-dev; pip)
- Python version: 3.6.9
- Is GPU used?: yes

**Describe the bug**
I currently have to use tf-nightly because of a separate issue. When I use tfa.rotate I get a segmentation fault. Behavior is the same with tfa 0.8.3 and tfa-nightly.

**Code to reproduce the issue**
```
import tensorflow as tf
import tensorflow_addons as tfa

img = tf.io.read_file(IMG_PATH)
img = tf.image.decode_png(img)
print(img.shape)
img = tfa.image.rotate(img, 90)
```
Output:     
> (128, 128, 3)
> Segmentation fault (core dumped)

I also tried `interpolation="BILINEAR"`. Problem is the same.

**Comment by gabrieldemarmiesse** [comment]
Segfaults are normal when using tfa with tensorflow nightly. Tensorflow Addons is built against tensorflow 2.1.0 stable. Since the ABI is not stable from version from version to version, people get segfaults when using it with other tensorflow versions than the 2.1.0.

Can you install tensorflow 2.1.0 and tell us if the error still occurs?

**Comment by bw0248** [comment]
Ah ok, thanks for your quick reply.
I can confirm that it works without issues with tensorflow 2.1.0.

**Comment by gabrieldemarmiesse** [comment]
I understand that the fact that we're targeting TF stable is not obvious, you're not the first person raising an issue like that. So there is a  problem on our side. 

We need to do a better job at checking the tensorflow version and tell users that something is wrong. 

Just leaving them with a segmentation is not good enough. I'll open a pull request for that. Sorry about the trouble.

**Comment by Cospel** [comment]
Why is this happening? I successfully built tf-addons with CUDA 10.0.130, CUDNN 7.5, and custom build of TensorFlow-2.2. However, when using any function from tf.addons I always get a segmentation fault.
