### ISSUE TITLE
Make tfa.seq2seq.AttentionWrapper 2.0 compatible

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/addons#128]
The `AttentionWrapper` class is currently not compatible with TF2.0:

* it extends `tf.compat.v1.nn.rnn_cell.RNNCell` instead of `tf.keras.layers.AbstractRNNCell`
* it uses `tf.compat.v1.layers.Dense` instead of `tf.keras.layers.Dense`
* attention layers are saved in a `tuple` instead of a `list` which prevent them to be tracked

I can contribute to this change, unless this is a WIP by @qlzh727.

**Comment by qlzh727** [comment]
Ah, sure. Contribution are welcome :)
