### ISSUE TITLE
ValueError for RSquare metric - requested dtype float32 for Tensor with dtype float64

### ISSUE THREAD

**Issue by beeb** [tensorflow/addons#1282]
Hey there!

I was trying to use the latest version of `RSquare` that fixes the missing `sample_weight` argument, but there is another error when I try to use it. It seems the conversion to float32 fails or something.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version and how it was installed (source or binary): `2.1.0` from pip
- TensorFlow-Addons version and how it was installed (source or binary): `0.9.0-dev` tfa-nightly from pip
- Python version: 3.7
- Is GPU used? (yes/no): yes

**Describe the bug**

```
Exception has occurred: ValueError
in converted code:

    C:\Users\vbersier\AppData\Local\Continuum\miniconda3\envs\smsl\lib\site-packages\tensorflow_addons\metrics\r_square.py:65 update_state  *
        y_true = tf.convert_to_tensor(y_true, tf.float32)
    C:\Users\vbersier\AppData\Local\Continuum\miniconda3\envs\smsl\lib\site-packages\tensorflow_core\python\framework\ops.py:1256 convert_to_tensor_v2
        as_ref=False)
    C:\Users\vbersier\AppData\Local\Continuum\miniconda3\envs\smsl\lib\site-packages\tensorflow_core\python\framework\ops.py:1290 convert_to_tensor
        (dtype.name, value.dtype.name, value))

    ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float64: <tf.Tensor 'y_true:0' shape=(None, 1) dtype=float64>
```

**Code to reproduce the issue**

```python
model = tf.keras.Model(inputs, outputs)
model.compile('...', metrics=[tfa.metrics.RSquare()])
```

**Other info / logs**

N/A

**Comment by AakashKumarNain** [comment]
Thanks foe reporting this. Looks like the same issue as in #1261

**Comment by beeb** [comment]
@AakashKumarNain the error does not happen in the same file. The exception is roughly the same but the cause is probably different. I would say "not a duplicate"

**Comment by beeb** [comment]
After upgrading to `tf-nightly` 2.2.0 it seems the problem is gone. So the issue might be upstream on tf 2.1.0...

**Comment by AakashKumarNain** [comment]
`tf.convert_to_tensor()` takes `dtype` as an argument, so that shouldn't be a problem. `self.dtye` makes it possible to use with any type of `float`
