### ISSUE TITLE
Handling resource inputs of a custom optimizer op for add_ons

### ISSUE THREAD

**Issue by spidyDev** [tensorflow/addons#1285]
Hi ,
I am working on writing a custom optimizer to be added to add_ons. I have a custom kernel for this optimizer.
Since this op takes resource type  as one of its inputs , similar to ResourceApplyAdam op, I am trying to use "GetInputTensorFromVariable" function. But the header file "training_ops_helpers.h" in  tensorflow/core/kernels is not public. 

Is there a reason this file was not made public by TF? 
Any suggestions on how can i setup  the modify/update for the resource input ?

**Comment by Squadrick** [comment]
See https://github.com/tensorflow/tensorflow/issues/27899

**Comment by 372046933** [comment]
Seems that this issue is not resolved on TF 2.8
