### ISSUE TITLE
Developer environment Dockerfile for ide

### ISSUE THREAD

**Issue by bhack** [tensorflow/addons#1305]
I want to add a Vscode devcontainer entry for tensorflow/addons in https://github.com/microsoft/vscode-dev-containers/issues/14.
Something like the already existing [Tensorflow-examples repo](https://github.com/microsoft/vscode-dev-containers/tree/master/repository-containers/github.com/aymericdamien/TensorFlow-Examples/.devcontainer).

But it is not clear to me what to put in a complete developer environment `Dockerfile` receipts for Addons cause the current docker images receipts are fragmented in stages (Test, pre-commit, build etc..) as I see in https://github.com/tensorflow/addons/tree/master/tools/docker

**Comment by gabrieldemarmiesse** [comment]
I believe that gpu_tests.Dockerfile has all the necessary tools for developement. It's what we actually tell people to use in the CONTRIBUTING.md to compile interactively. For the code format, no need to have the tools installed locally. `bash tools/pre-commit.sh` works in pretty much all situations, even on Windows.

**Comment by bhack** [comment]
I suppose that we need IDE python and cpp extensions for the addons right?

**Comment by gabrieldemarmiesse** [comment]
I'm not sure I understand your question. Could you expand on this?

**Comment by bhack** [comment]
I meant developer need to have both python and cpp support in the IDE right?
Also have you arleady a published `gpu_tests.Dockerfile` image on Dockerhub where I can start `FROM`? 
If not i need to copy `tools/install_deps/tensorflow.txt` `tools/install_deps/tensorflow.txt` and `tools/install_deps/finish_bazel_install.sh` to replicate the same image build.

**Comment by seanpmorgan** [comment]
@bhack per your comment on the Discord issue, would you like to join our gitter if you think thats a better discussion forum?
https://gitter.im/tensorflow/sig-addons

We've avoided pushing docker images to hub since we have no access to the `tensorflow` account and creating more accounts which we have to share across a community SIG has challenges. Not to say it can't be done we could use GitHub secrets and push images through CI.

**Comment by bhack** [comment]
An initial stub is at https://github.com/microsoft/vscode-dev-containers/pull/258. 
Probably we want some other kind of stuffs in the container cause the formatting is in the IDE but the LSP (languge server protocol) daemon run in the (local/remote) container.

**Comment by bhack** [comment]
I moved the PR here cause it is directly ready for devs with Vscode at checkout https://github.com/tensorflow/addons/issues/1305

**Comment by seanpmorgan** [comment]
@karmel as discussed in our monthly meeting we would like to be able to publish our own development docker image for this issue and other reasons. #1309 may have more details on this particular request.

Would you be able to get us in touch with someone who would know if it's possible to publish under tensorflow namespace on DockerHub. That would be preferable to how we're currently publishing images under one of our own accounts. Perhaps commiting a Dockerfile to the tensorflow/tensorflow repo that gets picked up?

**Comment by bhack** [comment]
Just a reminder:
If we want to let the users to use theirs GitHub codespaces  with addons we will need to recover something from this PR.

https://help.github.com/en/github/developing-online-with-codespaces/configuring-codespaces-for-your-project
