### ISSUE TITLE
Make a better UX around the issue of tensorflow ABI instability.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [tensorflow/addons#1317]
**Describe the feature and the current behavior/state.**

See #1298

Currently, if we compile Tensorflow Addons against tensorflow 2.1.0, we have no garantees that it's going to work with another version of tensorflow. We don't even have a garantee that it will work with the same version if tensorflow has been compiled from source. As such, we should try to find ways of making this as painless as possible to users until Tensorflow provides backward compatibily garantees about the ABI (see tensorflow/community#77, tensorflow/community#101 and  tensorflow/community#133). Ideas welcome.

**Comment by failure-to-thrive** [comment]
Make a [black]list of builds/hashes of `.so`/`.dll`that are seems to be good / proven to be bad. Print out appropriate warnings.

**Comment by MarkDaoust** [comment]
If you have a different version installed, `tfa-nightly` does warn that it was built for TensorFlow 2.1 and may not work.  So steps have already been taken towards @failure-to-thrive's suggestion. It's just not included in the 0.8 package.

**Comment by gabrieldemarmiesse** [comment]
> It's just not included in the 0.8 package.

#1307 was merged. We just need to make a new release. @seanpmorgan , you may want to add this to your todo list.


I propose that we make a 0.9 release, compiled against TF 2.1, and at the same time, we make a 0.10  release, compile against TF 2.2, both with an appropriate warning message similar to the one we had before. We'll need to backport all the bugfixes twice, but with the bot in place it's fairly painless.

**Comment by gabrieldemarmiesse** [comment]
I believe we also need a section in our readme describing the ins and outs of the problem so that users really understand what is going on and why our compatibility with TF is so uncommon. We can put a link to this section in our warning message.

**Comment by gabrieldemarmiesse** [comment]
We have two types of incompatibilities:
1) Python incompatibilities
2) ABI incompatibility.

It's possible for a user to use the python-only features and be completely fine. So I think we should have two warning messages, one at import time, for python incompatibility, and one when loading the first SO, to warn about ABI incompatibility. We except more compatibility in the python world than in the ABI world so the conditions should be different.
