### ISSUE TITLE
Fix Addons compatibility with TF2.2

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#1320]
**System information**
- TensorFlow version and how it was installed (source or binary): TF2.2

**Describe the bug**
As we prepare for the upcoming TF2.2 release we need to fix a number of bugs that have surfaced when linking with the new version. It may be better to break these out into individual issues, but wanted to make a placeholder issue in the mean time.

See https://github.com/tensorflow/addons/pull/1303/files

**Comment by gabrieldemarmiesse** [comment]
All the bugs are fixed! We're now compatible with TF 2.2. What's left now is to change our CI to build on all OS against tf 2.1 and 2.2.
