### ISSUE TITLE
tensorflow2.0 can't use this module

### ISSUE THREAD

**Issue by ididhmc** [tensorflow/addons#1325]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  window10
- TensorFlow version and how it was installed (source or binary):  2.0.0
- TensorFlow-Addons version and how it was installed (source or binary): get it by github
- Python version:  3.6
- Is GPU used? (yes/no):   no

**Describe the bug**
when i use addons in my program ,it tell me that i only use this module in tensorflow2.1.0, Do you know how can get this module be used in tensorflow2.0.0

**Comment by gabrieldemarmiesse** [comment]
I believe we need to add a section in the readme describing the incompatibility problems. But I'll try to at least answer shortly your question here.

> TensorFlow-Addons version and how it was installed (source or binary): get it by github 

Can you expand a bit more on this? The version installed will affect how I answer :)

**Comment by AakashKumarNain** [comment]
> I believe we need to add a section in the readme describing the incompatibility problems. But I'll try to at least answer shortly your question here.

Agreed. We really need to make it explicit so that people don't run these issues

**Comment by seanpmorgan** [comment]
Totally agree with better documentation. In the interim you can try `tensorflow-addons==0.6.0` which is built against TF2.0.... but it may not have the functionality you're looking for.

**Comment by gabrieldemarmiesse** [comment]
Closing this issue since we got no answer from the author. Tracking the docs part in #1317
