### ISSUE TITLE
[2/2] Add Image Ops for Data Augmentation

### ISSUE THREAD

**Issue by vinayvr11** [tensorflow/addons#1353]
Part 1: https://github.com/tensorflow/addons/issues/1333

As part of #1226, relevant image ops need to be added to `tfa.image`. List of ops tracked in this issue (tick the op only once the corresponding PR is *merged*):
- [x] to grayscale
- [ ] color jitter
- [ ] color jitter nonrand
- [ ] color jitter rand
- [ ] compute crop shape
- [ ] center crop
- [ ] distorted bounding box crop
- [ ] crop and resize
- [x] gaussian blur
- [ ] random crop with resize
- [ ] random color jitter
- [ ] random blur
- [ ] batch random blur

Reference: https://github.com/google-research/simclr/blob/master/data_util.py

**Comment by vinayvr11** [comment]
@gabrieldemarmiesse, @dynamicwebpaige does this issue is meaningfull for Tensorlfow.

**Comment by Squadrick** [comment]
@vinayvr11 Closing #1342, create separate PRs for each op.

**Comment by vinayvr11** [comment]
Sure @Squadrick i will make seperate PR for all operations.

**Comment by ghosalsattam** [comment]
@gabrieldemarmiesse The list does not contain Canny Edge detection. But it is useful functionality an is contained in almost all Standard image processing libraries. Should it be added?

**Comment by bhack** [comment]
> @gabrieldemarmiesse The list does not contain Canny Edge detection. But it is useful functionality and is contained in almost all Standard image processing libraries. Should it be added?

About image processing I think that we need to think about priorities:

- Is the op useful for image (auto)augmentation/preprocessing?
- Is the op useful for postprocessing the network output?
- if are not in the first two cases what is the use case of that specific op VS a network that learn that task (e.g. in the edge detector case see https://arxiv.org/abs/2003.08235 just to mention a recent work)? Are we planning to contribute a differentiable version of the ops to learn that task? 

In the first two case, as an example, see [how many Opencv calculators ](https://github.com/google/mediapipe/tree/master/mediapipe/calculators/image) (search for `cv::`)  mediapipe still need to implement in its demos other then tensorflow inference.

**Comment by seanpmorgan** [comment]
Per https://github.com/tensorflow/addons/issues/1226#issuecomment-634755922 the autoaugment/randaugment features will be a part of https://github.com/keras-team/keras-cv

Apologies for not being able to present this information sooner to the contributors.
