### ISSUE TITLE
Add Bounding Box Ops

### ISSUE THREAD

**Issue by vinayvr11** [tensorflow/addons#1354]
As part of #1226, relevant image bounding box operations need to be added to `tfa.image`. List of ops tracked in this issue (tick the op only once the corresponding PR is *merged*):
- [ ] TranslateX BBox
- [ ] TranslateY Only BBoxes
- [ ] ShearX BBox
- [ ] Rotate BBox
- [ ] Cutout Only BBoxes
- [ ] ShearY BBox
- [ ] ShearY Only BBoxes

Reference: https://github.com/google-research/simclr/blob/master/data_util.py

**Comment by Squadrick** [comment]
Similar to #1333, #1353

**Comment by seanpmorgan** [comment]
Per https://github.com/tensorflow/addons/issues/1366#issuecomment-634902190 these features would better fit in:
https://github.com/keras-team/keras-cv
