### ISSUE TITLE
@test_utils.run_all_in_graph_and_eager_modes creates bug while testing with eager mode enabled

### ISSUE THREAD

**Issue by Mainak431** [tensorflow/addons#141]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0 
- TensorFlow Addons installed from (source, PyPi): pypi
- TensorFlow Addons version: 1.12
- Python version and type (eg. Anaconda Python, Stock Python as in Mac, or homebrew installed Python etc): 2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- Is GPU used? (yes/no):
- GPU model (if used):

# In TF 2.0 Eager mode is enabled. by default. 
When testing with this test util I am getting error as i think this is creating a additional session.

class Median2DTest(tf.test.TestCase):

  def _validateMedian_2d(self, inputs, expected_values, filter_shape = (3, 3)):

    values_op = md.median_filter_2D(inputs)
    expected_values = expected_values.numpy()
    values = values_op.numpy()
    self.assertShapeEqual(values, inputs)
    self.assertShapeEqual(expected_values, values_op)
    self.assertAllClose(expected_values, values)

 def testcase(self):
    tf_img = [[[0.32801723, 0.08863795, 0.79119259],
              [0.35526001, 0.79388736, 0.55435993],
              [0.11607035, 0.55673079, 0.99473371]],

             [[0.53240645, 0.74684819, 0.33700031],
              [0.01760473, 0.28181609, 0.9751476 ],
              [0.01605137, 0.8292904,  0.56405609]],

             [[0.57215374, 0.10155051, 0.64836128],
              [0.36533048, 0.91401874, 0.02524159],
              [0.56379134, 0.9028874,  0.19505117]]]

    tf_img = tf.convert_to_tensor(tf_img)
    expt = [[[  0,   0,   0],
            [  4,  71, 141],
            [  0,   0,  0]],

           [[ 83,  25,  85],
            [ 90, 190, 143],
            [  4, 141,  49]],

           [[  0,   0,   0],
            [  4,  71,  49],
            [  0,   0,   0]]]
    expt = tf.convert_to_tensor(expt)
    self._validateMedian_2d(tf_img,expt)

if __name__ == "__main__":
  tf.test.main()

# The above code runs with test OK.

# Now if i add the decorator 

@test_utils.run_all_in_graph_and_eager_modes
class Median2DTest(tf.test.TestCase):

  def _validateMedian_2d(self, inputs, expected_values, filter_shape = (3, 3)):

    values_op = md.median_filter_2D(inputs)
    expected_values = expected_values.numpy()
    values = values_op.numpy()
    self.assertShapeEqual(values, inputs)
    self.assertShapeEqual(expected_values, values_op)
    self.assertAllClose(expected_values, values)

 def testcase(self):
    tf_img = [[[0.32801723, 0.08863795, 0.79119259],
              [0.35526001, 0.79388736, 0.55435993],
              [0.11607035, 0.55673079, 0.99473371]],

             [[0.53240645, 0.74684819, 0.33700031],
              [0.01760473, 0.28181609, 0.9751476 ],
              [0.01605137, 0.8292904,  0.56405609]],

             [[0.57215374, 0.10155051, 0.64836128],
              [0.36533048, 0.91401874, 0.02524159],
              [0.56379134, 0.9028874,  0.19505117]]]

    tf_img = tf.convert_to_tensor(tf_img)
    expt = [[[  0,   0,   0],
            [  4,  71, 141],
            [  0,   0,  0]],

           [[ 83,  25,  85],
            [ 90, 190, 143],
            [  4, 141,  49]],

           [[  0,   0,   0],
            [  4,  71,  49],
            [  0,   0,   0]]]
    expt = tf.convert_to_tensor(expt)
    self._validateMedian_2d(tf_img,expt)

if __name__ == "__main__":
  tf.test.main()

It creates an issue . 

# First it throws a Warning :

W0405 00:52:14.287210 140481921550144 deprecation.py:323] From /home/scholar/anaconda2/lib/python2.7/contextlib.py:84: test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.

# Then the test fails with the error

AttributeError: 'Tensor' object has no attribute 'numpy'

Please fix the issue.

**Comment by Mainak431** [comment]
@seanpmorgan Please fix this issue.

**Comment by seanpmorgan** [comment]
@Mainak431 this error is telling you that you're attempting to call `.numpy()` on a Tensor in graph mode. This fails and is why we run with that decorator on our tests. All addons need to be able to run in either graph or eager. Eager by default does not mean eager only.

If there are questions please ask in your PR #111
