### ISSUE TITLE
Publish developer docker containers on dockerhub

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#1414]
See #1309

**Comment by gabrieldemarmiesse** [comment]
In the long term, we should push the build cache in dockerhub (or some other registry) in the master branch, and then we would be able to reuse the cache in other build or even locally. This is enabled by the docker buildx option  [--cache-from and --cache-to](https://github.com/docker/buildx#--cache-fromnametypetypekeyvalue).

Buildx should be included in docker at some point ( see https://github.com/moby/moby/issues/40379) but I'm unsure of the timeline.

So an option might be to just provide a remote docker cache for users to make sure they always work with an up to date image. But pushing a docker image is easy too and shouldn't cause any issues too so we can do both and then users don't need to `docker build`.

About the docker remote caching, I experimented with it a while ago and it seemed too slow (like actually slower than pulling a docker image, that makes no sense). I hope it gets better in the future.

**Comment by bhack** [comment]
In Tensorflow see also https://github.com/tensorflow/tensorflow/pull/38755

**Comment by seanpmorgan** [comment]
Friendly bump @karmel on this issue brought up here:
https://github.com/tensorflow/addons/issues/1305#issuecomment-612189891

Would it be possible for us to push a developer image to the `tensorflow/` namespace on dockerhub?

**Comment by karmel** [comment]
Ah, sorry for the delay. It sounds like this is technically possible, but we need a policy and someone to review the pushes. @ewilderj @theadactyl -- are you able to help here?

**Comment by bhack** [comment]
Just as a reminder when we will have the developer image I think that we need to refactor the pre-commit hooks cause we will not want to run Docker in Docker just for linting and all the linting tools will be already available in the Dev image.
