### ISSUE TITLE
pip install tensorflow-addon with mac

### ISSUE THREAD

**Issue by Yudonggeun** [tensorflow/addons#142]
Error executing pipe install sensorflow-addons on the Mac.

Error:
"""
  Could not find a version that satisfies the requirement tensorflow_addons (from versions: )
No matching distribution found for tensorflow_addons
"""

**Comment by seanpmorgan** [comment]
Hi, currently we're only uploading linux pypi packages, but we're hoping to have that solved in the near future. Please see #77 

In the meantime you can [build the package from source if you'd like](https://github.com/tensorflow/addons#installing-from-source) but note that you'll need to run against `tf-nightly-2.0-preview`

**Comment by syedalamabbas** [comment]
Even in windows its the same problem 
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>pip install tensorflow-addons
Collecting tensorflow-addons
  ERROR: Could not find a version that satisfies the requirement tensorflow-addons (from versions: none)
ERROR: No matching distribution found for tensorflow-addons
`

**Comment by seanpmorgan** [comment]
Hi @syedalamabbas! Addons will be packaged for Windows, but it is not currently. You can track the progress in #173
