### ISSUE TITLE
./configure.sh fails on mac with conda python 3.7

### ISSUE THREAD

**Issue by armando-fandango** [tensorflow/addons#143]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OSX 10.14.3
- TensorFlow installed from (source or binary): none
- TensorFlow version (use command below): none
- TensorFlow Addons installed from (source, PyPi): source
- TensorFlow Addons version: latest master
- Python version and type (eg. Anaconda Python, Stock Python as in Mac, or homebrew installed Python etc): conda python 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- Is GPU used? (yes/no):
- GPU model (if used):

**Describe the bug**

Running ./configure.sh tries to install nightly-2.0-preview that is not available for the mac.

`fluid:tensorflow-addons armando$ ./configure.sh
Collecting tf-nightly-2.0-preview (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement tf-nightly-2.0-preview (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for tf-nightly-2.0-preview (from -r requirements.txt (line 1))

**Describe the expected behavior**`

**Comment by armando-fandango** [comment]
Depends on fixing of https://github.com/tensorflow/tensorflow/issues/27470

**Comment by seanpmorgan** [comment]
We currently have no way of providing python 3.7 whl's and are waiting for the new BUILD toolchain (see #119 )

Once the toolchain is complete... tf-nightly will begin publishing 3.7 wheels and our configure script will work again. Closing as there is nothing we can do here and as of today we do not support python3.7
