### ISSUE TITLE
LAMB optimizer parses regex patterns improperly

### ISSUE THREAD

**Issue by jarednielsen** [tensorflow/addons#1530]
The [LAMB optimizer](https://github.com/tensorflow/addons/blob/r0.8/tensorflow_addons/optimizers/lamb.py#L45) declares that its `exclude_from_weight_decay` argument should take in a comma-separated string of regex patterns. However, [the code expects a list of regex patterns](https://github.com/tensorflow/addons/blob/r0.8/tensorflow_addons/optimizers/lamb.py#L234) and instead iterates through each character in the string. Thus nearly every call to `_do_use_weight_decay()` returns False.

I attempted to pass in a list to circumvent this bug, but this leads to a `typeguard` error. So there's no easy way around this in the meantime. A similar bug exists for `exclude_from_layer_adaption`. 

Two proposed fixes, and I'm happy to contribute either:
- Change the desired datatype from `Optional[str]` to `List[str]`. This would be preferred, and match the style of other implementations in the TensorFlow repo. [See here](https://grep.app/search?q=exclude_from_weight_decay&filter[repo.pattern][0]=tensorflow/) for a list of examples. My PR is open at https://github.com/tensorflow/addons/pull/1532.
- Add `.split(',')` to `exclude_from_weight_decay` and `exclude_from_layer_adaption` in the constructor.

**Comment by gabrieldemarmiesse** [comment]
This has been fixed and ported to the 0.8.x branch.
