### ISSUE TITLE
Update the CI badges on central README

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#1534]
Currently these badges point to workflows that we no longer run:
https://github.com/tensorflow/addons/actions?query=workflow%3Amanylinux-nightly

We can't update it to point toward our primary CI workflow though since this runs on PRs that are created as well as those that have been merged. Any good ideas jump out to anyone?

**Comment by gabrieldemarmiesse** [comment]
> We can't update it to point toward our primary CI workflow though since this runs on PRs that are created as well as those that have been merged.

I think that github actions already takes care of this.

https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository

> A common place to add a status badge is in the README.md file of your repository, but you can add it to any web page you'd like. By default, badges display the status of your default branch (usually master).
