### ISSUE TITLE
Standardize formatting

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#16]
Would like to standardize repository style using a code formatter. @facaiy suggested https://github.com/google/yapf which looks like it would work very nicely. 

In the future this should be tied in with our CI testing

**Comment by facaiy** [comment]
yapf cannot handle document correctly, I once used docformatter tools: https://pypi.org/project/docformatter/ 
- currently automatically formats docstrings to follow a subset of the PEP 257 conventions.

**Comment by lgeiger** [comment]
One other very popular code formatter to consider would be https://github.com/ambv/black

**Comment by seanpmorgan** [comment]
Thanks, I've used black extensively on other projects and love it. I didn't mention it because I didn't want to argue for its departures from PEP8, but it's certainly an option.

**Comment by facaiy** [comment]
@karmel Hi, Karmel. Do you have any suggestion?

**Comment by karmel** [comment]
There are two pieces here-- autoformatting, and linting when we run tests to block merges with lint errors.

I think you should pick the tool you all prefer, though it's complicated by the fact that TF adheres to the [Google Python style guide](http://google.github.io/styleguide/pyguide.html), which deviates slightly from PEP8 (ie, two-space tabs). Ideally, then, a formatter that is configurable would be best.

For TF Models, we didn't set up an autoformatter, but we did set up a [pylint check](https://github.com/tensorflow/models/blob/master/official/utils/testing/scripts/presubmit.sh#L44) with a [custom rcfile](https://github.com/tensorflow/models/blob/master/official/utils/testing/pylint.rcfile) that approximated Google's style guidelines. We can copy that here if you want, or use whatever you think best.

**Comment by facaiy** [comment]
@karmel Thank your for the input. I think it's better to stick with PEP 0008, which is supported by nearly all python toolchains (IDE, text editor, etc). 

Yes, both yapf and pylint are configurable. I'll submit a shell script later for the issue.
