### ISSUE TITLE
Remove `__init__.py` in custom_ops directory

### ISSUE THREAD

**Issue by facaiy** [tensorflow/addons#163]
When reviewing #140, I find we forget to remove init python file in tensorflow_addons/custom_ops?
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/custom_ops/__init__.py

cc @seanpmorgan Sean, what do you think?

**Comment by seanpmorgan** [comment]
Yes no need for this file. As you mention its leftover from the custom op re-org
