### ISSUE TITLE
Make our CI faster

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [tensorflow/addons#1655]
Currently our CI take ~30 min to run. After some analysis, here is the critical path and the big steps:

* Building the wheel on linux: 25m
  * pull the docker image: 3m
  * install TF and dependencies: 2m
  * build CPU and GPU ops: 8m (building CPU ops only takes 2m in another build, so we can assume 6m for building the GPU ops)
  * Run all tests: 6m, I should re-enable pytest-xdist here.
  * Rebuild all ops for the wheel: 5m (because the bazel cache was cleaned before)
* Test the release wheel on Windows: 4m10s
* Upload to pypi, but not really: 25s.

I'll work toward making this faster, help and ideas are welcome too of course.

**Comment by bhack** [comment]
Can you point on the CI scripts sources?
Can we take any speed-up with https://github.com/actions/cache?

**Comment by bhack** [comment]
See also this thread https://github.community/t5/GitHub-Actions/Cache-docker-images/td-p/44978

**Comment by gabrieldemarmiesse** [comment]
Caching may help, but it may also make things slower. It's usually hard to know until we try.

**Comment by bhack** [comment]
I've not built the linux wheel Dockerfile with the [progress option](https://docs.docker.com/develop/develop-images/build_enhancements/) but I suppose that in `25m` the main problem is that this is [`/root/.cache/bazel`](https://github.com/tensorflow/addons/blob/master/tools/docker/build_wheel.Dockerfile#L39) is an empty volume when you run the Action vs local build right?

**Comment by bhack** [comment]
I've asked if we there is ware cache in action/cache the mount of buildkit `RUN --mount=type=cache` at https://github.com/actions/cache/issues/260.

**Comment by bhack** [comment]
In the meantime I think that
```
--cache-from=type=registry,ref=$CACHE_TAG
--cache-to=type=registry,ref=$CACHE_TAG,mode=max
```
could work if we have a registry to push. See https://medium.com/titansoft-engineering/docker-build-cache-sharing-on-multi-hosts-with-buildkit-and-buildx-eb8f7005918e

**Comment by gabrieldemarmiesse** [comment]
I did that a while ago, didn't seem very fast to me at the time. If someone wants to try again, a pull request is welcome: https://github.com/tensorflow/addons/pull/1043

**Comment by seanpmorgan** [comment]
@gabrieldemarmiesse Can this be closed or are there pending actions we need to do?

**Comment by gabrieldemarmiesse** [comment]
Let's close it as there is no obvios path right now

**Comment by bhack** [comment]
If you want you could subscribe to https://github.com/tensorflow/build/issues/5 cause we are marginally talking also about the bazel cache for github actions. 
That ticket was created yesterday by build the on of SIG Build leader (in google team) after our chat on the SIG Build Gitter channel.
