### ISSUE TITLE
Minimal examples in Contribution policy

### ISSUE THREAD

**Issue by bhack** [tensorflow/addons#1656]
Can we request to contribute an example or to point to third party repo with samples in the [Contributing Policy](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md)?

**Comment by gabrieldemarmiesse** [comment]
What do you mean exactly? That each new features should have detailed examples?

**Comment by bhack** [comment]
Yes, in some case it could be something simple like forked from the test itself. In other cases could be like a notebook tutorial or a py example.

**Comment by bhack** [comment]
In many cases I think that this example could be expanded when the contribution is in the same sub-namespace.

**Comment by gabrieldemarmiesse** [comment]
Sure, if there is an example, I believe the best place for that would be the docstring since we have control over it. Feel free to open a pull request to edit the contributing guidelines, I'll review it.

**Comment by bhack** [comment]
https://github.com/tensorflow/addons/pull/1659
