### ISSUE TITLE
Add example information to contribution guidelines

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#168]
I wanted to start an issue to discuss our examples. I think it's probably best that we upload a slightly modified [template](https://github.com/tensorflow/docs/blob/master/tools/templates/notebook.ipynb) which includes whatever changes we'd like for TFA. 

Some notable changes:
* Personally I think images should be allowed in the saved outputs. Git diffs are tough, but with reviewNB I think it's fine?
* Unless I'm doing something wrong...I believe we need to instruct users to write in the colab notebook link as if it were merged (for example [this URL](https://github.com/tensorflow/addons/pull/166/files#diff-e58588a57dedf057b058b087ed4696f3R64) which does not yet exist)
* I'm in favor of just removing the script examples and having `tensorflow_addons/examples` just contain notebooks with links to colab. Certainly open for discussion though.

If nothing else I think we need to add some more detailed instructions to our CONTRIBUTING guide.

Some PRs that are waiting on this discussion #166 #167 #144

**Comment by seanpmorgan** [comment]
So thinking about this a bit more, I think we can probably get away with some detailed information in the CONTRIBUTING guide and forgo an extra template.

**Comment by amanp592** [comment]
Hey! @seanpmorgan can i help you with this!?

**Comment by seanpmorgan** [comment]
Hi @amanp592

Sure, you're more than welcome to submit a PR for this! The directions for adding an example are a little tricky seeing as there's some colab notebook work which is not extremely intuitive, but you can follow the information in the template linked above and we can iterate on the PR.

Welcome to Addons!

**Comment by amanp592** [comment]
@seanpmorgan Thankyou Sir, will soon update you with my progress!

**Comment by amanp592** [comment]
@seanpmorgan what i am assuming here to be done is to give a detailed information in `CONTRIBUTION` guide and update the `Colab links` of the present notebooks(for the ones it shows not found). 

Current `CONTRIBUTION` guide does not have anything on `reviewNB`,  `Colab` notebook links. I think we should mention them too so that the new contributions will have no problem.

Please correct if i am wrong anywhere!

**Comment by seanpmorgan** [comment]
Yes updating the CONTRIBUTING file should be what we need to do. Please let us know if any of the colab links in the current notebooks do not work.

The tricky thing is that the links have to be written so that they'll be in their correct spot on the master branch once they're merged in. While they're in PR they'll be broken links.

For example in the PR the user should link to:
`https://colab.research.google.com/github/tensorflow/addons/blob/master/examples/foo.ipynb`

But until the PR is completed that link won't exist.

**Comment by amanp592** [comment]
The `CONTRIBUTION` guide will be according to the [template]('https://github.com/tensorflow/docs/blob/master/tools/templates/notebook.ipynb') you provided. 

I'll work on it now and soon send a PR regarding this.
