### ISSUE TITLE
Build out examples with working colab notebooks

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#17]
Would be nice to mirror the TF2 doc style of colab notebooks being first-class tutorials.

I think it's also a good idea to require colab notebooks for new contributions in order to showcase their benefits and best practices. Certainly won't be possible/necessary for everything.

**Comment by armando-fandango** [comment]
Let us refactor this issue with separate issue for each specific example that we propose to build. That way it would be easier to know and close out when the issue the done.

**Comment by Smokrow** [comment]
Should we showcase the benefit of the implementations with some kind of before/after comparison and some kind of explanation? Or more like a basic usage?

**Comment by seanpmorgan** [comment]
I think anytime we can compare it to some control that'd be great. For example optimizers could be compared to SGD on some demo mnist model.

This won't always be appropriate though, and basic usage is definitely useful to have examples for.

**Comment by seanpmorgan** [comment]
Closing this as we'll create specific example requests in the coming days.
