### ISSUE TITLE
Bug: WeightNorm variable aggregation

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#171]
**Describe the bug**

Since https://github.com/tensorflow/tensorflow/commit/68c4b5234f2c722031f4386f31b8e48a4ec31b2b our nightly test is failing with the error: `ValueError: Invalid variable aggregation mode: VariableAggregationV2.MEAN for variable: g`

@allenlavoie would you be able to explain this error a little more? The call in addons is:
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/layers/wrappers.py#L128 and I'm not following why that is an invalid mode?

**Comment by allenlavoie** [comment]
Yep, that's annoying. Guess we need a hacky isinstance check there.

**Comment by allenlavoie** [comment]
Should be fixed by https://github.com/tensorflow/tensorflow/commit/138bbd7f318cc557230183434320d387c57633ff. Thanks for the report.
