### ISSUE TITLE
Finish migration of keras_contrib to here

### ISSUE THREAD

**Issue by WurmD** [tensorflow/addons#1710]
**"Keras-contrib is deprecated. Use TensorFlow Addons."**

But https://github.com/keras-team/keras-contrib/tree/master/keras_contrib/applications is not here yet.

In particular it includes https://github.com/keras-team/keras-contrib/blob/master/keras_contrib/applications/resnet.py#L437 ResNet18's network definition that is not included anywhere else

**Relevant information**
- Are you willing to contribute it (yes/no): no
- Are you willing to maintain it going forward? (yes/no): no
- Is there a relevant academic paper? (if so, where): na
- Is there already an implementation in another framework? (if so, where): na
- Was it part of tf.contrib? (if so, where): na

**Who will benefit with this feature?**
Any user looking for a smaller network

**Comment by gabrieldemarmiesse** [comment]
Models like resnet18 are supposed to go to TF garden if I'm not mistaken. @seanpmorgan do you have any insight here?

**Comment by seanpmorgan** [comment]
Hi @WurmD . So much of keras-contrib fits within the Addons scope, but full models was deemed out of scope. TF model garden is likely the best place for them, but there may be room for discussion regarding a more community driven repository. Perhaps keras-team/keras repository (after it gets moved out of TF core) could be the landing place for some architectures?

Sorry for the not super helpful response, but Addons is not the right place so I'm going to close this issue. Feel free to continue discussion if it helps though... it's clearly a gap but not one Addons is likely to fill.
