### ISSUE TITLE
Dropping support for tensorflow < 2.2.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [tensorflow/addons#1734]
We have three pull requests that need TF 2.2 and above: #1733 #1726 #905 

They are blocked until we drop support, since Addons 0.9 was released with support for both tf 2.1 and 2.2, I don't think it's going to be a very big inconvenience for users if we drop support for 2.1 now. They have a good fallback.

**Comment by seanpmorgan** [comment]
Agree. Going to mark those PRs as blocked until we swap our CI to only test 2.2
