### ISSUE TITLE
Remove all elements from allowlists in source_code_test.py

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [tensorflow/addons#1735]
We enforce some rules in [source_code_test.py](https://github.com/tensorflow/addons/blob/master/tools/testing/source_code_test.py) about what API we can't use in addons. (no private api, no tf.compat.v1, and no experimental API in user-facing code).

We didn't enforce it in some files because they didn't respect the rules before the check was put into place. Replacing the problematic code takes some time, so this is why there are blacklists now. To track the progress. Replacing some APIs by public ones can be very easy or very hard depending on what the code is about. We'll gladly take pull request removing some elements from the blacklists. When we remove all elements, we can remove the blacklists entirely.

It's possible to copy the code needed into addons, or to find another similar API as long as the effect is the same.

**Comment by fsx950223** [comment]
#1324 
Rollback?

**Comment by gabrieldemarmiesse** [comment]
@fsx950223  I think we need to copy the code of the wrapper in Addons (we may already have some of it) and use that instead.

**Comment by fsx950223** [comment]
> @fsx950223 I think we need to copy the code of the wrapper in Addons (we may already have some of it) and use that instead.

It's difficult if the API depends on lots of internal APIs.

**Comment by gabrieldemarmiesse** [comment]
We can limit the functionality to our use cases if that can help. For example, we don't support tf.compat.v1. The wrapper in TF seems fairly small, I think we should be able to port it.

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
