### ISSUE TITLE
addons 0.9 for osx 10.12

### ISSUE THREAD

**Issue by ruiguo-bio** [tensorflow/addons#1737]
I cannot install addon 0.9 by pip on osx 10.12. I think it requires 10.13, if I would like to install it on 10.12, is there any way to do it?

**Comment by seanpmorgan** [comment]
Hi @ruiguo-bio, unfortunately 10.13 is the oldest macOS we built the wheels for. However, you should be able to install it from source:
https://github.com/tensorflow/addons#cpu-only-custom-ops

You'll need to install bazel locally though (can be installed from brew)

**Comment by ruiguo-bio** [comment]
Hi, I tried use bazel to build addons from github source code, but it outputs a file tensorflow_addons-0.10.0.dev0-cp36-cp36m-macosx_10_13_x86_64.whl, which still cannot be used on my 10.12 platform. Any idea to solve that?

**Comment by ruiguo-bio** [comment]
I modified the build_pip_pkg.sh file the line with 10_13 to 10_12, that works now!
