### ISSUE TITLE
Standardize all optimizer serialization checks

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#1747]
Part of #992. We need to crate a common serialization check for optimizers similar to `check_metrics_serialization`:
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/testing/serialization.py#L10

Ideally this will extend the base `check_config` method, but we noticed in #1728 that there are some issues that need to be adressed.

After this is complete we can move on to serialization checks for all submodules.

**Comment by tacho090** [comment]
I'm interested in helping. Could you assign this to me please?

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
