### ISSUE TITLE
On the usage of ContrastiveLoss

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/addons#1757]
Hi.

I am following this tutorial from the keras.io website: https://keras.io/examples/mnist_siamese/. 

I am replacing the `contrastive_loss` as specified there with `tfa.losses.ConstrastiveLoss` and I am not getting consistent results (in particular, the results are random). I think I have matched the requirements of `ConstrastiveLoss`. Here's the [notebook](https://colab.research.google.com/gist/sayakpaul/4a5818af29c556a7ee346995de5ebfb3/scratchpad.ipynb) that reproduces this issue. 

Thanks in advance for your help.

**Comment by AakashKumarNain** [comment]
@sayakpaul Thanks for reporting it. We will look into it

**Comment by henry-eigen** [comment]
I can take a look at this if no one else is already working on it.

**Comment by seanpmorgan** [comment]
That'd be great thanks @henry-eigen! Please let us know your findings, and also be sure to comment in the thread if for some reason you can't work on the issue anymore.

**Comment by henry-eigen** [comment]
@sayakpaul @seanpmorgan I think this issue may have already been fixed. I was able to replicate the issue using tfa version 0.8.3, as is used in the notebook, or version 0.9.1. Building from the master branch, however, I got the expected behavior. I think it was this [commit](https://github.com/tensorflow/addons/commit/10f718f9ca3862e56ef3abb5ccb9360372af047a) that fixed it.

**Comment by AakashKumarNain** [comment]
Thanks @henry-eigen for looking into it. @sayakpaul if you can please confirm this, we will close the issue. I looked into the code as well and on the first look, I didn't find any bug.

**Comment by sayakpaul** [comment]
Apologies for the late reply. Seems like the solution for now is to install tfa from source. I will check it and report back accordingly. As @henry-eigen already checked it (thanks for that :)) I think we can close the issue.

**Comment by AakashKumarNain** [comment]
@sayakpaul I don't think you need to install from the source. Just upgrade tfa to the latest version and let us know if you face any issues

**Comment by sayakpaul** [comment]
Point noted. Will get back :)
