### ISSUE TITLE
Deprecate ImageProjectiveTransformV2

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/addons#1779]
`ImageProjectiveTransformV2` seems to be integrated into core TF at https://github.com/tensorflow/tensorflow/commit/26992815bf7ee136c49f658596a9fbde7881d425 in Jan. We have to deprecate the use of it.

https://github.com/tensorflow/addons/blob/master/tensorflow_addons/custom_ops/image/cc/kernels/image_projective_transform_op.cc

Also, it was unclear to me that `ImageProjectiveTransformV2` has been integrated into TF many months ago. Maybe we should check new stuff in TF regularly. Thanks @bhack for pointing out!

cc @tensorflow/sig-addons-maintainers

**Comment by bhack** [comment]
@seanpmorgan It will be hard to make a guard about this and routing to an upstream process that we are defining in https://github.com/tensorflow/community/issues/239 like for AMD GELU PR. Cause in this case the code it was not landing with a public PR but it was in the internal google review pipeline. 
@karmel Do you think that the checklist about Addons (or SIG)/upstreaming could be done also in the internal revision pipeline?

**Comment by bhack** [comment]
@tanzhenyu suggested to talk with us about image processing at https://github.com/tensorflow/addons/issues/1226#issuecomment-609060765. 
Could we propose this topic for the next meeting agenda and invite him?
So we could clarify `tf.image`, `tfa.image`, and Keras image preprocessing relationship.

**Comment by bhack** [comment]
@WindQAQ Also, now it is official https://summerofcode.withgoogle.com/projects/#4863446367076352

**Comment by seanpmorgan** [comment]
@bhack this issue is for what needs to be done to deprecate ImageProjectTransformV2. 

Please create a new issue to discuss how we can clarify the clarify `tf.image`, `tfa.image`, and Keras image preprocessing relationship. Alternatively, add it to the meeting agenda. and let us know who you want us to try to get to the meeting for in person discussion.

**Comment by tanzhenyu** [comment]
> @bhack this issue is for what needs to be done to deprecate ImageProjectTransformV2.
> 
> Please create a new issue to discuss how we can clarify the `tf.image`, `tfa.image`, and Keras image preprocessing relationship. Alternatively, add it to the meeting agenda. and let us know who you want us to try to get to the meeting for in person discussion.

Yeah I believe those are separate issues. For `ImageProjectiveTransformV2` we could either 1) completely remove it from tfa.image, or 2) keep a reference to core.

**Comment by AakashKumarNain** [comment]
I believe any redundancy is bad. If we have this in TF core, then I suggest we start with a deprecation warning and remove it gradually in the next version

**Comment by gabrieldemarmiesse** [comment]
Thanks @bhack  for bringing this to our attention! I believe we should replace the body of our implementation and call the one in TF while keeping the same API on our side for backward compatibility. If the TF implementation is the same as ours, the tests should pass. Though we should also keep the C++/CUDA code on our side for a while because if we remove the custom op, people trying to load their models will get an error.

But the biggest problem right now is that we can't access their implementation because it's not exposed in the public API. We could ask the TF team to expose it for TF 2.3?

**Comment by bhack** [comment]
We could talk in a new ticket but I think that is the normality of the bottom-up process about recognize the single instance of an issue and trying to find the root process/generalizzation that it is creating this kind of issue. 
If we are working on the same or overlapped things but we don't know what we are planning on both sides we will go to generate more and more of these issues in image operations.

**Comment by seanpmorgan** [comment]
> We could talk in a new ticket but I think that is the normality of the bottom-up process about recognize the single instance of an issue and trying to find the root process/generalizzation that it is creating this kind of issue.
> If we are working on the same or overlapped things but we don't know what we are planning on both sides we will go to generate more and more of these issues in image operations.

If we do it that way then we end up with the mess that is the AutoAugment issue. We don't want to have to dig through issues related to a larger topic to see the high level discussion. Feel free to link to the lower level issues in the higher level discussion not the other way around.

**Comment by gabrieldemarmiesse** [comment]
@bhack we totally agree with your point about duplication, but the best place to discuss a new process is a new standalone issue where is referenced all other issues where the pain point is appearing.

**Comment by gabrieldemarmiesse** [comment]
Cleaning up the discussion for the future readers.

**Comment by bhack** [comment]
I removed all the comments here and also the original comment on the @WindQAQ PR that generated this ISSUE.
