### ISSUE TITLE
TripletSemiHardLoss with inception model

### ISSUE THREAD

**Issue by Fabian-Leon** [tensorflow/addons#1783]
Hi, I'm trying to use TripletSemiHardLoss() with a inception model but it doesn't work. Actually I use colab and my code is:
```
image_generator = ImageDataGenerator(rescale=1./255)
train_data_gen = image_generator.flow_from_directory(directory=path,
                                                     batch_size=32,
                                                     shuffle=True,
                                                     target_size=(224, 224),
                                                     class_mode='sparse')
base_model = InceptionV3(include_top=False, weights='imagenet', input_shape=(224, 224, 3))
x_top = base_model.output
x_out = Flatten()(x_top)
x_out = Dense(256, name='nactivation', activation=None)(x_out)
x_out = Lambda(lambda x: tf.math.l2_normalize(x, axis=1))(x_out)
model = Model(base_model.input, x_out)
model.summary()
model.compile(optimizer=optimizers.Adam(lr=0.001),
              loss=tfa.losses.TripletSemiHardLoss(), metrics = ['accuracy'])
model.fit(train_data_gen, epochs=10)
```
This shows the following error:

```
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError:  Can not squeeze dim[0], expected a dimension of 1, got 32
	 [[node loss_14/lambda_8_loss/TripletSemiHardLoss/weighted_loss/Squeeze (defined at /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3009) ]] [Op:__inference_keras_scratch_graph_851796]

Function call stack:
keras_scratch_graph
```

However when I use a sequential keras model it works fine this is the code:

```
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(filters=64, kernel_size=2, padding='same', activation='relu', input_shape=(224, 224, 3)),
    tf.keras.layers.MaxPooling2D(pool_size=2),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Conv2D(filters=32, kernel_size=2, padding='same', activation='relu'),
    tf.keras.layers.MaxPooling2D(pool_size=2),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(256, activation=None),  # No activation on final dense layer
    tf.keras.layers.Lambda(lambda x: tf.math.l2_normalize(x, axis=1))  # L2 normalize embeddings
])
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tfa.losses.TripletSemiHardLoss())
image_generator = ImageDataGenerator(rescale=1./255)
train_data_gen = image_generator.flow_from_directory(directory=path,
                                                     batch_size=32,
                                                     shuffle=True,
                                                     target_size=(224, 224),
                                                     #classes = list(CLASS_NAMES),
                                                     #color_mode='grayscale',
                                                     class_mode='sparse')
model.fit(train_data_gen, epochs=10, steps_per_epoch=100)
```
I think it may be an error with the data format, but I'm not sure.

**Comment by bhack** [comment]
https://stackoverflow.com/questions/59728921/tripleloss-from-tensorflow-add-on-give-reshape-error

**Comment by Fabian-Leon** [comment]
> https://stackoverflow.com/questions/59728921/tripleloss-from-tensorflow-add-on-give-reshape-error

yes, try to do this but it still doesn't work, it gives me the same error. It works with tf.keras.Sequential but when I used this in the inception loss it doesn't work

**Comment by bhack** [comment]
Yes sorry I pasted the other ticket. I wanted to make a reference to https://stackoverflow.com/questions/61362751/invalidargumenterror-when-training-with-tripletsemihardloss-and-keras-sequence

**Comment by Fabian-Leon** [comment]
> Yes sorry I pasted the other ticket. I wanted to make a reference to https://stackoverflow.com/questions/61362751/invalidargumenterror-when-training-with-tripletsemihardloss-and-keras-sequence

Yes, I think that is about the same error, but in that thread nobody responds yet.

**Comment by bhack** [comment]
@Fabian-Leon In the meantime, it could be useful if you can, to open a very minimal test PR with you `fit` use case  like e.g https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/tests/loss_test.py#L269.
You need to place the test in https://github.com/tensorflow/addons/blob/master/tensorflow_addons/losses/triplet.py

Lets the CI to fail in the PR on your test.

**Comment by WindQAQ** [comment]
Hi @Fabian-Leon, can you provide the code to reproduce the issue? I try to follow your code snippet but it works. (let the nan loss alone because images are the same)

https://colab.research.google.com/drive/13khyT64lIYiZx_SJIT9GPOiFfJuwXgWT?usp=sharing

**Comment by WindQAQ** [comment]
@Fabian-Leon I've updated the link :-)

**Comment by Fabian-Leon** [comment]
> Hi @Fabian-Leon, can you provide the code to reproduce the issue? I try to follow your code snippet but it works. (let the nan loss alone because images are the same)
> 
> https://colab.research.google.com/drive/13khyT64lIYiZx_SJIT9GPOiFfJuwXgWT?usp=sharing

OMG! yes it works with my data! I've spent too much time on this, but I don't understand why if I use your same code but import libraries differently, it doesn't work, this is my code.

https://colab.research.google.com/drive/1TXtan1x7ZmaSwcKfZggbRYavlhfUqX-Q?usp=sharing

**Comment by bhack** [comment]
@Fabian-Leon https://github.com/keras-team/keras/releases/tag/2.4.0

**Comment by WindQAQ** [comment]
Seems that it is version issue. Hopefully, it works. The best practice to use keras in TF is directly using `tf.keras.*`. Feel free to reopen the issue if you have any further problem.
