### ISSUE TITLE
Misleading flow field in dense_image_warp / sign seems "wrong"

### ISSUE THREAD

**Issue by olesalscheider** [tensorflow/addons#1786]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow version and how it was installed (source or binary): source master
- TensorFlow-Addons version and how it was installed (source or binary): source master
- Python version: 3.6.7
- Is GPU used? (yes/no): yes

**Describe the bug**

While the implementation of `dense_image_warp` follows the documentation, I think that it does not make sense.

The goal of the function is to warp an output image back to a source image given a flow field.
From the description it makes sense to assume that the flow field is forward optical flow from the source to the output image.
In this case the flow field has to be added to the "source" coordinates to find the corresponding "output" coordinates when doing the lookup.
This is for example what happens in the original PWCNet implementation:

https://github.com/NVlabs/PWC-Net/blob/master/PyTorch/models/PWCNet.py#L157

But this is not what happens in `dense_image_warp`:

https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/dense_image_warp.py#L238

An alternative assumption could be that the flow field is the backward optical flow. In this case it makes sense to calculate the difference. But then the queried coordinates of the flow field must match these of the "output" image and not these of the "source" image (which is difficult). Or alternatively you have to loop over all coordinates c of the "output" image and write them to c - flow(c) (which leaves holes).

Of course one interpretation could be that the expected flow field is the negative forward optical flow. But this should be clearly stated in the documentation. Otherwise it is misleading at best.

I am happy to provide a patch if you tell me what the desired interpretation is. Right now I am a bit hesitant to change the behaviour of the function.

**Comment by WindQAQ** [comment]
@olesalscheider Thanks for catching this! I would suggest that we can update the documentation to make it more precise. Feel free to open an PR and request my review! Thanks!

**Comment by olesalscheider** [comment]
Fixed
