### ISSUE TITLE
Why this isn't included in main tensorflow?

### ISSUE THREAD

**Issue by saahiluppal** [tensorflow/addons#1787]
Tensorflow addons have a large no of very useful features used in day to day projects. 
But why these aren't included in main tensorflow instead?

**Comment by bhack** [comment]
The addons features could go in the "main" tensorflow repo.
We are trying to improve the migration/upstreaming process. If you want to contribute check https://github.com/tensorflow/community/pull/241

**Comment by saahiluppal** [comment]
Looking forward for contribution
