### ISSUE TITLE
Cohen kappa metrics value provided by tfa is not matching with sklearn calculation 

### ISSUE THREAD

**Issue by yuvaramsingh94** [tensorflow/addons#1822]
Hi all, i am currently using tfa Cohen kappa metrics to monitor my keras training of a model . i observed a strange behavior where during training, the tfa cohen kappa reports a value for validation dataset . but, when i test the performance over the same validation dataset with sklearn, it reports a different number. there are huge disparity between the numbers reported between tfa and sklearn.

**Comment by AakashKumarNain** [comment]
Can you please provide a minimal code to reproduce?

**Comment by yuvaramsingh94** [comment]
Hi @AakashKumarNain unfortunately i am not able to produce the same error again. thanks for replaying . i will close this thread for now .
