### ISSUE TITLE
Testcase of tfa.image.sharpness is not robust

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/addons#1828]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18/04
- TensorFlow version and how it was installed (source or binary): binary
- TensorFlow-Addons version and how it was installed (source or binary): source
- Python version: provided docker image
- Is GPU used? (yes/no): no

**Describe the bug**
The [testcase](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/tests/color_ops_test.py#L67-L76) of `tfa.image.sharpness` is not robust, where the absolute tolerance is set to 1 for uint8. If setting it to 0, the testcase fails. The link down below shows the results are very different.

```
#23 168.9 factor = 0.5
#23 168.9
#23 168.9     @pytest.mark.parametrize("factor", [0, 0.25, 0.5, 0.75, 1])
#23 168.9     def test_sharpness_with_PIL(factor):
#23 168.9         np.random.seed(0)
#23 168.9         image = np.random.randint(low=0, high=255, size=(10, 5, 5, 3), dtype=np.uint8)
#23 168.9         sharpened = np.stack(
#23 168.9             [ImageEnhance.Sharpness(Image.fromarray(i)).enhance(factor) for i in image]
#23 168.9         )
#23 168.9         np.testing.assert_allclose(
#23 168.9 >           color_ops.sharpness(tf.constant(image), factor).numpy(), sharpened, atol=0
#23 168.9         )
#23 168.9 E       AssertionError:
#23 168.9 E       Not equal to tolerance rtol=1e-07, atol=0
#23 168.9 E
#23 168.9 E       Mismatched elements: 59 / 750 (7.87%)
#23 168.9 E       Max absolute difference: 255
#23 168.9 E       Max relative difference: 6.53846154
#23 168.9 E        x: array([[[[172,  10, 127],
#23 168.9 E                [140,  47, 170],
#23 168.9 E                [196, 151, 117],...
#23 168.9 E        y: array([[[[172,  10, 127],
#23 168.9 E                [140,  47, 170],
#23 168.9 E                [196, 151, 117],...
```

**Code to reproduce the issue**

https://colab.research.google.com/drive/1Lwa_FFhvk_DsUoLzq9DBSWi9ZKWNdQtK?usp=sharing

**Comment by bhack** [comment]
@WindQAQ all your colab are private :smile:

**Comment by WindQAQ** [comment]
> @WindQAQ all your colab are private

@bhack Thanks for the reminder! I've changed the permission. Please let me know if they are still private :-)

**Comment by bhack** [comment]
It was almost ported from the official code https://github.com/tensorflow/models/blob/master/official/vision/image_classification/augment.py#L456-L482

We have just a different approach to casting in our code.

**Comment by WindQAQ** [comment]
Testing against uint8 is super hard as `tf.nn.depthwise_conv2d` does not support integer computation. For example, 2.99999999 is 3 in floating point, but when casting (floor operation) to uint8, it becomes 2 :-(

My opinion is not to use pillow, which is uint8 anywhere, as ground truth of testcase. However, this function tries to mimic the functionality in pillow...

Also, the testcases in the original repo do not really verify the correctness of sharpness's implementation.
https://github.com/tensorflow/models/blob/master/official/vision/image_classification/augment_test.py

**Comment by bhack** [comment]
> Also, the testcases in the original repo do not really verify the correctness of sharpness's implementation.
https://github.com/tensorflow/models/blob/master/official/vision/image_classification/augment_test.py

And is it not under `research` folder :wink:

**Comment by gabrieldemarmiesse** [comment]
The implementation might be slightly different. Maybe asking the atol to be lower than 1 is too much when working in uint8? Maybe I'm missing something.

**Comment by WindQAQ** [comment]
I assume the implementation should be the same with the one that we test against so the output should totally match. If they are different, then yep, maybe the value of 1 is negligible in for uint8.
