### ISSUE TITLE
tfa.image.equalize is not compatible with tf.data.Dataset

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/addons#1829]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab
- TensorFlow version and how it was installed (source or binary): 2.2.0
- TensorFlow-Addons version and how it was installed (source or binary): tfa-nightly
- Python version: 3.6
- Is GPU used? (yes/no): no

**Describe the bug**
The error raises if using `tfa.image.equalize` with `tf.data.Dataset`. The error is either
```
OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution
```
or
```
OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did not convert this function.
```
depending on whether `tf.function` is used.

Seems that there are something mysterious about the subgraph in `tf.data.Dataset`. The direct fix is to use `tf.cond` instead of python control flow, but it might violate TF 2.x style.

**Code to reproduce the issue**

https://colab.research.google.com/drive/1B2Bl0Dwmto7sN8rqRodrtXEtZdp07e0w?usp=sharing

**Comment by bhack** [comment]
https://github.com/tensorflow/addons/pull/1830

**Comment by WindQAQ** [comment]
For tracking, this is related to tensorflow/tensorflow#26091 and tensorflow/tensorflow#26602.

**Comment by bhack** [comment]
@WindQAQ It was `map_fn`. My PR was merged in Tensorflow https://github.com/tensorflow/tensorflow/pull/39541
