### ISSUE TITLE
tfa.layers.MultiHeadAttention

### ISSUE THREAD

**Issue by 190407543** [tensorflow/addons#1843]
tfa.layers.MultiHeadAttention
corrected as below

after
!pip install tensorflow-addons

import tensorflow_addons as tfa
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-da33c24ddbfa> in <module>()
     92 
     93 
---> 94 mha = tfa.layers.MultiHeadAttention(head_size=512, num_heads=8)
     95 #query =(32, 20, 200)) # (batch_size, query_elements, query_depth)
     96 #key = ((32, 15, 300)) # (batch_size, key_elements, key_depth)

AttributeError: module 'tensorflow_addons.layers' has no attribute 'MultiHeadAttention'

____
original as below:

AttributeError Traceback (most recent call last)
in ()
92
93
--> 94 mh-a = tfa.layers.MultiHeadSelfAttention(head_size=512, num_heads=8)
95 #query =(32, 20, 200)) # (batch_size, query_elements, query_depth)
96 #key = ((32, 15, 300)) # (batch_size, key_elements, key_depth)

AttributeError: module 'tensorflow_addons.layers' has no attribute 'MultiHeadSelfAttention'

System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):colab
TensorFlow version and how it was installed (source or binary):colab
TensorFlow-Addons version and how it was installed (source or binary):
Python version:3
Is GPU used? yes
Describe the bug
AttributeError: module 'tensorflow_addons.layers' has no attribute 'MultiHeadSelfAttention'

Code to reproduce the issue
mh-a = tfa.layers.MultiHeadSelfAttention(head_size=512, num_heads=8)
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
tensorflow official tfa.layers.MultiHeadSelfAttention example
Other info / logs

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by 190407543** [comment]
tfa.layers.MultiHeadAttention

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-6ba7436f86f5> in <module>()
     92 
     93 
--> 94 mh-a = tfa.layers.MultiHeadSelfAttention(head_size=512, num_heads=8)
     95 #query =(32, 20, 200)) # (batch_size, query_elements, query_depth)
     96 #key = ((32, 15, 300)) # (batch_size, key_elements, key_depth)

AttributeError: module 'tensorflow_addons.layers' has no attribute 'MultiHeadSelfAttention'

System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):colab
TensorFlow version and how it was installed (source or binary):colab 
TensorFlow-Addons version and how it was installed (source or binary):
Python version:3
Is GPU used? yes
Describe the bug
AttributeError: module 'tensorflow_addons.layers' has no attribute 'MultiHeadSelfAttention'
A clear and concise description of what the bug is.

Code to reproduce the issue
mh-a = tfa.layers.MultiHeadSelfAttention(head_size=512, num_heads=8)
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
tensorflow official tfa.layers.MultiHeadSelfAttention example 
Other info / logs

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by WindQAQ** [comment]
Hi, do you mean `tfa.layers.MultiHeadSelfAttention` or `tfa.layers.MultiHeadAttention`? Seems that you mistype `tfa.layers.MultiHeadAttention`. Thank you.

**Comment by 190407543** [comment]
> Hi, do you mean `tfa.layers.MultiHeadSelfAttention` or `tfa.layers.MultiHeadAttention`? Seems that you mistype `tfa.layers.MultiHeadAttention`. Please let me know if I missed anything. Thank you.

sorry for mistype
but the same 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-da33c24ddbfa> in <module>()
     92 
     93 
---> 94 mha = tfa.layers.MultiHeadAttention(head_size=512, num_heads=8)
     95 #query =(32, 20, 200)) # (batch_size, query_elements, query_depth)
     96 #key = ((32, 15, 300)) # (batch_size, key_elements, key_depth)

AttributeError: module 'tensorflow_addons.layers' has no attribute 'MultiHeadAttention'

**Comment by bhack** [comment]
Is It caused by https://github.com/googlecolab/colabtools/issues/1243?

**Comment by 190407543** [comment]
how about the gelu?
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    390       obj = module_objects.get(object_name)
    391       if obj is None:
--> 392         raise ValueError('Unknown ' + printable_module_name + ':' + object_name)
    393     # Classes passed by name are instantiated with no args, functions are
    394     # returned as-is.

ValueError: Unknown activation function:tfa.activations.gelu

**Comment by bhack** [comment]
Have you tried in Colab to `pip install tensorflow-addons==0.10.0`?

**Comment by 190407543** [comment]
it fixed.thx
also, is there any super class transformer , bert, positional encoding embedding layer?
although they just call a few tfa stuff, it is easiler to build models.thx

**Comment by seanpmorgan** [comment]
> it fixed.thx
> also, is there any super class transformer , bert, positional encoding embedding layer?
> although they just call a few tfa stuff, it is easiler to build models.thx

[Not in addons](https://www.tensorflow.org/addons/api_docs/python/tfa) we aim to provide fundamental building blocks. Feel free to open issues requesting these but I think you're more likely to find those features in tensorflow/models.
