### ISSUE TITLE
tensorflow addons 0.10.0 error 

### ISSUE THREAD

**Issue by sioan** [tensorflow/addons#1850]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04
- TensorFlow version and how it was installed : tf 2.1 installed via pip into a conda environment
- TensorFlow-Addons version and how it was installed: 0.10.0 installed via pip into a conda environment
- Python version: 3.7.6
- Is GPU used? (yes/no): yes

**Describe the bug**

import tensorflow_addons

Can't find a generator module for rrelu.  See error message below.

**Code to reproduce the issue**

import tensorflow_addons

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

import tensorflow_addons

**Other info / logs**

~/miniconda3/envs/rapids_v1_4cr/lib/python3.7/site-packages/tensorflow_addons/__init__.py in <module>
     19 
     20 # Local project imports
---> 21 from tensorflow_addons import activations
     22 from tensorflow_addons import callbacks
     23 from tensorflow_addons import image

~/miniconda3/envs/rapids_v1_4cr/lib/python3.7/site-packages/tensorflow_addons/activations/__init__.py in <module>
     20 from tensorflow_addons.activations.mish import mish
     21 from tensorflow_addons.activations.softshrink import softshrink
---> 22 from tensorflow_addons.activations.rrelu import rrelu
     23 from tensorflow_addons.activations.sparsemax import sparsemax
     24 from tensorflow_addons.activations.tanhshrink import tanhshrink

~/miniconda3/envs/rapids_v1_4cr/lib/python3.7/site-packages/tensorflow_addons/activations/rrelu.py in <module>
     26     training: Optional[bool] = None,
     27     seed: Optional[int] = None,
---> 28     rng: Optional[tf.random.Generator] = None,
     29 ) -> tf.Tensor:
     30     """rrelu function.

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

This error isn't present for tensorflow addons 0.9.1.  It's only present for tensorflow 0.10.0

**Comment by RayXie29** [comment]
I also met the same issue.

**Comment by WindQAQ** [comment]
Hi all,

`tensorflow_addons==0.10.0` is only compatible with `tensorflow==2.2.0`. Please let me know if there is any other problem. Thank you!

https://github.com/tensorflow/addons#python-op-compatibility-matrix

**Comment by RayXie29** [comment]
Thanks, my bad. Mine tensorflow version is 2.1.0.

**Comment by WindQAQ** [comment]
Then I'm going to close the issue. Please reopen it if I missed anything. Thank you!

**Comment by sioan** [comment]
> Hi all,
> 
> `tensorflow_addons==0.10.0` is only compatible with `tensorflow==2.2.0`. Please let me know if there is any other problem. Thank you!
> 
> https://github.com/tensorflow/addons#python-op-compatibility-matrix

Well. I feel dumb.  

Thank you for the quick response.

**Comment by bhack** [comment]
@WindQAQ Do you know why we don't have Tensorflow with the version we need in https://github.com/tensorflow/addons/blob/master/setup.py#L88?

**Comment by seanpmorgan** [comment]
Thanks @WindQAQ !

> @WindQAQ Do you know why we don't have Tensorflow with the version we need in https://github.com/tensorflow/addons/blob/master/setup.py#L88?

Because then users who have `tensorflow-gpu` or `tensorflow-cpu` already will get multiple TF packages installed when trying to installing TFA. We tried both strategies and had more and worse issues from the strict requirements packaging. 

The current way we do it is the same as say TensorFlow Probability:
https://github.com/tensorflow/probability/blob/master/setup.py#L30
