### ISSUE TITLE
TypeError: __call__() got an unexpected keyword argument 'training'

### ISSUE THREAD

**Issue by Abonia1** [tensorflow/addons#1853]
Hello I have issue in using dynamic_decode in tfa as below with tensorflow 2.X

I really appreciate if anyone have already resolved this issue as I have spent last 4 hours in it but still no solution out there.

Provide a reproducible test case that is the bare minimum necessary to generate the problem.
![image](https://user-images.githubusercontent.com/22887323/82151662-d53a4380-985c-11ea-8a6d-da8dfb5e9f8c.png)

**Comment by bhack** [comment]
Do you have a minimal colab code to share?

**Comment by Abonia1** [comment]
Sure I can...Here you go:
https://drive.google.com/file/d/1g95NyX7-HniSBeFkqKtYzyW0ZNKjuVML/view?usp=sharing

**Comment by bhack** [comment]
Thanos but It Is too long. I meant really if you have the very minimal code to reproduce this error.

**Comment by Abonia1** [comment]
def attention(rnn_size,encoder_outputs,target_sequence_length,dec_cell):
    attention_mechanism = tfa.seq2seq.BahdanauAttention(rnn_size*2,encoder_outputs,
                                                                   memory_sequence_length=target_sequence_length)
    attention_cell = tfa.seq2seq.AttentionWrapper(dec_cell, attention_mechanism,
                                                             attention_layer_size=rnn_size/2)
    return attention_cell

attention_cell = attention(rnn_size,encoder_outputs,target_data_len,dec_cell)
state = attention_cell.get_initial_state(dtype=tf.float32, batch_size=batch_size)
state = state.clone(cell_state=encoder_states)

sampler = tfa.seq2seq.sampler.TrainingSampler()

decoder_train = tfa.seq2seq.BasicDecoder(cell=attention_cell ,sampler=sampler,
                                                  output_layer=dense_layer) 

outputs_train, _, _ =tfa.seq2seq.dynamic_decode(decoder = decoder_train,
                            maximum_iterations = tf.reduce_max(target_data_len),
                            impute_finished=True,
                            swap_memory = True,
                            decoder_init_input= decoder_embedded,
                            sequence_length=target_data_len,
                            decoder_init_kwargs= {
                                'initial_state' : state
                            })

Hope you can get some idea from below code.Thank you

**Comment by bhack** [comment]
I need to have something minimal to copy, paste and run. That snippet Is not runnable as is.

If you can't probably you will need to wait for  a maintainer or the seq2seq codeowner.

**Comment by Abonia1** [comment]
@bhack okay thank you

**Comment by guillaumekln** [comment]
You are using:

```python
import tensorflow.compat.v1 as tf
```

but TensorFlow Addons only supports TensorFlow 2.x APIs. You should change the import statement to:

```python
import tensorflow as tf
```

and try to update your usage based on TensorFlow 2.x APIs.

**Comment by guillaumekln** [comment]
Let me close this issue. Feel free to reopen or create a new issue if you find something that is not working.
