### ISSUE TITLE
Pip installation fails on Linux

### ISSUE THREAD

**Issue by aawdeh** [tensorflow/addons#1858]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux 7
- TensorFlow version and how it was installed (source or binary): 2.1.0, binary 
- Python version: Python 3.6 (Also tried 3.5 and 3.7) 
- Is GPU used? (yes/no): yes

I get the error below every time I try to install tensorflow-addons using 'pip install tensorflow-addons'. I've tried all versions of tensorflow-addons with varying versions of Python and TensorFlow. However, nothing seems to work. 

**ERROR: Could not find a version that satisfies the requirement tensorflow-addons (from versions: none)
ERROR: No matching distribution found for tensorflow-addons**

Code to reproduce the issue: 
pip install tensorflow-addons

Other info:
pip == 20.1

**Comment by seanpmorgan** [comment]
Hi @aawdeh this is quite strange. The wheel files are available and my only guess would be that your running a different pip that you think you are (perhaps by running sudo). 

Could you show the exact commands you're running:
```
pip --version
pip install tensorflow-addons
```

As a last resort you can always download the whl files from PYPI, but I would suggest you determine what's going on. For TF 2.1 use Addons 0.9.1:
https://pypi.org/project/tensorflow-addons/0.9.1/#files

**Comment by seanpmorgan** [comment]
Closing as I'm not sure there is any bug here. Feel free to ask to re-open if the problem persists.
