### ISSUE TITLE
Documentation: Focal loss example misleading

### ISSUE THREAD

**Issue by ketograph** [tensorflow/addons#1859]
In the example of the focal loss (`tfa.losses.SigmoidFocalCrossEntropy`) the label and the prediction data seems to be swapped. 
This is misleading as `sigmoid_focal_crossentropy()` expects `y_true, y_pred`, whereas the example presents `y_pred, y_true`.

https://github.com/tensorflow/addons/blob/efa0cd9c86578f53a2eb9d80849e186bffa4d64a/tensorflow_addons/losses/focal_loss.py#L42-L47

https://github.com/tensorflow/addons/blob/efa0cd9c86578f53a2eb9d80849e186bffa4d64a/tensorflow_addons/losses/focal_loss.py#L90-L92

**Comment by seanpmorgan** [comment]
Thanks @ketograph for pointing this out! Would you want to submit a PR fixing the documentation?

**Comment by yil532** [comment]
Hi do we still need help on this?
