### ISSUE TITLE
reuse the instance of class BeamSearchDecoder  more easily

### ISSUE THREAD

**Issue by zhanfengchen** [tensorflow/addons#1868]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow version and how it was installed (source or binary):
- TensorFlow-Addons version and how it was installed (source or binary):
- Python version: 3.6
- Is GPU used? (yes):

**Describe the bug**

**Code to reproduce the issue**

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**

I'm new for TF. I trained a seq2seq model based on LSTM for NLG, then to predict with Seq2SeqPredict, code as follows. The decoder of Seq2SeqPredict is the instance of `BeamSearchDecoder`, and My Error raised in it.
```
class Seq2SeqPredict(tf.keras.Model):
    def __init__(self, Ty, beam_width, start_token, end_token, seq2seq_train):
        super(Seq2SeqPredict, self).__init__()
        
        ## encoder
        self.encoder_embedding = seq2seq_train.encoder_embedding
        self.encoder_rnn = seq2seq_train.encoder_rnn
        
        ## decoder embedding
        self.decoder_embedding_mtx = seq2seq_train.decoder_embedding.variables[0]
        ## Output
        # # self.decoder_dense_layer = seq2seq_train.decoder_dense_layer
        ## attention_mechanism
        self.decoder_attention_mechanism = seq2seq_train.decoder_attention_mechanism
        
        ## rnn_cell
        self.decoder_rnn_cell = seq2seq_train.decoder_rnn_cell
        
        ## beam_search_decoder
        self.beam_search_decoder = tfa.seq2seq.BeamSearchDecoder(
            cell=self.decoder_rnn_cell,
            beam_width=beam_width,
            output_layer=seq2seq_train.decoder_dense_layer,
        )
        
        ## other attributions
        self.beam_width = beam_width
        self.maximum_iterations = Ty * 2
        self.start_token = start_token
        self.end_token = end_token
        
    def _decoder_initial_state(self, size, state):
        _initial_state = self.decoder_rnn_cell.get_initial_state(batch_size=size*self.beam_width, dtype=tf.float32)
        decoder_initial_state = _initial_state.clone(cell_state=state)
        return decoder_initial_state
    
    def _generate_lines(self, start_tokens, tiled_state):
        beam_width = self.beam_width
        (first_finished, first_inputs, first_state) = self.beam_search_decoder.initialize(self.decoder_embedding_mtx,
                                                                                         start_tokens=start_tokens,
                                                                                         end_token=self.end_token,
                                                                                         initial_state=self._decoder_initial_state(1, state=tiled_state),
                                                                                         )
        inputs = first_inputs
        state = first_state
        pred_mtx, path_mtx = [], []

        for j in range(self.maximum_iterations):
            outputs, next_state, next_inputs, finished = self.beam_search_decoder.step(j, inputs, state)
            inputs = next_inputs
            state = next_state

            pred_mtx.append(outputs.predicted_ids)
            path_mtx.append(outputs.parent_ids)
        
        return pred_mtx, path_mtx

    def call(self, inputs, training=False):
        encoder_input = inputs
        # encoder
        encoder_x = self.encoder_embedding(encoder_input)
        a, a_tx, c_tx = self.encoder_rnn(encoder_x)
        
        beam_width = self.beam_width
        # beam_search_decoder
        ## tiled
        tiled_a = tfa.seq2seq.tile_batch(a, multiplier=self.beam_width)
        tiled_a_tx = tfa.seq2seq.tile_batch(a_tx, multiplier=self.beam_width)
        tiled_c_tx = tfa.seq2seq.tile_batch(c_tx, multiplier=self.beam_width) 
        start_tokens = tf.fill([1], self.start_token)

        self.decoder_attention_mechanism.setup_memory(tiled_a)

        pred_mtx, path_mtx = self._generate_lines(start_tokens, [tiled_a_tx, tiled_c_tx])
        return pred_mtx, path_mtx
```
when I predict sequences twicely with the same instance of class Seq2SeqPredict, an error raised "embedding and embedding_fn cannot be provided at same time". 

Reason is that instance would create automatically a `_embedding_fn` with `embedding` in the first prediction without any notice.

I think some action should be taken, as follows:
1.  One set `embedding` in function `initialize()`, so he want to replace old `_embedding_fn` with it. So replace older.

2. Given performance, it's better to set `embedding` when creating new instance. So append a message to the note.

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by zhanfengchen** [comment]
Tensorflow 2.1.0    installed by Anaconda
Tensorflow_addons 0.9.1   installed by Anaconda
Python 3.6.9    install by Anaconda
GPU      yes!

**Comment by guillaumekln** [comment]
You can set `embedding_fn` in the constructor of `BeamSearchDecoder`. Would that work for you?

A typical embedding function would look like this:

```python
lambda ids: tf.nn.embedding_lookup(embedding, ids)
```

**Comment by zhanfengchen** [comment]
yes, I had done as you said before creating this issue.&nbsp; But it's better giving advice in note or other.&nbsp;



---Original---

**Comment by guillaumekln** [comment]
@qlzh727 What is the rationale for having the `embedding` argument in the call method and not only in the constructor?

**Comment by zhanfengchen** [comment]
If we set `embedding` in `initialize` method, the instance of BeamSearchDecoder run only once. It is one-off.
