### ISSUE TITLE
tfa.layers.sparsemax fail after pip

### ISSUE THREAD

**Issue by py9rjr6858yffiy6i** [tensorflow/addons#1869]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):colab
- TensorFlow version and how it was installed (source or binary):colab
- TensorFlow-Addons version and how it was installed (source or binary):latest in pip
- Python version:3
- Is GPU used? (yes/no):ues

**Describe the bug**
after !pip install tensorflow-addons

ValueError: Unknown activation function:tfa.layers.Sparsemax

after !pip install tensorflow-addons

ValueError: Unknown activation function:tfa.layers.Sparsemax
**Code to reproduce the issue**
model.add(layers.Dense(len(train_category), activation='tfa.layers.Sparsemax'))

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by seanpmorgan** [comment]
Hi! TFA activations can't be passed as a string parameter and need instead the python object to be passed. Additionally you're trying to pass the Sparsemax layer and not the sparsemax activation.

Try:
```
layers.Dense(32, activation=tfa.activations.sparsemax)
```
