### ISSUE TITLE
Error in types description of tfa.seq2seq.AttentionWrapper

### ISSUE THREAD

**Issue by avnx** [tensorflow/addons#1870]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LT
- TensorFlow version and how it was installed (source or binary): 2.2.0
- TensorFlow-Addons version and how it was installed (source or binary): 0.10.0
- Python version: 3.6.9
- Is GPU used? (yes/no): yes

As I noticed you added type description to classes.
But I found that at least in my case there is a conflict of types in description with real mission of arguments.
According to docs _attention_mechanism_ and _attention_layer_size_ in **tfa.seq2seq.AttentionWrapper** could be lists (for MultiHead attention case) or single instances. But in types you specified that _attention_mechanism_ and _attention_layer_size_ must be **tf.keras.layers.Layer** and  **Optional[FloatTensorLike]** respectively.

https://github.com/tensorflow/addons/blob/v0.9.1/tensorflow_addons/seq2seq/attention_wrapper.py#L1621

**Comment by guillaumekln** [comment]
Thanks for reporting. The description is correct but not the types annotation. The PR referenced above should fix this.
