### ISSUE TITLE
transformer   sequential to AttentionWrapper with LSTMCell

### ISSUE THREAD

**Issue by py9rjr6858yffiy6i** [tensorflow/addons#1874]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):colab
- TensorFlow version and how it was installed (source or binary):colab
- TensorFlow-Addons version and how it was installed (source or binary):
- Python version:
- Is GPU used? (yes/no):yes

**Describe the bug**
Sorry, I not clear is it a bug or my fault,
Since I need to add a AttentionWrapped LSTMCells at the output of a transformer and a dense layer below the LSTMCells, but it output fault message.
The class of the transformer model is tensorflow`s tutorial at
https://www.tensorflow.org/tutorials/text/transformer
also, have u developing a transformer or a bert class? will you just copy above class from tensorflow
and provide a bert calss ? since it seems very trouble to sequcential them up. 

i want the shape output from transformer (batch,char in sequence length,attn/d_model)  to output to the attention wrapper LSTMCell with shape (batch,timesetp,d_model), is it ok to regard tf.shape(transformer_out)[1], the seq. length, to tf.shape(AttentionWrapped_LSTMCell_input)[1],the timestep?
def AttenLSTM(d_model,vocab_size,dec_outputs):
inputs= tf.keras.layers.Input(shape=(None,d_model),name='inputs')(encoder_output)
cell = tf.keras.layers.LSTMCell(d_model)
output_attention=False,attention_size=256)
attn_cell=tfa.seq2seq.AttentionWrapper(cell, attention_mechanism,attention_layer_size=vocab_size,name='outputs',initial_cell_state=cell.get_initial_state(batch_size=64, dtype=tf.float32))
return tf.keras.Model(
      inputs=inputs,
      outputs=outputs,
      name='longmemory')
  
outputs = tf.keras.layers.Dense(units=vocab_size, name="outputs")(longmemory(d_model,vocab_size,dec_outputs))
  
---------------------------------------------------------------------------
OperatorNotAllowedInGraphError            Traceback (most recent call last)
<ipython-input-4-e23cb3fb29e6> in <module>()
    544     num_heads=4,
    545     dropout=0.3,
--> 546     name="sample_transformer")
    547 
    548 tf.keras.utils.plot_model(

10 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in _disallow_in_graph_mode(self, task)
    535     raise errors.OperatorNotAllowedInGraphError(
    536         "{} is not allowed in Graph execution. Use Eager execution or decorate"
--> 537         " this function with @tf.function.".format(task))
    538 
    539   def _disallow_bool_casting(self):

OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

**Code to reproduce the issue**

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by guillaumekln** [comment]
Could you post a small code snippet that we can copy-paste to reproduce the error? Thanks.

**Comment by guillaumekln** [comment]
Let me close this stale issue. Feel free to reopen if you can share a code snippet reproducing the error.
