### ISSUE TITLE
_prepend_batch is receiving a shape as an integer and is causing an exception

### ISSUE THREAD

**Issue by 5demayo** [tensorflow/addons#1910]
**System information**
- Debian 10
- TF 2.2 source
- TensorFlow-Addons 0.10.0 source
- Python version: 3.7
- Is GPU used? (yes/no): no

**Describe the bug**

_prepend_batch is receiving a shape as an integer and is causing an exception to be raised on:

return tf.concat(([batch_size], shape), axis=0)

**Code to reproduce the issue**

Pass in a shape that is an integer or a dictionary of an integer

**Other info / logs**

This is how I rewrote the function, first checking to see if the shape is a TensorShape, similar to how you check if batch_size is a Tensor:

`def _prepend_batch(batch_size, shape):
    """Prepends the batch dimension to the shape.

    If the batch_size value is known statically, this function returns a
    TensorShape, otherwise a Tensor.
    """
    if isinstance(batch_size, tf.Tensor):
        static_batch_size = tf.get_static_value(batch_size)
    else:
        static_batch_size = batch_size
    if static_batch_size is None:
        if isinstance(shape,tf.TensorShape):
            return tf.concat(([batch_size], shape), axis=0)
        else:
            return tf.concat(([batch_size], tf.shape(shape)), axis=0)

    return [static_batch_size] + shape`

**Comment by 5demayo** [comment]
I am more than happy to fix, just haven't done a pull request on a major project before.

**Comment by seanpmorgan** [comment]
Hi @5demayo would you be able to expand on this issue and point to where this is occurring in the source code (I assume seq2seq?) Also a reproducible example of code that triggers this error is needed so we can verify that the use case is correct. 

Thanks!

**Comment by guillaumekln** [comment]
It's not clear to me whether the exception was raised when using `seq2seq` layers, or when this function is called directly. I'm going to close this issue, but feel free to reopen if you can provide more details.
