### ISSUE TITLE
tfa.text.crf_decode causes error when converting to tflite.

### ISSUE THREAD

**Issue by invencode** [tensorflow/addons#1923]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow version and how it was installed (source or binary): 2.3.0-dev20200609 / binary
- TensorFlow-Addons version and how it was installed (source or binary): 0.11.0.dev20200609192739 / binary
- Python version: 3.7.5
- Is GPU used? (yes/no): no

**Describe the bug??**
On `tfa.text.crf_decode`, there is an if-else that looks functionally identical for the condition of `potentials.shape[1]`.
But, the `else` part can cause errors when converting to tflite if the `shape[1] is None`. (e.g: `[1, None, 10]`)

```python
if potentials.shape[1] is not None:
        # shape is statically know, so we just execute
        # the appropriate code path
        if potentials.shape[1] == 1:
            return _single_seq_fn()
        else:
            return _multi_seq_fn()
else:
        return tf.cond(
            tf.equal(tf.shape(potentials)[1], 1), _single_seq_fn, _multi_seq_fn
        )
```

**Comment by Squadrick** [comment]
@invencode Can you post your code, as well as how you converted to tflite? It'll really help with debugging the issue.

**Comment by howl-anderson** [comment]
@invencode Could you provide code for reproduce this issue? Or if your problem is solved by using new TFLite, please close this issue. Thank you very much.

**Comment by invencode** [comment]
I think it is solved by using new TFLite.
