### ISSUE TITLE
Packaged Addons can't run on TF2-nightly if built against TF2-alpha

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#193]
We're in the process of getting ready to release a 0.3 version, but there are several breaking changes in the tf2-nightly vs. tf2-alpha (as there should be). 

To start the shared libraries are now named with versions and OS syntax. We can get around this by using the link flag that has now been added to tf.sysconfig though.

API changes are harder to work around. For example:  https://github.com/tensorflow/addons/pull/192 -- which means on the 0.3 release branch we'll need to roll-back some changes if we continue to build against tf2-alpha. I think this is the best course of action while we wait for a tf2-beta, but wanted to discuss.

We can also point users to this issue if they are building from source and running against tf2-alpha.

cc @karmel @martinwicke

**Comment by martinwicke** [comment]
We did make some tf.image name changes to eliminate duplicate "image"s.

In theory you could use a try block to ensure the code works for alpha and
nightly, which could be eliminated once the 2.0 is in RC (or beta) and
people stop caring about alpha0.

How much trouble would that be?

**Comment by seanpmorgan** [comment]
Now that we have [nightlies being published](https://pypi.org/project/tfa-nightly/#files), the recommended way to run against `tf-nightly-2.0-preview` is to use `tfa-nightly`

```
pip install tfa-nightly
```

Once we publish 0.4 we'll do our best to keep it compatible with tf2-nightly but that is not something we can guarantee.
