### ISSUE TITLE
Usage with tf.keras API

### ISSUE THREAD

**Issue by abhijitmjj** [tensorflow/addons#1936]
https://github.com/tensorflow/addons/blob/5f618fdb92d9737da059de2a33fa606e97505398/tensorflow_addons/losses/focal_loss.py#L52-L53

The usage in `tf.keras` API example is incorrect. It should be replaced with:

```python
model = tf.keras.Model(inputs, outputs)
model.compile('sgd', loss=tfa.losses.SigmoidFocalCrossEntropy())
```

**Comment by AakashKumarNain** [comment]
Thanks @abhijitmjj for pointing this out. Can you create a PR with the correction?
