### ISSUE TITLE
feature request for Snake activation function

### ISSUE THREAD

**Issue by turmeric-blend** [tensorflow/addons#1939]
**Capable of learning a periodic function from the data better than current standard activation functions such as ReLU and tanh. Also performs as well as ReLU/leaky-ReLU on image task (refer paper)**

**Relevant information**
- Are you willing to contribute it (yes/no): yes
- Are you willing to maintain it going forward? (yes/no): no
- Is there a relevant academic paper? (if so, where): https://arxiv.org/pdf/2006.08195.pdf
- Is there already an implementation in another framework? (if so, where): no
- Was it part of tf.contrib? (if so, where): no

Implement under: **tfa.activation for base case, possibly tfa.layer for learnable param 'a' (frequency - refer paper)**

Who it benefits: **researches and practitioners from the time-series related space**

**Any other info.**

**Comment by turmeric-blend** [comment]
not sure if this counts as a contribution but here is my implementation of Snake using layer:

```
import tensorflow as tf
import tensorflow.keras.backend as K

class Snake(tf.keras.layers.Layer):
	def __init__(self, freq=10.0, trainable=False, **kwargs):
		super(Snake, self).__init__(**kwargs)
		self.freq = freq
		self.trainable = trainable

	def build(self, input_shape):
		self.freq = K.variable(self.freq, dtype=K.floatx(), name='frequency')

		if self.trainable:
            self._trainable_weights.append(self.freq)

        super(Snake, self).build(input_shape)

    def call(self, inputs, freq):
        return inputs + (1-K.cos(2*freq*inputs))/(2*freq)

    def get_config(self):
        config = {'freq': self.get_weights()[0] if self.trainable else self.freq,
                  'trainable': self.trainable}
        base_config = super(Snake, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))

    def compute_output_shape(self, input_shape):
        return input_shape
```

I based the template off https://datascience.stackexchange.com/questions/58884/how-to-create-custom-activation-functions-in-keras-tensorflow

**Comment by failure-to-thrive** [comment]
@turmeric-blend I could incorporate it into TFA and maintain further instead of you, if you really do not want to. However, if you just do not know "how to", there are [Contribution Guidelines](https://github.com/tensorflow/addons/tree/master/tensorflow_addons/activations) out there.

**Comment by turmeric-blend** [comment]
Thanks @failure-to-thrive . I think its better if you implement it. Also I'm not sure if the code above is 100% accurate to the paper, so you might want to double check.

**Comment by failure-to-thrive** [comment]
> Also I'm not sure if the code above is 100% accurate to the paper, so you might want to double check.

I see nothing wrong with your implementation. If you have any doubts, please do not hesitate to reveal them upfront.
