### ISSUE TITLE
Fix typo on contrastive loss

### ISSUE THREAD

**Issue by gugarosa** [tensorflow/addons#1957]
There is a typo on the contrastive loss wrapper. Not that it will change a lot, but it is nice to keep things straight.

https://github.com/tensorflow/addons/blob/v0.10.0/tensorflow_addons/losses/contrastive.py#L100

Best regards,
Gustavo.

**Comment by seanpmorgan** [comment]
Hi @gugarosa nice catch! Would you like to submit a PR to fix it?

**Comment by gugarosa** [comment]
Sure, sounds great! Let me clone the repo and submit it.
