### ISSUE TITLE
[Seq2Seq] Add build/get_config/from_config and other layer methods.

### ISSUE THREAD

**Issue by gcuder** [tensorflow/addons#1961]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- TensorFlow version and how it was installed (source or binary): 2.2/binary
- TensorFlow-Addons version and how it was installed (source or binary): 0.10/ binary
- Python version: 3.5.6
- Is GPU used? (yes/no): yes

**Describe the bug**
When a tried to save a model with the BeamSearchDecoder, it complained that the layer has not been built yet. So I discovered that the `get_conig` as well as the `build` Method is missing and I found a TODO in line 256 of `decoder.py`. 
It would be great if you added that missing parts.

**Comment by guillaumekln** [comment]
Could you post a small code examples describing how you tried to save the model?

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
