### ISSUE TITLE
tfa.image.rotate and tfa.image.transform crashes colaboratory

### ISSUE THREAD

**Issue by MathisFederico** [tensorflow/addons#1984]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colaboratory so i don't really know
- TensorFlow version and how it was installed (source or binary): Colaboratory so i don't really know
- TensorFlow-Addons version and how it was installed (source or binary): Colaboratory so i don't really know
- Python version: Colaboratory so i don't really know
- Is GPU used? (yes/no): yes
In this [tensorflow tutorial](https://colab.research.google.com/github/tensorflow/addons/blob/master/docs/tutorials/image_ops.ipynb#scrollTo=HTh1Qpps8Rg5 )

**Describe the bug**
Session crashed when tfa.image.rotate or tfa.image.transform is used.

**Code to reproduce the issue**
In this [tensorflow tutorial](https://colab.research.google.com/github/tensorflow/addons/blob/master/docs/tutorials/image_ops.ipynb#scrollTo=HTh1Qpps8Rg5 )

**Other info / logs**
None

**Comment by bhack** [comment]
It is https://github.com/googlecolab/colabtools/issues/1243

**Comment by MathisFederico** [comment]
Nice to know ! Thank you ! So downgrading to TF2.1 would work ?

**Comment by bhack** [comment]
You can add `!pip install tensorflow-addons == 0.10.0` line before imports.

**Comment by bhack** [comment]
Oh and of course upvote https://github.com/googlecolab/colabtools/issues/1243 :wink:

**Comment by seanpmorgan** [comment]
> You can add `!pip install tensorflow-addons == 0.10.0` line before imports.

Yeah would recommend this instead of downgrading TF. Sorry for the confusion we're working on getting these updated.
