### ISSUE TITLE
Deprecate GELU 

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#2005]
Per https://github.com/tensorflow/community/pull/252, oonce  https://github.com/tensorflow/tensorflow/pull/41178 merges we'll need to deprecate our GELU for versions of TensorFlow that include it within core.

**Comment by marload** [comment]
May I do this?

**Comment by seanpmorgan** [comment]
> May I do this?

Sure! Still need GELU to merge into core and determine which version of TF it will be included in.
