### ISSUE TITLE
WeightNormalization test are failing without symbolic tensors in build

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#203]
Since https://github.com/tensorflow/tensorflow/commit/9df99aafc3480638cd8d2bf6a0caeab111b68302 our keras_layer test is failing on weightnorm. 

This is the block that fails from the [test uti](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/testing_utils.py#L207)l:
```
 # test serialization, weight setting at model level
  model_config = model.get_config()
  recovered_model = keras.models.Sequential.from_config(model_config)
  if model.weights:
    weights = model.get_weights()
    recovered_model.set_weights(weights)
    output = recovered_model.predict(input_data)
    np.testing.assert_allclose(output, actual_output, rtol=2e-3
```
So our model config isn't properly serializing the data. 

@omalleyt12 could you take a look and provide some insight. I'm not overly familiar with `ops.init_scope` and the check for `_keras_style`

Here is our weight norm layer:
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/layers/wrappers.py#L24

**Comment by seanpmorgan** [comment]
I submitted a PR which sets `keras_style` to false and then tests pass. From my understanding of keras_style though I don't think this is the correct thing to do? We are not utilizing any legacy tf.layers or tf.rnn

**Comment by omalleyt12** [comment]
Thanks for the issue! Could you provide a minimal repro?
