### ISSUE TITLE
float16 support for text/crf

### ISSUE THREAD

**Issue by xuxingya** [tensorflow/addons#2030]
text/crf.py doesn't support float16 training or TF Lite converter.
According to the error information, the type of  masks In line 256 and line 294 is tf.float32:
```
masks = tf.sequence_mask(
        sequence_lengths, maxlen=tf.shape(tag_indices)[1], dtype=tf.float32
    )
```
which raises error when doling multiply op, like in line 259: 
```unary_scores = tf.reduce_sum(unary_scores * masks, 1)```

**Which API type would this fall under (layer, metric, optimizer, etc.)**
text
![image](https://user-images.githubusercontent.com/13343428/88151388-37387000-cc35-11ea-963f-68585a69f0e6.png)

**Comment by bhack** [comment]
Can you share a very minimal but runnable dummy example to reproduce this?

**Comment by xuxingya** [comment]
> Can you share a very minimal but runnable dummy example to reproduce this?
I have implemented the example below. The "tf2crf" is a small package that I wrote for using CRF layer with tf 2.0 keras. It just called tfa.text.crf_decode and tfa.text.crf_log_likelihood for computing crf scores and loss.
```
from tensorflow.keras.layers import Input, Embedding, Bidirectional, GRU, Dense
from tensorflow.keras.models import Model
from tf2crf import CRF
from tensorflow.keras.mixed_precision import experimental as mixed_precision
policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_policy(policy)

def test():
    inputs = Input(shape=(None,), dtype='int32')
    output = Embedding(100, 40, trainable=True, mask_zero=True)(inputs)
    output = Bidirectional(GRU(64, return_sequences=True))(output)
    output = Dense(9, activation=None)(output)
    crf = CRF()
    output = crf(output)
    model = Model(inputs, output)
    model.compile(loss=crf.loss, optimizer='adam', metrics=[crf.accuracy])

    x = [[5, 2, 3] * 3] * 10
    y = [[1, 2, 3] * 3] * 10

    model.fit(x=x, y=y, epochs=2, batch_size=2)
    model.save('model')


if __name__ == '__main__':
    test()
```
When run the code, I got this error:
```
TypeError: true_fn and false_fn arguments to tf.cond must have the same number, type, and overall structure of return values.
    
    true_fn output: Tensor("Identity:0", shape=(None, None, 9), dtype=float16)
    false_fn output: Tensor("Identity:0", shape=(None, None, 9), dtype=float32)
    
    Error details:
    Tensor("Identity:0", shape=(None, None, 9), dtype=float16) and Tensor("Identity:0", shape=(None, None, 9), dtype=float32) have different types
```
The error raised when called tfa.text.crf_decode in the CRF layer

**Comment by WindQAQ** [comment]
I think we can change these two dtypes from `tf.float32` to `unary_scores.dtype` and `binary_scores.dtype` respectively.
@xuxingya Can you try it or even issue an PR for it? Thanks!

https://github.com/tensorflow/addons/blob/master/tensorflow_addons/text/crf.py#L256
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/text/crf.py#L294

**Comment by bhack** [comment]
@WindQAQ no we need something else.

**Comment by zara44** [comment]
I am facing the same issue. Are there any plans to fixing this. I'm happy to help out!

**Comment by WindQAQ** [comment]
> I am facing the same issue when using the recently added CRF layer in the TFA nightly package from this commit:
> [4f65776](https://github.com/tensorflow/addons/commit/4f65776d7ab6d31884aa91445fd9fe94a504bac1)
> Are there any plans to fixing this. I'm happy to help out! @bhack @WindQAQ

I'll investigate it later, could you provide runnable minimal code snippet to reproduce the issue? seems that the code above requires some customized model. Thanks.

**Comment by zara44** [comment]
> > I am facing the same issue when using the recently added CRF layer in the TFA nightly package from this commit:
> > [4f65776](https://github.com/tensorflow/addons/commit/4f65776d7ab6d31884aa91445fd9fe94a504bac1)
> > Are there any plans to fixing this. I'm happy to help out! @bhack @WindQAQ
> 
> I'll investigate it later, could you provide runnable minimal code snippet to reproduce the issue? seems that the code above requires some customized model. Thanks.

Here's an example code that uses the recently added CRF layer as well as the error produced.

```
from tensorflow.keras.layers import Input, Embedding, Bidirectional, LSTM, Dense
from tensorflow.keras.models import Model
from tensorflow_addons.layers.crf import CRF
from tensorflow.keras.mixed_precision import experimental as mixed_precision
policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_policy(policy)

def test():
    inputs = Input(shape=(None,), dtype='int32')
    output = Embedding(100, 40, trainable=True, mask_zero=True)(inputs)
    output = Bidirectional(LSTM(10, return_sequences=True))(output)
    output = Dense(9, activation=None)(output)
    crf = CRF()
    output = crf(output)
    model = Model(inputs, output)
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics='acc')
    x = [[5, 2, 3] * 3] * 10
    y = [[1, 2, 3] * 3] * 10

    model.fit(x=x, y=y, epochs=2, batch_size=2)


if __name__ == '__main__':
    test()

```

Error:
```
...
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:506 _apply_op_helper
        inferred_from[input_arg.type_attr]))

    TypeError: Input 'y' of 'Mul' Op has type float64 that does not match type int32 of argument 'x'.
```

**Comment by WindQAQ** [comment]
>     x = [[5, 2, 3] * 3] * 10
>     y = [[1, 2, 3] * 3] * 10

I'm not so familiar with CRF, but can it really be used to compute cross entropy with targets? Seems that it's output is sparse integer.

**Comment by zara44** [comment]
@WindQAQ the issue is not resolved yet. I Still get the same error.

**Comment by WindQAQ** [comment]
Hi @zara44, seems that it's the issue of your example. CRF cannot work with `categorical_crossentropy` directly. I am not an expert of CRF, but you can take a look at https://github.com/tensorflow/addons/blob/master/tensorflow_addons/layers/tests/crf_test.py#L125-L164.
