### ISSUE TITLE
Add `tfa.metrics.HarmonicMean`

### ISSUE THREAD

**Issue by marload** [tensorflow/addons#2035]
**Describe the feature and the current behavior/state.**
Computes HarmonicMean

**Relevant information**
- Are you willing to contribute it (yes/no): YES
- Are you willing to maintain it going forward? (yes/no): YES
- Is there a relevant academic paper? (if so, where): NO
- Is there already an implementation in another framework? (if so, where): python stdlib statistics
- Was it part of tf.contrib? (if so, where): NO

**Which API type would this fall under (layer, metric, optimizer, etc.)**
`tfa.metrics`

**Who will benefit with this feature?**
Developers and researchers who want to obtain representative values using harmonic mean

**Any other info.**

**Comment by tomerk** [comment]
Notes from ecosystem review: This isn't on core tf's roadmap and we're trying to avoid expanding the official api surface if possible atm (even for small things). Seems reasonable to us to have in addons
