### ISSUE TITLE
AttentionWrapper throws TypeError when passing multiple attention mechanisms

### ISSUE THREAD

**Issue by pas** [tensorflow/addons#2041]
**System information**
OS Platform and Distribution: **Ubuntu 18.04**
TensorFlow version and how it was installed: **TF 2.1.0 (binary)** / **TF 2.2.0 (binary)**
TensorFlow-Addons version and how it was installed (source or binary): **0.9.1 (binary)**, **0.10.0 (binary)**
Python version: **3.6.9**
Is GPU used? (yes/no): **no**

**Bug description**
AttentionWrapper constructor throws a TypeError when passing multiple attention mechanisms as list or as tuple. This is due the `@typechecked` annotation from typeguard. Running python with `__debug__` set to false throws no error and seems to work.

**Code to reproduce**
```javascript
import tensorflow as tf
import tensorflow_addons as tfa

attention1 = tfa.seq2seq.BahdanauAttention(2, memory=None)
attention2 = tfa.seq2seq.BahdanauAttention(2, memory=None)
cell = tf.keras.layers.LSTMCell(2)
tfa.seq2seq.AttentionWrapper(cell, [attention1,attention2])
```

**Logs**
```
../../anaconda3/envs/p36/lib/python3.6/site-packages/typeguard/__init__.py:809: in wrapper
    check_argument_types(memo)
../../anaconda3/envs/p36/lib/python3.6/site-packages/typeguard/__init__.py:670: in check_argument_types
    raise exc from None
../../anaconda3/envs/p36/lib/python3.6/site-packages/typeguard/__init__.py:668: in check_argument_types
    check_type(description, value, expected_type, memo)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

argname = 'argument "attention_mechanism"'
value = [<tensorflow_addons.seq2seq.attention_wrapper.BahdanauAttention object at 0x7f7914611128>, <tensorflow_addons.seq2seq.attention_wrapper.BahdanauAttention object at 0x7f7914611e48>]
expected_type = <class 'tensorflow.python.keras.engine.base_layer.Layer'>, memo = <typeguard._CallMemo object at 0x7f797a745c48>

(...)

../../anaconda3/envs/p36/lib/python3.6/site-packages/typeguard/__init__.py:598: TypeError`
```

**Comment by bhack** [comment]
Please use an updated version of TF addons instead of 0.9.1. 
As you can see we support a list:
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/attention_wrapper.py#L1594

**Comment by pas** [comment]
This seems not to be released on the newest version available for pip https://pypi.org/project/tensorflow-addons/#history even though the r10 branch is holding the change https://github.com/tensorflow/addons/commit/94ea1fe0d86ce115c36b59fe3d541ed76cf755ef#diff-3a8f0828390ee9bafeddb0d3c96257da . Is there a release plan for a version 0.10.1? What's the best way to handle this currently?

**Comment by bhack** [comment]
Yes It Is just two months old https://github.com/tensorflow/addons/pull/1872.

/cc @seanpmorgan if he want to make a comment about a new minor release.

**Comment by seanpmorgan** [comment]
> Yes It Is just two months old #1872.
> 
> /cc @seanpmorgan if he want to make a comment about a new minor release.

We should have a 0.11 release by the end of the week latest.
