### ISSUE TITLE
layers.WeightNormalization does not support custom keras layer?

### ISSUE THREAD

**Issue by gitlabspy** [tensorflow/addons#2042]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04
- TensorFlow version and how it was installed (source or binary): 2.3
- TensorFlow-Addons version and how it was installed (source or binary): 0.10
- Python version: 3.7
- Is GPU used? (yes/no): no

**Describe the bug**
```
raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: Rescale 
```
Rescale is a custom keras layer
**Code to reproduce the issue**
```
class Rescale(layers.Layer):
    """
    Per-channel rescaling.
    Args:
        num_channels (int): Number of channels in the input.
    """

    def __init__(self, num_channels):
        super(Rescale, self).__init__()
        self.num_channels = num_channels

    def build(self, input_shape):
        self.kernel = self.add_weight("rescale_kernel",
                                      shape=[1, 1, self.num_channels])

    def get_config(self):
        config = {"num_channels":self.num_channels}
        base_config = super(Rescale, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))

    def call(self, x):
        x = tf.matmul(x, self.kernel)
        return x

rescale = tfa.layers.WeightNormalization(Rescale(3))

print(rescale(tf.random.normal((1, 12, 12 , 3)))) # throw error
```

**Comment by bhack** [comment]
```
class Rescale(layers.Layer):
    """
    Per-channel rescaling.
    Args:
        num_channels (int): Number of channels in the input.
    """
 
    def __init__(self, num_channels, **kwargs):
        super(Rescale, self).__init__(**kwargs)
        self.num_channels = num_channels
 
    def build(self, input_shape):
        self.kernel = self.add_weight("rescale_kernel",
                                      shape=[1, 1, self.num_channels])
 
    def get_config(self):
        config = {"num_channels":self.num_channels}
        base_config = super(Rescale, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))
 
    def call(self, x):
        x = tf.matmul(x, self.kernel)
        return x
 
with tf.keras.utils.CustomObjectScope({"Rescale":Rescale}):
  rescale = tfa.layers.WeightNormalization(Rescale(3))
  print(rescale(tf.random.normal((1, 12, 12, 1)))) # throw error
```

**Comment by gitlabspy** [comment]
> Can you try?
> 
> ```
> class Rescale(layers.Layer):
>     """
>     Per-channel rescaling.
>     Args:
>         num_channels (int): Number of channels in the input.
>     """
>  
>     def __init__(self, num_channels, **kwargs):
>         super(Rescale, self).__init__(**kwargs)
>         self.num_channels = num_channels
>  
>     def build(self, input_shape):
>         self.kernel = self.add_weight("rescale_kernel",
>                                       shape=[1, 1, self.num_channels])
>  
>     def get_config(self):
>         config = {"num_channels":self.num_channels}
>         base_config = super(Rescale, self).get_config()
>         return dict(list(base_config.items()) + list(config.items()))
>  
>     def call(self, x):
>         x = tf.matmul(x, self.kernel)
>         return x
>  
> with tf.keras.utils.CustomObjectScope({"Rescale":Rescale}):
>   rescale = tfa.layers.WeightNormalization(Rescale(3))
>   print(rescale(tf.random.normal((1, 12, 12, 1)))) # throw error
> ```

Thx! That works!
