### ISSUE TITLE
About cos sin at tfa.image.transform_ops.angles_to_projective_transforms

### ISSUE THREAD

**Issue by Smankusors** [tensorflow/addons#2054]
Sorry, it's just my personal opinion, but if you look at this code :
https://github.com/tensorflow/addons/blob/5639b712c81e81ef2ec93d592c0ea704074a3c67/tensorflow_addons/image/transform_ops.py#L213-L268

`tf.math.cos` and `tf.math.sin` is called several times with same argument. Why not.... save this into new variables instead of calling it again and again? Something like this below :

```
cos_angles = tf.math.cos(angles)
sin_angles = tf.math.sin(angles)
```

I tried and the performance improves..... well, very little IMO, but why not?

Thanks,
Smankusors

**Comment by bhack** [comment]
You can open a small PR. Thanks
