### ISSUE TITLE
Cannot build tensorflow-addons-0.10.0 with bazel3.4.1

### ISSUE THREAD

**Issue by khsee** [tensorflow/addons#2060]
- OS: Ubuntu 20.04-arm64
- TensorFlow 2.2.0 - installed via wheel
- TensorFlow-Addons version and how it was installed (source or binary): attempting to build from source
- Python version: 3.8.2
- Is GPU used? (yes/no): no

When attempting "python3 ./configure.py", I have got errors for lines 131, 93 & 64. The error for line 64 (return tf.sysconfig.get_link_flags()[0][2:] "IndexError: list indexout of range". When I dumped out the contents of tf.sysconfig.get_link_flags(), it was empty! Need help.

**Comment by bhack** [comment]
Check https://github.com/tensorflow/addons/issues/1982#issuecomment-657273649
