### ISSUE TITLE
Testable docstrings

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/addons#2066]
https://github.com/tensorflow/addons/pull/677 is merged, so we are happy to introduce doctest on the docstring. This feature is awesome that can avoid wrong example usage.

Because the change might be small, please submit one sub-module, for example, activations, per PR. For more details, please refer to https://www.tensorflow.org/community/contribute/docs_ref.

Note that available namespace in our repo is `tf` for `tensorflow`, `np` for `numpy` and `tfa` for `tensorflow_addons`.

- [x] activations: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/activations
- [ ] callbacks: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/callback
- [ ] image: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/image
- [x] layers: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/layers
- [x] losses: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/losses
- [x] metrics: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/metrics
- [ ] optimizers: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/optimizers
- [x] rnn: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/rnn
- [ ] seq2seq: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/seq2seq
- [ ] text: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/text

It's also really appreciated that one can help improve our doc based on https://www.tensorflow.org/community/contribute/docs_style when scrutinizing docstrings.

**Comment by WindQAQ** [comment]
Seems that it wasn't integrated in our CI in #677 yet. I will do it in #2067.

**Comment by ashwin-phadke** [comment]
@WindQAQ  I am working on optimizers and just wanted to check if the following is the right way to update docstrings 

```
        >>> from tf.keras.optimizers import schedules

        >>> lr_schedule = schedules.TriangularCyclicalLearningRate(
        ... initial_learning_rate=1e-4,
        ... maximal_learning_rate=1e-2,
        ... step_size=2000,
        ... scale_mode="cycle",
        ... name="MyCyclicScheduler")

        >>> model.compile(optimizer=tf.keras.optimizers.SGD(
        ... learning_rate=lr_schedule),
        ... loss='sparse_categorical_crossentropy',
        ... metrics=['accuracy'])

        >>> model.fit(data, labels, epochs=5)


```
Also do I need to run doctest locally or will it run on the PR directy?

**Comment by Harsh188** [comment]
Hi! I'm gonna get started on working on `tensorflow_addons/losses`.

**Comment by tacho090** [comment]
Is help still required for this issue? I'm looking to collaborate

**Comment by WindQAQ** [comment]
@tacho090 sure, feel free to take any module you want to deal with and request my review :-)

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
