### ISSUE TITLE
ensure_tf_install

### ISSUE THREAD

**Issue by swimmiing** [tensorflow/addons#2075]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04
- TensorFlow version and how it was installed (source or binary): 2.3.0
- TensorFlow-Addons version and how it was installed (source or binary): 0.11.0
- Python version: 3.8
- Is GPU used? (yes/no): yes

**Describe the bug**
Now tfa supports TF 2.3.0
But UserWarning message still exists. (in ensure_tf_install.py)

> UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.2.0 and strictly below 2.3.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.3.0 and is not supported. 

min_version <= LooseVersion(tf.__version__) < max_version needs to be fixed to min_version <= LooseVersion(tf.__version__) <= max_version

**Code to reproduce the issue**

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by bhack** [comment]
Can you send a small PR to fix this? I think that the new policy could be `<=` changing the `strictly below` text in the warning.
I think It Is easier to maintain.

**Comment by seanpmorgan** [comment]
Thanks for bringing this up! Looks like we'll need to patch 0.11.1 and update the release procedure to include this:
https://github.com/tensorflow/community/blob/master/sigs/addons/RELEASE.md

**Comment by seanpmorgan** [comment]
Version 0.11.1 patch was released that should solve this. Thanks again!
