### ISSUE TITLE
Markdown parsing error in NovoGrad documentation page

### ISSUE THREAD

**Issue by seungjaeryanlee** [tensorflow/addons#2085]
The documentation page of NovoGrad has a broken Markdown link shown below:

![novograd](https://user-images.githubusercontent.com/6107926/89725432-69760a00-da4a-11ea-9c8c-1495ecf9ec69.png)

I suspect this is because only the first line of the docstring is used for the first line of the documentation page. In the docstring (shown below), the link spans multiple lines.

https://github.com/tensorflow/addons/blob/5f746971d0d9491716f2f13206299a2c45941b0c/tensorflow_addons/optimizers/novograd.py#L26-L28

The simplest solution would be to edit the docstring so that there is a one-line summary for the first line with a paper link after the newline. One example would be [LAMB's documentation page](https://www.tensorflow.org/addons/api_docs/python/tfa/optimizers/LAMB). I will create a PR with this solution.

**Comment by WindQAQ** [comment]
Feel free to request my review after submitting the PR 😃 It's also appreciated that you can add testable docstring for it. See https://github.com/tensorflow/addons/issues/2066 for more details.

**Comment by seungjaeryanlee** [comment]
I'll integrate doctest in a separate PR once I understand how everything works. Thanks for the suggestion and the link to the issue!
