### ISSUE TITLE
NotFoundError in transform function for images

### ISSUE THREAD

**Issue by andy7809** [tensorflow/addons#2089]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow version and how it was installed (source or binary): TF 2.3
- TensorFlow-Addons version and how it was installed (source or binary): 0.8.3
- Python version: 3.6.7
- Is GPU used? (yes/no): I am not sure

**Describe the bug**

There is an undefined symbol in _image_so, and using  the transform function for images in tfa will throw a NotFoundError.

**Code to reproduce the issue**
```
import tensorflow as tf
import numpy as np
import tensorflow_addons as tfa

img_path = tf.keras.utils.get_file('tensorflow.png','https://tensorflow.org/images/tf_logo.png')
img_raw = tf.io.read_file(img_path)
img = tf.io.decode_image(img_raw)
img = tf.image.convert_image_dtype(img, tf.float32)
img = tf.image.resize(img, [500,500])

rotate = tfa.image.rotate(img, tf.constant(np.pi/8))
```
[gist](https://gist.github.com/andy7809/b03eda61cabb7227aeaa3aec5de3105e?short_path=4e6c1fa)
**Other info / logs**

Could this be a Google Colab issue specifically? Is there a way I could ensure that its only a Colab issue?

[Traceback as gist](https://gist.github.com/andy7809/4b1d8481c4cbabd09cd08c6f6a0d2509)

**Comment by andy7809** [comment]
Upon further investigation, could this be waiting on googlecolab/colabtools#1243? If it is related to that, I will close this issue.

**Comment by bhack** [comment]
Try `!pip install --upgrade tensorflow-addons` in colab

**Comment by andy7809** [comment]
Yep, that worked! Closing this now, thanks
