### ISSUE TITLE
Deprecate MultiHeadAttention

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/addons#2090]
Deprecate MultiHeadAttention since https://github.com/tensorflow/tensorflow/commit/f32c80b3ed0d64eb0363f4196171467de79390d1 is merged.

I'm quite confused what our roadmap is. Should we alias/wrap the functionality to core TF or just remove it? In `gelu` case, the default argument is changed, and for `MultiHeadAttention`, the input signature is totally different.

**Comment by WindQAQ** [comment]
cc @tensorflow/sig-addons-maintainers

**Comment by AakashKumarNain** [comment]
Yeah there are differences. IMO, we should remove it.

**Comment by failure-to-thrive** [comment]
Just wondering, is there any policy on backward compatibility?

**Comment by bhack** [comment]
We have a no merged draft at https://github.com/tensorflow/community/pull/241
