### ISSUE TITLE
TQDMProgressBar still not working in TF-2.3.0

### ISSUE THREAD

**Issue by putopavel** [tensorflow/addons#2091]
**System information**
- OS Platform and Distribution: Google Colab
- TensorFlow version and how it was installed: 2.3.0, Colab preinstalled package
- TensorFlow-Addons version and how it was installed: 0.8.3, Colab preinstalled package
- Python version: 3.6.9
- Is GPU used? (yes/no): Yes

**Describe the bug**

Although https://github.com/tensorflow/addons/issues/1495 seems already corrected, I am still having the same problem with the environment described.

**Code to reproduce the issue**

Exactly the same as in https://github.com/tensorflow/addons/issues/1495

**Other info / logs**

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-33-2629815e8661> in <module>()

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_addons/callbacks/tqdm_progress_bar.py in on_train_begin(self, logs)
    100     def on_train_begin(self, logs=None):
    101         self.num_epochs = self.params["epochs"]
--> 102         self.metrics = self.params["metrics"]
    103 
    104         if self.show_overall_progress:

KeyError: 'metrics'
```

I checked the versions installed in Colab like this:

```python
(tf.__version__, tfa.__version__, tf.keras.__version__)
>>> ('2.3.0', '0.8.3', '2.4.0')
```

**Comment by bhack** [comment]
Can you test with `pip install --upgrade tensorflow-addons`?

**Comment by putopavel** [comment]
Upgrading the version solved the issue. Thanks for your help.
