### ISSUE TITLE
tfa.image.translate_xy, tfa.image.shear_* fails to work with float images

### ISSUE THREAD

**Issue by swghosh** [tensorflow/addons#2092]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Google Colaboratory` (Debian) / `macOS v10.15.6`
- TensorFlow version and how it was installed (source or binary): `Binary TF_v2.3.0`
- TensorFlow-Addons version and how it was installed (source or binary): `Binary tfa-nightly_v0.12.0.dev20200811022730`
- Python version: `3.7.6`
- Is GPU used? (yes/no): `no`

**Describe the bug**

`tfa.image.shear_x`, `tfa.image.shear_y`, `tfa.image.translate_xy` and possibly other args that make use of the `replace` argument fails to work with float images. The `replace` argument should strictly be an integer (uint8) which is also suggested in the documentation, but the same results in either `TypeError` or `ConcatV2` errors when working with non-integer images.

**Code to reproduce the issue**

```python3
float_image = tf.random.uniform([32, 32, 3], 0, 1, dtype=tf.float32)
sheared_image = tfa.image.shear_x(float_image, 0.3, replace=0.5)  # fails with TypeError
sheared_image = tfa.image.shear_x(float_image, 0.3, replace=128)  # fails with Concat error
```

A more detailed Colab with the stack trace and other possible combinations that still won't work for the same reason can be found in [[tfa.image] op bug w/ replace argument.ipynb](https://colab.research.google.com/gist/swghosh/7245f498ba407f5552a304fa2784c0ac/-tfa-image-op-bug-w-replace-argument.ipynb)

**Other info / logs**

```python3
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-50c68fed8a6d> in <module>()
----> 1 sheared_image3 = tfa.image.shear_x(float_image, 0.3, replace=0.5)
      2 sheared_image4 = tfa.image.shear_y(float_image, 0.4, replace=0.4)
      3 
      4 plt.imshow(sheared_image3)
      5 plt.show()

5 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_addons/image/transform_ops.py in shear_x(image, level, replace)
    324     #  0  1].
    325     image = transform(wrap(image), [1.0, level, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0])
--> 326     return unwrap(image, replace)
    327 
    328 

/usr/local/lib/python3.6/dist-packages/tensorflow_addons/image/utils.py in unwrap(image, replace)
    135     alpha_channel = flattened_image[:, 3]
    136 
--> 137     replace = tf.constant(replace, tf.uint8)
    138     if tf.rank(replace) == 0:
    139         replace = tf.expand_dims(replace, 0)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py in constant(value, dtype, shape, name)
    262   """
    263   return _constant_impl(value, dtype, shape, name, verify_shape=False,
--> 264                         allow_broadcast=True)
    265 
    266 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
    273       with trace.Trace("tf.constant"):
    274         return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
--> 275     return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
    276 
    277   g = ops.get_default_graph()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py in _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
    298 def _constant_eager_impl(ctx, value, dtype, shape, verify_shape):
    299   """Implementation of eager constant."""
--> 300   t = convert_to_eager_tensor(value, ctx, dtype)
    301   if shape is None:
    302     return t

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py in convert_to_eager_tensor(value, ctx, dtype)
     96       dtype = dtypes.as_dtype(dtype).as_datatype_enum
     97   ctx.ensure_initialized()
---> 98   return ops.EagerTensor(value, ctx.device_name, dtype)
     99 
    100 

TypeError: Cannot convert 0.5 to EagerTensor of dtype uint8
```

```python3
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-13-ffd69f46b291> in <module>()
----> 1 sheared_image3 = tfa.image.shear_x(float_image, 0.3, replace=128)
      2 sheared_image4 = tfa.image.shear_y(float_image, 0.4, replace=0)
      3 
      4 plt.imshow(sheared_image3)
      5 plt.show()

6 frames
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: cannot compute ConcatV2 as input #1(zero-based) was expected to be a uint8 tensor but is a float tensor [Op:ConcatV2] name: concat
```

What would be the way out to run these op(s) with float images?

@windqaq @facaiy @sayoojbk
/cc: @tanzhenyu

**Comment by WindQAQ** [comment]
This is the bug in our part. I can fix it recently. But personally, I discourage use this function after https://github.com/tensorflow/tensorflow/pull/41365 gets merged. Once one can control `fill_value` when doing transformation, `wrap`/`unwrap` is redundant.

**Comment by swghosh** [comment]
Hi @WindQAQ, thanks for sharing the update on TF `ImageProjectiveTransformV2` and it's upcoming support for `fill_mode` as a complete op arg.
So as a workaround we should wait for the changes to get merged on tf/master and then look into a fix for this (float support on image ops with `replace`), right?

**Comment by WindQAQ** [comment]
> Hi @WindQAQ, thanks for sharing the update on TF `ImageProjectiveTransformV2` and it's upcoming support for `fill_mode` as a complete op arg.
> So as a workaround we should wait for the changes to get merged on tf/master and then look into a fix for this (float support on image ops with `replace`), right?

Yes, I can fix it today or you can open an PR for it!

**Comment by swghosh** [comment]
> > Hi @WindQAQ, thanks for sharing the update on TF `ImageProjectiveTransformV2` and it's upcoming support for `fill_mode` as a complete op arg.
> > So as a workaround we should wait for the changes to get merged on tf/master and then look into a fix for this (float support on image ops with `replace`), right?
> 
> Yes, I can fix it today or you can open an PR for it!

I'll work on a PR and get this done. (utilising the `fill_mode` argument from ImageProjectiveTransformV2)
Should I then skip wrap / unwrap completely?

**Comment by WindQAQ** [comment]
> > > Hi @WindQAQ, thanks for sharing the update on TF ImageProjectiveTransformV2 and it's upcoming support for fill_mode as a complete op arg.
> > > So as a workaround we should wait for the changes to get merged on tf/master and then look into a fix for this (float support on image ops with replace), right?
> 
> > Yes, I can fix it today or you can open an PR for it!
> 
> I'll work on a PR and get this done. (utilising the fill_mode argument from ImageProjectiveTransformV2)
> Should I then skip wrap / unwrap completely?

Sorry that I accidentally edited your comment... And just leave it alone as `fill_value` has not supported yet.

**Comment by swghosh** [comment]
Oh cool cool. We can wait till the support is added. Thanks.
