### ISSUE TITLE
tfa.image.rotate fails to work

### ISSUE THREAD

**Issue by luke199629** [tensorflow/addons#2093]
I was running this tutorial on [google colab](https://colab.research.google.com/github/tensorflow/addons/blob/master/docs/tutorials/image_ops.ipynb) with TF2.3 and this command 
`rotate = tfa.image.rotate(img, tf.constant(np.pi/8))`
under "Rotate" section fails to work with the following error message:
<img width="1701" alt="Screen Shot 2020-08-15 at 1 12 52 AM" src="https://user-images.githubusercontent.com/8813788/90305856-faa70f80-de94-11ea-86ae-a7d1fc7e6d1e.png">
Can someone tell me how to fix this? Thank you very much!

**Comment by WindQAQ** [comment]
try to upgrade tensorflow-addons to latest version (either 0.11 or nightly), which pins to tensorflow==2.3.0. Like the following command on colab
```bash
!pip install --upgrade tensorflow-addons --no-deps
```
https://colab.research.google.com/drive/1CYLJumUABwrm1R5KC6WOcnLHrCjq3x1S?usp=sharing

**Comment by luke199629** [comment]
Thanks a lot! This fix works perfectly!
