### ISSUE TITLE
MovingAverage optimizer swap_weights is not very usable 

### ISSUE THREAD

**Issue by marksandler2** [tensorflow/addons#2107]
**System information**
Any

**Describe the bug**

If one calls `optimizer.swap_weights` without calling `optimizer.shadow_copy` it crashes with cryptic error message
 (of _average_weights not existing) - despite successfully optimizing for earlier steps (and presumably creating average variables - just not setting up _average_weight!). 

However, ` shadow_copy` requires a `var_list`, which is not something that is necessarily available at the call site that needs eed to swap_weights, which leads to implementation details leaking over the place. 

**Code to reproduce the issue**
```python
optimizer = tf.keras.optimizers.RMSprop(
       learning_rate=lr_schedule, rho=0.9, momentum=0.9, epsilon=0.001)
optimizer = tfa.optimizers.MovingAverage(
        optimizer, average_decay=FLAGS.moving_average_decay)

run_training(optimizer) # trainng loop code (that is not aware that optimizer is MovingAverage optimizer
# now I want to swap weights to run evaluation:
optimizer.swap_weights()  # crashes because shadow_copy was never created. 
run_eval()
```

**Other info / logs**

It would be much better if _create_slots() would also setup _average_weights, and_model_weights,
 so that swap_weights could be called as soon as slots are created. Here is a simple change that makes it workable again:

```python
  def _create_slots(self, var_list):
    self._optimizer._create_slots(var_list=var_list)  # pylint: disable=protected-access
    for var in var_list:
      self.add_slot(var, "average", var.read_value()) 
    ###### new code
    self._average_weights = [
        self.get_slot(var, "average") for var in var_list
    ]
    self._model_weights = var_list
    ###### end new code
```
Optional: delete shadow_copy function

**Comment by bhack** [comment]
Can you open a PR? Thanks
