### ISSUE TITLE
Switch to CUDA 11 and cuDNN 8 

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#2110]
TF-Nightly has switched already and this should match TF2.4. We'll likely wait until 2.4rc0 to do this, but the groundwork was laid in #1950 and we can likely test both CUDA versions in CI.

https://groups.google.com/a/tensorflow.org/g/discuss/c/G4E2VPY-X_8
https://github.com/tensorflow/tensorflow/issues/42047

**Comment by Harsh188** [comment]
Any news on this? TF2.4rc1 to works with CUDA 11.1 on my machine.
