### ISSUE TITLE
List TensorFlow as an "extra" requirement to install the correct TFA for a given TF version

### ISSUE THREAD

**Issue by tgaddair** [tensorflow/addons#2111]
When installing `tensorflow_addons` without specifying an exact version, users may install a version that is incompatible with their existing TensorFlow version.  

As such, users are advised to check the [Python Op Compatibility Matrix](https://github.com/tensorflow/addons#python-op-compatibility-matrix) and manually install the correct version of TFA to be safe.

For most Python projects, this can be taken care of automatically by listing a specific `tensorflow` version(s) as a requirement in the `setup.py` file:

```
install_requires=['tensorflow>=2.2,<2.4']
```

I suspect that this project does not do this because of the various different pip package names TensorFlow uses (e.g., `tf-nightly`, `tensorflow-gpu`, `tensorflow-cpu`).  By having such a requirement, user could accidentally install two different versions of TensorFlow at the same time.

To get around this, we could introduce an extra requirement:

```
extras_require = {'tensorflow': ['tensorflow>=2.2,<2.4']}
```

This way, users will only get automatic dependency resolution when running `pip install tensorflow_addons[tensorflow]`.

The benefit of doing this is that if a new version of TFA is released that no longer supports TensorFlow 2.2 (for example), pip will fall back to installing the previous version of TFA if the user has TF 2.2 installed.

**Comment by seanpmorgan** [comment]
Thanks @tgaddair this could be a very nice addition! Wanted to clarify one thing:

> The benefit of doing this is that if a new version of TFA is released that no longer supports TensorFlow 2.2 (for example), pip will fall back to installing the previous version of TFA if the user has TF 2.2 installed.

Is that correct? My understanding of `extras_require` is that instead it would attempt to install/overwrite whatever newer version of TF was specified by TFA. I'm not getting a definitive answer from this:
https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by tgaddair** [comment]
Hey @seanpmorgan, thanks for raising this point.  I did some tests, and you are correct, the extra will overwrite any existing version of TF.  So not quite as useful as I'd hoped, but still useful.  Basically, it serves as a forced upgrade.  Also, it seems that non-extra requirements have the same behavior, so it's still equivalent to having it as a general install dependency, only optional.

If that all sounds reasonable to you, I will update the docs for the PR.

**Comment by seanpmorgan** [comment]
Yes that sounds reasonable. Thanks for double checking.. please proceed to updating the PR
