### ISSUE TITLE
Why MovingAverage num_steps takes 'string'?

### ISSUE THREAD

**Issue by ildoonet** [tensorflow/addons#2113]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow version and how it was installed (source or binary): TF 2.3.0, binary
- TensorFlow-Addons version and how it was installed (source or binary): 0.11.0
- Python version: 3.6.8
- Is GPU used? (yes/no): yes

**Describe the bug**

MovingAverage type error seems to be weird. 

```
type of argument "num_updates" must be one of (str, NoneType); got tensorflow.python.distribute.values.MirroredVariable instead
```

Optional[str] is wrong : https://github.com/tensorflow/addons/blob/v0.10.0/tensorflow_addons/optimizers/moving_average.py#L50

**Code to reproduce the issue**

```
optimizer = tfa.optimizers.SGDW(
            learning_rate=FLAGS.lr, weight_decay=FLAGS.weight_decay, momentum=0.9, nesterov=True)
        optimizer = tfa.optimizers.MovingAverage(optimizer, average_decay=0.9999, num_updates=optimizer.iterations)
```

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by AakashKumarNain** [comment]
Yeah that's a bug. It should either be a `int` or a `tf.Varaible` with correct dtype. Thanks for reporting. Can you please add a PR with the correction?
