### ISSUE TITLE
Cannot save model after custom metric, i.e. F1Score,FBetaScore etc.

### ISSUE THREAD

**Issue by TimbusCalin** [tensorflow/addons#2125]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow 2.3, via pip install tensorflow:
- TensorFlow-Addons 0.11.1:
- Python version: 3.6.5
- Is GPU used? (yes) GTX 1080Ti:

**Describe the bug**

Practically, if I want to save the model after` val_f1_score` or any other custom metric besides val_loss, I get the error mentioned below. It is very frustrating.

**Code to reproduce the issue**
The callbacks ReduceLROnPlateau or ModelCheckpoint do not work with custom metric `tfa.metrics.F1Score(num_classes=3) `

```

callbacks = [best_model_callback(save_model_filepath='weights/model_{val_categorical_accuracy:.4f}.hdf5'),
                 reduce_lr_on_plateau_callback(),
                 tensorboard_callback(tensorboard_logs_dir="logs/"),
                 ]
def reduce_lr_on_plateau_callback():
    reduce_lr_callback = tf.keras.callbacks.ReduceLROnPlateau(monitor="val_f1_score",
                                                              factor=0.1,
                                                              patience=3,
                                                              verbose=1,
                                                              mode='max')
    return reduce_lr_callback

def best_model_callback(save_model_filepath):
    best_model_checkpoint = tf.keras.callbacks.ModelCheckpoint(
        filepath=save_model_filepath, monitor="val_f1_score", verbose=1,
        save_best_only=False, mode='max', save_freq='epoch')
    return best_model_checkpoint


 model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0003),
                  loss=tf.keras.losses.KLDivergence(),
                  metrics=[tf.keras.metrics.CategoricalAccuracy(),
                           tfa.metrics.F1Score(num_classes=3)])

 history = model.fit(training_dataset.repeat(),
                        epochs=15,
                        steps_per_epoch=training_length
                        validation_data=validation_dataset.repeat(),
                        validation_steps=validation_length,
                        callbacks=callbacks,
                        verbose=1)

```

**Other info / logs**

The error is: ValueError: 

> The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by bhack** [comment]
Can you send a very minimal but runnable example that we can copy, past and run to reproduce this?
Thanks.

**Comment by TimbusCalin** [comment]
@bhack I can understand why this is happening now and solved the issue, after printing the logs.

Apparently, when the metrics F1Score is declared,
`tfa.metrics.F1Score(num_classes=3)`, the metric generates the F1-Score value per-class, i.e. np.array(length_of_classes).

Of course, this does not go well with the ModelCheckpoint, which needs to receive a float value instead of an array of numpy, hence the error with 

> The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


The solution to this is to declare/exactly specify the average parameter, since the default is None: 
```

                           tfa.metrics.F1Score(num_classes=3,average='macro'),
```

**Comment by TimbusCalin** [comment]
@bhack  I also want to mention that during the training the values displayed for the metrics are good, the problem is only related to ModelCheckpoint or ReduceLROnPlateau.
