### ISSUE TITLE
Generated documentation of type aliases are included in unrelated modules

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/addons#2132]
For example, the documentation of `TensorLike` is located in `tfa.image.color_ops`:

https://www.tensorflow.org/addons/api_docs/python/tfa/image/color_ops/TensorLike

Presumably, the system selects the module where the symbol was first found. This is not a big issue but it produces strange and unexpected documentation for type annotations, see for example:

https://www.tensorflow.org/addons/api_docs/python/tfa/seq2seq/LuongAttention

I see 2 possible solutions:

1. Hide non public symbols in the generated documentation
1. Properly export type aliases in a public module

**Comment by seanpmorgan** [comment]
Good catch. I think I'd prefer #2 since those TensorTypes are pretty important to the end user as it stands today.

**Comment by souradeepmajumdar05** [comment]
can i take this up?

**Comment by seanpmorgan** [comment]
Hi @souradeepmajumdar05 it's currently being handled in https://github.com/tensorflow/addons/pull/2162 . Please feel free to ask in our issues though we're always looking for help!
