### ISSUE TITLE
Refactor docs directory

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/addons#2161]
Per comment https://github.com/tensorflow/addons/pull/2160#discussion_r487230647, better to move these stuff out of `docs`.

- [ ] Move build tools to `tools/docs`
- [ ] Modify related documentation

**Comment by souradeepmajumdar05** [comment]
can i take this up?

**Comment by hp77-creator** [comment]
@seanpmorgan there seems to be two tasks in this issue, You can assign both of us one task or howsoever you deem fit. I would also like to work on this.

**Comment by seanpmorgan** [comment]
> @seanpmorgan there seems to be two tasks in this issue, You can assign both of us one task or howsoever you deem fit. I would also like to work on this.

Hi @hp77-creator the two tasks should probably be done in the same PR. Since you've started with #2167 please feel free to add another commit on that branch

**Comment by hp77-creator** [comment]
Hi @seanpmorgan, I am not sure as to what I have to do in the documentation. Can you specify what I should write? I also reviewed the failed check of my pull request, there it said 
```bash
#18 0.454 python: can't open file 'docs/build_docs.py': [Errno 2] No such file or directory
```
So should I keep a copy of build_docs.py in docs to pass this check or do I have to modify any tests too?

**Comment by Harsh188** [comment]
@hp77-creator you have to remove `build_docs.py` from [`BUILD`](https://github.com/tensorflow/addons/blob/master/docs/BUILD#L12). You would also have to update the `README.md` to reflect your changes.

**Comment by hp77-creator** [comment]
@Harsh188 Removing build_docs.py from BUILD is leading to more fails in CI tests. I tried with updating readme with the correct paths but still of no use. Can you have a look at the PR?
