### ISSUE TITLE
Add recompute_grad decorator

### ISSUE THREAD

**Issue by olesalscheider** [tensorflow/addons#218]
**System information**
- TensorFlow version (you are using): 2.0 alpha
- TensorFlow Addons version: 1.2.1
- Is it in the tf.contrib (if so, where): Yes, tf.contrib.layers.recompute_grad
- Are you willing to contribute it (yes/no): Yes
- Are you willing to maintain it going forward? (yes/no): No

**Describe the feature and the current behavior/state.**
The tf.contrib.layers.recompute_grad decorator allows to recompute the decorated function on the backward pass. This way the activation maps do not have to be kept in memory.
It allows to train larger models that normally would not fit into the VRAM but with higher computational costs. The current implementation works fine for me.

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
Anyone who wants to train a very large network with limited GPU memory.

**Any Other info.**
I know that the current RFC for addons (https://github.com/tensorflow/community/blob/master/rfcs/20181214-move-to-addons.md) proposes not to move the decorator, but it is marked "pending objections". I would like to ask you to reconsider your decision. I have used the decorator in the past whenever necessary (i. e. when I would run out of memory). The reason why you don't find OSS projects using it by default might be that you do not want the annotation if it is not necessary because it slows down the training process. But it is still a good alternative if you do not have a GPU with lots of VRAM available.

**Comment by seanpmorgan** [comment]
Hi @olesalscheider welcome and thanks for bringing this up. I agree this is a useful thing to have, but I do want to make sure we're not duplicating functionality. 

I haven't looked tpo closely at the details, but is the same capability provided by:
https://github.com/openai/gradient-checkpointing

It looks like it's set for tf1.x, but perhaps upgrading that repo is another option.

**Comment by olesalscheider** [comment]
The implementation that you linked to existed before the decorator. It replaces tf.gradients and actually offers more than the decorator in TensorFlow: It also comes with some heuristics to decide without manual annotation which activation maps can be recomputed.
I think TF has something like that in grappler's memory optimizer nowadays but it will only recompute very cheap operations: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/grappler/optimizers/memory_optimizer.cc#L60

The code that you linked to has not been updated in some time and it is not compatible with TF 2.
Ideally I would like to see improved heuristics in grappler: Have costs for each common operation without state and recompute as much as needed to fit the model into the memory. But a decorator for manual annotation that is compatible with TF2 would still be valuable for tuning in edge cases.

**Comment by seanpmorgan** [comment]
Hi @olesalscheider so we think this is certainly a valuable contribution. Would you be willing to create a WIP pull request so we can decide where it can be housed? Perhaps a decorators submodule within tfa.layers?

Looking at the contrib code it looks like it utilizes variable scope which no longer exists in TF2. It will need to be slightly modified to analyze the variables of a python object.

**Comment by olesalscheider** [comment]
I started to port the code. You can see the progress here:
https://github.com/tensorflow/addons/pull/256

**Comment by WindQAQ** [comment]
Hi, @olesalscheider, I just found https://github.com/tensorflow/tensorflow/commit/f958df6b557176f6858742fabd97ade4f71bf212 in core TF (June 4th). Does this have the same functionality with the one in tf.contrib?

**Comment by seanpmorgan** [comment]
Good find @WindQAQ. I've made a note in our monthly meeting to discuss a better way for us to be informed of contrib moves/changes within TF core.  Apologies for the extra work @olesalscheider (assuming this covers all the functionality you were looking for)

**Comment by olesalscheider** [comment]
Yes, it looks like this would work for me. I can test it later.

**Comment by seanpmorgan** [comment]
Sounds good! Happy to re-open this if there is some functionality missing (though it might make more sense as a PR to TF core)

**Comment by pidajay** [comment]
@olesalscheider Did you ever get to test this recompute_grad function that got ported to TF core? I can wrap my model in it and perform a training loop (in eager mode). But I am not sure it is producing the desired memory savings.

**Comment by olesalscheider** [comment]
I think I tried it back then. But in the end the memory savings were not large enough and I ended up splitting the model across multiple GPUs.

**Comment by WingsOfPanda** [comment]
> I think I tried it back then. But in the end the memory savings were not large enough and I ended up splitting the model across multiple GPUs.

hi @olesalscheider this question might be irrelevant, but I don't have other place to ask you around. I am trying to train a DL model with large input (not a large model), say a super-resolution image, and I can't fit my model training into one GPU. I tried to split my model across multiple GPUs but I end up with no luck. Could u share me some reference/ideas that how u did it? Thx!

**Comment by olesalscheider** [comment]
> hi @olesalscheider this question might be irrelevant, but I don't have other place to ask you around. I am trying to train a DL model with large input (not a large model), say a super-resolution image, and I can't fit my model training into one GPU. I tried to split my model across multiple GPUs but I end up with no luck. Could u share me some reference/ideas that how u did it? Thx!

In your case, the activations of your network will probably consume a lot of memory. These have to be kept around for the backward pass.
Unfortunately, tensorflow currently executes the backward pass on just one device, even if you split your model. That's why you will can run into memory problems even if you split your training.

I tried to fix this here: https://github.com/tensorflow/tensorflow/issues/33688
My patch got reverted because it caused some performance regression with internal models at Google, but it allows me to train my models. You could try to apply the patch and build tensorflow yourself.

**Comment by WingsOfPanda** [comment]
> > hi @olesalscheider this question might be irrelevant, but I don't have other place to ask you around. I am trying to train a DL model with large input (not a large model), say a super-resolution image, and I can't fit my model training into one GPU. I tried to split my model across multiple GPUs but I end up with no luck. Could u share me some reference/ideas that how u did it? Thx!
> 
> In your case, the activations of your network will probably consume a lot of memory. These have to be kept around for the backward pass.
> Unfortunately, tensorflow currently executes the backward pass on just one device, even if you split your model. That's why you will can run into memory problems even if you split your training.
> 
> I tried to fix this here: [tensorflow/tensorflow#33688](https://github.com/tensorflow/tensorflow/issues/33688)
> My patch got reverted because it caused some performance regression with internal models at Google, but it allows me to train my models. You could try to apply the patch and build tensorflow yourself.

yep sir. I tried sth myself to split model training into multi-gpus. What I did is sth like follows: 

1. split the forward pass into two parts, let's say 'f0' and 'f1'. Then I place 'f0' and 'f1' on gpu0 and gpu1, respectively. 
2. record 'tf.GradientTape(persistent=True)' for 'f1' and watch the input of 'f1', and obtain the gradient of output of 'f1' with respect to the input of 'f1', say it be 'grad_f1_input'
3.  compute the 'tape.jacobian' of 'f0' for the output of 'f0' and all variables of 'f0', then use 'grad_f1_input' to multiplay with those Jacobin to obtain the correct gradient of variables of 'f0'.

I test this method and verified that the gradient I obtained for 'f0' is correct. However, I meet the trouble is that 'tape.jacobian'  itself is extremely large (since the size of input is huge), and I end up with OOM again...

I will checkout the fix u mentioned there and see if I can use it.

Thank you!

**Comment by nyngwang** [comment]
> I think I tried it back then. But in the end the memory savings were not large enough and I ended up splitting the model across multiple GPUs.

@olesalscheider Does this still happen on tensorflow 2.9.1, i.e. the latest version for now?
