### ISSUE TITLE
The meaning of Triangular2CyclicalLearningRate's `step_size` should be clarified

### ISSUE THREAD

**Issue by CNOCycle** [tensorflow/addons#2181]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): None
- TensorFlow version and how it was installed (source or binary): None
- TensorFlow-Addons version and how it was installed (source or binary): None
- Python version: None
- Is GPU used? (yes/no): None

**Describe the bug**

This is a issue about document.

Hi authors,

I suggest that the document about `CyclicalLearningRate` series[[1]](https://www.tensorflow.org/addons/api_docs/python/tfa/optimizers/TriangularCyclicalLearningRate) [[2]](https://www.tensorflow.org/addons/api_docs/python/tfa/optimizers/Triangular2CyclicalLearningRate) [[3]](https://www.tensorflow.org/addons/api_docs/python/tfa/optimizers/CyclicalLearningRate) should be clarified.

Deveplovers are not abel to understand of the meaning of `step_size`.

Instead, pytorch's document provides understandable meaning of `step_size_up` and `step_size_down` [[4]](https://pytorch.org/docs/stable/optim.html#torch.optim.lr_scheduler.CyclicLR).

The original defintion of `step_size` is **number of training iterations per half cycle**.

I guess that tfa follows the original defintion.

Any help will be appreciated.

Thanks.

**Code to reproduce the issue**

None

**Other info / logs**
None

**Comment by seanpmorgan** [comment]
PR merged thanks for brining this up!
