### ISSUE TITLE
Drop Python3.5 Support

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#2183]
Per SIG Build, python3.5 will not be supported in TF2.4 since it has reached end of life. We should align.

**Comment by bhack** [comment]
https://github.com/tensorflow/build/issues/14

**Comment by Saqhas** [comment]
Hi @seanpmorgan 
I can take up this task to port any module in python 3.5 to higher version
I think we should aim for python 3.8 as it is latest and has many good features.
What do you say @bhack

**Comment by seanpmorgan** [comment]
Hi @Saqhas. So there should be no need to port anything as code is already built against py3.5, 3.6, 3.7, and 3.8:
https://github.com/tensorflow/addons/blob/master/.github/workflows/release.yml#L42

This more or less just involves dropping py3.5 from all of our build matrices. We could however use some py3.6+ features like f-strings though.

**Comment by bhack** [comment]
https://github.com/tensorflow/tensorflow/commit/df6a423036492c10de26b33b0f5a7bbff51b95ec
