### ISSUE TITLE
[Feature Request] Natural-Logarithm-Rectified Activation Function

### ISSUE THREAD

**Issue by abhinavsp0730** [tensorflow/addons#2186]
**Describe the feature and the current behaviour/state.**
I want to implement [Natural-Logarithm-Rectified Activation Function](https://arxiv.org/ftp/arxiv/papers/1908/1908.03682.pdf).
And want NLReLU to be a part of addon's activation function.
Benefits of NLReLU:-
NLReLU retains the sparse activation characteristic of ReLU, but it also alleviates the “dying ReLU” and vanishing gradient problems to some extent. It also reduces the bias shift effect and heteroscedasticity of neuron data distributions among network layers in order to accelerate the learning process. (from paper)
**Relevant information**
- Are you willing to contribute it (yes/no): yes
- Are you willing to maintain it going forward? (yes/no): yes
- Is there a relevant academic paper? (if so, where): yes, https://arxiv.org/ftp/arxiv/papers/1908/1908.03682.pdf
- Is there already an implementation in another framework? (if so, where): Not able to find any implementation
- Was it part of tf.contrib? (if so, where): No

**Which API type would this fall under (layer, metric, optimizer, etc.)**
Activation

**Who will benefit with this feature?**
Everyone who wants to find an alternative of ReLU which retains sparse activation feature and also it's gonna alleviates "dying ReLU" problem and vanishing gradient problems to some extent.

**Comment by bhack** [comment]
Just a note after more than 1 year I don't see any other paper referencing this work.

**Comment by AakashKumarNain** [comment]
Yeah, the number of references are very low

**Comment by abhinavsp0730** [comment]
Thanks @bhack  @AakashKumarNain . So, that means I should close this Issue? And for the future contributions(activation functions, optimizer, loss etc)  I've to also keep in mind no. of references of respective paper?

**Comment by AakashKumarNain** [comment]
Yes, we will close this issue for now. For the future contributions, we will update this point in the `CONTRIBUTING` guide very soon so that the contributors have a clarity about it
