### ISSUE TITLE
Build binaries for python3.9

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#2188]
**Describe the feature and the current behavior/state.**

Py39 is out but we need to wait for core TF to support it first. We should quickly follow.

**Comment by Harsh188** [comment]
Would like to help out!

**Comment by seanpmorgan** [comment]
Blocked by https://github.com/tensorflow/tensorflow/issues/44485 hopefully coming soon.

**Comment by bhack** [comment]
Waiting for https://github.com/protocolbuffers/protobuf/pull/8121

**Comment by seanpmorgan** [comment]
Unblocking but this needs to wait for TF2.5 release candidates

**Comment by bersbersbers** [comment]
> Unblocking but this needs to wait for TF2.5 release candidates

Here we go - this installs fine on 3.9.4:
https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0-rc0

**Comment by GuillemGSubies** [comment]
TF 2.5.0 is out. Any plans on supporting python3.9?

**Comment by bersbersbers** [comment]
@GuillemGSubies see #2441 linked just before your comment.
