### ISSUE TITLE
missing `exclude_from_weight_decay` in AdamW

### ISSUE THREAD

**Issue by dathudeptrai** [tensorflow/addons#2217]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow version and how it was installed (source or binary): binary 2.3
- TensorFlow-Addons version and how it was installed (source or binary): binary nightly
- Python version: 3.6
- Is GPU used? (yes/no): yes

**Describe the bug**

seem `exclude_from_weight_decay` is missed in `tfa.optimizers.AdamW`. in `tfa.optimizers.LAMB`, we have this parameter. 

**Code to reproduce the issue**

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by bhack** [comment]
https://github.com/tensorflow/addons/issues/1903
