### ISSUE TITLE
pip install tensorflow-addons fails on windows machine Python 3.6.4

### ISSUE THREAD

**Issue by Mainak431** [tensorflow/addons#222]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.0.0-a.0
- TensorFlow Addons installed from (source, PyPi):
- TensorFlow Addons version:
- Python version and type (eg. Anaconda Python, Stock Python as in Mac, or homebrew installed Python etc): python 3.6.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- Is GPU used? (yes/no):
- GPU model (if used):

**Describe the bug**

**Describe the expected behavior**

**Code to reproduce the issue**

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Collecting tensorflow-addons
  ERROR: Could not find a version that satisfies the requirement tensorflow-addons (from versions: none)
ERROR: No matching distribution found for tensorflow-addons

**Comment by seanpmorgan** [comment]
This is on the roadmap, but is not yet available. See https://github.com/tensorflow/addons/issues/173
