### ISSUE TITLE
contrib.layers.initializers

### ISSUE THREAD

**Issue by AdRever** [tensorflow/addons#2221]
I am currently trying to upgrade a code from tf 1.x to 2.x and I came across the following import:
`from tensorflow.contrib.layers.python.layers.initializers import variance_scaling_initializer`
After reviewing the information regarding tf.comtrib I believe partial contrib.layer were add to add-ons but I don't seem to see it in the add-ons, I would like to know if contrib.layers.initializers is planned to be implemented or if it exists already but under a different name?
Thank you!

**Comment by bhack** [comment]
Are you looking for this one?
https://www.tensorflow.org/api_docs/python/tf/keras/initializers/VarianceScaling

**Comment by AdRever** [comment]
It is certainly that. I was looking on the wrong side because it was said that part of contrib.layer were move to add-ons. Thank you I will check out that.

**Comment by bhack** [comment]
Ok please close this after your check
