### ISSUE TITLE
WeightNormalization can not be used within tf.while_loop

### ISSUE THREAD

**Issue by hellomotor** [tensorflow/addons#2228]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- TensorFlow version and how it was installed (source or binary): binary
- TensorFlow-Addons version and how it was installed (source or binary): source
- Python version: 3.74.
- Is GPU used? (yes/no): yes

**Describe the bug**
    When using WeightNormalization within tf.while_loop, the following exception will raised:

      ValueError: Operation '*variable/scope/name*/weight_normalization/data_dep_init/VarIsInitializedOp' has been marked as not fetchable.

     This is be caused the session.run method cannot be used in tf.while_loop,  and the get_weights method is used at 
(https://github.com/tensorflow/addons/blob/81529ff7dd246f7575338b8cfe65784b0cc8a502/tensorflow_addons/layers/wrappers.py#L120)，but get_weights will invoke session.run finally. 

**Code to reproduce the issue**
     
     time = tf.constant(0, dtype=tf.int32)
     total = tf.constant(10, dtype=tf.int32)

     def cond(time, total, _, _):
            return tf.less(time, total)
      
      def body(time, total, encoded, results):
            ...
            conv = WeightNormalization(
                tf.keras.layers.Conv1D(100, kernel_size=5,strides=2)
            )
           encoded = conv(encoded)
           ...
           return time + 1, total, encoded, results

       time, total, encoded, hypothesis = tf.while_loop(
            cond, 
            body, 
            loop_vars=(time, total, encoded, results)
       )

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
 

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by bhack** [comment]
Can you share a very, very minimal but complete "copy and run" example or Colab to reproduce this?

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
