### ISSUE TITLE
ValueError: All inputs to `ConcreteFunction`s must be Tensors

### ISSUE THREAD

**Issue by moha23** [tensorflow/addons#2232]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu20.04
- TensorFlow version and how it was installed (source or binary): pip
- TensorFlow-Addons version and how it was installed (source or binary): pip
- Python version: 3.6
- Is GPU used? (yes/no): yes, gtx1080Ti
- Tf version 2.1.2 (required for compatibility with another library)
- Tfa version 0.9.1

**Describe the bug**

Tf.train_on_batch cant take numpy array as input, asks for tensor and even using tf.convert_to_tensor doesn't help. It works in Tf2.3, but Tf2.1 is a requirement for compatibility with another library. Not using tfa library no such error occurs, I cant find exactly which part of tfa is causing the issue. 

**Code to reproduce the issue**

    import tensorflow as tf
    import numpy as np
    from sklearn.model_selection import train_test_split
    from tensorflow.keras.layers import (Conv2D,Input)
    from tensorflow.keras.models import Model
    from tensorflow.keras.optimizers import Adam
    import tensorflow_addons as tfa #version 0.9.1

    opt = Adam(lr=1e-4)
    tf.config.experimental_run_functions_eagerly(True)

    def custom_mean_squared_error(y_true, y_pred):
        return(tf.reduce_mean(tf.math.squared_difference(y_true, y_pred)))

    def firstStream(ip):
            layer = Conv2D(64, kernel_size=(5, 5), padding='same')(ip)
            op = Conv2D(3, (5, 5), activation='sigmoid', padding='same')(layer)
            return op
        
    def secStream(ip):
            layer = Conv2D(8, kernel_size=(5, 5), padding='same')(ip)
            flow = Conv2D(2, (5, 5), activation='sigmoid', padding='same')(layer)
            return flow

    def main():

        ip = Input(shape=(None, None, 3))
        op = firstStream(ip)
        flow = secStream(ip)
        warped = tf.expand_dims(tfa.image.dense_image_warp(op,flow,name='warp'),axis=1)
        model = Model(ip,warped)
        model.compile(optimizer=opt, loss=custom_mean_squared_error)
            
        numEpochs = 1
 
        for epochNo in range(numEpochs):

                print("Running epoch : %d" % epochNo)
                batch_ip=np.ones((1,64,64,3))
                      
                curr_loss = model.train_on_batch(batch_ip, batch_ip)
                print(curr_loss)

    main()

**Other info / logs**

main()
  File "/home/mohana/work/simple.py", line 46, in main
    curr_loss = model.train_on_batch(batch_ip, batch_ip)
  File "/home/mohana/virtualenvs/tfcomp/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 1078, in train_on_batch
    standalone=True)
  File "/home/mohana/virtualenvs/tfcomp/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 433, in train_on_batch
    output_loss_metrics=model._output_loss_metrics)
  File "/home/mohana/virtualenvs/tfcomp/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 312, in train_on_batch
    output_loss_metrics=output_loss_metrics))
  File "/home/mohana/virtualenvs/tfcomp/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 269, in _process_single_batch
    grads = tape.gradient(scaled_total_loss, trainable_weights)
  File "/home/mohana/virtualenvs/tfcomp/lib/python3.6/site-packages/tensorflow_core/python/eager/backprop.py", line 1029, in gradient
    unconnected_gradients=unconnected_gradients)
  File "/home/mohana/virtualenvs/tfcomp/lib/python3.6/site-packages/tensorflow_core/python/eager/imperative_grad.py", line 77, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File "/home/mohana/virtualenvs/tfcomp/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1256, in _backward_function_wrapper
    processed_args, remapped_captures)
  File "/home/mohana/virtualenvs/tfcomp/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1684, in _call_flat
    "Tensor." % (self._func_graph.name, i, str(arg)))
ValueError: All inputs to `ConcreteFunction`s must be Tensors; on invocation of __backward__defun_call_1331, the 0-th input (IndexedSlices(indices=tf.Tensor([  65   65   66 ... 4028 4029 4030], shape=(16384,), dtype=int32), values=tf.Tensor(
[[-0.0000000e+00 -0.0000000e+00 -0.0000000e+00]
 [-0.0000000e+00 -0.0000000e+00 -0.0000000e+00]
 [-0.0000000e+00 -0.0000000e+00 -0.0000000e+00]
 ...
 [-2.7218828e-05 -2.6730117e-05 -2.4183297e-05]
 [-2.7333013e-05 -2.7423557e-05 -2.2896325e-05]
 [-2.1508897e-05 -2.1834361e-05 -1.8788463e-05]], shape=(16384, 3), dtype=float32), dense_shape=tf.Tensor([4096    3], shape=(2,), dtype=int32))) was not a Tensor.

**Comment by bhack** [comment]
Thanks for you report, this but I don't think anyone will prepare a 2.1.x cause the policy here is mainly to make this type o release only for security fixes.

**Comment by WindQAQ** [comment]
@moha23 It seems to be a bug in older TF version when you do not wrap the tensor operations inside `tf.keras.layers.Lambda` when using symbolic tensor. You can do that with

```python
warped = tf.keras.layers.Lambda(lambda x: tf.expand_dims(tfa.image.dense_image_warp(x[0],x[1],name='warp'),axis=1))([op, flow])
```

https://colab.research.google.com/drive/1EygYzVK8mizBvQ74cT9w5Fa_Vs3e15Ai?usp=sharing

Let me know if it works well. Thanks you!

**Comment by moha23** [comment]
Awesome! Thank you for figuring.
