### ISSUE TITLE
tfa.image.interpolate_spline

### ISSUE THREAD

**Issue by andrekassis** [tensorflow/addons#2246]
I'm not sure if this is a bug, but when I use this methods with a batch of one sample only, I get different results than what is outputted for larger batches containing the same input. That is, ig I invoke the method on a batch containing sample x only and then repeat with a batch of two samples [x, y], the output fo the same sample x is different in the second run, although the existence of y should affect the output for x. Is this a bug?

Thanks

**Comment by WindQAQ** [comment]
I would say it shouldn't be the case. Can you provide your example codes to reproduce it? Thank you!

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
