### ISSUE TITLE
NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_addons/custom_ops/image/_image_ops.so: undefined symbol

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/addons#2251]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow version and how it was installed (source or binary): 2.3.0
- TensorFlow-Addons version and how it was installed (source or binary):`pip install tensorflow-addons`
- Python version:
- Is GPU used? (yes/no): No

**Describe the bug**

Getting the above-mentioned problem when using the `tfa.image.translate` function. 

**Code to reproduce the issue**

```python
import tensorflow as tf
import tensorflow_addons as tfa

(X_train, _), (_, _) = tf.keras.datasets.cifar10.load_data()
X_train = X_train/255.

s = tfa.image.translate(X_train[0], [2, 2])
```

Am I missing out on something here? I couldn't find any example usage [in the documentation](https://www.tensorflow.org/addons/api_docs/python/tfa/image/translate) as well. 

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by seanpmorgan** [comment]
Hi @sayakpaul could you try `!pip install -U tensorflow-addons`. Colab has been quite slow to update:
https://github.com/googlecolab/colabtools/issues/1243

**Comment by sayakpaul** [comment]
Sure thing, Sean. I will try it out tomorrow and get back. Thanks!

**Comment by sayakpaul** [comment]
That solved it, @seanpmorgan.
