### ISSUE TITLE
Drop GELU for 0.13 release

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#2252]
https://www.tensorflow.org/api_docs/python/tf/keras/activations/gelu will be available in TF2.4. Deprecation warning is already set for our upcming 0.12 release

**Comment by WindQAQ** [comment]
@seanpmorgan Shouldn't we maintain the backward compatibility as we're still in 0.x release? Maybe we can discuss to bump the major to 1.x along with the breaking change of optimizers in #2187.

**Comment by seanpmorgan** [comment]
So I don't think we **have** to keep backward compatibility while in 0.x verisons, but I do think it's a good idea. Making this one of the 1.0 breaking changes sounds good (will post an issue soon with tasks).

**Comment by aaronmondal** [comment]
I just want to mention that there will apparently only be a `gelu` activation in TF 2.4, not a `GELU` layer. So while `tfa.activations.gelu` is the same as `tf.keras.activations.gelu`/`tf.nn.gelu`, we have `tfa.layers.GELU` but no `tf.keras.layers.GELU`.
