### ISSUE TITLE
 tfa.image.translate_xy does not support image with single channel or more than three channel

### ISSUE THREAD

**Issue by kelvinkoh0308** [tensorflow/addons#2275]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- TensorFlow version and how it was installed (source or binary): 2.2
- TensorFlow-Addons version and how it was installed (source or binary): 0.11.2
- Python version: 3.7
- Is GPU used? (yes/no): yes

**Describe the bug**

tfa.image.translate_xy only works on three-channel image. It will fail when passing a single or more than 3 channel image to these two functions.

**Code to reproduce the issue**

dog =np.expand_dims(cv2.imread("dog.jpeg")[...,0],axis=-1)
translate_image = tfa.image.translate_xy(dog,[2,3],replace=1)

**Other info / logs**

/usr/local/lib/python3.6/dist-packages/tensorflow_addons/image/translate_ops.py in translate_xy(image, translate_to, replace)
    126     trans = tf.convert_to_tensor(translate_to)
    127     image = translate(image, [trans[0], trans[1]])
--> 128     return unwrap(image, replace)

/usr/local/lib/python3.6/dist-packages/tensorflow_addons/image/utils.py in unwrap(image, replace)
    133 
    134     # Find all pixels where the last channel is zero.
--> 135     alpha_channel = flattened_image[:, 3]
    136 
    137     replace = tf.constant(replace, tf.uint8)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py in _slice_helper(tensor, slice_spec, var)
   1022         ellipsis_mask=ellipsis_mask,
   1023         var=var,
-> 1024         name=name)
   1025 
   1026 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py in strided_slice(input_, begin, end, strides, begin_mask, end_mask, ellipsis_mask, new_axis_mask, shrink_axis_mask, var, name)
   1194       ellipsis_mask=ellipsis_mask,
   1195       new_axis_mask=new_axis_mask,
-> 1196       shrink_axis_mask=shrink_axis_mask)
   1197 
   1198   parent_name = name

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py in strided_slice(input, begin, end, strides, begin_mask, end_mask, ellipsis_mask, new_axis_mask, shrink_axis_mask, name)
  10318       return _result
  10319     except _core._NotOkStatusException as e:
> 10320       _ops.raise_from_not_ok_status(e, name)
  10321     except _core._FallbackException:
  10322       pass

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6841   message = e.message + (" name: " + name if name is not None else "")
   6842   # pylint: disable=protected-access
-> 6843   six.raise_from(core._status_to_exception(e.code, message), None)
   6844   # pylint: enable=protected-access
   6845 

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: slice index 3 of dimension 1 out of bounds. [Op:StridedSlice] name: strided_slice/

**Comment by WindQAQ** [comment]
I believe we can fix it by changing this line

https://github.com/tensorflow/addons/blob/664762a6b64d1625db24d4c886b2fd07ee8e6ea0/tensorflow_addons/image/utils.py#L135

to

```python
alpha_channel = flattened_image[:, -1]
```

However, I do encourage you to use `tfa.image.translate` in the next release because we will natively support `fill_value` (`replace` arg for `translate_xy`).

**Comment by kelvinkoh0308** [comment]
@WindQAQ thanks, do you have any idea when the next version will be released?

**Comment by seanpmorgan** [comment]
> @WindQAQ thanks, do you have any idea when the next version will be released?

Within a few days most likely.

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
