### ISSUE TITLE
tfa.image.random_cutout  random centre locations do not guarantee application of full mask

### ISSUE THREAD

**Issue by JulianRodert** [tensorflow/addons#2276]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow version and how it was installed (source or binary): 2.3.1
- TensorFlow-Addons version and how it was installed (source or binary):0.11.2
- Python version: 3.6
- Is GPU used? (no):

**Description**
The randomly chosen cutout_center_heights and cutout_center_widths can result in the mask not being fully applied.

The bounds for these are set between zero and the max height/width but should be adjusted to ensure the lower and upper bounds allow the mask to be fully applied. Sometimes it is observed that only part of the mask is applied within the image boundary.

**Example**
Applied to the fashin_minst dataset, where the images are shape (28,28)

@tf.function
def make_some_noise(image):
  img = tfa.image.random_cutout(image, (14,14), constant_values = 1)
  
  return img

You can see from the image below that the first 4 images have part of the mask missing as the centre is outside the correct bounds.

![cutout_bug](https://user-images.githubusercontent.com/72381446/101528969-d3b2a300-3987-11eb-9ea6-d3259b88e8d2.png)

**Solution**

> 
>  cutout_center_height = tf.random.uniform(
>         shape=[batch_size], minval=mask_size[0]//2, maxval=image_height-mask_size[0]//2, dtype=tf.int32, seed=seed
>     )
>     cutout_center_width = tf.random.uniform(
>         shape=[batch_size], minval=mask_size[1]//2, maxval=image_width-mask_size[0]//2, dtype=tf.int32, seed=seed
>     )

Applying the above fix to the randomly chosen bounds results in the below, here you can see that the mask is always within the bounds.
![cutout_bug_fix](https://user-images.githubusercontent.com/72381446/101529193-2e4bff00-3988-11eb-84b9-ee99b34d821a.png)

**Comment by bhack** [comment]
Can you submit a PR?

**Comment by JulianRodert** [comment]
Sure, no problem
