### ISSUE TITLE
unexpected starting position on input tensor in CorrelationCost layer

### ISSUE THREAD

**Issue by lsy323** [tensorflow/addons#2280]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11.0.1
- TensorFlow version and how it was installed (source or binary): 2.3.1 installed from binary
- TensorFlow-Addons version and how it was installed (source or binary): 0.11.2 installed from binary
- Python version: 3.6.5
- Is GPU used? (yes/no): no

**Describe the bug**

In the CorrelationCost layer, the start position is way out of bound when stride_1 is larger than 1. In correlation_cost_op.cc (https://github.com/tensorflow/addons/blob/76249547c481ed47bd6f2f8092a99cd64d37fd2f/tensorflow_addons/custom_ops/layers/cc/kernels/correlation_cost_op.cc#L65), the starting position is '(h - pad) * stride_1 + max_displacement + kernel_rad'. It looks like a typo, personally I think "h * stride_1 - pad + max_displacement + kernel_rad" makes sense.

**Code to reproduce the issue**

```python
import tensorflow as tf
from tensorflow_addons.layers import CorrelationCost

ccl = CorrelationCost(
       kernel_size=1,
       max_displacement=2,
       stride_1=2,
       stride_2=2,
       pad=2,
       data_format='channels_first')

x1 = tf.constant([[[[1,2,3],
                    [1,2,3],
                    [1,2,3]],
                   [[1,2,3],
                    [1,2,3],
                    [1,2,3]]]], dtype=tf.float32)
x2 = tf.constant([[[[1,1,1],
                    [2,2,2],
                    [3,3,3]],
                   [[1,1,1],
                    [2,2,2],
                    [3,3,3]]]], dtype=tf.float32)

out = ccl([x1,x2])
print(out)
```
In the simple example above, the padded input spatial size is 7x7. In the CorrelationCost layer, the start position is (-2, -2), which shouldn't be expected.

**Other info / logs**

**Comment by WindQAQ** [comment]
Umm, I don't get it. What if `kernel_size` is larger? Shouldn't these lines do boundary check?

https://github.com/tensorflow/addons/blob/9bac29cce0c4d254b332f3006432593eed2b8ad6/tensorflow_addons/custom_ops/layers/cc/kernels/correlation_cost_op.cc#L88-L108

**Comment by lsy323** [comment]
Hi @WindQAQ 
 
Thanks for taking a look.

The out-of-bound checks make sure there is no runtime error in such cases. What I meant is the locations of evaluation centers don't look right when stride_1 > 1.

Also, in GPU implementation (https://github.com/tensorflow/addons/blob/76249547c481ed47bd6f2f8092a99cd64d37fd2f/tensorflow_addons/custom_ops/layers/cc/kernels/correlation_cost_op_gpu.cu.cc#L92), the starting location is '-pad + max_displacement + kernel_rad', instead of '-pad*stride_1 + max_displacement + kernel_rad'. In the referenced code there is no '-pad' as the input tensor is already padded.

Between these two, the GPU impl makes more sense to me.

Thanks

**Comment by WindQAQ** [comment]
> Hi @WindQAQ
> 
> Thanks for taking a look.
> 
> The out-of-bound checks make sure there is no runtime error in such cases. What I meant is the locations of evaluation centers don't look right when stride_1 > 1.
> 
> Also, in GPU implementation (
> 
> https://github.com/tensorflow/addons/blob/76249547c481ed47bd6f2f8092a99cd64d37fd2f/tensorflow_addons/custom_ops/layers/cc/kernels/correlation_cost_op_gpu.cu.cc#L92
> 
> ), the starting location is '-pad + max_displacement + kernel_rad', instead of '-pad*stride_1 + max_displacement + kernel_rad'. In the referenced code there is no '-pad' as the input tensor is already padded.
> Between these two, the GPU impl makes more sense to me.
> 
> Thanks

Great! Thanks for the clarification. Are you willing to submit a PR for it?

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
