### ISSUE TITLE
Can't save keras model weights when using LayerNormLSTMCell and Eager mode due to non-unique weight names

### ISSUE THREAD

**Issue by vlawhern** [tensorflow/addons#2283]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow version and how it was installed (source or binary): TF 2.2, installed with Anaconda through `conda` package manager
- TensorFlow-Addons version and how it was installed (source or binary): 0.11.2, pip install
- Python version: 3.7.6
- Is GPU used? (yes/no): Yes

**Describe the bug**

When using a model with LayerNormLSTMCell with Eager Execution enabled, you cannot save the model weights due to it having non-unique weight names. Apparently this is a known Keras issue (see https://github.com/tensorflow/tensorflow/issues/27688#issuecomment-595950270).

For example, this code works just fine:
```python
import tensorflow as tf
from tensorflow_addons.rnn import LayerNormLSTMCell
from tensorflow.keras.layers import LSTMCell

import numpy as np

x_train = np.random.randn(1000, 10, 20)
y_train = np.random.randint(0, 1, x_train.shape[0])

model = tf.keras.Sequential([
    tf.keras.layers.RNN(LSTMCell(10), input_shape = (10,20)),
    tf.keras.layers.Dense(2),
    tf.keras.layers.Activation('softmax')
])


model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['sparse_categorical_accuracy'])

model.fit(x_train, y_train, epochs=1)
model.save_weights('/tmp/weights.h5')
```
while this code fails
```python
import tensorflow as tf
from tensorflow_addons.rnn import LayerNormLSTMCell
from tensorflow.keras.layers import LSTMCell

import numpy as np

x_train = np.random.randn(1000, 10, 20)
y_train = np.random.randint(0, 1, x_train.shape[0])

model = tf.keras.Sequential([
    tf.keras.layers.RNN(LayerNormLSTMCell(10), input_shape = (10,20)),
    tf.keras.layers.Dense(2),
    tf.keras.layers.Activation('softmax')
])


model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['sparse_categorical_accuracy'])

model.fit(x_train, y_train, epochs=1)
model.save_weights('/tmp/weights.h5')
```
with the following error:
RuntimeError: Unable to create link (name already exists)

I believe this is happening due to the LayerNormLSTMCell weight names not being unique. Here are the weight names; weights 3,5,7 and 4,6,8 each have the same name.

```python
model.layers[0].weights[0].name
Out[7]: 'rnn_2/kernel:0'

model.layers[0].weights[1].name
Out[8]: 'rnn_2/recurrent_kernel:0'

model.layers[0].weights[2].name
Out[9]: 'rnn_2/bias:0'

model.layers[0].weights[3].name
Out[10]: 'rnn_2/gamma:0'

model.layers[0].weights[4].name
Out[11]: 'rnn_2/beta:0'

model.layers[0].weights[5].name
Out[12]: 'rnn_2/gamma:0'

model.layers[0].weights[6].name
Out[13]: 'rnn_2/beta:0'

model.layers[0].weights[7].name
Out[14]: 'rnn_2/gamma:0'

model.layers[0].weights[8].name
Out[15]: 'rnn_2/beta:0'
```

The suggested solution is to disable eager execution (via `tf.compat.v1.disable_eager_execution()`) which does allow both code snippets to work; however, in my use case I run into severe performance degradation this way. If possible I'd like to be able to save model weights when use LayerNormLSTMCell with Eager mode.

**Comment by WindQAQ** [comment]
Seems that the name of `LayerNormalization` layer does not propagate successfully. Hi @qlzh727, can you confirm if this is a keras upstream issue and is there any workaround on this?

https://colab.research.google.com/drive/1M9BUa8t0ynV8qPQzGh8T_OH2IpKMnog8?usp=sharing

**Comment by qlzh727** [comment]
I think its a layerNormCell issue, since the duplicated name is caused by kernel_norm/recurrent_norm/state_norm sub layers. More specifically, build() method of LayerNormLSTMCell should call kernel_norm.build() with a name scope, so that the weights created will the proper name to identify them.

https://github.com/tensorflow/addons/blob/master/tensorflow_addons/rnn/layer_norm_lstm_cell.py#L157

**Comment by WindQAQ** [comment]
Sounds good. So the name passed into layer does nothing for name scope?

https://github.com/tensorflow/addons/blob/master/tensorflow_addons/rnn/layer_norm_lstm_cell.py#L196-L202

**Comment by qlzh727** [comment]
It should, but since we manually invoke the build() method for those sublayers, and that is causing the problem for missing the name. If you take a look for the base_layer in keras, there are quite some logic around build() method before it is invoked.

**Comment by WindQAQ** [comment]
Thanks for clarification!
