### ISSUE TITLE
Remove wrap/unwrap for image ops

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/addons#2295]
We have many image ops that relies on `tfa.image.transform`. Since TF2.4, it can natively support `fill_value` to fill out of bound pixel after transformation. Moreover, it can also supports different `fill_mode`/`interpolation` for image transformation.

However, some of our image ops use [`wrap`/`unwrap`](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/utils.py#L104-L151) to fill OOB pixel like [shear_x](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/transform_ops.py#L334-L350), [shear_y](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/transform_ops.py#L353-L369) and [translate_xy](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/translate_ops.py#L120-L139). These ops do not fully utilize the power of `tfa.image.transform` and is slightly slower due to `wrap`/`unwrap`.

The only reason that I think we still need them is that `wrap` and `unwrap` can support different fill value for different channel. This is totally viable with native C++ support. See the feature request from TensorFlow https://github.com/tensorflow/tensorflow/issues/45717. If the request is passed, we can deprecate the use of `wrap`/`unwrap` and even `translate_xy` because it will become a one-line wrapper of `tfa.image.translate`.

/cc @seanpmorgan @bhack for visibility.

**Comment by bhack** [comment]
@WindQAQ Something related also in https://github.com/tensorflow/tensorflow/issues/45326

**Comment by aaronmondal** [comment]
+1 this is important. Besides the reduction in code, the performance hit is actually quite significant at ~2.5 times the execution time of `ImageProjectiveTransformV3` ([Colab](https://colab.research.google.com/drive/1VT6DPA46jv47Wx5jU9QIUKTdtbjfTQGT#scrollTo=7svSSUOkIf1F)). I can also verify that the current ops are a major bottleneck candidate in preprocessing pipelines.

The current implementation of `unwrap` requires integer inputs for the `replace` value as well, making wrapped ops unusable with float images in the range `[0, 1)`, which requires the user to *know* not to use `tf.image.convert_image_dtype` with TFA, because that scales to `[0, 1)` for `float32`.

**Comment by WindQAQ** [comment]
@aaronmondal can you make the colab link public? Thank you!

**Comment by aaronmondal** [comment]
My bad. This should work: https://colab.research.google.com/drive/1VT6DPA46jv47Wx5jU9QIUKTdtbjfTQGT?usp=sharing

**Comment by WindQAQ** [comment]
> My bad. This should work: https://colab.research.google.com/drive/1VT6DPA46jv47Wx5jU9QIUKTdtbjfTQGT?usp=sharing

Hmm, it's still unavailable. You have to choose something like "anyone who knows the link can access"

**Comment by aaronmondal** [comment]
@WindQAQ does it work now?

**Comment by WindQAQ** [comment]
Yes it it! Thanks for the benchmark.

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
