### ISSUE TITLE
Build out contributing guidelines

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#23]
In an effort to encourage involvement, and standardize contributions we should make a concerted effort to build thorough docs on how to contribute for each sub-package (layers, crf, etc.) 

For example:
Building from #19 dicussion. We should create standards for adding custom keras Layers. Some things to include:

- Testing with the [Keras layer test](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/testing_utils.py#L68)
- [Registering the Layer](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/utils/generic_utils.py#L37) so a Model can be serialized / deserialized

**Comment by martinwicke** [comment]
We should maybe think about a package-spanning registration mechanism. I think that would require a design, and feedback from the Keras community. I can certainly imagine this working via directories, or via calling some registration function on import. 

Until then, I think passing the objects is a reasonable fallback.

**Comment by seanpmorgan** [comment]
Initial pass of this is complete. We'll continue to iterate on the docs though.
