### ISSUE TITLE
Batch Processing for Tensorflow_addons.image filters functionalities

### ISSUE THREAD

**Issue by Mainak431** [tensorflow/addons#230]
Batch processing is very much required for all the image functionalities. Batch processing will enable direct use of these features with layers like conv2d. Hence no preprocessing steps will be required for CNN applications. Currently, this is required. Directly, the user can create the network and feed the images for training. I wish to implement the batch processing for median_filter2d and mean_filter2d using the currently available functions. Please provide feedback on the same.

**Comment by Mainak431** [comment]
@seanpmorgan CC.

**Comment by seanpmorgan** [comment]
Closing this as it'll be address with #234
