### ISSUE TITLE
Nested Model using WeightNormalization

### ISSUE THREAD

**Issue by carl2g** [tensorflow/addons#2307]
**System information**
- Using Google Colab
- Use GPU: No

**Describe the bug**
Hello,
I have created a nested model using WeightNormaization on a Conv1d layer. I ran this model on non eagerly mode using fit.  But it seems to produce a infinite loop.

**Code to reproduce the issue**
This was my test : [colab_test](https://colab.research.google.com/drive/1scWp0LWfl7iMSqPLPrzJG3V70v3RA5xw)

I would appreciate if you could help me find the issue here.
Have a nice day :) !

**Comment by WindQAQ** [comment]
Hi @carl2g, thanks for your report. I cannot reproduce the issue with latest stable tensorflow-addons. Can you try to upgrade addons with `pip install --upgrade tensorflow-addons`? Thank you!

https://colab.research.google.com/drive/1HRm0k8GqQ9tqWbrDraiz4LfY6qTdyq1n?usp=sharing

**Comment by carl2g** [comment]
Thank you @WindQAQ, seem's to work fine with the upgrade.
Cheers !
