### ISSUE TITLE
Copy / Pointer Mechanism in Seq2Seq

### ISSUE THREAD

**Issue by yrutis** [tensorflow/addons#231]
**System information**
- TensorFlow version (you are using): 1.15 - 2.0
- TensorFlow Addons version:
- Is it in the tf.contrib (if so, where):
- Are you willing to contribute it (yes/no):
- Are you willing to maintain it going forward? (yes/no):

**Describe the feature and the current behavior/state.**
I am looking for a copying / pointer Seq2Seq. (Pointer-Generator model, CopyNet model)

**Who will benefit with this feature?**
Hi for a project I am looking for a Seq2Seq model using a copy mechanism. I wondered if anyone has already implemented a similar model using either eager execution or tensorflow with the newest style guidelines.

**Comment by seanpmorgan** [comment]
Hi @yrutis I think this type of request may be outside the scope of Addons. There are repositories showing [CopyNet TF 1.x models](https://github.com/lspvic/CopyNet) that use seq2seq and there shouldn't be an overwhelming amount of work needed to adapt to the eager style.

I think requests for simple blocks using seq2seq are acceptable requests for this repo, but we do have to manage our scope. 

cc @qlzh727 to see if he has any thoughts or knows of a repo that might contain this.

**Comment by qlzh727** [comment]
I am not aware of any TF repo that has CopyNet.
