### ISSUE TITLE
Generate TFA Docs for 0.12 Release

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#2317]
@lamberta @MarkDaoust @yashk2810 When time allows could we re-build the TFA docs with the new 0.12 release. There should be substantial fixes to the docs (e.g. typing).

Thanks!

**Comment by lamberta** [comment]
@seanpmorgan Sounds good. We're currently in a site freeze for the holidays but will push the latest after the new year. Thanks

**Comment by seanpmorgan** [comment]
This was completed
