### ISSUE TITLE
/usr/bin/ld.gold: error: cannot find -l_pywrap_tensorflow_internal

### ISSUE THREAD

**Issue by genius0182** [tensorflow/addons#2328]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): raspberry-pi-4b aarch64 docker image ubuntu1804
- TensorFlow version and how it was installed (source or binary):2.1.0
- TensorFlow-Addons version and how it was installed (source or binary):0.7.1
- Python version:3.7.9
- Is GPU used? (yes/no): no

**Describe the bug**

source build error, 
tenflow 2.1.0 can be used.

**Code to reproduce the issue**

**Other info / logs**

`
Requirement already satisfied: tensorflow>=2.1.0 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: tensorflow-estimator<2.2.0,>=2.1.0rc0 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: scipy==1.4.1 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (1.4.1)
Requirement already satisfied: google-pasta>=0.1.6 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (0.2.0)
Requirement already satisfied: astor>=0.6.0 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (0.8.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (3.3.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (1.34.0)
Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (0.36.2)
Requirement already satisfied: gast==0.2.2 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (0.2.2)
Requirement already satisfied: keras-preprocessing>=1.1.0 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (1.1.2)
Requirement already satisfied: wrapt>=1.11.1 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (1.12.1)
Requirement already satisfied: absl-py>=0.7.0 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (0.11.0)
Requirement already satisfied: numpy<2.0,>=1.16.0 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (1.19.4)
Requirement already satisfied: protobuf>=3.8.0 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (3.14.0)
Requirement already satisfied: tensorboard<2.2.0,>=2.1.0 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: keras-applications>=1.0.8 in /usr/local/lib/python3.7/site-packages (from tensorflow>=2.1.0->-r requirements.txt (line 1)) (1.0.8)
Requirement already satisfied: h5py in /usr/local/lib/python3.7/site-packages (from keras-applications>=1.0.8->tensorflow>=2.1.0->-r requirements.txt (line 1)) (3.1.0)
Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.7/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (1.0.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in /usr/local/lib/python3.7/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (1.24.0)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.7/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (51.0.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.7/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (3.3.3)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.7/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (2.25.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.7/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (0.4.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (4.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (4.6)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/site-packages (from markdown>=2.6.8->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (3.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (0.4.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (1.26.2)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (2020.12.5)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (3.1.0)
Requirement already satisfied: cached-property in /usr/local/lib/python3.7/site-packages (from h5py->keras-applications>=1.0.8->tensorflow>=2.1.0->-r requirements.txt (line 1)) (1.5.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (3.4.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard<2.2.0,>=2.1.0->tensorflow>=2.1.0->-r requirements.txt (line 1)) (3.7.4.3)

Build configurations successfully written to .bazelrc

Starting local Bazel server and connecting to it...
WARNING: /root/.cache/bazel/_bazel_root/05fec5a36c83f24c9f73cdaccf3bbd7b/external/local_config_tf/BUILD:2012:1: target '_pywrap_tensorflow_internal.so' is both a rule and a file; please choose another name for the rule
INFO: Analyzed target //:build_pip_pkg (37 packages loaded, 239 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /root/.cache/bazel/_bazel_root/05fec5a36c83f24c9f73cdaccf3bbd7b/sandbox
INFO: From Compiling tensorflow_addons/custom_ops/image/cc/kernels/resampler_ops.cc:
tensorflow_addons/custom_ops/image/cc/kernels/resampler_ops.cc: In instantiation of 'void tensorflow::addons::functor::ResamplerGrad2DFunctor<Eigen::ThreadPoolDevice, T>::operator()(tensorflow::OpKernelContext*, const CPUDevice&, const T*, const T*, const T*, T*, T*, int, int, int, int, int) [with T = Eigen::half; tensorflow::addons::CPUDevice = Eigen::ThreadPoolDevice]':
tensorflow_addons/custom_ops/image/cc/kernels/resampler_ops.cc:379:51:   required from 'void tensorflow::addons::ResamplerGradOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = Eigen::half]'
tensorflow_addons/custom_ops/image/cc/kernels/resampler_ops.cc:334:8:   required from here
tensorflow_addons/custom_ops/image/cc/kernels/resampler_ops.cc:219:11: warning: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct Eigen::half'; use assignment or value-initialization instead [-Wclass-memaccess]
     memset(grad_data, 0, sizeof(T) * grad_data_size);
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from bazel-out/aarch64-opt/bin/external/local_config_tf/include/unsupported/Eigen/CXX11/../../../Eigen/Core:164,
                 from bazel-out/aarch64-opt/bin/external/local_config_tf/include/unsupported/Eigen/CXX11/Tensor:14,
                 from bazel-out/aarch64-opt/bin/external/local_config_tf/include/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from bazel-out/aarch64-opt/bin/external/local_config_tf/include/tensorflow/core/framework/numeric_types.h:20,
                 from bazel-out/aarch64-opt/bin/external/local_config_tf/include/tensorflow/core/framework/allocator.h:26,
                 from bazel-out/aarch64-opt/bin/external/local_config_tf/include/tensorflow/core/framework/op_kernel.h:25,
                 from tensorflow_addons/custom_ops/image/cc/kernels/resampler_ops.cc:22:
bazel-out/aarch64-opt/bin/external/local_config_tf/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/Default/Half.h:95:8: note: 'struct Eigen::half' declared here
 struct half : public half_impl::half_base {
        ^~~~
tensorflow_addons/custom_ops/image/cc/kernels/resampler_ops.cc:220:11: warning: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct Eigen::half'; use assignment or value-initialization instead [-Wclass-memaccess]
     memset(grad_warp, 0, sizeof(T) * grad_warp_size);
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from bazel-out/aarch64-opt/bin/external/local_config_tf/include/unsupported/Eigen/CXX11/../../../Eigen/Core:164,
                 from bazel-out/aarch64-opt/bin/external/local_config_tf/include/unsupported/Eigen/CXX11/Tensor:14,
                 from bazel-out/aarch64-opt/bin/external/local_config_tf/include/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from bazel-out/aarch64-opt/bin/external/local_config_tf/include/tensorflow/core/framework/numeric_types.h:20,
                 from bazel-out/aarch64-opt/bin/external/local_config_tf/include/tensorflow/core/framework/allocator.h:26,
                 from bazel-out/aarch64-opt/bin/external/local_config_tf/include/tensorflow/core/framework/op_kernel.h:25,
                 from tensorflow_addons/custom_ops/image/cc/kernels/resampler_ops.cc:22:
bazel-out/aarch64-opt/bin/external/local_config_tf/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/Default/Half.h:95:8: note: 'struct Eigen::half' declared here
 struct half : public half_impl::half_base {
        ^~~~
ERROR: /opt/build_soft/tensorflow-addons-on-arm/addons-0.7.1/tensorflow_addons/custom_ops/image/BUILD:39:1: Linking of rule '//tensorflow_addons/custom_ops/image:_resampler_ops.so' failed (Exit 1)
/usr/bin/ld.gold: error: cannot find -l_pywrap_tensorflow_internal
collect2: error: ld returned 1 exit status
Target //:build_pip_pkg failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 50.328s, Critical Path: 32.79s
INFO: 2 processes: 2 local.
FAILED: Build did NOT complete successfully
`

**Comment by bhack** [comment]
We have integrated something for Raspberry with https://github.com/tensorflow/addons/pull/2230

So probably you can try with an update TF/TF Addons versions

**Comment by chazuttu** [comment]
It may  be the case that the file exists but is not named properly. Or it may be the case that file exists but it is owned by another user / root. 
Install glibc-static and retry. Hope that helps

**Comment by genius0182** [comment]
I used "ld -l_pywrap_tensorflow_internal --verbose" command to find the following file failed to open,an error is as follows
`
attempt to open //usr/local/lib/aarch64-linux-gnu/lib_pywrap_tensorflow_internal.so failed
attempt to open //usr/local/lib/aarch64-linux-gnu/lib_pywrap_tensorflow_internal.a failed
attempt to open //lib/aarch64-linux-gnu/lib_pywrap_tensorflow_internal.so failed
attempt to open //lib/aarch64-linux-gnu/lib_pywrap_tensorflow_internal.a failed
attempt to open //usr/lib/aarch64-linux-gnu/lib_pywrap_tensorflow_internal.so failed
attempt to open //usr/lib/aarch64-linux-gnu/lib_pywrap_tensorflow_internal.a failed
attempt to open //usr/local/lib/lib_pywrap_tensorflow_internal.so failed
attempt to open //usr/local/lib/lib_pywrap_tensorflow_internal.a failed
attempt to open //lib/lib_pywrap_tensorflow_internal.so failed
attempt to open //lib/lib_pywrap_tensorflow_internal.a failed
attempt to open //usr/lib/lib_pywrap_tensorflow_internal.so failed
attempt to open //usr/lib/lib_pywrap_tensorflow_internal.a failed
attempt to open //usr/aarch64-linux-gnu/lib/lib_pywrap_tensorflow_internal.so failed
attempt to open //usr/aarch64-linux-gnu/lib/lib_pywrap_tensorflow_internal.a failed
ld: cannot find -l_pywrap_tensorflow_internal
`
I would like to ask how the file “lib_pywrap_tensorflow_internal.so” is generated？
