### ISSUE TITLE
TPU Socket Closed with tfa Optimizer

### ISSUE THREAD

**Issue by innat** [tensorflow/addons#2330]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Kaggle 
- TensorFlow version '2.2.0'
- TensorFlow-Addons version '0.10.0':
- TPU

**Describe the bug**

Whenever I tried to do as follows: 

```python
radam  = tfa.optimizers.RectifiedAdam(lr=0.001)
ranger = tfa.optimizers.Lookahead(radam, 
                                  sync_period=6, 
                                  slow_step_size=0.5)

model.compile(optimizer=ranger, ... )
```

The socket close error occurred. I think it's not an error exactly. However, without `Lookahead` and with simply `radam`, it works. 

This seems probably a small issue to raise but I think the potential solution may solve other problems of `tfa` functionalities.

**Comment by bhack** [comment]
Thanks,
please share a very very minimal code sample that we could copy, paste and run (or a Colab) to reproduce this.

**Comment by innat** [comment]
Hello, thanks for the quick response. However, I've solved it already. Mainly I forgot to declare the optimizer within the training scope, such as:

```python
with strategy.scope():
	model = create_moedl()
    
	# previously I declared radam+lookahead outside this scope
	# Optimizer
    radam  = tfa.optimizers.RectifiedAdam(lr=0.001)
    ranger = tfa.optimizers.Lookahead(radam, 
                                      sync_period=6, 
                                      slow_step_size=0.5)

	model.compile(optimizer=ranger, ...)
```
