### ISSUE TITLE
Make selection between C++ kernel/python ops  a function API instead of global variable

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/addons#2331]
Currently, there is no docs for `tfa.options.TF_ADDONS_PY_OPS` because it's a global variable instead of a function. Ideally, we can implement something like instead of let users access global variable.

```python
def enable_custom_kernel():
    """Docs go here."""
    # Use _TF_ADDONS_PY_OPS
    pass

def disable_custom_kernel():
     """Docs go here."""
    # Use _TF_ADDONS_PY_OPS
    pass
```

**Comment by jonpsy** [comment]
I would like to take a stab at this issue!

**Comment by WindQAQ** [comment]
@jonpsy Please do!

**Comment by jonpsy** [comment]
Alright, made the PR let's discuss there :)

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
