### ISSUE TITLE
Stocastic Weight Averaging doesn't work with Learning Rate scheduling and mixed precision

### ISSUE THREAD

**Issue by grofte** [tensorflow/addons#2332]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab / Linux Ubuntu 18.04
- TensorFlow version and how it was installed (source or binary): TF 2.4, binaries from pip
- TensorFlow-Addons version and how it was installed (source or binary): TFA 0.12, binaries from pip
- Python version: 3.6.9 / 3.8
- Is GPU used? (yes/no): yes

**Describe the bug**

When I combine _learning rate reduction on plateau_ with _stocastic weight averaging_ and _mixed precision_ the training fails after the first epoch. 

**Code to reproduce the issue**

I have commented out the two lines related to SWA to make it easier to find them. Toggle them back on and run and the error will occur. Comment them out and the training fails. 

https://gist.github.com/grofte/8142164f6b8be3d912cad9f2f1660f05 

**Other info / logs**

```
AttributeError                            Traceback (most recent call last)
<ipython-input-229-7c4428eca112> in <module>()
----> 1 model.fit(x_train, y_train, epochs=6, callbacks=[lr_reduce])

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/mixed_precision/loss_scale_optimizer.py in __getattribute__(self, name)
    882   def __getattribute__(self, name):
    883     try:
--> 884       return object.__getattribute__(self, name)
    885     except AttributeError as e:
    886       if name == '_optimizer' or name == '_hyper':

AttributeError: 'LossScaleOptimizer' object has no attribute 'lr'
```

**Comment by grofte** [comment]
Oops, sorry. Google Colab hides some of the error message

```
AttributeError                            Traceback (most recent call last)
<ipython-input-229-7c4428eca112> in <module>()
----> 1 model.fit(x_train, y_train, epochs=6, callbacks=[lr_reduce])

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1143           epoch_logs.update(val_logs)
   1144 
-> 1145         callbacks.on_epoch_end(epoch, epoch_logs)
   1146         training_logs = epoch_logs
   1147         if self.stop_training:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py in on_epoch_end(self, epoch, logs)
    430         if numpy_logs is None:  # Only convert once.
    431           numpy_logs = tf_utils.to_numpy_or_python_type(logs)
--> 432         callback.on_epoch_end(epoch, numpy_logs)
    433 
    434   def on_train_batch_begin(self, batch, logs=None):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py in on_epoch_end(self, epoch, logs)
   2522   def on_epoch_end(self, epoch, logs=None):
   2523     logs = logs or {}
-> 2524     logs['lr'] = K.get_value(self.model.optimizer.lr)
   2525     current = logs.get(self.monitor)
   2526     if current is None:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/mixed_precision/loss_scale_optimizer.py in __getattribute__(self, name)
    893       if name in self._optimizer._hyper:
    894         return self._optimizer._get_hyper(name)
--> 895       raise e
    896 
    897   def __dir__(self):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/mixed_precision/loss_scale_optimizer.py in __getattribute__(self, name)
    882   def __getattribute__(self, name):
    883     try:
--> 884       return object.__getattribute__(self, name)
    885     except AttributeError as e:
    886       if name == '_optimizer' or name == '_hyper':

AttributeError: 'LossScaleOptimizer' object has no attribute 'lr'
```

**Comment by rushabh-v** [comment]
Looking at [these lines](https://github.com/tensorflow/tensorflow/blob/9ef254e44d96e8c33718f42fb90a336763bca739/tensorflow/python/keras/mixed_precision/loss_scale_optimizer.py#L893-L894), it is searching for `learning_rate` in `self._optimizer._hyper`.

`self._optimizer` is `SWA` in our case and that is inherited from `AveragedOptimizerWrapper`. There are some setter methods that set `lr` and `learning_rate` using `_set_hyper` method. And the reason this is failing is that those setter methods are not called anywhere.

I couldn't figure out the solution but a workaround is that you can manually call `_set_hyper` as follows:

```python
optimizer = tf.keras.optimizers.Adam()
optimizer = tfa.optimizers.SWA(optimizer, start_averaging=4*1875, average_period=20)
optimizer._set_hyper("learning_rate", 3e-3)
```

If it's a bug, I would like to take this up if someone could guide me on how/where to call those setter methods. Thanks.

**Comment by grofte** [comment]
@rushabh-v 
Hey, that works! Thanks a bunch. Or... it runs. I better check whether a callback can actually change the learning rate.

I think it qualifies as a bug. Optimizers, optimizer wrappers, callbacks that address the optimizer, and the loss scaler for mixed precision should all be able the work together.

**Comment by grofte** [comment]
Yeah, it doesn't work. The `optimizer._set_hyper()` allows the training to run but the callback can't actually update the learning rate when SWA is enabled.

Example: https://gist.github.com/grofte/ebb93bdc9b1f87f77f3e24da6665bd16 

I tried it both with reducing on plateau and a simple scheduler. =(

**Comment by WindQAQ** [comment]
This is a bug of our optimizer. We haven't delegate (near) all properties/attributes/methods of wrapped optimizer for SWA. A quick fix is to delegate the `_get_hyper` of `AveragedOptimizerWrapper` to `self._optimizer._get_hyper` like

```python
def _get_hyper(self, name, dtype=None):
    return self._optimizer._get_hyper(name, dtype)
```

But I'm thinking to have a mixin class to do the job. Hi @reedwm, can you give us some advice on passing a optimizer wrapper into another optimizer wrapper, say `LossScaleOptimizer`? Thank you!

Related to #2187 .

**Comment by reedwm** [comment]
Since LossScaleOptimizer checks `self.optimizer._hyper`, you would need to delegate `_hyper`, not `_get_hyper`. For example:

```python
@property
def _hyper(self):
  return self._optimizer.hyper
```

There's a chance this will cause issues, as some Optimizer methods might get confused that `AveragedOptimizerWrapper` has a non-empty `_hyper` dict yet does not own the hyperparameter. If this causes issues, I'll try to find another solution.

Feel free to assign this issue to me.

**Comment by WindQAQ** [comment]
> There's a chance this will cause issues, as some Optimizer methods might get confused that `AveragedOptimizerWrapper` has a non-empty `_hyper` dict yet does not own the hyperparameter. If this causes issues, I'll try to find another solution.
> 
> Feel free to assign this issue to me.

Sure! Thanks for the help!

**Comment by grofte** [comment]
No rush on my account. I disabled the learning rate reduction and the models trained but at the inference step it was suddenly unbelievably slow. So I am finally giving up on mixed precision. 

The slowness probably has something to do with me wrapping the models with a top-k layer or tensorflow tried to execute the models on the CPU or something. Not worth troubleshooting because the models will be deployed without a GPU so the models would also have to be converted from mixed precision. Too much overhead and unnecessary complexity.

**Comment by bhack** [comment]
@reedwm Can you take a look at https://github.com/tensorflow/addons/pull/2333 ?

**Comment by reedwm** [comment]
I think this issue was fixed by https://github.com/tensorflow/tensorflow/commit/31d58c65625592453cb9456e9cf663d891de599e.
