### ISSUE TITLE
Compile with AVX only

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/addons#2336]
Seems that TF2.4.0 is accidentally compiled with AVX2 (or more, not sure what's the CPU spec on TF release CI), and we follow it in https://github.com/tensorflow/addons/pull/2299. We should fallback to subset of ISAs, probably AVX, once there is a new release.

https://github.com/tensorflow/tensorflow/pull/46229

/cc @seanpmorgan

**Comment by bhack** [comment]
Yes
