### ISSUE TITLE
Use tf.__internal__.ops.broadcast_weights for RSquare

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/addons#2340]
`tensorflow.python.ops.weights_broadcast_ops.broadcast_weights` has been exported as internal API in tf-nightly, and will be shipped in TF2.5. We should switch to it as long as we drop TF2.3 and TF2.4 support.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/weights_broadcast_ops.py#L137

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
