### ISSUE TITLE
[Metric] Adding AdjustedRsquared Metric

### ISSUE THREAD

**Issue by jonpsy** [tensorflow/addons#2350]
**Describe the feature and the current behavior/state.**
   The issue #265 dealt with adding innovative metric functions to the repository. Some of which were not completed, one of that, is AdjustedRsquared metric. The author has already finished Rsquared metric, so I decided to add the adjusted R squared metric as an optional feature of that class. Much like how NMS function of tensorflow supports soft NMS as an additional feature https://www.tensorflow.org/api_docs/python/tf/image/non_max_suppression_with_scores.

Here's a slight demonstration of the PR I want to submit.
https://colab.research.google.com/drive/1Kn1TGFEKrGry8uTI5OLhHvbKRx6fXwum?usp=sharing

**Relevant information**
- Are you willing to contribute it (yes/no): Yes
- Are you willing to maintain it going forward? (yes/no): yes
- Is there a relevant academic paper? (if so, where): https://onlinelibrary.wiley.com/doi/abs/10.1002/9781118445112.stat06627
- Is there already an implementation in another framework? (if so, where): None that I know of
- Was it part of tf.contrib? (if so, where):

**Which API type would this fall under (layer, metric, optimizer, etc.)** Metric

**Who will benefit with this feature?**

Expert statisticians who utilize these features who are dependent on tensorflow for their research. Beginners who are exploring data science could also benefit from this.

**Any other info.**

**Comment by Harsh188** [comment]
Hey, @jonpsy unfortunately it looks like the academic paper you have referenced does not meet our minimum requirements of 50 citations.  We are still trying to improve our feature/contribution guidelines but for the time being this is the metric we are using to filter out feature requests.

**Comment by jonpsy** [comment]
I see, so shall we  put this PR on hold till it passes 50 citations +?  I can work on other metrics meanwhile.

**Comment by bhack** [comment]
That one is only an article and not the original paper.
You need to find some Deep learning papers that use this metric.

**Comment by jonpsy** [comment]
@bhack  I haven't been able to find a research paper which explicitly introduces this idea, though I have had some luck finding papers which use them. For ex: Harel, Ofer. "The estimation of R 2 and adjusted R 2 in incomplete data sets using multiple imputation." Journal of Applied Statistics 36.10 (2009): 1109-1118. 

Citation count: 214.

Would this suffice?

**Comment by bhack** [comment]
@jonpsy Do you have something applied in the Deep learning context?

**Comment by jonpsy** [comment]
@bhack Not really, but neither is R2 metric. Both of them are used primarily in Linear regression. Basically, it represents how well the line fit using the residue. 

Adjusted R2, as the name suggests, is just a small tweak to the original formula. So, if R2 metric can be considered for TFA, I think Adjusted should be as well.

**Comment by bhack** [comment]
You can try to send a PR
