### ISSUE TITLE
Nightly Tests have stopped or are lagging

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#237]
Checking the nightly tests is looks as though the last test ran on May 5th. When I run locally there are several failing tests and getting this information the day of makes troubleshooting problematic commits from TF core a lot easier.

https://source.cloud.google.com/results/invocations/7f864214-a363-4ccd-9887-28f752d0e4a4/targets/tensorflow_addons%2Fubuntu%2Fcpu%2Fpy2%2Fcontinuous/log

Could you take a look when you're free @av8ramit @karmel

**Comment by seanpmorgan** [comment]
FYI it looks like today's fail is from missing SelectV2 gradient and it got rolledback so build should pass tomorrow.
https://github.com/tensorflow/tensorflow/pull/15982

**Comment by karmel** [comment]
@qlzh727 -- is this related to the changes you made to the build frequency?

**Comment by qlzh727** [comment]
Humm, the change I made for changing the project type is submitted on Apr 30, and I still can see new build is triggered after May 5, eg https://source.cloud.google.com/results/invocations/ee86873d-b266-40e6-8ebd-64e8a8273cd1/targets.

**Comment by qlzh727** [comment]
Btw, the tests are triggered now by change commit to the master branch on tfa, so that any change that is breaking tfa can be quickly picked up. That said, if there isn't any change, then it will not run.

**Comment by karmel** [comment]
Hmm, yes, it looks like tests are running again? Was it just the SelectV2 that was the problem, @seanpmorgan ?

**Comment by seanpmorgan** [comment]
Yeah there is no issue with the build at the moment. So if I understand correctly tests will only be ran daily if there are changes to our master branch? I'm not sure that's sufficient as a large portion of our code breaks have been because of the daily changes to TF core master branch.

**Comment by qlzh727** [comment]
I changed it to only run after any change in the tfa repo, and skip the nightly run. Let me update it to run with in both CI fashion and with nightly trigger.

**Comment by qlzh727** [comment]
Should be fixed now.

**Comment by seanpmorgan** [comment]
Thanks!
