### ISSUE TITLE
Ideally the bins in histogram equalization is variable rather than limited to 256 

### ISSUE THREAD

**Issue by Ouwen** [tensorflow/addons#2379]
https://github.com/tensorflow/addons/blob/d26e2ed5f68092aed57016a7005ce534b1be3dce/tensorflow_addons/image/color_ops.py#L36

**Comment by bhack** [comment]
It could be but some other APIs don't expose this. E.g. Opencv https://docs.opencv.org/4.5.1/d6/dc7/group__imgproc__hist.html#ga7e54091f0c937d49bf84152a16f76d6e

**Comment by Ouwen** [comment]
I can appreciate that the original goal of histeq is to use all the dynamic range for human eyes. The main benefit of adopting 2^12 or 2^16 bins is for where a larger dynamic range worth of signal is available to be standardized for model training purposes. Medical imaging would be where this use case is most commonly used.

**Comment by bhack** [comment]
You could try to propose a PR so we could see if the new API could be ok.

**Comment by whatwilliam** [comment]
@bhack @Ouwen https://github.com/tensorflow/addons/issues/2379 Could you review this PR

**Comment by Ouwen** [comment]
@whatwilliam seems reasonable to me, @bhack would this API work?

**Comment by bhack** [comment]
It could be ok but tests are failing
