### ISSUE TITLE
BasicDecoder: TypeError: __call__() got an unexpected keyword argument 'training'

### ISSUE THREAD

**Issue by fzehracetin** [tensorflow/addons#2383]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colaboratory
- TensorFlow version and how it was installed (source or binary): 2.4.1
- TensorFlow-Addons version and how it was installed (source or binary): 0.8.3
- Python version: 3.6
- Is GPU used? (yes/no): yes

**Problem**

I am trying to migrate a spell checker model that uses Seq2Seq Encoder-Decoder from Tensorflow 1.1 to Tensorflow 2.4. 

In TF version 1.1 Training Decoding Layer looks like this: 
```
def training_decoding_layer(dec_embed_input, targets_length, dec_cell, initial_state, output_layer, 
                            vocab_size, max_target_length):    
    with tf.name_scope("Training_Decoder"):
        training_helper = tf.contrib.seq2seq.TrainingHelper(inputs=dec_embed_input,
                                                            sequence_length=targets_length,
                                                            time_major=False)

        training_decoder = tf.contrib.seq2seq.BasicDecoder(dec_cell,
                                                           training_helper,
                                                           initial_state,
                                                           output_layer) 

        training_logits, _ = tf.contrib.seq2seq.dynamic_decode(training_decoder,
                                                               output_time_major=False,
                                                               impute_finished=True,
                                                               maximum_iterations=max_target_length)
        return training_logits
```
I migrated code to Tensorflow 2.4 with the help of the [Seq2Seq Migration Guide](https://github.com/tensorflow/addons/tree/master/tensorflow_addons/seq2seq). But I got errors with my different approaches to solve the problem.

**Migration Guide a Like Approach**

```
def training_decoding_layer(dec_embed_input, targets_length, dec_cell, initial_state, output_layer, 
                            vocab_size, max_target_length):
    
    with tf.name_scope("Training_Decoder"):
        training_helper = tfa.seq2seq.TrainingSampler(time_major=False)

        training_decoder = tfa.seq2seq.BasicDecoder(dec_cell, training_helper,
                                                    output_layer)
        
        output, _, _ = training_decoder(dec_embed_input,
                                        sequence_length=targets_length, 
                                        initial_state=initial_state,
                                        training=True,
                                        )

        return output
```
I got his error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-73-4988f863ff0b> in <module>()
      8                                                     threshold) 
      9             model = build_graph(keep_probability, rnn_size, num_layers, batch_size, 
---> 10                                 learning_rate, embedding_size, direction)
     11             train(model, epochs, log_string)

5 frames
<ipython-input-38-6344cfd038e7> in build_graph(keep_prob, rnn_size, num_layers, batch_size, learning_rate, embedding_size, direction)
     19                                                       batch_size,
     20                                                       embedding_size,
---> 21                                                       direction)
     22 
     23     # Create tensors for the training logits and inference logits

<ipython-input-34-b39707531bf6> in seq2seq_model(inputs, targets, keep_prob, inputs_length, targets_length, max_target_length, vocab_size, rnn_size, num_layers, vocab_to_int, batch_size, embedding_size, direction)
     25                                                         batch_size,
     26                                                         num_layers,
---> 27                                                         direction)
     28 
     29     return training_logits, inference_logits

<ipython-input-33-a3388773d030> in decoding_layer(dec_embed_input, embeddings, enc_output, enc_state, vocab_size, inputs_length, targets_length, max_target_length, rnn_size, vocab_to_int, keep_prob, batch_size, num_layers, direction)
     36                                                   output_layer,
     37                                                   vocab_size,
---> 38                                                   max_target_length)
     39     with tf.compat.v1.variable_scope("decode", reuse=True):
     40         inference_logits = inference_decoding_layer(embeddings,  

<ipython-input-72-c01c95e93861> in training_decoding_layer(dec_embed_input, targets_length, dec_cell, initial_state, output_layer, vocab_size, max_target_length)
     11                                         sequence_length=targets_length,
     12                                         initial_state=initial_state,
---> 13                                         training=True,
     14                                         )
     15 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py in __call__(self, *args, **kwargs)
    784               with autocast_variable.enable_auto_cast_variables(
    785                   self._compute_dtype_object):
--> 786                 outputs = call_fn(cast_inputs, *args, **kwargs)
    787 
    788             except errors.OperatorNotAllowedInGraphError as e:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    668       except Exception as e:  # pylint:disable=broad-except
    669         if hasattr(e, 'ag_error_metadata'):
--> 670           raise e.ag_error_metadata.to_exception(e)
    671         else:
    672           raise

TypeError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_addons/seq2seq/decoder.py:163 call  *
        self,
    /usr/local/lib/python3.6/dist-packages/tensorflow_addons/seq2seq/decoder.py:405 body  *
        (next_outputs, decoder_state, next_inputs, decoder_finished) = decoder.step(
    /usr/local/lib/python3.6/dist-packages/tensorflow_addons/seq2seq/basic_decoder.py:134 step  *
        cell_outputs, cell_state = self.cell(inputs, state, training=training)
    /usr/local/lib/python3.6/dist-packages/tensorflow_addons/seq2seq/attention_wrapper.py:2035 call  *
        cell_output, next_cell_state = self._cell(cell_inputs, cell_state, **kwargs)

    TypeError: __call__() got an unexpected keyword argument 'training'

**Second Approach: Delete training parameter**

So I deleted the training argument:
```
def training_decoding_layer(dec_embed_input, targets_length, dec_cell, initial_state, output_layer, 
                            vocab_size, max_target_length):
    
    with tf.name_scope("Training_Decoder"):
        training_helper = tfa.seq2seq.TrainingSampler(time_major=False)

        training_decoder = tfa.seq2seq.BasicDecoder(dec_cell, training_helper,
                                                    output_layer)
        
        output, _, _ = training_decoder(dec_embed_input,
                                        sequence_length=targets_length, 
                                        initial_state=initial_state
                                        )

        return output


```

Then I got the same error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-75-4988f863ff0b> in <module>()
      8                                                     threshold) 
      9             model = build_graph(keep_probability, rnn_size, num_layers, batch_size, 
---> 10                                 learning_rate, embedding_size, direction)
     11             train(model, epochs, log_string)

5 frames
<ipython-input-38-6344cfd038e7> in build_graph(keep_prob, rnn_size, num_layers, batch_size, learning_rate, embedding_size, direction)
     19                                                       batch_size,
     20                                                       embedding_size,
---> 21                                                       direction)
     22 
     23     # Create tensors for the training logits and inference logits

<ipython-input-34-b39707531bf6> in seq2seq_model(inputs, targets, keep_prob, inputs_length, targets_length, max_target_length, vocab_size, rnn_size, num_layers, vocab_to_int, batch_size, embedding_size, direction)
     25                                                         batch_size,
     26                                                         num_layers,
---> 27                                                         direction)
     28 
     29     return training_logits, inference_logits

<ipython-input-33-a3388773d030> in decoding_layer(dec_embed_input, embeddings, enc_output, enc_state, vocab_size, inputs_length, targets_length, max_target_length, rnn_size, vocab_to_int, keep_prob, batch_size, num_layers, direction)
     36                                                   output_layer,
     37                                                   vocab_size,
---> 38                                                   max_target_length)
     39     with tf.compat.v1.variable_scope("decode", reuse=True):
     40         inference_logits = inference_decoding_layer(embeddings,  

<ipython-input-74-5bc29c379c50> in training_decoding_layer(dec_embed_input, targets_length, dec_cell, initial_state, output_layer, vocab_size, max_target_length)
     10         output, _, _ = training_decoder(dec_embed_input,
     11                                         sequence_length=targets_length,
---> 12                                         initial_state=initial_state
     13                                         )
     14 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py in __call__(self, *args, **kwargs)
    784               with autocast_variable.enable_auto_cast_variables(
    785                   self._compute_dtype_object):
--> 786                 outputs = call_fn(cast_inputs, *args, **kwargs)
    787 
    788             except errors.OperatorNotAllowedInGraphError as e:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    668       except Exception as e:  # pylint:disable=broad-except
    669         if hasattr(e, 'ag_error_metadata'):
--> 670           raise e.ag_error_metadata.to_exception(e)
    671         else:
    672           raise

TypeError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_addons/seq2seq/decoder.py:163 call  *
        self,
    /usr/local/lib/python3.6/dist-packages/tensorflow_addons/seq2seq/decoder.py:405 body  *
        (next_outputs, decoder_state, next_inputs, decoder_finished) = decoder.step(
    /usr/local/lib/python3.6/dist-packages/tensorflow_addons/seq2seq/basic_decoder.py:134 step  *
        cell_outputs, cell_state = self.cell(inputs, state, training=training)
    /usr/local/lib/python3.6/dist-packages/tensorflow_addons/seq2seq/attention_wrapper.py:2035 call  *
        cell_output, next_cell_state = self._cell(cell_inputs, cell_state, **kwargs)

    TypeError: __call__() got an unexpected keyword argument 'training'

I really need help.

**Comment by guillaumekln** [comment]
How is `dec_cell` defined in this example?

**Comment by fzehracetin** [comment]
In Tf 1.1, it defined like this:
```
 with tf.name_scope("Attention_Wrapper"):
        dec_cell = tf.contrib.seq2seq.DynamicAttentionWrapper(dec_cell,
                                                              attn_mech,
                                                              rnn_size)
    
    initial_state = tf.contrib.seq2seq.DynamicAttentionWrapperState(enc_state,
                                                                    _zero_state_tensors(rnn_size, 
                                                                                        batch_size, 
                                                                                        tf.float32))
```
I converted to version 2.4 like this:
```
    with tf.name_scope("Attention_Wrapper"):
        dec_cell = tfa.seq2seq.AttentionWrapper(dec_cell, attn_mech, rnn_size, 
                                                {'state_size': rnn_size})
    
    zero_state = dec_cell.get_initial_state(batch_size=batch_size, dtype=tf.float32)
    initial_state = zero_state.clone(cell_state=enc_state)

```

I disabled eager execution because this code uses placeholders etc. Could it be a problem for this situation?

**Comment by guillaumekln** [comment]
What is the RNN cell class that you are passing to `AttentionWrapper`?

**Comment by fzehracetin** [comment]
Sorry, I did not see the dec_cell parameter.

version 2.4
```
with tf.name_scope("RNN_Decoder_Cell"):
    for layer in range(num_layers):
        with tf.compat.v1.variable_scope('decoder_{}'.format(layer)):
            lstm = tf.compat.v1.nn.rnn_cell.LSTMCell(rnn_size)
            dec_cell = tf.compat.v1.nn.rnn_cell.DropoutWrapper(lstm, 
                                                     input_keep_prob = keep_prob)
```

**Comment by guillaumekln** [comment]
See this comment: https://github.com/tensorflow/addons/issues/647#issuecomment-547838754

**Comment by fzehracetin** [comment]
Thanks for your help 👍
