### ISSUE TITLE
Cannot load SavedModel with RSquare metric

### ISSUE THREAD

**Issue by n18abdel** [tensorflow/addons#2389]
**System information**
- macOS 11.2.1
- TensorFlow 2.4.1 , via pip install tensorflow
- TensorFlow-Addons 0.12.1 , via pip install tensorflow_addons
- Python version: 3.7.7
- Is GPU used? no

**Describe the bug**

I have a saved keras model. 
If the model uses the RSquare metric, I am not able to load it back. 
But with the exact same model defined without the RSquare metric, I do not have any issue.

**Code to reproduce the issue**

```
import tensorflow as tf
import tensorflow_addons as tfa

USE_R2 = True

model = tf.keras.models.Sequential(tf.keras.layers.Dense(1))
if USE_R2:
    metrics = [tfa.metrics.RSquare(y_shape=(1,))]
else:
    metrics = None
model.compile(loss='mse', metrics=metrics)

x = tf.constant( [[1, 2, 3, 4]] )
y = tf.constant( [[1]] )

model.fit(x,y)

model.save('./tmp')
model = tf.keras.models.load_model('./tmp')
```

**Other info / logs**

I get the following error:

> ValueError: Shapes () and (1,) are incompatible

**Comment by seanpmorgan** [comment]
Thanks @n18abdel for reporting. Should be fixed in latest nightly
