### ISSUE TITLE
euclidean_dist_transform 11441 times slower on CPU and 4 times slower on GPU vs cv2.distanceTransform on CPU

### ISSUE THREAD

**Issue by shkarupa-alex** [tensorflow/addons#2399]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow version and how it was installed (source or binary): default for Google Colab
- TensorFlow-Addons version and how it was installed (source or binary): 0.12.1, binary
- Python version: default for Google Colab
- Is GPU used? (yes/no): all cases

**Describe the bug**
I need to use euclidean_dist_transform in my model, but found that it is terribly slower then cv2 analog.

**Code to reproduce the issue**
https://colab.research.google.com/drive/1y_lMWt3idEwtJou1F6owDXafpVl0wZcM?usp=sharing

**Comment by bhack** [comment]
On Gpu on your colab I see:
```
CV2 0.06606674194335938
TFA 0.006447553634643555
```
On CPU can you test also skimage impl?

```
ndimage.distance_transform_edt(src_np)
```

**Comment by shkarupa-alex** [comment]
Updated code to reproduce:

# GPU
CV2 0.136826753616333
SCP 0.3186626434326172 // scipy
TFA 0.03255462646484375

# CPU
CV2 0.05006909370422363
SCP 0.400362491607666 // scipy
TFA 565.4394438266754

# Result
TFA-GPU vs CV2-CPU near the same performance (from 4 times slower to 3 times faster)
TFA-CPU ~11441-11293 times slower vs CV2-CPU

**Comment by WindQAQ** [comment]
Our implementation is expected to be very slow. We implement it with naive approach. For each pixel we scan the whole plane to find the minimal distance, so the complexity is O(H^2 W^2) for single thread (default). There should be a single-threaded linear time dynamic programming two pass algorithm for better speed. I'll mark this help wanted to see if someone want to implement it.

**Comment by fsx950223** [comment]
Interesting

**Comment by bhack** [comment]
I think Meijster's approach It Is still quite competitive:

https://stackoverflow.com/questions/53678520/speed-up-computation-for-distance-transform-on-image-in-python

**Comment by bhack** [comment]
Just a side note, I hope that at some point in time we could write this kind of "Classic" cv ops in python. 
There was a thread related to distance transform in the old npcomp repo https://github.com/google/mlir-npcomp/issues/1

/cc @stellaraccident

**Comment by fsx950223** [comment]
I test my implementation on my CPU, I got:
CV2 0.023948192596435547
TFA 0.1315934658050537

**Comment by bhack** [comment]
I think the benchmark could be plausibile as Opencv has some specialized kernels (e.g. 3x3 5x5) https://www.github.com/opencv/opencv/tree/master/modules%2Fimgproc%2Fsrc%2Fdistransform.cpp

**Comment by WindQAQ** [comment]
> I tested my implementation on my CPU, I got:
> CV2 0.02393149199997424
> TFA 0.10997058800057857

The results look great! Can you try to compile TFA with -O3, which enables auto vectorization?

**Comment by fsx950223** [comment]
> > I tested my implementation on my CPU, I got:
> > CV2 0.02393149199997424
> > TFA 0.10997058800057857
> 
> The results look great! Can you try to compile TFA with -O3, which enables auto vectorization?

CV2 0.023186317997897277
TFA 0.10534513300081016

**Comment by fsx950223** [comment]
I got ```
CV2 0.01852703094482422
SCP 0.2986025810241699
TFA 0.07228779792785645
``` on current implementation

**Comment by bhack** [comment]
Can you benckmark it with comparable args? I suppose with the default ones in opencv there Is a different impl.

**Comment by WindQAQ** [comment]
Hi @shkarupa-alex, would you mind building addons from source and benchmark again? The optimization is landed on master branch. Let us know if the performance is good enough. Thank you.

**Comment by fsx950223** [comment]
I test the gpu kernel via following example:
``` pip install tfa-nightly```
```python
import cv2
import numpy as np
import scipy.ndimage
import tensorflow as tf
import time
from tensorflow_addons.image import euclidean_dist_transform

src_np = np.round(np.random.rand(512, 512, 1) * 255).astype('uint8')
src_tf = tf.constant(src_np[None, ...])


cv2.distanceTransform(src_np, cv2.DIST_L2, 0)
start = time.time()
for _ in range(10):
    cv2.distanceTransform(src_np, cv2.DIST_L2, 0)
end = time.time()
print('CV2', end - start)

scipy.ndimage.distance_transform_edt(src_np)
start = time.time()
for _ in range(10):
    scipy.ndimage.distance_transform_edt(src_np)
end = time.time()
print('SCP', end - start)

euclidean_dist_transform(src_tf)
start = time.time()
for _ in range(10):
    euclidean_dist_transform(src_tf)
end = time.time()
print('TFA', end - start)
```

then I got 
```
CV2 0.03821134567260742
SCP 0.2969224452972412
TFA 0.0027060508728027344
```

**Comment by shkarupa-alex** [comment]
I've tried new kernel and found that most of the time GPU implementation is about 80 times slower then CPU one.
Here is a test: https://colab.research.google.com/drive/1y_lMWt3idEwtJou1F6owDXafpVl0wZcM?usp=sharing#scrollTo=d4EeCVbs426t

I don't understand why, but only in first of 10 tests (each makes 10 executions) GPU is faster then CPU.

**Comment by fsx950223** [comment]
Here is my test case:https://colab.research.google.com/drive/1y_lMWt3idEwtJou1F6owDXafpVl0wZcM?usp=sharing#scrollTo=gou4qJU63soT
I got
```

Check  0
CV2     0.008583521842956543
SCP     0.07889585494995117
TFA GPU 0.0002519130706787109
TFA CPU 0.016139841079711913


Check  1
CV2     0.008875679969787598
SCP     0.06887569427490234
TFA GPU 0.00029644966125488283
TFA CPU 0.016008996963500978


Check  2
CV2     0.009157276153564453
SCP     0.06919741630554199
TFA GPU 0.00029861927032470703
TFA CPU 0.015951156616210938


Check  3
CV2     0.00928342342376709
SCP     0.06887285709381104
TFA GPU 0.00023777484893798827
TFA CPU 0.015878820419311525


Check  4
CV2     0.008911323547363282
SCP     0.06766142845153808
TFA GPU 0.0002354145050048828
TFA CPU 0.01582674980163574


Check  5
CV2     0.009492707252502442
SCP     0.06809210777282715
TFA GPU 0.0002519130706787109
TFA CPU 0.015852975845336913


Check  6
CV2     0.008872580528259278
SCP     0.06856760978698731
TFA GPU 0.00024890899658203125
TFA CPU 0.01594688892364502


Check  7
CV2     0.009044861793518067
SCP     0.06895742416381836
TFA GPU 0.0002959728240966797
TFA CPU 0.01600203514099121


Check  8
CV2     0.008984589576721191
SCP     0.06754066944122314
TFA GPU 0.0003019094467163086
TFA CPU 0.016387557983398436


Check  9
CV2     0.009071874618530273
SCP     0.06899504661560059
TFA GPU 0.00029895305633544924
TFA CPU 0.016098880767822267
```

**Comment by shkarupa-alex** [comment]
Could someone else try provided code?
I've tried it on colab:
```python
Check  0
CV2     0.008406257629394532
SCP     0.07660105228424072
TFA GPU 0.0003614902496337891
TFA CPU 0.015309882164001466


Check  1
CV2     0.008504796028137206
SCP     0.07720611095428467
TFA GPU 0.8189992427825927
TFA CPU 0.015161871910095215


Check  2
CV2     0.008882999420166016
SCP     0.07647917270660401
TFA GPU 0.8027088403701782
TFA CPU 0.015963125228881835


Check  3
CV2     0.008594870567321777
SCP     0.07733423709869384
TFA GPU 0.802504587173462
TFA CPU 0.015290141105651855


Check  4
CV2     0.008850693702697754
SCP     0.07725903987884522
TFA GPU 0.8017091035842896
TFA CPU 0.01555778980255127


Check  5
CV2     0.008573698997497558
SCP     0.0781489372253418
TFA GPU 0.8016223907470703
TFA CPU 0.015253520011901856


Check  6
CV2     0.008754730224609375
SCP     0.07833621501922608
TFA GPU 0.8018173933029175
TFA CPU 0.015215659141540527


Check  7
CV2     0.008560895919799805
SCP     0.07867443561553955
TFA GPU 0.8007907629013061
TFA CPU 0.015265488624572754


Check  8
CV2     0.008526062965393067
SCP     0.07569401264190674
TFA GPU 0.8041980981826782
TFA CPU 0.015035247802734375


Check  9
CV2     0.008694720268249512
SCP     0.07705929279327392
TFA GPU 0.801639986038208
TFA CPU 0.015179729461669922
```
and on kaggle
```python
Check  0
CV2     0.008725142478942871
SCP     0.08810336589813232
TFA GPU 0.06316821575164795
TFA CPU 0.01588599681854248


Check  1
CV2     0.007919120788574218
SCP     0.07388026714324951
TFA GPU 2.0087994813919066
TFA CPU 0.016141939163208007


Check  2
CV2     0.008398103713989257
SCP     0.07571439743041992
TFA GPU 2.0054722309112547
TFA CPU 0.01600480079650879


Check  3
CV2     0.007853388786315918
SCP     0.07453539371490478
TFA GPU 2.0090930223464967
TFA CPU 0.023412704467773438


Check  4
CV2     0.007876396179199219
SCP     0.07455101013183593
TFA GPU 2.0008246183395384
TFA CPU 0.016316485404968262


Check  5
CV2     0.008171606063842773
SCP     0.09572982788085938
TFA GPU 1.9887922286987305
TFA CPU 0.01615939140319824


Check  6
CV2     0.008967995643615723
SCP     0.07510759830474853
TFA GPU 2.005467915534973
TFA CPU 0.01589195728302002


Check  7
CV2     0.00826435089111328
SCP     0.07413172721862793
TFA GPU 2.0062133073806763
TFA CPU 0.015863251686096192


Check  8
CV2     0.008236503601074219
SCP     0.07350404262542724
TFA GPU 2.009607672691345
TFA CPU 0.015805506706237794


Check  9
CV2     0.008133745193481446
SCP     0.07443795204162598
TFA GPU 2.008491945266724
TFA CPU 0.015694952011108397
```

**Comment by fsx950223** [comment]
> Could someone else try provided code?
> I've tried it on colab:
> 
> ```python
> Check  0
> CV2     0.008406257629394532
> SCP     0.07660105228424072
> TFA GPU 0.0003614902496337891
> TFA CPU 0.015309882164001466
> 
> 
> Check  1
> CV2     0.008504796028137206
> SCP     0.07720611095428467
> TFA GPU 0.8189992427825927
> TFA CPU 0.015161871910095215
> 
> 
> Check  2
> CV2     0.008882999420166016
> SCP     0.07647917270660401
> TFA GPU 0.8027088403701782
> TFA CPU 0.015963125228881835
> 
> 
> Check  3
> CV2     0.008594870567321777
> SCP     0.07733423709869384
> TFA GPU 0.802504587173462
> TFA CPU 0.015290141105651855
> 
> 
> Check  4
> CV2     0.008850693702697754
> SCP     0.07725903987884522
> TFA GPU 0.8017091035842896
> TFA CPU 0.01555778980255127
> 
> 
> Check  5
> CV2     0.008573698997497558
> SCP     0.0781489372253418
> TFA GPU 0.8016223907470703
> TFA CPU 0.015253520011901856
> 
> 
> Check  6
> CV2     0.008754730224609375
> SCP     0.07833621501922608
> TFA GPU 0.8018173933029175
> TFA CPU 0.015215659141540527
> 
> 
> Check  7
> CV2     0.008560895919799805
> SCP     0.07867443561553955
> TFA GPU 0.8007907629013061
> TFA CPU 0.015265488624572754
> 
> 
> Check  8
> CV2     0.008526062965393067
> SCP     0.07569401264190674
> TFA GPU 0.8041980981826782
> TFA CPU 0.015035247802734375
> 
> 
> Check  9
> CV2     0.008694720268249512
> SCP     0.07705929279327392
> TFA GPU 0.801639986038208
> TFA CPU 0.015179729461669922
> ```
> 
> and on kaggle
> 
> ```python
> Check  0
> CV2     0.008725142478942871
> SCP     0.08810336589813232
> TFA GPU 0.06316821575164795
> TFA CPU 0.01588599681854248
> 
> 
> Check  1
> CV2     0.007919120788574218
> SCP     0.07388026714324951
> TFA GPU 2.0087994813919066
> TFA CPU 0.016141939163208007
> 
> 
> Check  2
> CV2     0.008398103713989257
> SCP     0.07571439743041992
> TFA GPU 2.0054722309112547
> TFA CPU 0.01600480079650879
> 
> 
> Check  3
> CV2     0.007853388786315918
> SCP     0.07453539371490478
> TFA GPU 2.0090930223464967
> TFA CPU 0.023412704467773438
> 
> 
> Check  4
> CV2     0.007876396179199219
> SCP     0.07455101013183593
> TFA GPU 2.0008246183395384
> TFA CPU 0.016316485404968262
> 
> 
> Check  5
> CV2     0.008171606063842773
> SCP     0.09572982788085938
> TFA GPU 1.9887922286987305
> TFA CPU 0.01615939140319824
> 
> 
> Check  6
> CV2     0.008967995643615723
> SCP     0.07510759830474853
> TFA GPU 2.005467915534973
> TFA CPU 0.01589195728302002
> 
> 
> Check  7
> CV2     0.00826435089111328
> SCP     0.07413172721862793
> TFA GPU 2.0062133073806763
> TFA CPU 0.015863251686096192
> 
> 
> Check  8
> CV2     0.008236503601074219
> SCP     0.07350404262542724
> TFA GPU 2.009607672691345
> TFA CPU 0.015805506706237794
> 
> 
> Check  9
> CV2     0.008133745193481446
> SCP     0.07443795204162598
> TFA GPU 2.008491945266724
> TFA CPU 0.015694952011108397
> ```

Do you try my test case?

**Comment by shkarupa-alex** [comment]
> Do you try my test case?
Your link is the same as mine

**Comment by fsx950223** [comment]
Test with the link https://drive.google.com/file/d/1XcVKtiNBWa5iu032W8bZcu8YCB4t7JyM/view?usp=sharing.

**Comment by shkarupa-alex** [comment]
Ok, my mistake.
With warmup GPU kernel is much faster.
