### ISSUE TITLE
Dynamic Margin

### ISSUE THREAD

**Issue by tdrvlad** [tensorflow/addons#2401]
**Dynamic Margin for Triplet Loss** would allow for the embedding space distances to be weighted by the data instances categorical relationships (in the case of nested categories).

Example: *Dog / Cat classifier with breeds*
DOG_Shepherd vs DOG_Husky has different margin than DOG_Shepherd vs CAT_Persian

- I am willing to contribute
- Relevant academic paper:

https://www.researchgate.net/figure/Triplet-loss-with-dynamic-margin-better-separation-achieved-by-setting-different_fig3_321815679

**Comment by bhack** [comment]
We are evaluating to add a paper threshold. See https://github.com/tensorflow/addons/pull/2370

**Comment by bhack** [comment]
This seems to have a number of citations under the threshold. Please reopen this if it will accumulate more citations.
