### ISSUE TITLE
Lookahead fails with mixed precision and `ReduceLROnPlateau`

### ISSUE THREAD

**Issue by rroseandrieux** [tensorflow/addons#2403]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04
- TensorFlow version and how it was installed (source or binary): pip install tensorflow==2.4.1
- TensorFlow-Addons version and how it was installed (source or binary): pip install tensorflow-addons==0.12.1 
- Python version: 3.8.5
- Is GPU used? (yes/no): no

**Describe the bug**

Lookahead is not compatible with mixed precision and lr callbacks. The attribute 'lr' or 'learning_rate' is missing.
This may be due to the learning_rate being an attribute in Lookahead while being search with get_hyper by the LossScaleOptimizer when using mixed precision. 
It will fail with any callbacks that try to access the learning rate. 

**Code to reproduce the issue**
```
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import mixed_precision
from tensorflow_addons.optimizers import Lookahead, RectifiedAdam
from tensorflow.keras.callbacks import ReduceLROnPlateau

policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_global_policy(policy)

model = tf.keras.Sequential()
model.add(layers.Dense(10))

test_ones = tf.ones([1, 20])

optimizer = Lookahead(RectifiedAdam(0.003))
model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy'],
    run_eagerly=False,
)
model.fit(test_ones, tf.constant([0]), 8, epochs=100, callbacks=[ReduceLROnPlateau(monitor="accuracy")])
```

**Other info / logs**
```
Traceback (most recent call last):
  File "/home/raphael/Workspace/classification-api/test_r.py", line 23, in <module>
    model.fit(test_ones, tf.constant([0]), 8, epochs=100, callbacks=[ReduceLROnPlateau(monitor="accuracy")])
  File "/home/raphael/Workspace/envs/test/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1145, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/raphael/Workspace/envs/test/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 432, in on_epoch_end
    callback.on_epoch_end(epoch, numpy_logs)
  File "/home/raphael/Workspace/envs/test/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 2524, in on_epoch_end
    logs['lr'] = K.get_value(self.model.optimizer.lr)
  File "/home/raphael/Workspace/envs/test/lib/python3.8/site-packages/tensorflow/python/keras/mixed_precision/loss_scale_optimizer.py", line 895, in __getattribute__
    raise e
  File "/home/raphael/Workspace/envs/test/lib/python3.8/site-packages/tensorflow/python/keras/mixed_precision/loss_scale_optimizer.py", line 884, in __getattribute__
    return object.__getattribute__(self, name)
AttributeError: 'LossScaleOptimizer' object has no attribute 'lr'
```

**Comment by bhack** [comment]
It seems similar to https://github.com/tensorflow/addons/issues/2332#issuecomment-754999736

**Comment by rroseandrieux** [comment]
@bhack You're right it is similar but with the Lookahead optimizer..

**Comment by jonpsy** [comment]
I'd like to take a stab at this :)

**Comment by bhack** [comment]
There was a @fsx950223 stub for the same issue to the other mentioned optimizer at https://github.com/fsx950223/addons/commit/137de6b07365093758d0ce00754352625c691013

**Comment by jonpsy** [comment]
@bhack  Instead of using ```ReduceLROnPlateau``` I used ```LearningRateSchecduler``` and I got this error 

```
  File "<input>", line 32, in <module>
  File "/home/psykik/PycharmProjects/addons/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1090, in fit
    callbacks.on_epoch_begin(epoch)
  File "/home/psykik/PycharmProjects/addons/venv/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 411, in on_epoch_begin
    callback.on_epoch_begin(epoch, numpy_logs)
  File "/home/psykik/PycharmProjects/addons/venv/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 1902, in on_epoch_begin
    raise ValueError('Optimizer must have a "lr" attribute.')
ValueError: Optimizer must have a "lr" attribute.
```

Notice that I got the error in ```epoch_begin``` itself, which already checks if the ```self.model.optimizer```(LossScaleOptimizer) has ```lr```. I wonder how did ```ReduceLROnPlateau``` got past this since it got the error in ```epoch_end()```

Here's the check

```
callbacks.py/on_epoch_begin()
    if not hasattr(self.model.optimizer, 'lr'):
      raise ValueError('Optimizer must have a "lr" attribute.')
```

**Comment by jonpsy** [comment]
Turns out the ```epoch_begin``` of ```ReduceLRonPlateau``` is noop, which is why it **skipped** the ```lr``` check at the beginning.

**Comment by jonpsy** [comment]
Okay, I'm ready for a naive PR :)

**Comment by reedwm** [comment]
Talking with @omalleyt12 and @fchollet, we decided the best approach is for LossScaleOptimizer to uncondtionally delegate the `learning_rate` attribute. I have not seen issues with nested optimizer wrappers and hyperaparmeters other than for `learning_rate`, so I think it's best not to add another API but instead special-case `learning_rate` to get uses cases such as this one to work properly. I will make the fix in LossScaleOptimizer by adding code similar to this:

```python
  @property
  def learning_rate(self):
    return self._optimizer.learning_rate

  @learning_rate.setter
  def learning_rate(self, value):
    self._optimizer.learning_rate = value
```

Since the fix is not in TF-Addons itself, `tf-nightly` or TF 2.5 (once released) will be required for the fix to take effect. Unfortunately, this doesn't affect hyperparameters, but I think accessing other hyperparameters is rare.
