### ISSUE TITLE
Webpage build instructions incorrect: CUDA_HOME should be CUDA_TOOLKIT_PATH

### ISSUE THREAD

**Issue by juliangilbey** [tensorflow/addons#2429]
On the installation webpage, https://www.tensorflow.org/addons/overview#installing_from_source the instructions say that the CUDA directory can be specified with an exported `CUDA_HOME`.  However, in the current `configure.py`, this has been replaced with `CUDA_TOOLKIT_PATH`.

**Comment by bhack** [comment]
Can you send a small PR?

**Comment by juliangilbey** [comment]
I don't know where the web page sources are.

**Comment by bhack** [comment]
> I don't know where the web page sources are.

We are trying to improve this cause we don't have a direct link to the Github source for Markdown files in the Website. 

In the meantime, for the PR, you can find the source of that page at https://github.com/tensorflow/addons/blob/master/docs/overview.md

/cc @theadactyl

**Comment by juliangilbey** [comment]
OK, thanks!
