### ISSUE TITLE
Enable Python 3.9 support

### ISSUE THREAD

**Issue by tgaddair** [tensorflow/addons#2436]
TensorFlow now publishes nightly wheels for Python 3.9 (see: https://github.com/tensorflow/tensorflow/issues/44485#issuecomment-797037619). However, looks like TensorFlow Addons does not.

For parity, TensorFlow Addons should also move to support Python 3.9 for the upcoming TF release (targeted for end of April).

**Comment by seanpmorgan** [comment]
Duplicate https://github.com/tensorflow/addons/issues/2188. Thanks for reminding us though we'll definitely build 3.9 when we target TF2.5

We used to build against nightlies in tfa-nightly but it was a maintenance burden. We now pin tfa-nightly and tensorflow-addons to latest stable release.
