### ISSUE TITLE
Can't Install Tensorflow-Addons=0.11.2 with Python=3.6.9 and Tensorflow=2.3: Compatibility Issues.

### ISSUE THREAD

**Issue by phillipshaong** [tensorflow/addons#2444]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 ARM Architecture Running on NVIDIA Jetson Xavier
- TensorFlow version and how it was installed (source or binary): 2.3 (From NVIDIA Docker Image)
- TensorFlow-Addons version and how it was installed (source or binary): >=0.11.1
- Python version: 3.6.9
- Is GPU used? (yes):

**Describe the bug**

I am trying to install TensorflowASR, and based on its requirements (https://github.com/TensorSpeech/TensorFlowASR/blob/main/requirements.txt), I need to install tensorflow-addon>=0.11.1. Despite meeting the requirements to install tensorflow-addon=0.11.2, it still doesn't show that I am able to install the library.

**Code to reproduce the issue**

1. Build and run the Dockerfile.

`DockerFile` is adapted from: https://github.com/TensorSpeech/TensorFlowASR/blob/main/Dockerfile
```
FROM nvcr.io/nvidia/l4t-tensorflow:r32.4.4-tf2.3-py3

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    && apt-get -y install apt-utils gcc libpq-dev libsndfile-dev git build-essential cmake screen

# Clear cache
RUN apt clean && apt-get clean

# Install dependencies
COPY requirements.txt /
#RUN  pip3 --no-cache-dir install -r /requirements.txt

# Install rnnt_loss
#COPY scripts /scripts
#ARG install_rnnt_loss=true
#ARG using_gpu=true
#RUN if [ "$install_rnnt_loss" = "true" ] ; \
#    then if [ "$using_gpu" = "true" ] ; then export CUDA_HOME=/usr/local/cuda ; else echo 'Using CPU' ; fi \
#    && ./scripts/install_rnnt_loss.sh \
#    else echo 'Using pure TensorFlow'; fi

# RUN echo "export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" >> /root/.bashrc
```
2. Run Python3 and try out the tensorflow libraries. Try to install tensorflow-addons with pip.
```
root@dc5c558bf459:/# python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import tensorflow as tf
2021-04-09 03:11:50.269736: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
>>> print(tf.__version__)
2.3.0
>>> os.system("python3 -m pip install tensorflow-addons>=0.11.1")
  Could not find a version that satisfies the requirement tensorflow-addons (from versions: )
No matching distribution found for tensorflow-addons
```
**Other info / logs**

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
