### ISSUE TITLE
The right way to apply `tfa.image.cutout`

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/addons#2448]
Hi folks.

I am trying to use `tfa.image.cutout()` for an experiment. However, I am unable to figure out how I should apply it. 

So far I have done the following:

```python
IMAGE_SIZE = 224
TOTAL_AREA = IMAGE_SIZE * IMAGE_SIZE

image = tf.io.read_file("image.jpg")
image = tf.image.decode_jpeg(image, channels=3)
image = tf.image.resize(image, (IMAGE_SIZE, IMAGE_SIZE))
image = tf.cast(image, tf.uint8)
image = tf.expand_dims(image, 0)

cutout_image = tfa.image.cutout(image, int(TOTAL_AREA*0.05), offset=(20, 20))

plt.imshow(cutout_image.numpy().squeeze(0))
plt.axis("off")
plt.show()
```

I am getting an all blacked out image:

![image](https://user-images.githubusercontent.com/22957388/114260427-76406880-99f2-11eb-9c93-9748626050ed.png)

Here's a [Colab Notebook](https://colab.research.google.com/gist/sayakpaul/5a0f6c0cec7508722c1a3be89d8d1bd8/scratchpad.ipynb) to reproduce this. Am I missing out on something?

**Comment by bhack** [comment]
Can you compare in your notebook with https://github.com/tensorflow/addons/issues/2384#issuecomment-776621306 ?

**Comment by sayakpaul** [comment]
Same phenomenon: https://colab.research.google.com/gist/sayakpaul/1fdeca61f6e7c10b0d47a2d13a867113/scratchpad.ipynb.

**Comment by bhack** [comment]
So probably do you want something like `int(math.sqrt(TOTAL_AREA*0.05)` (or `floor/ceil`) right?

**Comment by sayakpaul** [comment]
My apologies. I should have noted the documentation:

```
pad_size: Specifies how big the zero mask that will be generated is that is
applied to the image. The mask will be of size (2pad_size x 2pad_size).
```

On a related note, in `tfa` it's different I believe. It expects the mask size. A unification would have been really nice.

**Comment by fsx950223** [comment]
https://colab.research.google.com/drive/1m-3EKvK9Th9rRTDPytlv59TUgPYipxlr?usp=sharing
