### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [tensorflow/addons#2456]
It has been noticed that while using Gaurav0/backport@d69fd1d2469762a7b4007f671857e4f94deed0af your bot_token 1353d990cdb8b8ceb1b73d301dce83cc0da3db29 is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by bhack** [comment]
@seanpmorgan https://github.com/tensorflow/addons/pull/2133
