### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [tensorflow/addons#2457]
It has been noticed that while using Gaurav0/backport@d69fd1d2469762a7b4007f671857e4f94deed0af your bot_token_key a1b2c3d47311f8e29e204f85a81b4df4a44e252c is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by bhack** [comment]
@seanpmorgan https://github.com/tensorflow/addons/pull/2133
