### ISSUE TITLE
layer

### ISSUE THREAD

**Issue by RandinAk** [tensorflow/addons#2472]
**Describe the feature and the current behavior/state.**

**Relevant information**
- Are you willing to contribute it (yes/no)[](yes)
*If you wish to contribute, then read the requirements for new contributions in [`CONTRIBUTING.md`](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#requirements-for-new-contributions-to-the-repository)*
- Are you willing to maintain it going forward? (yes)
```
- Is there a relevant academic paper? (if so, where):idk. 
- Does the relavent academic paper exceed 50 citations? (yes/no):**Idk**
- Is there already an implementation in another framework? (if so, where):idk
Was it part of tf.contrib? (if so, where)

**Which API type would this fall under (layer, metric, optimizer, etc.)** layer

``**Who will benefit with this feature?idk

**Any other info.**

**Comment by bhack** [comment]
I don't understand this ticket I has no detail. Please open a new one.
