### ISSUE TITLE
Fix Kokoro GPU Testing

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#2485]
Hi @av8ramit, as of late last week we began getting failing Kokoro jobs with the error:
`[03:23:09][ERROR] Config validation failed!`

Example:
https://source.cloud.google.com/results/invocations/fe13d541-682a-4341-b512-c5be00905338/targets/tensorflow_addons%2Fubuntu%2Fgpu%2Fpy3%2Fcontinuous/log

I looked around and another repo had a similar issue a few weeks ago that they said was resolved on the kokoro side:
https://github.com/SymbiFlow/symbiflow-arch-defs/issues/2124

When time allows could you look around and see if something in the job configuration is out of date and causing these immediate job failures?

**Comment by av8ramit** [comment]
Hello @seanpmorgan I've taken a look and I believe I've fixed the root cause. The [latest run is green](https://source.cloud.google.com/results/invocations/90a6943a-dcca-4b65-996d-6b1b6d313102/targets).

**Comment by seanpmorgan** [comment]
Thanks so much @av8ramit !
