### ISSUE TITLE
Alert CI mailing list on nightly failures

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#249]
Edd was kind enough to set us up a google group for recieving alerts on failing nightlies. The past couple of days we've had failures though so I'm not sure that the email address is linked to the CI server.

@karmel @av8ramit  Is it possible to alert addons-testing@tensorflow.org on fails?

**Comment by karmel** [comment]
You are correct-- we had not set the email up yet. Sent out a fix; will update when it goes through. Thanks for noticing.

**Comment by seanpmorgan** [comment]
Currently our Travis CI alerts us of failures. Closing this for now unless we see a need in the future.
