### ISSUE TITLE
About the SWA tutorial

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/addons#2492]
Given that SWA needs to have access to a particular LR schedule, I think it might be a good idea to actually update the [tutorial](https://www.tensorflow.org/addons/tutorials/average_optimizers_callback) with a minimal example of incorporating such schedules. 

In my experience (as well as what the original authors assert), in order for someone to reap the benefits of SWA, the schedule is important.

**Comment by bhack** [comment]
Do you want to contribute a PR?

**Comment by sayakpaul** [comment]
I would rather ask the original author of the tutorial to do it as they would have a better idea.

**Comment by bhack** [comment]
I don't think that @abhichou4 is still active in the project.

**Comment by jonpsy** [comment]
I can give it a shot.

**Comment by jonpsy** [comment]
Thanks for opening this issue, it looks like there are a few errors in the implementation aside from the things you mentioned. I'll address them all in PR.

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
