### ISSUE TITLE
Weight Normalization layer doesn't work with mixed precision

### ISSUE THREAD

**Issue by stephen-systemfriend** [tensorflow/addons#2500]
copied from https://github.com/tensorflow/tensorflow/issues/46001

System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Minimal
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 'v2.4.0-rc4-71-g582c8d236cb'
Python version: 3.8
CUDA/cuDNN version: CUDA 11 cudnn 8
GPU model and memory: RTX 2080 11gb
Describe the current behavior
when using mixed precision and the weight normalization layer from tensorflow_addons, it throws an error
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float16: <tf.Tensor 'sequential/weight_normalization/cond/data_dep_init/mul:0' shape=(10,) dtype=float16>
from

assign_tensors = self._data_dep_init(inputs)
    \tensorflow_addons\layers\wrappers.py:204 _data_dep_init
        g_tensor = self.g.assign(self.g * scale_init)
    \tensorflow\python\keras\mixed_precision\autocast_variable.py:225 assign
Describe the expected behavior
layer to build and run normally as it does in float32 and float16 policies

Standalone code to reproduce the issue

import tensorflow as tf
import tensorflow_addons as tfa
import numpy as np

policy = tf.keras.mixed_precision.Policy("mixed_float16")
#runs fine with all the same type
#policy = tf.keras.mixed_precision.Policy("float16")

tf.keras.mixed_precision.set_global_policy(policy)

model = tf.keras.Sequential()

model.add(tfa.layers.WeightNormalization(tf.keras.layers.Dense(10, activation="relu")))

model.compile(loss=tf.keras.losses.MeanSquaredError())

X = np.random.randn(1,20)
Y = np.random.randn(1,10)

model.fit(X,Y)
Other info / logs Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

putting a tf.cast inside each call to assign in wrappers.py -> WeightNormalization stops the error, but I'm not certain if that is correct from a numerical stability perspective, and it seems like adding some functionality to the assign function in mixedPrecision/autocast_variable.py -> AutocastVariable would be better

**Comment by bhack** [comment]
/cc @smokrow (As he is the codeowner)

@stephen-systemfriend I don't think that the codeowner (@smokrow) is still available. 
Can you try to send a PR with an extend mixed precision test?

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
