### ISSUE TITLE
Is tensorflow multi-head attention layer autoregressive? e.g. “tfa.layers.MultiHeadAttention”

### ISSUE THREAD

**Issue by samiarja** [tensorflow/addons#2512]
I looked at the difference between an autoregressive vs non-autoregressive in transformer architecture. but I am wondering whether the attention layer in TensorFlow is actually autoregressive? or do I need to implement the autoregressive mechanism?

I don't see any option for causal (e.g. causal=true/false) or whether "tfa.layers.MultiHeadAttention" is autoregressive or not

Any thoughts on that would be appreciated.

**Comment by bhack** [comment]
Check https://keras.io/api/layers/attention_layers/multi_head_attention/

You can use now the Keras version directly as we are going to deprecate our one quite soon.

Use our forum https://discuss.tensorflow.org/ for any question.
