### ISSUE TITLE
CRF layers raise InvalidArgumentError in TPU

### ISSUE THREAD

**Issue by ziliwang** [tensorflow/addons#2519]
I tried training a CRF model in TPUStrategy, but it raised InvalidArgumentError. detail please see: https://colab.research.google.com/drive/1cRm0dd12TIPQbsl9pmI1KdiFtubB0ZIZ?usp=sharing

**Comment by bhack** [comment]
Thanks, we are looking for a CRF codeowner. See https://github.com/tensorflow/addons/issues/2476#issuecomment-874261227

**Comment by howl-anderson** [comment]
Hi @ziliwang, for keep you updated. I am working on this issue.

**Comment by howl-anderson** [comment]
Hi @ziliwang , after investigation, I am pretty sure it is a bug of Keras. If you change your code from:

```python
train_iterator = iter(train_dataset)
train_step(train_iterator)
  # print(round(float(training_loss.result()), 4))
  # training_loss.reset_states()
print(model.weights[0].numpy())
```

add one line of code:

```python
train_iterator = iter(train_dataset)
train_step(train_iterator)
  # print(round(float(training_loss.result()), 4))
  # training_loss.reset_states()
print(model.weights[0])   # ATTENTION: comment me will cause a bug in next line
print(model.weights[0].numpy())
```
 It will fix the error. it is a weird behavior. Maybe is a bug of functional Keras API. You can double check by running code at https://colab.research.google.com/drive/1ryCgLJxPbIcTe6xgN4EH6hDDLLSrpHQW?usp=sharing
 
And I have found that this behavior only exits on functional Keras API (not on Sequential API).  I have create a colab with a new model written in functional API and Sequential API at https://colab.research.google.com/drive/1GyBdh-fRV--BSOin4ldf48YitkvbyE7f?usp=sharing . You can double check it.

**Comment by qlzh727** [comment]
@yuefengzhou from distribution strategy team. 

From https://colab.sandbox.google.com/drive/1ryCgLJxPbIcTe6xgN4EH6hDDLLSrpHQW?usp=sharing#scrollTo=tpLYkZyVIoV6, the output of model.weights[0] is a TPUDistributedVariable, which is intended, but I am not sure why the chain_kernel:0 has numpy unavailable. The rest of the replica has the same value. Maybe it is a variable read issue when get_value is called outside of the strategy context.

**Comment by qlzh727** [comment]
@yuefengz

**Comment by ziliwang** [comment]
@howl-anderson Thanks for the replies. I tried to replace the CRF layer with a Keras dense layer, and it has shown everything is ok. I guess the CRF layer is in-compatibility with functional API when in the TPU strategy. I'm a newbie in Keras and TPU, and my target is to use the CRF in TPU strategy, the Sequential API really solved my issue. Thanks again for your help.

**Comment by howl-anderson** [comment]
Hi @ziliwang, it's great to see that my code can help you. Since your issue is solved by using sequential API. So, could you close this issue for me? And I will keep trying to find the root cause why CRF layer failed with the TPU strategy. I will keep you updated  in this thread.

**Comment by Damcy** [comment]
@howl-anderson  I meet the same problem when using crf_log_likelihood in TPU. Can CRF be used in TPU now?  Thank you!
