### ISSUE TITLE
How can I call adaptive average pooling function for 4D tensor

### ISSUE THREAD

**Issue by ifmaq1** [tensorflow/addons#2521]
**1-)** I have a .pth image features' file with 4D tensor **[batch,dimension,height,width]**. I can see this class **(AdaptiveAveragePooling2D(AdaptivePooling2D):**

Could you please tell me how can I Pass my .pth file tensor to this class in order to get the pooled features as output?

**2-)** How to use this function 

**tfa.layers.AdaptiveAveragePooling2D(
    output_size: Union[int, Iterable[int]],
    data_format=None,
    kwargs
)**

**3-)** I want final tensor of shape [2048,36]

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
