### ISSUE TITLE
F1Score can't be used due to TypeError for Greater operation

### ISSUE THREAD

**Issue by hasansalimkanmaz** [tensorflow/addons#2526]
**System information**
- MacOS
- tf version 2.2.1 via pip
- TensorFlow-Addons version 0.11.2 via pip
- Python version: 3.8
- Is GPU used? (yes/no): No

**Describe the bug**

I can't use `tfa.metrics.F1Score`due to the following error.

```
{TypeError}Expected int32 passed to parameter 'y' of op 'Greater', got 1e-12 of type 'float' instead. Error: Expected int32, got 1e-12 of type 'float' instead.
```

**Code to reproduce the issue**

```
tfa.metrics.F1Score(num_classes=len(label_encoder), average='micro')
```

**Other info / logs**

I think this error results from `tensorflow_addons/metrics/f_scores.py` line 129 ⬇️ from the 2nd arg `tf.abs(y_pred) > 1e-12`

```
y_pred = tf.logical_and(y_pred >= threshold, tf.abs(y_pred) > 1e-12)
```

I have seen that same error was encountered by another user as mentione on [stackoverflow](https://stackoverflow.com/questions/64833761/tensorflow-2-typeerror-expected-int32-passed-to-parameter-y-of-op-greater).

**Comment by bhack** [comment]
Can you share a minimal gist/Colab with a dummy input to reproduce this?

**Comment by hasansalimkanmaz** [comment]
I have solved my issue by the time. Sorry for not being so patient even if I opened this issue working on it for a few hours. I realized that I was feeding labels instead of predicted probabilities to `f1Score` (It is FRIDAY). After changing the input, it worked. Thank you for your very fast response.
