### ISSUE TITLE
tfa.rotate() doesn't work in tf.data.Dataset.map()

### ISSUE THREAD

**Issue by nicolas-gervais** [tensorflow/addons#2529]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version and how it was installed (source or binary): 2.3 binary
- TensorFlow-Addons version and how it was installed (source or binary): 0.13.0 binary
- Python version: 3.8.1
- Is GPU used? (yes/no): yes

**Describe the bug**

`tfa.image.rotate()` doesn't work in `tf.data.Dataset.map()`

**Code to reproduce the issue**
```
import tensorflow as tf
import tensorflow_addons as tfa
import tensorflow_datasets as tfds

mnist = tfds.load('mnist', split='test', as_supervised=True)

ds = mnist.map(lambda x, y: (tfa.image.rotate(x, 10), y))
```
> NotImplementedError: Cannot convert a symbolic Tensor (rotate/angles_to_projective_transforms/strided_slice_1:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

**Comment by bhack** [comment]
Can you try with this:

https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/python/keras/layers/preprocessing/benchmarks/image_preproc_benchmark.py#L42

**Comment by yarri-oss** [comment]
+1 for putting a process together to catch such duplication issues. I know
Sean wanted to discuss this. I wonder if we could create a pre-submit test
for this somehow?

**Comment by bhack** [comment]
`!pip install -U tf-models-official`

```python
import tensorflow as tf
from official.vision.beta.ops import augment as tfm
import tensorflow_datasets as tfds

mnist = tfds.load('mnist', split='test', as_supervised=True)
ds = mnist.map(lambda x, y: (tfm.rotate(x, 10), y))
```

**Comment by jeongukjae** [comment]
I found this while searching how to use `tfa.image.rotate`. I tried this using `tensorflow==2.6.0` and `tensorflow-addons==0.14.0` but I cannot reproduce this issue.

colab link: https://colab.research.google.com/drive/1MsywxouFx2Ikfh0nO-svjgeYgePdBarB?usp=sharing

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
