### ISSUE TITLE
tensorflow_addons tutorial

### ISSUE THREAD

**Issue by rosas-github** [tensorflow/addons#2537]
**System information**
- macOS 11.5.1 (Big Sur) Macbook Air M1 2020

Hi! Would you help with a tutorial for installing Tensorflow and tensorflow_addons in this system?

**Comment by lgeiger** [comment]
The newest `tfa-nightly` release ships with prebuilt Python 3.8 and 3.9 wheels for M1 Macs. So the next stable release should have full support. @bhack Do you think it would be good to trigger a 0.13.1 release? For 0.14.1 I guess it makes sense to wait until `tensorflow-macos` 2.6.0 is released.

**Comment by bhack** [comment]
Ok /cc @seanpmorgan what do you think?

**Comment by seanpmorgan** [comment]
Generally in support of 0.13.1 release on tensorflow-macos 2.5 but will hold off a day or two to see if we can settle our strategy on this:
https://github.com/tensorflow/addons/pull/2559#issuecomment-918738096

**Comment by rosas-github** [comment]
Sorry, but I still didn't quite understand how to install tensorflow and tensorflow-addons on M1 macos big sur 11+.

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
