### ISSUE TITLE
Build from source - Raspberry Pi - 64-bit OS aarch64: configure.py returns IndexError: list index out of range

### ISSUE THREAD

**Issue by HeatfanJohn** [tensorflow/addons#2539]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian aarch64 "Debian GNU/Linux 10 (buster)"
- TensorFlow version and how it was installed (source or binary): binary
- TensorFlow-Addons version and how it was installed (source or binary): source
- Python version: 3.7.3
- Is GPU used? (yes/no): no

**Describe the bug**
While trying to build addons from source, running `python3 ./configure.py` returns ` IndexError: list index out of range`

`./configure.py` function `is_raspi_arm()` doesn't recognize that `os.uname()[4]` is `aarch64` under 64-Bit Raspberry Pi OS (Raspbian). 

**Code to reproduce the issue**

Under 64-Bit Raspberry Pi OS follow instructions to build addons from source.  `python3 ./configure.py` will fail as follows:

```
pi@myrpi4-8gb:~/addons $ python3 ./configure.py

Configuring TensorFlow Addons to be built from source...
Traceback (most recent call last):
  File "./configure.py", line 179, in <module>
    create_build_configuration()
  File "./configure.py", line 126, in create_build_configuration
    write_action_env("TF_SHARED_LIBRARY_DIR", get_tf_shared_lib_dir())
  File "./configure.py", line 94, in get_tf_shared_lib_dir
    return tf.sysconfig.get_link_flags()[0][2:]
IndexError: list index out of range
```

**Other info / logs**

Fix is to update `configure.py` to recognize `aarch64` as follows:

```
diff --git a/configure.py b/configure.py
index 0ceb902..5126f6d 100644
--- a/configure.py
+++ b/configure.py
@@ -49,7 +49,7 @@ def is_linux():


 def is_raspi_arm():
-    return os.uname()[4] == "armv7l"
+    return os.uname()[4] == "armv7l" or os.uname()[4] == "aarch64"


 def is_linux_ppc64le():

```

`./configure.py` then completes normally:

```
pi@myrpi4-8gb:~/addons $ python3 ./configure.py

Configuring TensorFlow Addons to be built from source...
> Building only CPU ops

Build configurations successfully written to .bazelrc :

build --action_env TF_HEADER_DIR="/usr/local/lib/python3.7/dist-packages/tensorflow/include"
build --action_env TF_SHARED_LIBRARY_DIR="/usr/local/lib/python3.7/dist-packages/tensorflow/python"
build --action_env TF_SHARED_LIBRARY_NAME="_pywrap_tensorflow_internal.so"
build --action_env TF_CXX11_ABI_FLAG="1"
build --spawn_strategy=standalone
build --strategy=Genrule=standalone
build -c opt
build --cxxopt=-std=c++14
build --host_cxxopt=-std=c++14


```

**Comment by bhack** [comment]
Can you send a PR?
