### ISSUE TITLE
Update seq2seq to use tf.where V2

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#254]
As described in #250 and temporarily patched in #251 seq2seq has three instances of tf.where that need the broadcasting dimensions changed to match numpy and TF2 style.

cc @qlzh727

**Comment by seanpmorgan** [comment]
Also, curious if anyone knows wheather this will be caught using the tf2_upgrade script? Probably worth catching broadcasted tf.where cc @martinwicke

**Comment by martinwicke** [comment]
The upgrade script will translate tf.where to tf.compat.v1.where to preserve the behavior.
