### ISSUE TITLE
Do not Support Tensorflow 2.6.0 while Colab has already set Tensorflow 2.6.0 as the default. 

### ISSUE THREAD

**Issue by yifeipet** [tensorflow/addons#2543]
Tensorflow addon does not support Tensorflow 2.6.0 but Google Colab has already upgraded Tensorflow to version 2.6.0. I downgraded Tensorflow to 2.5.0 but Colab does not have GPU support for Tensorflow 2.5.0. 
Please add something so to make Tensorflow addon also supports Tensorflow 2.6.0. Thank you!

**Comment by bhack** [comment]
Thanks, you can subscribe to https://github.com/tensorflow/addons/pull/2516

**Comment by keshavbhandari** [comment]
Tensorflow addons does not support Tensorflow 2.7.0 now. Colab has updated its TF version to 2.7.0.

**Comment by seanpmorgan** [comment]
> Tensorflow addons does not support Tensorflow 2.7.0 now. Colab has updated its TF version to 2.7.0.

TFA 0.15 was just released.
