### ISSUE TITLE
Performance issue in the definition of test_crf_log_likelihood, tensorflow_addons/text/tests/crf_test.py(P1)

### ISSUE THREAD

**Issue by DLPerf** [tensorflow/addons#2553]
Hello, I found a performance issue in the definition of `test_crf_log_likelihood`, tensorflow_addons/text/tests/crf_test.py, [tf.expand_dims](https://github.com/tensorflow/addons/blob/a69c12a26e129d9fb388114fa65fc3ddac16a977/tensorflow_addons/text/tests/crf_test.py#L313) will be called repeatedly during program execution, resulting in reduced efficiency. I think it should be created before the loop.

The same issues exist in

- [`tf.expand_dims(sequence_lengths, 0)` in line 315](https://github.com/tensorflow/addons/blob/a69c12a26e129d9fb388114fa65fc3ddac16a977/tensorflow_addons/text/tests/crf_test.py#L315);

- [`tf.expand_dims(inputs, 0)` in line 349](https://github.com/tensorflow/addons/blob/a69c12a26e129d9fb388114fa65fc3ddac16a977/tensorflow_addons/text/tests/crf_test.py#L349);
- [`tf.expand_dims(sequence_lengths, 0)` in line 351](https://github.com/tensorflow/addons/blob/a69c12a26e129d9fb388114fa65fc3ddac16a977/tensorflow_addons/text/tests/crf_test.py#L351).

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by DLPerf** [comment]
@eli-osherovich Hi, my friend, could you consider my issue asap?

**Comment by howl-anderson** [comment]
@DLPerf Thank you for your reporting. I will take a closer look on it and I will keep you posted.

**Comment by howl-anderson** [comment]
@bhack @DLPerf Since this issue only affect testing not the CRF function itself and we have some high priority tasks for CRF (critical bugfix #2476 / refactor #2271 / tutorial #2552 / model wrapper #2555) need be done. So, I mark this issue as low priority. But don't worry, this issue is tracked and on my radar.

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
