### ISSUE TITLE
Add Connected Components from zero / one adjacency matrix 

### ISSUE THREAD

**Issue by keotic** [tensorflow/addons#2569]
**Describe the feature and the current behavior/state.**
Add function to extract the Connected Components of an adjacency matrix of an undirected graph. 

API: 
num_components, components_indexes = extreact_connected_components(adjacency matrix)

adjacency matrix: Tensor[batch, num nodes, num nodes]
num_components: Tensor[batch]
components_indexes: Tensor[batch, num nodes] - each node component index

**Relevant information**
- Are you willing to contribute it (yes/no): Don't have enough knowledge 
*If you wish to contribute, then read the requirements for new contributions in [`CONTRIBUTING.md`](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#requirements-for-new-contributions-to-the-repository)*
- Are you willing to maintain it going forward? (yes/no):
- Is there a relevant academic paper? (if so, where):
- Does the relavent academic paper exceed 50 citations? (yes/no):
- Is there already an implementation in another framework? (if so, where):
- Was it part of tf.contrib? (if so, where): No

**Which API type would this fall under (layer, metric, optimizer, etc.)**
Graph?
**Who will benefit with this feature?**
Anyone who works on graph structures 
**Any other info.**
Should be easy to implement via BFS / DFS until all nodes are reached

**Comment by bhack** [comment]
Thank you for the request but probably It Is better If you will try to propose this in:


https://github.com/aimat-lab/gcnn_keras

Or

https://github.com/danielegrattarola/spektral
