### ISSUE TITLE
Fork Keras Layer Test 

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#258]
Per https://github.com/tensorflow/tensorflow/issues/28601 it has been recommended that we fork and expose `keras.layer_test` for this project and others to utilize.

Any thoughts where we should put test utilities? I think for this one it makes sense somewhere under tfa.layers, but we might want the central tfa.utils location for all test utilities?

**Comment by facaiy** [comment]
My initial thought is tfa.utils. What's your opinion, Sean, Tzu-Wei? cc @WindQAQ

**Comment by WindQAQ** [comment]
I would go for tfa.utils.

**Comment by Squadrick** [comment]
Forking the fully functional layer test from keras is quite a challenge. It has calls to other private functions.

**Comment by AakashKumarNain** [comment]
`tfa.utils` lgtm

**Comment by bhack** [comment]
Is this still valid?
