### ISSUE TITLE
tfa.seq2seq: Error in AttentionWrapperState when the Decoder has Stacked RNN cells.

### ISSUE THREAD

**Issue by jeffersonrodriguezc** [tensorflow/addons#2596]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 20
- TensorFlow version and how it was installed (source or binary): Source - 2.6.0
- TensorFlow-Addons version and how it was installed (source or binary): Source - 0.14.0
- Python version: 3.7
- Is GPU used? (yes/no): yes

**Describe the bug**

I want to build a seq2seq model with a Decoder with multiple RNN Cells. I have been following tutorials and they all use only a single layer RNN LSTM. When I try to change just this, it raises an error coming from the **AttentionWrapperState** specifically: 

I changed:

`self.decoder_rnn_cell = tf.keras.layers.LSTMCell(self.dec_units) `

to:

`self.decoder_rnn_cell = tf.keras.layers.StackedRNNCells([tf.keras.layers.LSTMCell(self.dec_units) for _ in range(3)])`

and the error obtained is:

> TypeError: The two structures don't have the same nested structure.
> 
> ...
> 
> Entire first structure:
> AttentionWrapperState(cell_state=([., .], [., .], [., .]), attention=., alignments=., alignment_history=(), attention_state=.)
> Entire second structure:
> AttentionWrapperState(cell_state=[., .], attention=., alignments=., alignment_history=(), attention_state=.)

#### To reproduce the error you can check the classic tutorial on the Tensorflow page, in the Decoder model part, line 16: [Seq2Seq Translation Tutorial](https://colab.research.google.com/github/tensorflow/addons/blob/master/docs/tutorials/networks_seq2seq_nmt.ipynb#scrollTo=yJ_B3mhW3jFk)

_Thank you in advance and I hope you can help me._

**Comment by guillaumekln** [comment]
I think the code expects the encoder and decoder to have the same number of RNN layers (and so the same state structure). You should either use the same number of cells in the encoder, or update the code that initializes the decoder state from the encoder state.

**Comment by jeffersonrodriguezc** [comment]
Thank you very much, you are right.

For the encoder model:
![imagen](https://user-images.githubusercontent.com/18648306/140582502-bc2617ef-7d31-43a9-9e15-cbcd19afa9c3.png)

And for the Decoder states initialization:

![imagen](https://user-images.githubusercontent.com/18648306/140582586-dcf336e5-aeff-4f3a-af43-7b67a3737a9b.png)
