### ISSUE TITLE
Support for macOS Monterey

### ISSUE THREAD

**Issue by yarri-oss** [tensorflow/addons#2616]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Monterey 12.0
- TensorFlow version and how it was installed (source or binary): TF 2.6 binary
- TensorFlow-Addons version and how it was installed (source or binary): TFA v0.15.0
- Python version: 3.8
- Is GPU used? (yes/no): yes - M1

**Describe the bug**

Building from source on macOS Monterey 12.0 causes two issues, one related to the bazel version and the other related to the arch target.

**Code to reproduce the issue**

Use latest Apple recommended [TensorFlow M1 build](https://developer.apple.com/metal/tensorflow-plugin/) and set up, and install TFA to reproduce. 

Submitted [PR#2615](https://github.com/tensorflow/addons/pull/2615) to fix the issue but wonder if this is in conflict with other platforms or x86 Mac systems?

**Comment by bhack** [comment]
TF bazel version update was reverted some a few hours ago again:

https://github.com/tensorflow/tensorflow/commit/1f19aea3230acc158538951f4c510d98df3a99ee

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
