### ISSUE TITLE
module 'tensorflow_addons.optimizers' has no attribute 'MultiOptimizer'

### ISSUE THREAD

**Issue by ninoch** [tensorflow/addons#2622]
I followed the API [documentation](https://www.tensorflow.org/addons/api_docs/python/tfa/optimizers), and I cannot use **MultiOptimizer** optimizer. I'm getting the following error when I try to import it (`tfa.optimizers.MultiOptimizer`): 

`AttributeError: module 'tensorflow_addons.optimizers' has no attribute 'MultiOptimizer'` 

I can import all the other optimizers (`ProximalAdagrad`, `LazyAdam`, `MovingAverage`, ...), but not this one. Is there any versioning that is not mentioned in the doc / Github?

**Comment by bhack** [comment]
What Is you TF and Addons version?

**Comment by ninoch** [comment]
tf is '2.3.2'
tfa is '0.11.2'

**Comment by bhack** [comment]
Can you try with an updated version?

**Comment by seanpmorgan** [comment]
MultiOptimizer was added in TensorFlow Addons v0.12.0. Please update to use this feature. Thanks!
