### ISSUE TITLE
Using tfa.layers.InstanceNormalization()(x) in @tf.function decorated function fails

### ISSUE THREAD

**Issue by flobotics** [tensorflow/addons#263]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): tensorflow-gpu==2.0.0-alpha0 colab
- TensorFlow version (use command below): tensorflow-gpu==2.0.0-alpha0
- TensorFlow Addons installed from (source, PyPi):
- TensorFlow Addons version:
- Python version and type (eg. Anaconda Python, Stock Python as in Mac, or homebrew installed Python etc):
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- Is GPU used? (yes/no):
- GPU model (if used):

**Describe the bug**

When using tensorflow functional API with tfa.layers.InstanceNormalization()(x) in a generator model which is called from inside a @tf.function decorated train function like in DCGAN https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/r2/tutorials/generative/dcgan.ipynb#scrollTo=6bpTcDqoLWjY   then it fails with : 
tf.function-decorated function tried to create variables on non-first call

CODE:
Add tfa.layers.InstanceNormalization()(x) into the code inside this colab notebook https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/r2/tutorials/generative/dcgan.ipynb#scrollTo=6bpTcDqoLWjY to test

**Comment by Smokrow** [comment]
Hey there. 
Thank you for the feedback. I will take a look at this

**Comment by flobotics** [comment]
i wrote the code for the dcgan example:

```
def myfunc(l8):
  l8 = tfa.layers.InstanceNormalization()(l8)
  return l8
```

```
def make_generator_model():
  inputs = tf.keras.Input(shape=(100,))

  l = layers.Dense(7*7*256, use_bias=False)(inputs)
  l1 = layers.BatchNormalization()(l)
  l2 = layers.LeakyReLU()(l1)
  l3 = layers.Reshape((7, 7, 256))(l2)
  l4 = layers.Conv2DTranspose(128, (5, 5), strides=(1, 1), padding='same', use_bias=False)(l3)
  l5 = layers.BatchNormalization()(l4)
  l6 = layers.LeakyReLU()(l5)
  l7 = layers.Conv2DTranspose(64, (5, 5), strides=(2, 2), padding='same', use_bias=False)(l6)
  l8 = layers.BatchNormalization()(l7)
  l8 = myfunc(l8)
  l9 = layers.LeakyReLU()(l8)
  l10 = layers.Conv2DTranspose(1, (5, 5), strides=(2, 2), padding='same', use_bias=False, activation='tanh')(l9)
  return tf.keras.Model(inputs=inputs, outputs=l10)
```

but it works, it gets more than one training epoch done?  But in my code, there is only this tfa.layers.InstanceNormalization()(x) and it fails, if i out-comment this one statement, the code works ?

My code is here (github has now jupyter notebook view support, you can directly watch it there)
https://github.com/flobotics/colab/blob/master/tf2_ganimorph.ipynb

what could cause this?

**Comment by flobotics** [comment]
thats it, if its used as activation function it fails, here is the code for the dcgan example

```
def myfunc(l8):
  l8 = tfa.layers.InstanceNormalization()(l8)
  return l8
```


```
def make_generator_model():
  inputs = tf.keras.Input(shape=(100,))

  l = layers.Dense(7*7*256, use_bias=False)(inputs)
  l1 = layers.BatchNormalization()(l)
  l2 = layers.LeakyReLU()(l1)
  l3 = layers.Reshape((7, 7, 256))(l2)
  l4 = layers.Conv2DTranspose(128, (5, 5), strides=(1, 1), padding='same', use_bias=False)(l3)
  l5 = layers.BatchNormalization()(l4)
  l6 = layers.LeakyReLU()(l5)
  l7 = layers.Conv2DTranspose(64, (5, 5), strides=(2, 2), padding='same', use_bias=False, activation=myfunc)(l6)
  l8 = layers.BatchNormalization()(l7)
  l9 = layers.LeakyReLU()(l8)
  l10 = layers.Conv2DTranspose(1, (5, 5), strides=(2, 2), padding='same', use_bias=False, activation='tanh')(l9)
  return tf.keras.Model(inputs=inputs, outputs=l10)
```

thats the error output:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-26-3bfe38106dd7> in <module>()
----> 1 get_ipython().run_cell_magic('time', '', 'train(train_dataset, EPOCHS)')

31 frames
</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-60> in time(self, line, cell, local_ns)

<timed eval> in <module>()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in invalid_creator_scope(*unused_args, **unused_kwds)
    373       """Disables variable creation."""
    374       raise ValueError(
--> 375           "tf.function-decorated function tried to create "
    376           "variables on non-first call.")
    377 

ValueError: tf.function-decorated function tried to create variables on non-first call.
```

**Comment by facaiy** [comment]
@Smokrow Any update, Moritz? Or could anyone provide a minimal example, so we both can reproduce it and look into the issue :-) Thank you.

**Comment by flobotics** [comment]
hi @facaiy , 
code to reproduce is here: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/r2/tutorials/generative/dcgan.ipynb#scrollTo=6bpTcDqoLWjY


you just need to replace the def make_generator_model(): as in the above posting is described

**Comment by Smokrow** [comment]
Sorry for the late reply. I had quite a busy week :grimacing: 

Looks like this is a problem with the state of the layer. tf.function throws an error when a function inside the decorator tries to create new state after the second call.  the whole thing is discussed here:
https://github.com/tensorflow/community/blob/master/rfcs/20180918-functions-not-sessions-20.md#functions-that-create-state

@seanpmorgan @facaiy do you guys know how to handle this problem with keras layers? Are there any guidelines?

**Comment by flobotics** [comment]
is it such a bíg error ? What is e.g. tf.keras.layers.ReLU()(x) doing what tfa.layers.InstanceNormalization()(x) does not?

**Comment by seanpmorgan** [comment]
Hi @flobotics sorry for the delay in looking into this. So I think there might be some confusion. `tfa.layers.InstanceNormalization()` is a normalization method meant to improve training, which is quite different than a ReLU layer which is an activation layer that enables non-linear mappings.

In your example it would make sense to replace BatchNormalization with InstanceNormalization which have the same desired goal. I did not run into an issue when running your DCGAN example with instance norm:
https://colab.research.google.com/drive/1SECuoh7q4Zy9nHkEOq_U3tiuNfMw_PtC

There is a [WIP PR](https://app.reviewnb.com/tensorflow/addons/pull/144/) that'll provide more information but in short you can see the difference in normalization methods from this image:
![image](https://user-images.githubusercontent.com/18154355/58843876-775c1e00-8642-11e9-8d5e-6b43d7a54bcf.png)
Source: (https://arxiv.org/pdf/1803.08494.pdf)

And here you can see the activation layer mappings:
![image](https://user-images.githubusercontent.com/18154355/58844013-3adcf200-8643-11e9-91d2-ac90fe1cc51f.png)

**Comment by seanpmorgan** [comment]
Eh, sorry so I read through your report a little closer and it looks like you're trying to create a custom activation function and feed it as a parameter to Conv2DTranspose? I'm not sure I'm following why your activation function would include a normalization step and I believe they should be two separate layers?

**Comment by flobotics** [comment]
@seanpmorgan  yeah, if i use the layers separate instead as in a activation function it works. dumb that i didnt thought about that, thanks alot

**Comment by seanpmorgan** [comment]
@flobotics Anytime! The error you ran into is what @Smokrow was describing, but I didn't think you needed to run into that stateful tf.function problem... glad you're up and running.
