### ISSUE TITLE
MacOS Arm64 support for stable TF-Addons Releases

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#2631]
Previously, we've added support for M1 ARM64 wheels and added them to our nightly publishing:
https://github.com/tensorflow/addons/pull/2559

We've excluded this from the stable releases since we're gaited on the release of tensorflow-macos, and we didn't want this to slow down our release process with an unknown SLA:
https://github.com/tensorflow/addons/pull/2600

We've received word of a 1 week SLA for the publishing of tensorflow-macos so going forward with TFA 0.16 we will be gaiting our release in order to include macos wheels as part of our stable release.

**Comment by poinwater** [comment]
Hi, I want to ask a few questions about the mac arm support.
1. What is SLA and why you need to get it for supporting tensorflow-macos?
2. Is getting SLA a requirement for supporting m1 platform?
2. Will the TFA 0.16 release support tensorflow 2.5.0 - 2.7.0 on mac Arm64? It seems like the new release is against tensorflow 2.8.0. 

If you could answer my questions, I really appreciate it.

**Comment by seanpmorgan** [comment]
https://pypi.org/project/tensorflow-addons/0.16.1/#files

**Comment by seanpmorgan** [comment]
> Hi, I want to ask a few questions about the mac arm support.
> 
> 1. What is SLA and why you need to get it for supporting tensorflow-macos?
> 2. Is getting SLA a requirement for supporting m1 platform?
> 3. Will the TFA 0.16 release support tensorflow 2.5.0 - 2.7.0 on mac Arm64? It seems like the new release is against tensorflow 2.8.0.
> 
> If you could answer my questions, I really appreciate it.

1. Service level agreement, it means they will aim to release tensorflow-macos 1 week after tf releases.
