### ISSUE TITLE
Fix backport bot

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#2632]
Currently, our backport bot is broken. Need to do some investigation to see what the issue is. Help wanted, and ping @gabrieldemarmiesse to see if he can take a look. The error from this PR seemed like there was an issue with git on the bot runner:
https://github.com/tensorflow/addons/pull/2355

**Comment by gabrieldemarmiesse** [comment]
Sup Sean!, I wonder if the bot token is expired. I'll take a look :)
