### ISSUE TITLE
MultiOptimizer: Could not interpret optimizer identifier

### ISSUE THREAD

**Issue by deathrc** [tensorflow/addons#2643]
**System information**
- OS Platform and Distribution: Ubuntu 20.04
- TensorFlow version and how it was installed (source or binary): tensorflow-gpu via conda
- TensorFlow-Addons version and how it was installed (source or binary): via conda
- Python version:3.6.5
- Is GPU used? (yes/no): yes

**Describe the bug**
When I tried to use finetune from a existing model, set different learning rate for layers using tfa.optimizers.MultiOptimizer. The original code calls tensorflow.python.keras.* instead of tensorflow.keras to build model, multioptimizer seems not to be recognized. 

**Code to reproduce the issue**
minimum code modified from the [document](https://www.tensorflow.org/addons/api_docs/python/tfa/optimizers/MultiOptimizer)

```
from tensorflow.python import keras
import os
import tensorflow_addons as tfa
from tensorflow.python.keras.optimizer_v2.adam import Adam
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

model = keras.Sequential([
    keras.Input(shape=(4,)),
    keras.layers.Dense(8),
    keras.layers.Dense(16),
    keras.layers.Dense(32),
])

optimizers = [
    Adam(learning_rate=1e-4),
    Adam(learning_rate=1e-2)
]

optimizers_and_layers = [(optimizers[0], model.layers[0]), (optimizers[1], model.layers[1:])]
optimizer = tfa.optimizers.MultiOptimizer(optimizers_and_layers)
model.compile(optimizer=optimizer, loss="mse")
```

**Other info / logs**

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-ef28c1686b35> in <module>
      1 optimizers_and_layers = [(optimizers[0], model.layers[0]), (optimizers[1], model.layers[1:])]
      2 optimizer = tfa.optimizers.MultiOptimizer(optimizers_and_layers)
----> 3 model.compile(optimizer=optimizer, loss="mse")

~/anaconda3/envs/magenta-gpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in compile(self, optimizer, loss, metrics, loss_weights, weighted_metrics, run_eagerly, steps_per_execution, **kwargs)
    571       self._run_eagerly = run_eagerly
    572 
--> 573       self.optimizer = self._get_optimizer(optimizer)
    574       self.compiled_loss = compile_utils.LossesContainer(
    575           loss, loss_weights, output_names=self.output_names)

~/anaconda3/envs/magenta-gpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in _get_optimizer(self, optimizer)
    609       return opt
    610 
--> 611     return nest.map_structure(_get_single_optimizer, optimizer)
    612 
    613   @trackable.no_automatic_dependency_tracking

~/anaconda3/envs/magenta-gpu/lib/python3.6/site-packages/tensorflow/python/util/nest.py in map_structure(func, *structure, **kwargs)
    867 
    868   return pack_sequence_as(
--> 869       structure[0], [func(*x) for x in entries],
    870       expand_composites=expand_composites)
    871 

~/anaconda3/envs/magenta-gpu/lib/python3.6/site-packages/tensorflow/python/util/nest.py in <listcomp>(.0)
    867 
    868   return pack_sequence_as(
--> 869       structure[0], [func(*x) for x in entries],
    870       expand_composites=expand_composites)
    871 

~/anaconda3/envs/magenta-gpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in _get_single_optimizer(opt)
    600 
    601     def _get_single_optimizer(opt):
--> 602       opt = optimizers.get(opt)
    603       if (loss_scale is not None and
    604           not isinstance(opt, lso.LossScaleOptimizer)):

~/anaconda3/envs/magenta-gpu/lib/python3.6/site-packages/tensorflow/python/keras/optimizers.py in get(identifier)
    130   else:
    131     raise ValueError(
--> 132         'Could not interpret optimizer identifier: {}'.format(identifier))

ValueError: Could not interpret optimizer identifier: Multi Optimizer with 2 optimizer layer pairs

**Comment by bhack** [comment]
I cannot reproduce this on colab using `from tensorflow.keras.optimizers import Adam`
