### ISSUE TITLE
Cannot install tensorflow-addons with python 3.10

### ISSUE THREAD

**Issue by guillaumelorre28** [tensorflow/addons#2647]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow version and how it was installed (source or binary): pip install
- TensorFlow-Addons version and how it was installed (source or binary):
- Python version: 3.10
- Is GPU used? (yes/no):

**Describe the bug**
Tensorflow-addons cannot be installed with python 3.10.

**Code to reproduce the issue**

```
conda create -n tf python=3.10
conda activate tf
pip install tensorflow
pip install tensorflow-addons
```

**Other info / logs**

The installation of tensorflow works fine but not the installation of tensorflow-addons.
It gives the following error:
```
ERROR: Could not find a version that satisfies the requirement tensorflow-addons (from versions: none)
ERROR: No matching distribution found for tensorflow-addons
```

**Comment by bhack** [comment]
https://discuss.tensorflow.org/t/support-python-3-10/

**Comment by christian-steinmeyer** [comment]
With Tensorflow 2.8 released, python 3.10 now is supported on that end

**Comment by reyhashemi** [comment]
I have the exact same issue on Ubuntu 20.04.4 LTS

**Comment by TimotheeWright** [comment]
He's there a way to install tensorflow with conda using python 3.10 ?
