### ISSUE TITLE
Support Tensorflow 2.8 (and python 3.10)

### ISSUE THREAD

**Issue by christian-steinmeyer** [tensorflow/addons#2660]
**Describe the feature and the current behavior/state.**
In a virtual environment with python 3.10 and tensorflow 2.8.0 installed, running `pip install tensorflow-addons` yields:
```bash
ERROR: Could not find a version that satisfies the requirement tensorflow-addons (from versions: none)
ERROR: No matching distribution found for tensorflow-addons
```
**Relevant information**
- Tensorflow 2.8 [was released yesterday](https://github.com/tensorflow/tensorflow/releases/tag/v2.8.0)

**Who will benefit with this feature?**
all users that want to use python 3.10

**Comment by bhack** [comment]
The PR is WIP https://github.com/tensorflow/addons/pull/2635

**Comment by christian-steinmeyer** [comment]
Nice! Thanks! Searched for a couple of terms in the issues, but didn't come across this PR.
