### ISSUE TITLE
Fix Sklearn and Skimage Testing Dependencies

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#2666]
The build for TF2.8 and specifically python 3.10 requires us to increment the version of sklearn and skimage.  Unfortunately this causes conflicts with the lowest version of NumPy we need to support for our TensorFlow compatibility matrix. 

As each TF release occurs, we should check to see if we can return the 5 tests that were skipped as part of:
https://github.com/tensorflow/addons/pull/2635

Alternatively it would be nice to remove these testing dependencies all together if possible.

**Comment by bhack** [comment]
Please check https://github.com/tensorflow/addons/pull/2671#issuecomment-1041002480

**Comment by bhack** [comment]
I think that it is safe starting from TF 2.7 so with our next TFA release (TF 2.7, 2.8, 2.9) https://github.com/tensorflow/tensorflow/issues/50204#issuecomment-1007075682
We don't have any issue now with the TF 2.6 API surface that we are testing with our tests here but it is not totally safe.

If you want you close this as generally we are to merging too much features between one release and another one to be at risk to expand our TF API surface before the next release.
