### ISSUE TITLE
No module named 'keras' when importing tensorflow-addons

### ISSUE THREAD

**Issue by albert239825** [tensorflow/addons#2679]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows
- TensorFlow version and how it was installed (source or binary): installed with conda
- TensorFlow-Addons version and how it was installed (source or binary): pip installed
- Python version: 3.9.7
- Is GPU used? (yes/no): yes

**Describe the bug**

When I tried to import tensorflow-addons after installing with pip, I got an error saying that the keras module was not found. I'm using tensorflow version 2.6.0 and tensorflow-addons 0.16.1 so they should be compatible. It should be noted that I installed tensorflow with conda and tfa with pip although they are in the same virtual environment. I resolved this error by installing keras seperately with conda install keras, however, I do not believe this is the expected behavior. Thank you so much!

Sorry if this issue is not formatted well. I'm a high school just getting into machine learning. Much thanks!

**Code to reproduce the issue**

import tensorflow-addons

**Other info / logs**

Full error message:
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_2752/3041976499.py in <module>
      9 from tensorflow.keras.layers import Activation
     10 from tensorflow.keras.layers import Concatenate
---> 11 from tensorflow_addons.layers import InstanceNormalization
     12 
     13 # define the discriminator model

~\miniconda3\envs\tf_gpu\lib\site-packages\tensorflow_addons\__init__.py in <module>
     19 
     20 # Local project imports
---> 21 from tensorflow_addons import activations
     22 from tensorflow_addons import callbacks
     23 from tensorflow_addons import image

~\miniconda3\envs\tf_gpu\lib\site-packages\tensorflow_addons\activations\__init__.py in <module>
     15 """Additional activation functions."""
     16 
---> 17 from tensorflow_addons.activations.gelu import gelu
     18 from tensorflow_addons.activations.hardshrink import hardshrink
     19 from tensorflow_addons.activations.lisht import lisht

~\miniconda3\envs\tf_gpu\lib\site-packages\tensorflow_addons\activations\gelu.py in <module>
     17 import warnings
     18 
---> 19 from tensorflow_addons.utils.types import TensorLike
     20 
     21 

~\miniconda3\envs\tf_gpu\lib\site-packages\tensorflow_addons\utils\types.py in <module>
     22 # TODO: Remove once https://github.com/tensorflow/tensorflow/issues/44613 is resolved
     23 if tf.__version__[:3] > "2.5":
---> 24     from keras.engine import keras_tensor
     25 else:
     26     from tensorflow.python.keras.engine import keras_tensor

ModuleNotFoundError: No module named 'keras'

conda list:
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                       mkl
abseil-cpp                20210324.2           hd77b12b_0
absl-py                   0.15.0             pyhd3eb1b0_0
aiohttp                   3.8.1            py39h2bbff1b_0
aiosignal                 1.2.0              pyhd3eb1b0_0
astor                     0.8.1            py39haa95532_0
astunparse                1.6.3                      py_0
async-timeout             4.0.1              pyhd3eb1b0_0
attrs                     21.4.0             pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
blas                      1.0                         mkl
blinker                   1.4              py39haa95532_0
bottleneck                1.3.2            py39h7cc1a96_1
brotli                    1.0.9                ha925a31_2
brotlipy                  0.7.0           py39h2bbff1b_1003
ca-certificates           2021.10.26           haa95532_4
cachetools                4.2.2              pyhd3eb1b0_0
certifi                   2021.10.8        py39haa95532_2
cffi                      1.15.0           py39h2bbff1b_1
charset-normalizer        2.0.4              pyhd3eb1b0_0
clang                     5.0                      pypi_0    pypi
click                     8.0.3              pyhd3eb1b0_0
colorama                  0.4.4              pyhd3eb1b0_0
cryptography              36.0.0           py39h21b164f_0
cycler                    0.11.0             pyhd3eb1b0_0
dataclasses               0.8                pyh6d0b6a4_7
debugpy                   1.5.1            py39hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
entrypoints               0.3              py39haa95532_0
flatbuffers               1.12                     pypi_0    pypi
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.10.4               hd328e21_0
frozenlist                1.2.0            py39h2bbff1b_0
gast                      0.4.0              pyhd3eb1b0_0
giflib                    5.2.1                h62dcd97_0
google-auth               1.33.0             pyhd3eb1b0_0
google-auth-oauthlib      0.4.1                      py_2
google-pasta              0.2.0              pyhd3eb1b0_0
grpcio                    1.42.0           py39hc60d5dd_0
h5py                      3.6.0            py39h3de5c98_0
hdf5                      1.10.6               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       68.1                 h6c2663c_0
idna                      3.3                pyhd3eb1b0_0
importlib-metadata        4.8.2            py39haa95532_0
intel-openmp              2021.4.0          haa95532_3556
ipykernel                 6.6.0            py39h832f523_0    conda-forge
ipython                   7.31.1           py39haa95532_0
jedi                      0.18.1           py39haa95532_1
joblib                    1.1.0              pyhd3eb1b0_0
jpeg                      9d                   h2bbff1b_0
jupyter_client            7.1.2              pyhd3eb1b0_0
jupyter_core              4.9.1            py39haa95532_0
kaggle                    1.5.12             pyhd8ed1ab_4    conda-forge
keras                     2.6.0              pyhd3eb1b0_0
keras-preprocessing       1.1.2              pyhd3eb1b0_0
kiwisolver                1.3.2            py39hd77b12b_0
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.80.0               h86230a5_0
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.14.0               h23ce68f_0
libssh2                   1.9.0                h7a1dbc1_1
libtiff                   4.2.0                hd0e1b90_0
libwebp                   1.2.0                h2bbff1b_0
lz4-c                     1.9.3                h2bbff1b_1
markdown                  3.3.4            py39haa95532_0
matplotlib                3.5.1            py39haa95532_0
matplotlib-base           3.5.1            py39hd77b12b_0
matplotlib-inline         0.1.2              pyhd3eb1b0_2
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py39h2bbff1b_0
mkl_fft                   1.3.1            py39h277e83a_0
mkl_random                1.2.2            py39hf11a4ad_0
multidict                 5.1.0            py39h2bbff1b_2
munkres                   1.1.4                      py_0
nest-asyncio              1.5.1              pyhd3eb1b0_0
numexpr                   2.8.1            py39hb80d3ca_0
numpy                     1.21.5           py39ha4e8547_0
numpy-base                1.21.5           py39hc2deb75_0
oauthlib                  3.1.0                      py_0
olefile                   0.46               pyhd3eb1b0_0
openssl                   1.1.1m               h2bbff1b_0
opt_einsum                3.3.0              pyhd3eb1b0_1
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.4.1            py39hd77b12b_0
parso                     0.8.3              pyhd3eb1b0_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.4.0            py39hd45dc43_0
pip                       21.2.4           py39haa95532_0
prompt-toolkit            3.0.20             pyhd3eb1b0_0
protobuf                  3.14.0           py39hd77b12b_1
pyasn1                    0.4.8              pyhd3eb1b0_0
pyasn1-modules            0.2.8                      py_0
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.11.2             pyhd3eb1b0_0
pyjwt                     2.3.0              pyhd8ed1ab_1    conda-forge
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.4              pyhd3eb1b0_0
pyqt                      5.12.3           py39hcbf5309_8    conda-forge
pyqt-impl                 5.12.3           py39h415ef7b_8    conda-forge
pyqt5-sip                 4.19.18          py39h415ef7b_8    conda-forge
pyqtchart                 5.12             py39h415ef7b_8    conda-forge
pyqtwebengine             5.12.1           py39h415ef7b_8    conda-forge
pyreadline                2.1              py39haa95532_1
pysocks                   1.7.1            py39haa95532_0
python                    3.9.7                h6244533_1
python-dateutil           2.8.2              pyhd3eb1b0_0
python-flatbuffers        1.12               pyhd3eb1b0_0
python-slugify            5.0.2              pyhd3eb1b0_0
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd3eb1b0_0
pywin32                   302              py39h827c3e9_1
pyzmq                     22.3.0           py39hd77b12b_2
qt                        5.12.9               h5909a2a_4    conda-forge
requests                  2.27.1             pyhd3eb1b0_0
requests-oauthlib         1.3.0                      py_0
rsa                       4.7.2              pyhd3eb1b0_1
scikit-learn              1.0.2            py39hf11a4ad_1
scipy                     1.7.3            py39h0a974cb_0
seaborn                   0.11.2             pyhd3eb1b0_0
setuptools                58.0.4           py39haa95532_0
sip                       4.19.13          py39hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
snappy                    1.1.8                h33f27b4_0
sqlite                    3.37.2               h2bbff1b_0
tensorboard               2.6.0                      py_1
tensorboard-data-server   0.6.0            py39haa95532_0
tensorboard-plugin-wit    1.6.0                      py_0
tensorflow                2.6.0           mkl_py39h31650da_0
tensorflow-addons         0.16.1                   pypi_0    pypi
tensorflow-base           2.6.0           mkl_py39h9201259_0
tensorflow-estimator      2.6.0              pyh7b7c402_0
termcolor                 1.1.0            py39haa95532_1
text-unidecode            1.3                pyhd3eb1b0_0
threadpoolctl             2.2.0              pyh0d69192_0
tk                        8.6.11               h2bbff1b_0
tornado                   6.1              py39h2bbff1b_0
tqdm                      4.62.3             pyhd3eb1b0_1
traitlets                 5.1.1              pyhd3eb1b0_0
typeguard                 2.13.3                   pypi_0    pypi
typing-extensions         3.10.0.2             hd3eb1b0_0
typing_extensions         3.10.0.2           pyh06a4308_0
tzdata                    2021e                hda174b7_0
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   1.26.8             pyhd3eb1b0_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5              pyhd3eb1b0_0
werkzeug                  2.0.2              pyhd3eb1b0_0
wheel                     0.35.1             pyhd3eb1b0_0
win_inet_pton             1.1.0            py39haa95532_0
wincertstore              0.2              py39haa95532_2
wrapt                     1.13.3           py39h2bbff1b_2
xz                        5.2.5                h62dcd97_0
yarl                      1.6.3            py39h2bbff1b_0
zipp                      3.7.0              pyhd3eb1b0_0
zlib                      1.2.11               h8cc25b3_4
zstd                      1.4.9                h19a0ad4_0

**Comment by bhack** [comment]
> Based on tflow-addons requirements.txt and setup.py there shouldn't be and dependency on keras so maybe its a broken import statement.

Keras dependency is derived from TF dependency.

**Comment by cleebp** [comment]
I see that keras is bundled in tf now but I don't think that allows you to `from keras import...` you still need `from tf.keras...` right?

**Comment by cleebp** [comment]
I'm trying to find a way to patch [this line in the utils/types.py](https://github.com/tensorflow/addons/blob/18c8367945cca3897281f4c2eb6e8bf2fccf2d48/tensorflow_addons/utils/types.py#L24) to see if `from tf.keras.engine...` fixes this issue to match the other keras imports around tflow_addons, I'll update this comment if that fixes anything.
