### ISSUE TITLE
tensorflow-addons-0.6.0

### ISSUE THREAD

**Issue by long123524** [tensorflow/addons#2685]
**Describe the feature and the current behavior/state.**

**Relevant information**
- Are you willing to contribute it (yes/no):
*If you wish to contribute, then read the requirements for new contributions in [`CONTRIBUTING.md`](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#requirements-for-new-contributions-to-the-repository)*
- Are you willing to maintain it going forward? (yes/no):
- Is there a relevant academic paper? (if so, where):
- Does the relavent academic paper exceed 50 citations? (yes/no):
- Is there already an implementation in another framework? (if so, where):
- Was it part of tf.contrib? (if so, where):

**Which API type would this fall under (layer, metric, optimizer, etc.)**

**Who will benefit with this feature?**

**Any other info.**
How to install tensorflow-addons-0.6.0? I use pip failed to install tensorflow-addons-0.6.0.

**Comment by seanpmorgan** [comment]
Try updating pip first as 0.6.0 used manylinux2010 packaging:
```
pip install --upgrade pip
pip install tensorflow-addons==0.6.0
```
