### ISSUE TITLE
MovingAverage optimizer fails in graph mode

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#269]
Per today's failing nightly: 
`ValueError: Inconsistent values for attr 'Tin' [DT_FLOAT, DT_FLOAT] vs. [DT_RESOURCE, DT_FLOAT] while building NodeDef 'cond_dense/kernel/ExponentialMovingAverage' using Op<name=If; signature=cond:Tcond, input: -> output:; attr=Tcond:type; attr=Tin:list(type),min=0; attr=Tout:list(type),min=0; attr=then_branch:func; attr=else_branch:func; attr=output_shapes:list(shape),default=[]; is_stateful=true>`

A commit on tensorflow core has made it so that there is a mismatch in attr for variables being created in the ema and what is being passed in. My best guess on the commit is https://github.com/tensorflow/tensorflow/commit/d1ce3b1791b8447ceeea2d12fa60598701d80b9d though our current test setup makes it quite difficult to locate the specific commit.

**Comment by Squadrick** [comment]
@facaiy If you want I can take a look at this. I authored `MovingAverage` optimizer.

**Comment by seanpmorgan** [comment]
Hmmm tests against 2.0.0.dev20190604-cp27-cp27mu-manylinux1 are passing. Looks like it's been fixed on TF core. If anyone is able to find the commit I'd be interested.
