### ISSUE TITLE
 Character-level seq2seq model for translation and beam search.

### ISSUE THREAD

**Issue by VallabhMahajan1** [tensorflow/addons#2713]
I was trying to implement seq2seq translation model at **character level** along with beam search by referring the tensorflow documentation. 
[https://www.tensorflow.org/addons/tutorials/networks_seq2seq_nmt](url)

For this,  I tried to change parameter, 'char_level = True' in tf.keras tokenizer, but it didn't worked.

Can someone please help me to solve this issue.

Thank you in advance

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
