### ISSUE TITLE
Request for Python 3.10 Support for Arm64

### ISSUE THREAD

**Issue by iseong83** [tensorflow/addons#2715]
`tensorflow-macos` now support Python3.10 for arm64, so could you please help us to add Python 3.10 support for tensorflow-addons for arm64?

**Comment by sun1638650145** [comment]
I have a tutorial [here](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon) that you can build yourself, but you can also download it directly from the [releases](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/releases/download/v2.9/tensorflow_addons-0.17.0-cp310-cp310-macosx_11_0_arm64.whl). I hope to help you. 😊

**Comment by iseong83** [comment]
Thank you for your reply. This is great!  If you are okay, could you add this release to PyPi so that we can install it using `pip`?

**Comment by sun1638650145** [comment]
First, I'm glad to help you. At the same time, I'm also trying to build the `M1` package of `io` and `decision_forests` recently. If it helps you, welcome your star and fork. As for submitting `pip` I'm sorry, because it's not my repo so I can't do this.

**Comment by iseong83** [comment]
Gotcha. Thank you for helping with this. It is very useful. Since we are moving forward to Python 3.10, it would be very helpful if we can get official support.

**Comment by seanpmorgan** [comment]
TFA 0.17.1 released with support for py3.10 on macos arm64

**Comment by iseong83** [comment]
> TFA 0.17.1 released with support for py3.10 on macos arm64

@seanpmorgan That's great news! Thank you for updating this!
