### ISSUE TITLE
Where would I get the flow parameter to feed into dense_image_warp? 

### ISSUE THREAD

**Issue by Anton-Velikodnyy** [tensorflow/addons#274]
Not sure how to utilize Dense warp flow operation. 
I know there is a Dual_TVL1 function in cv, but is there something similar in tensorflow that I can utilize? 

Thank you @WindQAQ

**Comment by WindQAQ** [comment]
Hi, the short answer is no. There is no function that could generate optical flow between two frames like DUAL_TVL1 at least in addons. But I think you could generate flows with other packages (e.g. opencv) and feed them into `dense_image_warp`. That will also work fine. It's also welcome to contribute such functionality to addons! Thank you for asking.

**Comment by Anton-Velikodnyy** [comment]
Maybe my lack of familiarity with optical flow. Then what would be the input to the flow parameter of the dense_warp_flow function? Or is it output from cv.Dual_TVL1, cv.calcOpticalFlowPyrLK, calcOpticalFlowFarneback. if so which of these is best to use? also I would just be throwing this into a py_function.

Also found this, side note:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/jni/object_tracking/optical_flow.cc

**Comment by WindQAQ** [comment]
Hmm, I'm not familiar with optical flow either... But the `flow` argument for `dense_image_warp` is a vector field indicating the direction that each pixel should follow. I should have some time to make an example for this after the importing issue is fixed... Maybe that could help you and the community understand how to use it.

**Comment by WindQAQ** [comment]
Close this because we already had https://github.com/tensorflow/addons/blob/master/examples/image_ops.ipynb.

**Comment by Anton-Velikodnyy** [comment]
@WindQAQ I haven't look at a way to implement optical flow yet in tensorflow. However, the opencv method you mentioned uses cpu causing a some delay in time. I noticed there is a GPU implementation lurking, however that conflicts with tensorflow. Would definitely be a useful operation to have given its usage in video processing for activities.
