### ISSUE TITLE
Create mapping of all tf.contrib ports

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#275]
Per a request in this month's monthly meeting. If we can help put together a document of all tf.contrib functions/classes that were moved to addons then the tensorflow core team will have the converter script point to the addons equivalents. Ideally we can have this done by the end of the week.

I've started a public google sheet here:
https://docs.google.com/spreadsheets/d/1a22wKHcmt7Ad6BW8tFjX76qlovEsyF5WSje8tPwli6A/edit?usp=sharing

cc @karmel @tomerk

**Comment by seanpmorgan** [comment]
@tomerk is the spreadsheet above sufficient? After trying to detail the exact parameter changes I think I lean toward this being not a great idea if you're trying to refactor code in the upgrade script. A lot of these had to substantially change their inputs to fit the keras style etc.

IMO it's probably best to just point them to the counterpart in addons but not automatically replace the parameters

**Comment by tomerk** [comment]
I see. Okay, we can make the conversion script just output specific warnings saying which add-ons symbol they map to.

@dynamicwebpaige any thoughts?

**Comment by seanpmorgan** [comment]
@tomerk Closing this issue, but happy to re-open it if you have any additional requests from us. We'd love to see these pointers in the conversion scripts so please let us know anyway we can help.

**Comment by seanpmorgan** [comment]
For tracking it looks like this was added:
https://github.com/tensorflow/tensorflow/commit/adf9b3de1d4bdc71c28b9e5eed1efa9811ea2c27#diff-9f2f769bb59fddf61e604ff7ac1b1918
