### ISSUE TITLE
CUDA 11.7 support

### ISSUE THREAD

**Issue by ghylander** [tensorflow/addons#2758]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow version and how it was installed (source or binary): 2.9.1-binary
- TensorFlow-Addons version and how it was installed (source or binary): 0.17.1-binary
- Python version: 3.8
- Is GPU used? (yes/no): yes

Currantly, simply importing tfa in a script on a system with CUDA 11.7 will result at some point in a seg fault. Even without calling any funcion or object.
What would need to be done to add support for CUDA 11.7?

**Comment by bhack** [comment]
I think that we have only tested it with this compatibility matrix:

https://github.com/tensorflow/addons#c-custom-op-compatibility-matrix


Can you try with one of these?

**Comment by seanpmorgan** [comment]
Per compatibility matrix, you'll need to compile from source in order to run GPU custom op with CUDA 11.7
