### ISSUE TITLE
import tensorflow_addons as tfa fails with tensorflow-gpu==2.0.0-beta0

### ISSUE THREAD

**Issue by flobotics** [tensorflow/addons#277]
**System information**
- TensorFlow installed from (source or binary): colab
- TensorFlow version (use command below): !pip install tensorflow-gpu==2.0.0-beta0
- TensorFlow Addons installed from (source, PyPi): colab
- TensorFlow Addons version:!pip install tensorflow-addons

- Is GPU used? (yes/no):yes
- GPU model (if used): colab

**Describe the bug**

when i run the following code , it crashes

**Code to reproduce the issue** -- in colab

from __future__ import absolute_import, division, print_function, unicode_literals
!pip install tensorflow-gpu==2.0.0-beta0
!pip install tensorflow-addons
import tensorflow_addons as tfa

```
`---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-4-8e92e93ce06e> in <module>()
----> 1 import tensorflow_addons as tfa

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/load_library.py in load_op_library(library_filename)
     59     RuntimeError: when unable to load the library or get the python wrappers.
     60   """
---> 61   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     62 
     63   op_list_str = py_tf.TF_GetOpList(lib_handle)

NotFoundError: libtensorflow_framework.so: cannot open shared object file: No such file or directory`
```

**Comment by seanpmorgan** [comment]
Thanks for tracking this @flobotics! We're waiting for this issue and a few others to get patched:
https://github.com/tensorflow/tensorflow/issues/29540

We were told there should be a beta1 release in the next few days. Once that happens we'll quickly release a 0.4 which should be compatible with tf2-beta (and most likely the nightlies as well)

**Comment by flobotics** [comment]
ok, thx

**Comment by seanpmorgan** [comment]
We can leave this open until it's fixed. Other's may have the same question :grin:

**Comment by flobotics** [comment]
ok

**Comment by developeralgo8888** [comment]
i have the same issue

**Comment by flobotics** [comment]
just info, tensorflow-gpu==2.0.0-beta1 is available

**Comment by seanpmorgan** [comment]
Verison 0.4 built against tf2-beta is now released!

https://github.com/tensorflow/addons/releases/tag/v0.4.0
https://pypi.org/project/tensorflow-addons/0.4.0/#files
