### ISSUE TITLE
Avoid using lambda functions as default values for class __init__

### ISSUE THREAD

**Issue by pbk0** [tensorflow/addons#2773]
**Describe the bug**

Please avoid have default values as lambda function. They cause issues with serialization and pickling.
Also theses instances cannot be used with asyncio.
Note that the tensorflow classes do not have this issues and they can safely used with asyncio.

Instead of using lambda as defaults have them as global functions.

**Code to reproduce the issue**

Please check the code [here](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/optimizers/cyclical_learning_rate.py)
Line 238 and Line 312 

The `scale_fn` is lambda function. Can you please define them as global function. Defining it like this creates local functions and thus breaks serialization.

**Comment by bhack** [comment]
Can you contribute a failing serialization test PR for your case?

We have already other serialization tests in the repo.

**Comment by pbk0** [comment]
I am closing this issue. The problem is on my side. I was caching some non serializable items from `tfa` in my wrapper class.
