### ISSUE TITLE
Find centers of connected components 

### ISSUE THREAD

**Issue by PasaImage** [tensorflow/addons#2778]
If I had tensor image I can use tfa.image.connected_components(image) to find components but how can I find centers of each components ?

I suggest a function like OpenCV function connectedcomponentswithstats

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
