### ISSUE TITLE
TF 2.11 support release?

### ISSUE THREAD

**Issue by apivovarov** [tensorflow/addons#2788]
Hello, I just want to check when it is planned to release the next version which supports TF 2.11
@chenmoneygithub

**Comment by bhack** [comment]
https://github.com/tensorflow/addons/pull/2782#issuecomment-1339920517

**Comment by pbk0** [comment]
Yes me too

**Comment by apivovarov** [comment]
Python Op Compatibility Matrix shows tensorflow-addons-0.19.0 . However this tag (0.19.0) still does not exist.
TensorFlow Addons | TensorFlow | Python
-- | -- | --
tfa-nightly | 2.9, 2.10, 2.11 | 3.7, 3.8, 3.9, 3.10
tensorflow-addons-0.19.0 | 2.9, 2.10, 2.11 | 3.7, 3.8, 3.9, 3.10
