### ISSUE TITLE
Move python3 CI testing to python3.6

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#279]
Recently there has not been any [py34 tf2-nightlies published](https://pypi.org/project/tf-nightly-2.0-preview/#files). I've asked SIG-Build if this is a permanent change seeing as py34 is EOL, but regardless I think it's wise to move our CI testing to python3.6

Can this be easily done? @karmel @av8ramit

**Comment by seanpmorgan** [comment]
As a discussion topic: should we stop supporting python3.4 now that it's EOL?

**Comment by kyleabeauchamp** [comment]
I agree with deprecating 34.

**Comment by av8ramit** [comment]
If the official agreement is to do this with Python3.6 we can look into this. I'll let @karmel make the final decision.

**Comment by seanpmorgan** [comment]
**Update:**
It has been confirmed as a bug and tf2-nightlies for py34 have started being published again. They did mention that tf-core will indeed remove py34 support in the future -- so I think addons should just align with tensorflow core in doing this. For now this issue can be closed but we'll need to re-open this in the future it seems.

**Comment by seanpmorgan** [comment]
Re-opening this issue. We need to adjust our docker scripts to install py36 and test with that as py34 is no longer being published
