### ISSUE TITLE
Rename tag 0.19.0 to v0.19.0

### ISSUE THREAD

**Issue by apivovarov** [tensorflow/addons#2791]
In order to be consistent with tag naming convention in this project can you rename tag 0.19.0 to v0.19.0 ?
@seanpmorgan @bhack 
[List of tags](https://github.com/tensorflow/addons/tags)

**Comment by bhack** [comment]
Done

**Comment by apivovarov** [comment]
I think "[TensorFlow Addons v0.19.0](https://github.com/tensorflow/addons/releases/tag/v0.19.0)" should also be added to the list of releases https://github.com/tensorflow/addons/releases/ @bhack

**Comment by bhack** [comment]
> I think "[TensorFlow Addons v0.19.0](https://github.com/tensorflow/addons/releases/tag/v0.19.0)" should also be added to the list of releases https://github.com/tensorflow/addons/releases/ @bhack 

@seanpmorgan Can you trigger the action?
