### ISSUE TITLE
Contrast Enhancement Methods

### ISSUE THREAD

**Issue by parth-p** [tensorflow/addons#281]
**System information**
- TensorFlow version: 2.0 
- TensorFlow Addons version: 0.3
- Is it in the tf.contrib:  Not present untill now
- Are you willing to contribute it: Yes
- Are you willing to maintain it going forward?: Yes

**Describe the feature and the current behavior/state.**
I am proposing to add histogram equalization and adaptive histogram equalization methods. 

**Who will benefit with this feature?**
This improves contrast in images and spreads the frequent intensities.

Here is the colab link of the implementation and results: https://colab.research.google.com/drive/1s3Tv-NE12-a6H4x3sfFomgiVAqB4Nkek

**Comment by WindQAQ** [comment]
Hi Parth, thanks for the contribution! I have some thoughts on this:

1. Could you compare the result and the speed of your approach with existing framework (e.g. opencv)?
2. I think these lines
```python
for i in range(rows):
    for j in range(cols):
        final[i, j] = sk[int(image[i, j])]
```
can be replaced with
```python
final = tf.nn.embedding_lookup(sk, image)
```
With native tensor operation, it could speed up a lot. Still need more tests though.
https://colab.research.google.com/drive/1gjflcAigXXhUbMzXWkFAvi4niOJyDPkQ

**Comment by seanpmorgan** [comment]
> 1. Could you compare the result and the speed of your approach with existing framework (e.g. opencv)?

Great suggestion for benchmarking. Though we do need to consider how it works in practice as a tf.dataset (opencv would require numpy arrays instead of tensors... I would think that slows it down in a pyfunc?)

**Comment by WindQAQ** [comment]
> Great suggestion for benchmarking. Though we do need to consider how it works in practice as a tf.dataset (opencv would require numpy arrays instead of tensors... I would think that slows it down in a pyfunc?)

Yes, it might be slower for pyfunc. Just want to clarify if while and for loops hurt the performance a lot though...

**Comment by parth-p** [comment]
Following are the results that I observed :
For histogram equalization: 
![pic1](https://user-images.githubusercontent.com/28673760/59459879-7b0a5480-8e3b-11e9-87f5-60b5ec10eeba.png)

For Adaptive histogram equalization: 
![pic2](https://user-images.githubusercontent.com/28673760/59459926-8bbaca80-8e3b-11e9-9488-e5c482b2ff4b.png)

**Comment by WindQAQ** [comment]
@parth-p Parth, seems that adaptive histogram equalization renders different results. Is it possible to make them the same?

**Comment by Squadrick** [comment]
@parth-p Any update on this?

**Comment by parth-p** [comment]
@Squadrick @WindQAQ, the adaptive histogram equalization method is not correct. I am currently working on its correct implementation. Sorry for not mentioning it here earlier.

**Comment by bhack** [comment]
We have contrast and autocontrast in https://github.com/tanzhenyu/image_augmentation /cc @tanzhenyu
