### ISSUE TITLE
Suggestions for tfa.text features

### ISSUE THREAD

**Issue by shreyashub** [tensorflow/addons#282]
Hi all,
If anyone has any suggestions for what can be added in TF Addons - Text, please feel free to share them here.
I am rather new to NLP but seeing as TF Text is also a rather new library, I'm hoping there are various basic modules/ features that can be added and in which others and I can contribute.
@seanpmorgan  @facaiy If you have any ideas and/or suggestions please do share.

**Comment by Squadrick** [comment]
How are we planning on accepting contributions to tfa.text now that [tensorflow/text](https://github.com/tensorflow/text) is a thing?

**Comment by Squadrick** [comment]
We could accept contributions to tfa.text and graduate highly used and tested modules to tensorflow/text.

**Comment by seanpmorgan** [comment]
> We could accept contributions to tfa.text and graduate highly used and tested modules to tensorflow/text.

So my first thought was this because the barrier to entry for someone willing to maintain code in addons is lower than tensorflow/text (I assume but maybe incorrectly). Certainly worth a discussion though thanks for bringing this up! 

cc @ewilderj @dynamicwebpaige @karmel for thoughts

**Comment by karmel** [comment]
CC @edloper for thoughts.

**Comment by Squadrick** [comment]
@edloper @karmel Any update on this?

**Comment by edloper** [comment]
If any modules within tfa.text become highly used and well-tested, we'd be happy to talk about graduating them into tensorflow/text.

**Comment by seanpmorgan** [comment]
Closing this issue as we've set up a possible path from tensorflow/addons to tensorflow/text for the right submodules.

As far as suggestions of what to add to tfa.text I would generally prefer it happen a little more organically (i.e. we'll add them as requests come in). Apologies I don't work heavily with NLP so nothing jumps off the top of my head.
