### ISSUE TITLE
Python 3.11

### ISSUE THREAD

**Issue by Danguilhen** [tensorflow/addons#2822]
Is it possible to release this package for Python 3.11 ?

I want to update my package and tensorflow-addons is a dependancy :)

Thank you

**Comment by bhack** [comment]
Check https://github.com/tensorflow/addons/pull/2821

**Comment by christian-steinmeyer** [comment]
In #2821, it was mentioned, that tensorflow-macos 2.12 didn't seem to include a python 3.11 release. While accurate at the time, this seems to have been addressed in the meantime (see [files on pypi](https://pypi.org/project/tensorflow-macos/2.12.0/#files)). Currently, on macos and python 3.11, I cannot `pip install tensorflow-macos tensorflow-addons`. Does that mean that the ball is again in the court of tensorflow-addons?

**Comment by seanpmorgan** [comment]
> In #2821, it was mentioned, that tensorflow-macos 2.12 didn't seem to include a python 3.11 release. While accurate at the time, this seems to have been addressed in the meantime (see [files on pypi](https://pypi.org/project/tensorflow-macos/2.12.0/#files)). Currently, on macos and python 3.11, I cannot `pip install tensorflow-macos tensorflow-addons`. Does that mean that the ball is again in the court of tensorflow-addons?

TFA 0.21 has py3.11 for macos arm64
