### ISSUE TITLE
Create a TensorFlow Addons Release to work with TF Nightly

### ISSUE THREAD

**Issue by sampathweb** [tensorflow/addons#2831]
Please create a TF Addons Release that includes #2829 so it works with TF Nightly and fixes https://github.com/keras-team/keras/issues/17986

**Comment by sampathweb** [comment]
@bhack

**Comment by seanpmorgan** [comment]
Nightly builds are built for the latest stable release of TF and we make no guarantees of compatibility with tf-nightly (We used to and it burned a ton of time for bugs out of our control):
https://github.com/tensorflow/addons#nightly-builds

We do publish on commit though so #2829 should have fixed this:
https://pypi.org/project/tfa-nightly/0.20.0.dev20230418095337/
