### ISSUE TITLE
`tfa.optimizers.MovingAverage` & `tfa.optimizers.SWA` future

### ISSUE THREAD

**Issue by aaarrti** [tensorflow/addons#2844]
Hi, 

The average optimizer wrappers support only `tf.keras.optimizers.legacy` optimizers. Since TFA was deprecated, I doubt there will be not development work here to support the new APIs. Are there any plans to support average optimizers in https://github.com/keras-team/keras-core ? Is there any replacement compatible with newer Keras optimizers?

**Comment by bhack** [comment]
I suggest to open this ticket in Keras or Keras-core repo as feature request.
