### ISSUE TITLE
`tfa.image.rotate` and `tfa.image.gaussian_filter2d` 

### ISSUE THREAD

**Issue by felixT2K** [tensorflow/addons#2845]
Hi 👋🏼 ,

Since TFA has been deprecated, I wanted to ask if there is an equivalent implementation (functional) in Tensorflow or Keras ?

Thanks in advance

**Comment by bhack** [comment]
You have only the random rotation but not the rotation itself:
https://keras.io/api/layers/preprocessing_layers/image_augmentation/random_rotation/

Also in TF you have 90 degree rotation:
https://www.tensorflow.org/api_docs/python/tf/image/rot90

For gaussian filter your have:
https://keras.io/api/keras_cv/layers/augmentation/random_sharpness/
Or:
https://www.tensorflow.org/io/api_docs/python/tfio/experimental/filter/gaussian

**Comment by felixT2K** [comment]
Thannks @bhack 👍🏼
