### ISSUE TITLE
Python 3.12 wheels on PyPI?

### ISSUE THREAD

**Issue by ecederstrand** [tensorflow/addons#2868]
I was trying to install tensorflow-addons on Python 3.12 but there are no suitable wheels on PyPI and no source package so I can do a local compile: https://pypi.org/project/tensorflow-addons/#files

Whould it be possible for you to upload Python 3.12 wheels to PyPI?

**Comment by bhack** [comment]
The only opportunity we have is finalizing https://github.com/tensorflow/addons/pull/2866

Then the project will be wind down https://github.com/tensorflow/addons/issues/2807
