### ISSUE TITLE
Beam search decoder _check_static_batch_beam_maybe check correct?

### ISSUE THREAD

**Issue by sjmielke** [tensorflow/addons#289]
**System information**
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0=alpha
- TensorFlow Addons installed from (source, PyPi): PyPi
- TensorFlow Addons version: 0.3.1
- Python version and type (eg. Anaconda Python, Stock Python as in Mac, or homebrew installed Python etc): Google Colab Python
- Is GPU used? (yes/no): yes
- GPU model (if used): T4

The check in beam_search_decoder.py#L183 seems faulty. As a MWE, consider:
```
tfa.seq2seq.beam_search_decoder._check_static_batch_beam_maybe(tf.TensorShape([3, 5, None]), 3, 5)
```
which yields:
```
TensorArray reordering expects elements to be reshapable to (3, 5, None) which is incompatible with the current shape (3, 5, None).
```

Either this error message is misleading or the check is faulty. Sadly, since I do not quite understand what it is supposed to be checking, I cannot propose a solution (other than to remove the last condition).

**Comment by Squadrick** [comment]
cc: @qlzh727

**Comment by guillaumekln** [comment]
I'm the original author of this function as part of https://github.com/tensorflow/tensorflow/commit/838a8f54f92452a15e3bb62a23ad5cd67e86933f and indeed the check is incorrect.

The check is simply: when the batch size and beam size are known statically, the leading dimensions should either be [batch_size*beam_size, ...] or [batch_size, beam_size, ...]. There is probably a cleaner way to do this.

**Comment by sjmielke** [comment]
Alright, cool! I'll try to submit a PR to fix make it do just that one of these days then :)

**Comment by qlzh727** [comment]
Ack, I can reproduce the error. @sjmielke feel free to send a PR, or you can assign to me if don't have time to fix it.
