### ISSUE TITLE
installation issues with tensorflow==2.0.0-beta1

### ISSUE THREAD

**Issue by fnauman** [tensorflow/addons#296]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): PyPi (pip install tensorflow==2.0.0-beta1)
- TensorFlow version (use command below): tensorflow==2.0.0-beta1
- TensorFlow Addons installed from (source, PyPi): pip install tensorflow-addons
- TensorFlow Addons version: 0.4.0
- Python version and type (eg. Anaconda Python, Stock Python as in Mac, or homebrew installed Python etc): Anaconda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- Is GPU used? (yes/no): no
- GPU model (if used):

**Describe the bug**

I am getting the error:
" ERROR: Could not find a version that satisfies the requirement tensorflow-addons (from versions: none)
ERROR: No matching distribution found for tensorflow-addons
"
when I try to install tensorflow-addons after installing tensorflow==2.00-beta1 (both through PyPi). Tensorflow is working fine in my new conda environment. I also tried 
`pip install tensorflow-addons==0.4.0` with the same error.

**Describe the expected behavior**

Installation should work!

**Comment by WindQAQ** [comment]
Hi @fnauman, could you provide your python version? Seems that it works fine on colab.
https://colab.research.google.com/drive/1wQ5iPG3FlvQF8b6DPQwbkOIu8veVroJv

**Comment by facaiy** [comment]
one more question, do you use any mirror site for pip?

Can you run `pip install tensorflow-addons==`? It will list all available versions, for example:

```bash
pip install tensorflow-addons==      
                                                                       
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting tensorflow-addons==
  Could not find a version that satisfies the requirement tensorflow-addons== (from versions: 0.3.1, 0.4.0)
No matching distribution found for tensorflow-addons==

```

**Comment by fnauman** [comment]
Ahh sorry. I had not paid attention to the fact that python 3.7 is not supported. 

I just created a fresh conda environment with python==3.6. Then did:
`pip install tensorflow==2.0.0-beta1`
`pip install tensorflow-addons==0.4.0`

and tensorflow-addons installed and is now importing fine. 

When I tried: 
`pip install tensorflow-addons==?`

it returned this output:

> ERROR: Could not find a version that satisfies the requirement tensorflow-addons==? (from versions: 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.3.1, 0.4.0)
> ERROR: No matching distribution found for tensorflow-addons==?

but like I said above with `tensorflow-addons==0.4.0`, the installation seemed to work fine.

Thanks for the help!

**Comment by seanpmorgan** [comment]
> Ahh sorry. I had not paid attention to the fact that python 3.7 is not supported.
> 
> I just created a fresh conda environment with python==3.6. Then did:
> `pip install tensorflow==2.0.0-beta1`
> `pip install tensorflow-addons==0.4.0`
> 
> and tensorflow-addons installed and is now importing fine.
> 
> When I tried:
> `pip install tensorflow-addons==`
> 
> it returned this output:
> 
> > ERROR: Could not find a version that satisfies the requirement tensorflow-addons== (from versions: 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.3.1, 0.4.0)
> > ERROR: No matching distribution found for tensorflow-addons==
> 
> but like I said above with `tensorflow-addons==0.4.0`, the installation seemed to work fine.
> 
> Thanks for the help!

Sorry about that... we're working to get python3.7 supported ASAP: #75 . Once we get a compatible build environment we do not expect to lag behind python releases again.

**Comment by fisakhan** [comment]
Complete solution can be found here
https://stackoverflow.com/questions/59102460/install-tensorflow-addons/60724821#60724821
