### ISSUE TITLE
Convert? - Any interest in single_image_random_dot_stereograms

### ISSUE THREAD

**Issue by Mazecreator** [tensorflow/addons#301]
Hi,

I am the original Author of the **single_image_random_dot_stereograms** "contrib" in TensorFlow 1.X.  Is there any interests to move this image technology into the AddOn's?  I know there are a few users out there but understand it isn't an imperative to keep in TensorFlow.  Great way to view 3D without hidden lines (like the older waterfall plots).

"Single Image Random Dot Stereogram for Tensorflow

SIRDS is a means to present 3D data in a 2D image. It allows for scientific data display of a waterfall type of plot with no hidden lines due to perspective. Data is encoded to show data in the Z direction as depth.

This project is based upon: http://www.learningace.com/doc/4331582/b6ab058d1e206d68ab60e4e1ead2fe6e/sirds-paper
"

You can see a demo of what it can do here:

https://github.com/Mazecreator/TensorFlow-SIRDS/blob/master/single_image_random_dot_stereograms/SIRDS%20Demo.ipynb

If there is interest, I wouldn't mind spending some time trying to convert it for a future AddOn's release.

**Comment by WindQAQ** [comment]
Hi @Mazecreator, thanks for asking here! Could you update the url of http://www.learningace.com/doc/4331582/b6ab058d1e206d68ab60e4e1ead2fe6e/sirds-paper.
I could not access it.

**Comment by Mazecreator** [comment]
I will see if there is another copy of that paper, that link does seem to be dead now...

I found one:
https://www.cs.waikato.ac.nz/~ihw/papers/94-HWT-SI-IHW-SIRDS-paper.pdf

**Comment by WindQAQ** [comment]
cc @seanpmorgan

**Comment by seanpmorgan** [comment]
Hi @Mazecreator apologies for the slow response. So we looked at the [tf.contrib usage](https://tf-contrib-analyzer.herokuapp.com/) and unfortunately we didn't see a lot of use. In the interest of keeping our code base manageable I think we'll have to reject this unless there is an outreach from the community saying they're missing it.

Very sorry -- it's no fun turning down contributions.... but I hope you stick around and join the Addons community! FWIW the code looked solid.

**Comment by Mazecreator** [comment]
Understood, no problem.  It is a bit of a corner case for 3D data.
