### ISSUE TITLE
PEP8 or Google TF spacing?

### ISSUE THREAD

**Issue by mels630** [tensorflow/addons#307]
STYLE_GUIDE.md states that Python code for addons should be PEP8-compliant, but also points here: https://www.tensorflow.org/community/contribute/code_style#tensorflow_conventions_and_special_uses for TF conventions. Further up this page there's a discussion of pylint and Google's tf pylintrc, which deviates from PEP8 in preferring two spaces instead of PEP8's four.

Sorry if I've missed prior discussion; to me it seems that the desired format for addons is strictly PEP8 but I wonder if this should be made even more explicit in the docs (I spent some time reading up higher in the TF code style document and began trying to pylint before running into lots of whitespace warnings given that it is apparently a deviation from Tensorflow proper.

**Comment by seanpmorgan** [comment]
Hi Matt, yeah Addons is stylized with PEP8 and the link to tensorflow style is meant to refer to the conventions within tensorflow. Would be happy to review a PR which clarifies this.
