### ISSUE TITLE
Implement OneCycleLR callback

### ISSUE THREAD

**Issue by Squadrick** [tensorflow/addons#317]
Creating a separate issue for the discussion [here](https://github.com/tensorflow/addons/issues/61#issuecomment-479585706)

@Gokkulnath If you're still interested, you can open a PR.

**Comment by joaogui1** [comment]
Hi, can I try to implement this?

**Comment by Squadrick** [comment]
@joaogui1 Definitely, looking forward to the PR.

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
