### ISSUE TITLE
Request for example: CRF

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#337]
This is pending #22 and #314 but once it's merged we should be sure to add some examples as it's highly requested.

**Comment by howl-anderson** [comment]
I can do this job when #314 is ready.

**Comment by NLP-ZY** [comment]
@seanpmorgan I find some example in 1.x. I try to use crf as a tf.keras.layers.Layer or tf.keras.Model. However, crf need y_true to get viterbi_sequence in 
 this example. Can you give some better example like use crf as a Layer or Model ?
[https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/contrib/crf/README.md](url)

**Comment by howl-anderson** [comment]
Hi @NLP-ZY , If you are looking for CRF keras layer for TF 2.x, this PR  #377  is nearly done for this purpose, if you want the same keras layer in tf 1.15, there is a project ([tf_crf_layer](https://github.com/howl-anderson/tf_crf_layer)) for it.

**Comment by NLP-ZY** [comment]
@howl-anderson OK, thanks!

**Comment by seanpmorgan** [comment]
Bumping this as a highly requested feature for our new layer

**Comment by Harsh188** [comment]
Hey @seanpmorgan 

I'd love to help out! I read through the long history of #22 #314 #377 #1733 and #1999. I'm familiarizing myself with `layers/crf.py`. If I'm not mistaken the objective is to build examples and develop user-friendly documentation for `crf.py`?

**Comment by bhack** [comment]
@Harsh188 yes

**Comment by Harsh188** [comment]
Great! I'm gonna get started on that as soon as I can. I've noticed that It's not listed in the documentation how do I enable that? @bhack

**Comment by seanpmorgan** [comment]
> Great! I'm gonna get started on that as soon as I can. I've noticed that It's not listed in the documentation how do I enable that? @bhack

Hi @Harsh188 apologies for misunderstanding, what is not listed in the documentation?

**Comment by Harsh188** [comment]
@seanpmorgan Ignore that message. Can you assign this issue to me? I've started to work on it.

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
