### ISSUE TITLE
euclidean_distance_transform_op.cc build falied on GPU

### ISSUE THREAD

**Issue by facaiy** [tensorflow/addons#349]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nightly-gpu-2.0-preview
- TensorFlow Addons installed from (source, PyPi): source
- TensorFlow Addons version: master
- Python version and type (eg. Anaconda Python, Stock Python as in Mac, or homebrew installed Python etc): tensorflow/tensorflow:custom-op-gpu
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):
- Is GPU used? (yes/no): yes
- GPU model (if used):

**Describe the bug**

When I'm working in https://github.com/tensorflow/addons/pull/294, ` tensorflow_addons/custom_ops/image/cc/kernels/euclidean_distance_transform_op.cc` won't compile with gpu successfully. So I disable its gpu kernel registration temporality, and hope it will be fixed later.

**Describe the expected behavior**

**Code to reproduce the issue**

**Other info / logs**

**Comment by facaiy** [comment]
cc @mels630 maintainer of the submodule :-)

**Comment by Squadrick** [comment]
@mels630 @facaiy I'll take a look at this.

**Comment by mels630** [comment]
thanks @Squadrick -- i haven't been able to get my GPU environment up and running yet :/
