### ISSUE TITLE
the crf not find in the pypi version of 0.4.0

### ISSUE THREAD

**Issue by gjxcq** [tensorflow/addons#359]
in the crf branch,I can see the crf api in tfa.text,but when I pip install tensorflow-addons, I can't find it, the crf in where, how can I use it?

**Comment by seanpmorgan** [comment]
CRF is currently in review #314. There's been a little delay in reviewing it -- but it'll be in the 0.5.0 release most likely.

If you have experience using CRF we'd appreciate help in the review process
