### ISSUE TITLE
[Suggest]I would like to suggest code that I have implemented.

### ISSUE THREAD

**Issue by DevKiHyun** [tensorflow/addons#366]
There is a custom layer that will benefit people. It is the method proposed by 'Deep Complex Network' and I have already implemented it. What should I do to propose to TFA?

**Comment by seanpmorgan** [comment]
Hi @DevKiHyun! Welcome. Do you mind linking to the paper and your implementation?

**Comment by seanpmorgan** [comment]
Closing for now. Please feel free to re-open and change the title once you have more information
