### ISSUE TITLE
Re-name all C++ Ops to include package name

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#379]
Per new RFC:
https://github.com/tensorflow/community/pull/126

**Comment by seanpmorgan** [comment]
Just copying a note I made in the RFC:
This is currently blocked as `>` is an invalid character in an Op Name at the moment

**Comment by WindQAQ** [comment]
A minor thing related to package name is the ifndef/define in header files. We have to unify this macro too.

https://github.com/tensorflow/addons/blob/master/tensorflow_addons/custom_ops/image/cc/kernels/adjust_hsv_in_yiq_op.h#L14
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/custom_ops/image/cc/kernels/image_projective_transform_op.h#L16
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/custom_ops/layers/cc/kernels/correlation_cost_op.h#L16
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/custom_ops/seq2seq/cc/kernels/beam_search_ops.h#L16

**Comment by karmel** [comment]
I believe this should be unblocked from the TF side now: https://github.com/tensorflow/tensorflow/commit/3bda03617967d3ff3c9af0e96c8a66b2bdad6ffc

**Comment by karmel** [comment]
(CC @ewilderj , FYI)

**Comment by tomerk** [comment]
I'm putting together a pr to do this.

**Comment by tomerk** [comment]
I just put together a PR. I had to make some changes to TF as part of this because there were still bugs in the TF RC1 w/ namespaces in op names, so this does not work w/ RC1. It works w/ the TF 2.0 nightly & should work w/ the upcoming RC2.

**Comment by facaiy** [comment]
Closed as it's fixed by #516
