### ISSUE TITLE
TensorFlow API breaks management

### ISSUE THREAD

**Issue by arita37** [tensorflow/addons#386]
Hello,
TensorFlow APi breaks happens a lot , making contribution hard to maintain.

Is it posssible that Google engineer develops some API check breaker tools,
who is parsing by AST the current code and check with existing TF version... ?

One major hurdle of TF is the API breaks... (besides static graph)

**Comment by seanpmorgan** [comment]
Hi! 

This repository is not for the core tensorflow framework and so there's nothing that can really be done here. I disagree though, TensorFlow has been extremely structured in their API forward/backwards compatibility guarantees.

If you have specific examples I would recommend you raise an issue at the core repository:
https://github.com/tensorflow/tensorflow/

**Comment by arita37** [comment]
There are regular API changes in TF.
Is it possible to generate at each release
the signatures list of all classes/ method/functions into a text format ?

So we can compare existing code with new release.

Now, API break changes is pretty manual
for millions of people...

**Comment by seanpmorgan** [comment]
For example this?
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/compatibility/all_renames_v2.py

There are script to run these API changes between 1.x and 2.x:
https://www.tensorflow.org/beta/guide/upgrade

If you're talking about within TF 1.x versions please provide an example because there is very little API breakage (if any in recent releases).

**Comment by arita37** [comment]
Hello,

Your 1st file looks good.
But, this is not only function but argument names, all signatures changes that is
User friendly to use ?
(Mapping table , function name, class name ,
argument name...)


Checking manually the new API compatibility at each version, this is very time consuming.

Is it possible that Google Team generate this full mapping table at each release ?
Even for Google team, this is very useful.
