### ISSUE TITLE
Wrong example in docstring - cohens_kappa.py

### ISSUE THREAD

**Issue by PhilipMay** [tensorflow/addons#397]
In this example:
https://github.com/tensorflow/addons/blob/dab18121fa4253cf05320d41962bfbf1803e1f1b/tensorflow_addons/metrics/cohens_kappa.py#L46

The string `"quadratic"` is passed to `update_state`. This is wrong because it is passed to `tf.math.confusion_matrix` which does not accept a string as `weights` parameter. See here:  https://www.tensorflow.org/api_docs/python/tf/math/confusion_matrix

**Comment by WindQAQ** [comment]
cc @SSaishruthi @Squadrick
