### ISSUE TITLE
What is "graduate candidate" for TF Core?

### ISSUE THREAD

**Issue by Fatty-Ricky** [tensorflow/addons#413]
Sorry to disturb. I'm new here.
I just heard about TF Addons from [official blog](https://medium.com/tensorflow/introducing-tensorflow-addons-6131a50a3dcf). It says maintainers need "Manage graduate candidates for TensorFlow Core". What does it mean? Is there a boot camp or course for TF so that they can graduate?

**Comment by seanpmorgan** [comment]
Hi @Fatty-Ricky! This is a good question and an aspect of addons that we haven't gotten to yet. As part of our monthly action items we have the following todo:

1. Start an issue for candidate ops to move from addons to core (SIG)

Essentially if an op is extremely useful and has been vetted in addons it should eventually end up in core TensorFlow. To make that distinction though we likely need to wait for a few months after TF2 release for more use data. Related to https://github.com/tensorflow/addons/issues/236

**Comment by seanpmorgan** [comment]
Examples off the top of my head may be `tfa.losses.focal_loss` and `tfa.image.rotate`
