### ISSUE TITLE
tfa.text.crf_log_likelihood is not compatible with tf2.0-beta1

### ISSUE THREAD

**Issue by xuxingya** [tensorflow/addons#414]
When implement CRF with tf2.0-beta1, got `AttributeError: module 'tensorflow' has no attribute 'get_variable'` when using tfa.text.crf_log_likelihood.
`AttributeError: in converted code:
    relative to /home/xingya:

    resume_parser/resume_parser/training/train_ner_bp.py:329 train_step  *
        log_likelihood, _ = tfa.text.crf_log_likelihood(
    .conda/envs/tf2/lib/python3.6/site-packages/tensorflow_addons/text/crf.py:191 crf_log_likelihood  *
        transition_params = tf.get_variable("transitions",
    .conda/envs/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py:329 converted_call
        f = getattr(owner, f)

    AttributeError: module 'tensorflow' has no attribute 'get_variable'` 
Accordding to the example in the [official migration_guide](https://www.tensorflow.org/beta/guide/migration_guide), It should be tf.Variable.

**Comment by seanpmorgan** [comment]
Thanks for reporting @xuxingya! Yeah `get_variable` is v1 behavior. Would you like to submit a bug fix PR?
