### ISSUE TITLE
CuDNN is failing to load in newly updated custom-op image

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#418]
Since ~ yesterday we're seeing fails on our GPU tests that say 
```
Failed to get convolution algorithm. This is probably because cuDNN failed to initialize
```

A simple reproducible test is:
```
import numpy as np
import tensorflow as tf

data = np.random.random((2, 4, 4, 3))
layer = tf.keras.layers.Conv2D(5, (2,2), input_shape=(4,4,3))
print(layer(data))
```

I checked and it's not because of any change to the nightly TF package (today's version still works on an older docker image). The only change to the docker images was https://github.com/YINZHI-keji/tensorflow/commit/5f81522c88c38b897e4313c28bf6e6cc7cc1456e but my hunch is that the base docker image was updated between when custom-op-gpu was originally pushed and today. Perhaps they updated the cudnn version? It's currently 7.5 but I deleted my old image so I can't check if that's what it was before.

cc @yifeif @av8ramit

**Comment by yifeif** [comment]
Indeed sounds like an cudnn version issue. I don't see the base image being updated recently though https://hub.docker.com/r/nvidia/cuda/tags?page=3

**Comment by kyleabeauchamp** [comment]
Will look a bit from my GPU desktop when I get home.

**Comment by seanpmorgan** [comment]
> Indeed sounds like an cudnn version issue. I don't see the base image being updated recently though https://hub.docker.com/r/nvidia/cuda/tags?page=3

Hmmm looks like `10.0-cudnn7-devel-ubuntu16.04` was updated 14 days ago and I think the `custom-op-gpu-ubuntu16.04` was published 15 days ago? Certainly makes it less likely but I think it's possible?

> Will look a bit from my GPU desktop when I get home.

Thanks! Just to be clear I should have mentioned this is for `custom-op-gpu-ubuntu16.04` I tested this morning on my older docker image of it and everything worked. Then I cleared my image and re-pulled it after last nights build and it failed.

**Comment by seanpmorgan** [comment]
Quickly pulled the `nightly-gpu-py3` image and it also fails on tf 1.15. Temporarily could install the correct cudnn in the Dockerfile (needs to be tested). We should also raise an issue on tf-core to figure out why that cudnn is failing

**Comment by seanpmorgan** [comment]
I tried matching cudnn as v7.6  using `apt-get install libcudnn7=7.6.2.24-1+cuda10.0 --allow-change-held-packages`

But this breaks our build since there is no `cudnn.h` in `usr/include` anymore. Curious as to why the pip package was moved up to cudnn 7.6? Was that for cuda10.1?

**Comment by seanpmorgan** [comment]
@yifeif @av8ramit Would it be possible to trigger another build & push that docker image up? Looks like the new `nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04` has cudnn 7.6 installed correctly

**Comment by yifeif** [comment]
I just updated `custom-op-gpu-ubuntu16`, could you give it another try?

**Comment by seanpmorgan** [comment]
Tests are now passing.. thank you!
