### ISSUE TITLE
WeightNormalization data init fails with Keras experimental_run_tf_function

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#428]
Recent Keras change has made it so the data dependent initialization fails:
```
_SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'sequential_1/weight_normalization/mul:0'
```
I'm submitting a hotfix which flags the model compile with `experimental_run_tf_function=False`. Another issue I'm tracking is https://github.com/tensorflow/probability/issues/519 to see how TFP resolves their issue.

**Comment by WindQAQ** [comment]
This is related to https://github.com/tensorflow/addons/pull/219. If switching back to `.assign()`, then it works. However, it won't converge.

**Comment by facaiy** [comment]
Hi, is it still a problem? I think I have some time to look into it.

**Comment by WindQAQ** [comment]
@facaiy Hi, it's still a problem. It would be great that you could take over it!

**Comment by facaiy** [comment]
OK, Tzu-Wei, I'll take a try
