### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by richriley** [tensorflow/addons#432]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 9 (stretch)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nightly-gpu-2-0-preview 2.0.0.dev20190820
- TensorFlow Addons installed from (source, PyPi): PyPi
- TensorFlow Addons version: tfa-nightly 0.5.0.dev20190624
- Python version and type (eg. Anaconda Python, Stock Python as in Mac, or homebrew installed Python etc): Anaconda Python 3.6.2
- Is GPU used? (yes/no): yes
- GPU model (if used): Tesla V100

**Describe the bug**

Segmentation fault when using tfa.image.transform_ops.rotate

**Describe the expected behavior**
No segmentation fault

**Code to reproduce the issue**
```
import tensorflow as tf
import tensorflow_addons as tfa
import math

IMAGE_SIZE_INCEPTION_V3 = [299, 299]
IMAGE_CHANNELS = 3

def parse_preprocessed_image(image_size):
    def parse_preprocessed_image_at_size(serialised_tensor):
        result = tf.io.parse_tensor(serialised_tensor, out_type=tf.float32)
        result = tf.reshape(result, [*image_size, IMAGE_CHANNELS])
        return result

    return parse_preprocessed_image_at_size

images_dataset = tf.data.TFRecordDataset(['image.jpeg']) \
        .map(parse_preprocessed_image(IMAGE_SIZE_INCEPTION_V3)) \
        .map(lambda image: tfa.image.transform_ops.rotate(image, tf.random.uniform([], minval=-math.pi / 3, maxval=math.pi / 3)))
```
[output.log](https://github.com/tensorflow/addons/files/3520774/output.log)

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by WindQAQ** [comment]
Hi @richriley, would you mind providing `image.jpeg`?

**Comment by richriley** [comment]
It will fail with any image. I've just realised that this example doesn't actually make sense. In my real code the image.jpeg is a .tfrec file (hence the parse_preprocessed_image_at_size function parsing a tensor) but I tried to make it simpler for this example. I'm not able to provide the tfrec files as they are too large. Sorry if this makes it difficult to debug.

**Comment by seanpmorgan** [comment]
Could you try updating the `tfa-nightly` version **tfa-nightly 0.5.0.dev20190624** is manylinux1 compiled and **tf-nightly-gpu-2-0-preview 2.0.0.dev201908** is manylinux2010

**Comment by richriley** [comment]
@seanpmorgan I seem to get the same segmentation error with tfa-nightly 0.5.0.dev20190624

**Comment by seanpmorgan** [comment]
Hmmm yeah can you try to install the latest https://pypi.org/project/tfa-nightly/#files. It should be **tfa-nightly 0.5.0.dev20190815**

It requires pip version >19.0 `pip install --upgrade pip`, but that's strange because you should have needed to do that for the TF nightly: https://pypi.org/project/tf-nightly-gpu-2.0-preview/2.0.0.dev20190820/#files

**Comment by richriley** [comment]
Now I get:

```
 import tensorflow_addons as tfa
  File "/home/richard_riley/miniconda3/envs/tensorflow-image-classifier/lib/python3.6/site-packages/tensorflow_addons/__init__.py", line 82, in <module>
    from tensorflow_addons import seq2seq
  File "/home/richard_riley/miniconda3/envs/tensorflow-image-classifier/lib/python3.6/site-packages/tensorflow_addons/seq2seq/__init__.py", line 35, in <module>
    from tensorflow_addons.seq2seq.beam_search_decoder import BeamSearchDecoder
  File "/home/richard_riley/miniconda3/envs/tensorflow-image-classifier/lib/python3.6/site-packages/tensorflow_addons/seq2seq/beam_search_decoder.py", line 35, in <module>
    gather_tree = _beam_search_ops_so.gather_tree
AttributeError: module '5fa89fc3154996733eabb433e18fa62f' has no attribute 'gather_tree'
```

**Comment by seanpmorgan** [comment]
K thanks. Sorry about this we're in a transition on how we're packaging our binaries in preparation for TF2 release. I will look into this and try to get a new binary published later this afternoon.

If this is a blocker for you could you try **tfa-nightly 0.5.0.dev20190624** and **tf-nightly-gpu-2-0-preview 2.0.0.dev20190624**

**Comment by richriley** [comment]
Thanks. Those two nightly versions work as expected. Thanks for the quick solution!

**Comment by WindQAQ** [comment]
Feel free to re-open the issue again if you run into other problems. Thanks!
