### ISSUE TITLE
Image transform runs in CPU rather than GPU

### ISSUE THREAD

**Issue by ruanxt** [tensorflow/addons#443]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0b1
- TensorFlow Addons installed from (source, PyPi): Pypi
- TensorFlow Addons version: 0.4.0
- Python version and type (eg. Anaconda Python, Stock Python as in Mac, or homebrew installed Python etc): system
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- Is GPU used? (yes/no): yes
- GPU model (if used): GTX 1080Ti

The image transform function tfa.image.transform only uses CPU to perform image transform even though a GPU is available, which makes image transforms petty slow in the training. Is there any idea to set up GPU computing for TensorFlow addons? I'll really appreciate it if anyone can help this issue.

**Comment by WindQAQ** [comment]
Hello @ruanxt. It seems that you are using `tensorflow-addons==0.4.0`, in which, we haven't set up GPU kernels. You could try to install from source (master branch) to get the GPU support for `image.transform`.

This commit https://github.com/tensorflow/addons/commit/a7afaa703eb7e62526612867e9b0468dda51344b.

**Comment by ruanxt** [comment]
Thanks very much!! I will try that.
