### ISSUE TITLE
Image transform operation is very slow

### ISSUE THREAD

**Issue by lukaszgrad** [tensorflow/addons#445]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.0.0-rc0
- TensorFlow Addons installed from (source, PyPi): Pypi
- TensorFlow Addons version: 0.5.0.dev20190824
- Python version and type (eg. Anaconda Python, Stock Python as in Mac, or homebrew installed Python etc): Anaconda Python
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- Is GPU used? (yes/no): Yes (not required)
- GPU model (if used): T4

**Describe the bug**

Function tensorflow_addons.image.transform_ops.transform is super slow, when compared to a ad-hoc written function in basic TF, I've obtained almost a 10-fold speedup (on CPU) ...

`@tf.function
def transform_img(images, ops):
    images_channels = tf.shape(images)[-1]
    images_size = tf.shape(images)[1]
    batch_size = tf.shape(images)[0]
    op_matrix = tf.reshape(tf.concat([ops, tf.ones((tf.shape(ops)[0], 1))], axis=1), (batch_size, 3,3))
    batch_ind = tf.range(0, batch_size)
    
    ind = tf.range(0, images_size, dtype=tf.float32) # square images
    ind_x = tf.tile(ind, [images_size])
    ind_y = tf.reshape(tf.tile(tf.expand_dims(ind, 1), [1, images_size]), (-1,))
    indices = tf.stack([ind_y, ind_x, tf.ones_like(ind_x, dtype=tf.float32)], axis=1)
    indices = tf.tile(tf.expand_dims(indices, 0), [batch_size, 1, 1])
    
    indices_trans = tf.matmul(indices, op_matrix, transpose_b=True)[..., :2]
    indices_trans = tf.round(indices_trans)
    indices_trans = tf.cast(indices_trans, tf.int32)
    indices_trans = tf.math.floormod(indices_trans, images_size)

    indices_batch = tf.reshape(tf.tile(tf.reshape(batch_ind, (-1,1)), [1, images_size * images_size]), (-1,1))
    indices_trans = tf.concat([indices_batch, tf.reshape(indices_trans, (-1,2))], axis=1)
    return tf.reshape(tf.gather_nd(images, indices_trans), (batch_size, images_size, images_size, images_channels))`

**Code to reproduce the issue**

Link to colab reproducing the issue:

(https://colab.research.google.com/drive/1JMVU-Y58O49ltk16ZRbDySSMobzUR--m)

**Other info / logs**

Moreover, the above version has a further speedup when using GPU (particularly with larger batch size)

Sadly, I don't have any experience when it comes to custom C++ TF kernels, so probably can't fix it myself.

**Comment by WindQAQ** [comment]
Hi @lukaszgrad, could you make the colab link shareable? Thanks!

**Comment by lukaszgrad** [comment]
Should work now, sorry!

**Comment by WindQAQ** [comment]
Seems that it indeed speeds up a lot on colab with `tfa-nightly`. But when I build from source with `-c opt` flag, two implementations get similar performance (original kernel is a little bit faster in fact on both CPU/GPU).

@seanpmorgan, Sean, what's our compiling flag while build pip package? I see
https://github.com/tensorflow/addons/blob/master/tools/ci_build/builds/release_linux.sh, where we do not include any optimization flag. Please correct me if I'm wrong.

@lukaszgrad would you mind building from source with optimization flag and comparing it with your implementation again? Thanks.

My benchmark, avg over 10 runs:

|          | CPU w/o opt | CPU opt  | GPU w/o opt | GPU opt  |
|----------|-------------|----------|-------------|----------|
| original | 0.922506    | 0.273149 | 0.284497    | 0.234114 |
| yours    | 0.323355    | -        | 0.279174    | -        |

**Comment by lukaszgrad** [comment]
@WindQAQ I'm getting some errors when building from source with bazel:

`ERROR: /home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.0/cc_toolchain_config.bzl:1491:17: name 'CcToolchainConfigInfo' is not defined
ERROR: error loading package 'build_deps/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.0': Extension 'build_deps/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.0/cc_toolchain_config.bzl' has errors
INFO: Elapsed time: 0.142s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: build_deps/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.0`

**Comment by lukaszgrad** [comment]
Thanks for a quick response, any idea about my bazel compilation error? I have cuda-10.0 installed

**Comment by lukaszgrad** [comment]
Another error, and a quick google search gives no answers :-(

ERROR: /home/lukasz/kaggle/kaggle-recursion/tfrec/addons/tensorflow_addons/custom_ops/activations/BUILD:8:1: C++ compilation of rule '//tensorflow_addons/custom_ops/activations:gelu_op_gpu' failed (Exit 1)
gcc: error: unrecognized command line option '-nvcc_options=relaxed-constexpr'
gcc: error: unrecognized command line option '-nvcc_options=ftz=true'
Target //:build_pip_pkg failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by facaiy** [comment]
Hi, @lukaszgrad could you take a try within the docker image `tensorflow/tensorflow:custom-op-gpu-ubuntu16`?

**Comment by seanpmorgan** [comment]
Closing this as we packages are now built with optimizations. Please feel free to re-open if this problem is persisting.
