### ISSUE TITLE
Correlation cost layer is not placed on gpu

### ISSUE THREAD

**Issue by MoritzWillig** [tensorflow/addons#447]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3
- TensorFlow installed from (source or binary): PyPi
- TensorFlow version (use command below): tf-nightly-gpu-2.0-preview 2.0.0.dev20190824   
- TensorFlow Addons installed from (source, PyPi): PyPi (also tested with source)
- TensorFlow Addons version: tfa-nightly 0.5.0.dev20190824 (/master)
- Python version and type (eg. Anaconda Python, Stock Python as in Mac, or homebrew installed Python etc): system
- Bazel version (if compiling from source): (0.25.1)
- GCC/Compiler version (if compiling from source): (gcc/7.4.0)
- Is GPU used? (yes/no): yes
- GPU model (if used): Nvidia GTX 1080Ti

**Describe the bug**
The correlation cost layer gets executed on CPU instead of on GPU.

**Describe the expected behavior**
The correlation layer should be run on the GPU.

**Code to reproduce the issue**
```
import tensorflow as tf
import tensorflow_addons as tfa
import numpy as np
import time

from tensorflow.python.eager import context
context.context().log_device_placement = True


im = np.random.rand(1, 500, 500, 3)

model = tf.keras.Sequential([
    tfa.layers.CorrelationCost(
        kernel_size=1, max_displacement=4,
        stride_1=1, stride_2=1,
        pad=4, data_format="channels_last")])

start = time.time()
corr_volume = model([im, im])
print(f"computing correlation took {str(time.time() - start)} sec")
```

Output:
```
...
input_a: (_Arg): /job:localhost/replica:0/task:0/device:GPU:0
input_b: (_Arg): /job:localhost/replica:0/task:0/device:GPU:0
correlation_cost/CorrelationCost: (CorrelationCost): /job:localhost/replica:0/task:0/device:CPU:0
correlation_cost/transpose: (Transpose): /job:localhost/replica:0/task:0/device:GPU:0
Identity: (Identity): /job:localhost/replica:0/task:0/device:GPU:0
identity_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:GPU:0
correlation_cost/transpose/perm: (Const): /job:localhost/replica:0/task:0/device:GPU:0
...
computing correlation took 14.041364908218384 sec
```

**Other info / logs**
Replacing the correlation cost with a Conv2D shows, that the GPU is correctly utilized for other layers.

**Comment by MoritzWillig** [comment]
While GOOGLE_CUDA is defined for the `correlation_cost_op_gpu.cu.cc`, it is missing in `correlation_cost_op.cc`. Therefore the gpu kernel does get compiled but is not registered. 

As far as I can see, this comes from the fact, that the "_correlation_cost_ops.so" target is built without "-DGOOGLE_CUDA". However it contains the `correlation_cost_op.cc` file, that performs the kernel registration. Unfortunately I'm unfamiliar with the bazel build system, so I can't tell how to fix this.

**Comment by seanpmorgan** [comment]
@MoritzWillig Tomorrow's nightly package (and the soon to be released 0.5) will include pre-built GPU kernels.

I've also made a [change to the build docs](https://github.com/tensorflow/addons#installing-from-source) which should enable you to compile yourself if you still want to.

See the results of your script in this pull request: #456

**Comment by MoritzWillig** [comment]
@seanpmorgan thats good to hear. I just had a quick look into the changes (*). If I see it correctly `/tensorflow_addons/custom_ops/layers/BUILD` will still compile the `_correlation_cost_ops.so` without the "-DGOOGLE_CUDA=1" flag. The GPU kernel would be compiled, but the guard in `correlation_cost_op.cc` will prevent it from being registered.

(*) Maybe I also missed the change and it's working correctly. I can't test it at the moment.

**Comment by seanpmorgan** [comment]
> @seanpmorgan that's good to hear. I just had a quick look into the changes (*). If I see it correctly `/tensorflow_addons/custom_ops/layers/BUILD` will still compile the `_correlation_cost_ops.so` without the "-DGOOGLE_CUDA=1" flag. The GPU kernel would be compiled, but the guard in `correlation_cost_op.cc` will prevent it from getting registered.
> 
> (*) Maybe I also missed the change and it's working correctly. I can't test it at the moment.

So the change was setting the env variable `TF_NEED_CUDA` so `/configure.sh` will set the right toolchain. 

You're right though this looks incorrect as the flag is used in correlation cost:
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/custom_ops/layers/cc/kernels/correlation_cost_op.cc#L334

I'll submit a quick patch... thanks again!

**Comment by seanpmorgan** [comment]
Welp not as simple as it looked. Registering the op throws a number of errors coming from CUDA cub library:
```
In file included from bazel-out/k8-opt/bin/external/cub_archive/_virtual_includes/cub/gpu/cub/device/../iterator/../thread/thread_load.cuh:40:0,
                 from bazel-out/k8-opt/bin/external/cub_archive/_virtual_includes/cub/gpu/cub/device/../iterator/arg_index_input_iterator.cuh:39,
                 from bazel-out/k8-opt/bin/external/cub_archive/_virtual_includes/cub/gpu/cub/device/device_reduce.cuh:41,
                 from tensorflow_addons/custom_ops/layers/cc/kernels/correlation_cost_op_gpu.cu.cc:21:
bazel-out/k8-opt/bin/external/cub_archive/_virtual_includes/cub/gpu/cub/device/../iterator/../thread/../util_ptx.cuh: In function 'void cub::CTA_SYNC()':
bazel-out/k8-opt/bin/external/cub_archive/_virtual_includes/cub/gpu/cub/device/../iterator/../thread/../util_ptx.cuh:257:5: error: '__syncthreads' was not declared in this scope
     __syncthreads();
     ^~~~~~~~~~~~~
bazel-out/k8-opt/bin/external/cub_archive/_virtual_includes/cub/gpu/cub/device/../iterator/../thread/../util_ptx.cuh:257:5: note: suggested alternative: '__gthread_t'
     __syncthreads();
     ^~~~~~~~~~~~~
     __gthread_t
bazel-out/k8-opt/bin/external/cub_archive/_virtual_includes/cub/gpu/cub/device/../iterator/../thread/../util_ptx.cuh: In function 'int cub::CTA_SYNC_AND(int)':
bazel-out/k8-opt/bin/external/cub_archive/_virtual_includes/cub/gpu/cub/device/../iterator/../thread/../util_ptx.cuh:266:12: error: '__syncthreads_and' was not declared in this scope
     return __syncthreads_and(p);
            ^~~~~~~~~~~~~~~~~
bazel-out/k8-opt/bin/external/cub_archive/_virtual_includes/cub/gpu/cub/device/../iterator/../thread/../util_ptx.cuh:266:12: note: suggested alternative: '__gthread_once'
     return __syncthreads_and(p);
            ^~~~~~~~~~~~~~~~~
            __gthread_once
bazel-out/k8-opt/bin/external/cub_archive/_virtual_includes/cub/gpu/cub/device/../iterator/../thread/../util_ptx.cuh: In function 'int cub::WARP_ANY(int, unsigned int)':
bazel-out/k8-opt/bin/external/cub_archive/_virtual_includes/cub/gpu/cub/device/../iterator/../thread/../util_ptx.cuh:289:14: error: '::__any' has not been declared
     return ::__any(predicate);
              ^~~~~
bazel-out/k8-opt/bin/external/cub_archive/_virtual_includes/cub/gpu/cub/device/../iterator/../thread/../util_ptx.cuh:289:14: note: suggested alternative: '__ynl'
     return ::__any(predicate);
              ^~~~~
              __ynl
bazel-out/k8-opt/bin/external/cub_archive/_virtual_includes/cub/gpu/cub/device/../iterator/../thread/../util_ptx.cuh: In function 'int cub::WARP_ALL(int, unsigned int)':
bazel-out/k8-opt/bin/external/cub_archive/_virtual_includes/cub/gpu/cub/device/../iterator/../thread/../util_ptx.cuh:302:14: error: '::__all' has not been declared
     return ::__all(predicate);
```

Have no time to look into for now -- currently it'll revert to CPU but needs to get fixed
