### ISSUE TITLE
Add contribution guideline for moving from tf.contrib

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#45]
@dynamicwebpaige wisely suggested in #38 that we put together a guideline on moving from tf.contrib to addons. A majority of our code is currently ported from tf.contrib and there are many open issues for bringing over the rest of our addons RFC.  

Some things to include in the guideline:
- [TF2.0 symbols mapping](https://docs.google.com/spreadsheets/d/1FLFJLzg7WNP6JHODX5q8BDgptKafq_slHpnHVbJIteQ/edit#gid=0)
- Guidelines on when to use tf.function
- Common code changes (remove variable_scope, etc.)
- Suggestions on adding aditional test cases

I imagine we would hold this document in the repo for a substantial amount of time, but ultimately will want to remove it as we grow away from our original codebase of ported tf.contrib code

**Comment by dynamicwebpaige** [comment]
cc: @karmel for visibility.

**Comment by dynamicwebpaige** [comment]
Currently being worked by two Google Summer of Code students: Vishal and Adrian.

**Comment by seanpmorgan** [comment]
Closing as we're more or less past moving code from tf.contrib.
