### ISSUE TITLE
Use package manager to pin TF dependency

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#454]
Per https://github.com/tensorflow/community/pull/135 we should be using pip/conda to specify which Addons releases work with which TF versions. 

This is blocked until the `tensorflow` and `tensorflow-gpu` consolidation scheduled for 2.1 release

**Comment by guillaumekln** [comment]
What is the reason to wait for the package consolidation? It seems possible to depend on `tensorflow-gpu` today.

**Comment by seanpmorgan** [comment]
Good question.. one reason would be that TF does not package `tensorflow-gpu` for MacOS:
https://pypi.org/project/tensorflow-gpu/2.0.0rc0/#files

**Comment by guillaumekln** [comment]
Ah, it makes sense. A possible workaround could be to express the [platform dependencies](https://www.python.org/dev/peps/pep-0508/#environment-markers) in `setup.py`, e.g.:

```python
install_requires=[
    "tensorflow-gpu;platform_system!='Darwin'",
    "tensorflow;platform_system=='Darwin'",
]
```

Not sure it is something we want though...

**Comment by kyleabeauchamp** [comment]
I recall always having issues when using logic in the setup script.  Might be possible to do something with the new PEP518 approaches (e.g., https://www.python.org/dev/peps/pep-0518/).  Not 100% sure.

**Comment by guillaumekln** [comment]
TensorFlow Text is using a less restrictive TensorFlow version requirement:

> `'tensorflow>=2.0.0b1, <2.1'`

https://github.com/tensorflow/text/blob/v1.0.0-beta2/oss_scripts/pip_package/setup.py#L76

Should we do something similar?

**Comment by seanpmorgan** [comment]
> TensorFlow Text is using a less restrictive TensorFlow version requirement:
> 
> > `'tensorflow>=2.0.0b1, <2.1'`
> 
> https://github.com/tensorflow/text/blob/v1.0.0-beta2/oss_scripts/pip_package/setup.py#L76
> 
> Should we do something similar?

In general I think we should support a greater-than versioning if we know that there were no breaks between releases (Might have to adapt our travis tests).

For this specific case I believe 2.0.0b1 will break with TFA 0.6 as Op Namespacing wasn't implemented at that point (~90% sure of that, but not positive)

**Comment by facaiy** [comment]
Yes, I have the same concern with Guillaume. Perhaps we can always use greater-than version by default when releasing major version(say, tf >= 2.0 for addons 0.5). And we can release a minor version to pin tf version until there is a break or performance issue(say, tf>=2.0, <2.2 for addons 0.5.3).

**Comment by seanpmorgan** [comment]
Sounds good. Re-opening to track progress on adding greater-than
