### ISSUE TITLE
Adding sample weight parameter to metrics

### ISSUE THREAD

**Issue by SSaishruthi** [tensorflow/addons#467]
This will be the continuation of the metrics issue. We are planning to add  `sample weight` parameter to the metrics such as F1, R-Square, etc.

**Will this change the current api? How?** Yes. I will add a new parameter

@Squadrick and I will be working on this.

**Comment by SSaishruthi** [comment]
@seanpmorgan We are taking this parameter addition to a separate issue. Can you please assign this to me?

**Comment by facaiy** [comment]
Hi, @SSaishruthi , just a note that Metric class has supported sample_weight parameter :-)

**Comment by SSaishruthi** [comment]
Thanks @facaiy 
Was on vacation. Will work on this on top of the current PR

**Comment by AndersonHappens** [comment]
@SSaishruthi , MultiLabelConfusionMatrix and RSquare both still need the sample weight parameter added as well. 

Thank you for your hard work!

**Comment by SSaishruthi** [comment]
@AndersonHappens Thanks for the comment. PR is in progress for both.

**Comment by jharmsen** [comment]
Hi, are there any concrete plans to implement sample_weight for FBetaScore/F1Score?

Thanks!
