### ISSUE TITLE
python3.7 run failed

### ISSUE THREAD

**Issue by lw3259111** [tensorflow/addons#470]
ubuntu 18.04,cuda10.0,python3.7.3

```
 pip install tensorflow-addons

import tensorflow_addons as tfa

```
NotFoundError: tensorflow_addons/custom_ops/activations/_activation_ops.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

**Comment by seanpmorgan** [comment]
Hi @lw3259111! What version of TensorFlow and TensorFlow Addons are you running?

**Comment by lw3259111** [comment]
tensorflow-gpu==2.0.0-beta1
tensorflow_adds==0.5.0

**Comment by seanpmorgan** [comment]
Addons version 0.5 was built against tensorflow 2.0.0rc0. Could you please try that version? Soon we plan to pin our releases using pypi
