### ISSUE TITLE
Can ROCm be supported?

### ISSUE THREAD

**Issue by iszotic** [tensorflow/addons#471]
**System information**
- TensorFlow version (you are using): tensorflow-rocm 2.0.0b3, 15/07/19
- TensorFlow Addons version: 0.4.0
- Is it in the tf.contrib (if so, where): Not applicable
- Are you willing to contribute it (yes/no): testing, I guess, but No
- Are you willing to maintain it going forward? (yes/no): No, same as above

**Describe the feature and the current behavior/state.**
When I try to import the module it throws this in console, using the cpu version of tensorflow 2.0.0b1 it imports succesfully
`
>>> import tensorflow
>>> import tensorflow_addons
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/voltam/.local/lib/python2.7/site-packages/tensorflow_addons/__init__.py", line 75, in <module>
    from tensorflow_addons import image
  File "/home/voltam/.local/lib/python2.7/site-packages/tensorflow_addons/image/__init__.py", line 22, in <module>
    from tensorflow_addons.image.distance_transform import euclidean_dist_transform
  File "/home/voltam/.local/lib/python2.7/site-packages/tensorflow_addons/image/distance_transform.py", line 24, in <module>
    get_path_to_datafile("custom_ops/image/_image_ops.so"))
  File "/home/voltam/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/voltam/.local/lib/python2.7/site-packages/tensorflow_addons/custom_ops/image/_image_ops.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

`
**Will this change the current api? How?**
No
**Who will benefit with this feature?**
AMD ROCm supported GPUs

**Comment by facaiy** [comment]
Hi, would you mind take give v0.0.5 (the latest release) a try? Thanks for reporting!

**Comment by iszotic** [comment]
I tried tfa-nightly and the same keeps happening, this is the version
`pip show tfa-nightly
Name: tfa-nightly
Version: 0.5.0.dev20190811
`

**Comment by seanpmorgan** [comment]
So tensorflow-rocm is still packaged as `manylinux1` meaning it is not built with the same toolchain as TFA or TF2-RC. 
https://pypi.org/project/tensorflow-rocm/2.0.0b3/#files
https://pypi.org/project/tensorflow/2.0.0rc0/#files

Notice we now publish as `manylinux2010` spec compliant. Do you happen to know a point of contact who builds/publishes `tensorflow-rocm`?

**Comment by iszotic** [comment]
Here I guess https://github.com/ROCmSoftwarePlatform/tensorflow-upstream, but a specific person, nop, :(

**Comment by seanpmorgan** [comment]
@whchung Would you happen to know if there are plans to publish `tensorflow-rocm` as a manylinux2010 package as will be done for TF2?

**Comment by whchung** [comment]
@seanpmorgan , @sunway513 and @parallelo would provide updates on this.

**Comment by parallelo** [comment]
We'll take a look into this.

**Comment by seanpmorgan** [comment]
Great, thanks! Closing this issue... but happy to re-open it if problems persist.

**Comment by mbonaker** [comment]
Well, the problem does persist as I get `undefined symbol: _ZNK10tensorflow15shape_inference16InferenceContext11DebugStringEv` if I try using `tfa.image.rotate` with tfa 0.9.1 and tf-rocm 2.1.1 – same result with tfa-nightly 0.10.0. Was this originally closed because it was thought to be solved or because the responsibility lies with the `tensorflow-rocm` project? In case of the latter just ignore this comment.

**Comment by fsx950223** [comment]
@seanpmorgan @bhack I could add rocm support for addons and I have passed custom layer ops tests in my local environment. Could tensorflow team provides a CI/CD environment?

**Comment by bhack** [comment]
@fsx950223 My opinion is that we could try to upstream the few custom ops we have in TF as we are not trying to accumulate other custom ops if we don't have a quite clear roadmap on the topic we have opened at:
https://discuss.tensorflow.org/t/deformable-convolution-and-other-custom-ops/1951

If these PRs will be accepted in TF we have already the ROCM CI available there.

**Comment by DanielWicz** [comment]
Is ROCm dead for TFA ? Or I can install and then tensorflow-rocm without a problem (except using some cuda-kernelized functions) ?

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
