### ISSUE TITLE
Would like to contribute parse time operator into tfa.text

### ISSUE THREAD

**Issue by helinwang** [tensorflow/addons#492]
Hi SIG Addons community,

I would like to contribute parse time operator into tfa.text.

Here is the short description (detailed description in the attachment):

The parse time operator parses a timestamp string with the given format into the Unix time representation, the number of seconds / milliseconds / microseconds / nanoseconds elapsed since January 1, 1970 UTC.
For example, “2019-05-17T23:56:09.05Z” with the format “%Y-%m-%dT%H:%M:%E*S%Ez” gets parsed into 1558137369, when the output unit is set to SECOND.

For more details please see:
[Parse Time Operator.pdf](https://github.com/tensorflow/addons/files/3593194/Parse.Time.Operator.-.external.2.pdf)

I would be willing to maintain the Op going forward.

**Comment by seanpmorgan** [comment]
Hi @helinwang as mentioned on the mailing list -- I think this would be a nice addition. Could you go ahead with a PR and we can review there.

**Comment by helinwang** [comment]
Thanks, Sean!
I sent https://github.com/tensorflow/addons/pull/530.
Btw, the docker based development / build environment that tensorflow/addons provides is pretty convenient to use :)
