### ISSUE TITLE
Backport "Fix handling of sequence_length w/ beam search decoder"

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/addons#494]
**System information**
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow version and how it was installed: binary
- TensorFlow-Addons version and how it was installed: binary
- Python version: 3.6
- Is GPU used? No

**Describe the bug**

For some reasons, patches are still pushed to `tf.contrib.seq2seq`, see:

https://github.com/tensorflow/tensorflow/commit/8bbc0392bc2e843df07de38d8ab66414fbfa3e82

The bug is described in the commit message.

**Code to reproduce the issue**

None.

**Other info / logs**

@qlzh727 as you refactored the seq2seq module, do you confirm this bug is also applicable to the addons version?

**Comment by qlzh727** [comment]
Thanks for the notice, let me take a look for the change in contrib.

As a side note, since addons has been port into google internal yet, eng within google is still using existing contrib version of seq2seq.

**Comment by qlzh727** [comment]
I think tensorflow/tensorflow@8bbc039 should be mirrored to addons. let me send a PR quickly

**Comment by ebrevdo** [comment]
@qlzh727 thanks so much for handling this!
