### ISSUE TITLE
Utilize Bazel 1.0 during build

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#498]
Bazel 1.0 should be released this month, and with it we'll get guarantees of backwards compatibility (currently the build may fail depending which version of bazel is installed)

https://github.com/bazelbuild/bazel/issues/8573

**Comment by Squadrick** [comment]
TFA builds fine on Bazel 1.0

Colab: https://colab.research.google.com/drive/12Krat_CFTeztcJsUTg1OdciZc-2Cih8w

I've tested locally on 1.0.1, and it works great as well.

**Comment by hmnshupndey** [comment]
> TFA builds fine on Bazel 1.0
> 
> Colab: https://colab.research.google.com/drive/12Krat_CFTeztcJsUTg1OdciZc-2Cih8w
> 
> I've tested locally on 1.0.1, and it works great as well.

How did you manage to remove spaces in your paths. I have also tried it but it is showing error:-
WARNING: ignoring LD_PRELOAD in environment.
Starting local Bazel server and connecting to it...
ERROR: bazel does not currently work properly from paths containing spaces (com.google.devtools.build.lib.runtime.BlazeWorkspace@44e17dda).
INFO: Invocation ID: f0c627d8-14c5-4909-8af4-9e011749347e
Please help!!
