### ISSUE TITLE
Remove use of internal tensorflow API

### ISSUE THREAD

**Issue by AndreasMadsen** [tensorflow/addons#50]
The current implementations use the internal `tensorflow.python` interface. I know this was how it was done in `tf.contrib`. However, since `addons` are not an integrated part of `tensorflow` but rather decoupled from the main `tensorflow` module, using that internal API seams highly wrong.

**Comment by seanpmorgan** [comment]
Thanks Andreas! This is a good call out. We initially discussed this in the below thread, and the reason I had preferred the internal API was that it made many things easier to do in an IDE (Verify subclasses match their parent methods, etc.).  The TF export is not understood... and is to me a hindrance while developing with TF.

That said... the way we're doing it is incorrect and unstable so we should use the correct API endpoints as this issue requests. It looks like in the future TF may be re-organized and we can have the best of both worlds with e.g. `import tensorflow_keras.keras.optimizers`


https://groups.google.com/a/tensorflow.org/forum/#!topic/addons/-QEXKmznCdA

**Comment by AndreasMadsen** [comment]
Yeah, I think you can be sure that developers will look to `addons` as an example on how to develop add-ons. So I think it is important to set a good example.
