### ISSUE TITLE
Package 0.5.1 against TF2-RC1

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#504]
Looks like RC1 was released. We were already planning the next minor release so should probably build against this version.

https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/9kOKxqVsv8Q

cc @facaiy

**Comment by facaiy** [comment]
Thanks for reminding me, Sean. Totally agree.

I suggest that we should make correlation_cost private, see https://github.com/tensorflow/addons/issues/509 . I'm happy to release 0.5.1 after finishing it. What do you think?

**Comment by facaiy** [comment]
+@tensorflow/model-maintainers for visibility

**Comment by seanpmorgan** [comment]
Release looks great... thanks Yan!

**Comment by facaiy** [comment]
```bash
```

**Comment by facaiy** [comment]
@guillaumekln reported the bug in https://github.com/tensorflow/addons/issues/532

**Comment by facaiy** [comment]
@seanpmorgan Is it good to drop 0.5.1 release, and create 0.5.2 package built on rc0? Perhaps we'd better to support rc1 or newer tf version after https://github.com/tensorflow/addons/issues/532

**Comment by seanpmorgan** [comment]
I think that's a good idea. I don't see a reason to not use rc1 and just not pin it using setup.py though. However, seeing as rc2 is coming soon whatever is easiest to rollback and release is good with me

**Comment by seanpmorgan** [comment]
Think we'll have to fix this on the next minor release. Closing.
