### ISSUE TITLE
BasicDecoder input error

### ISSUE THREAD

**Issue by kaushikb258** [tensorflow/addons#508]
I followed the basic decoder example from the TF addons home page: 

sampler = tfa.seq2seq.sampler.TrainingSampler()

decoder_cell = tf.keras.layers.LSTMCell(256)
projection_layer = tf.keras.layers.Dense(num_outputs)
decoder = tfa.seq2seq.BasicDecoder(decoder_cell, sampler, output_layer=projection_layer)

outputs, _, _ = decoder(decoder_emb_inp,  initial_state=encoder_state, sequence_length=decoder_lengths)

But get this error:
tensorflow.python.framework.errors_impl.InvalidArgumentError: In[0] is not a matrix. Instead it has shape [256] [Op:MatMul] name: my_taco/basic_decoder/decoder/while/lstm_cell/MatMul/

It is something to do with the file: tensorflow_addons/seq2seq/basic_decoder.py on line 126: 
cell_outputs, cell_state = self.cell(inputs, state, training=training) 

Please help.

**Comment by kaushikb258** [comment]
Sorry, its a silly bug. I fixed it. Please close/delete this issue.

**Comment by shivam2298** [comment]
@kaushikb258 how did you fix it, could you please share.
