### ISSUE TITLE
Add docstring for Correlation cost layer

### ISSUE THREAD

**Issue by facaiy** [tensorflow/addons#509]
1. Hide [correlation_cost](https://github.com/tensorflow/addons/blob/cffee80779e606870ebf2b7fce241eeb870053f5/tensorflow_addons/layers/optical_flow.py#L30) function, and make it private.
2. Add document for [CorrelationCost](https://github.com/tensorflow/addons/blob/cffee80779e606870ebf2b7fce241eeb870053f5/tensorflow_addons/layers/optical_flow.py#L143)

For details please check the discussion in https://github.com/tensorflow/addons/pull/207

**Comment by PyExtreme** [comment]
Hello @facaiy ,

I am new to open source but have good experience in ML. I am interested to contribute to **_addons_**.
Could you please assign it to me?

Thanks

**Comment by facaiy** [comment]
Welcome, @PyExtreme :-)

**Comment by PyExtreme** [comment]
Hi @facaiy , @WindQAQ , I am facing some bazel related issue while running the tests. I am trying to  solve it. I have followed the documentation as well.
It would be great if you could please provide me the commands list in sequence to set up the entire environment and run tests.
