### ISSUE TITLE
AttentionWrapperZeroState error

### ISSUE THREAD

**Issue by kaushikb258** [tensorflow/addons#512]
I am trying something similar to Tacotron using tfa.seq2seq wrappers, here is my code below:

encoder = tf.keras.layers.LSTM(num_units, return_state=True)
encoder_outputs, state_h, state_c = encoder(encoder_emb_inp)
encoder_state = [state_h, state_c]

sampler = tfa.seq2seq.sampler.TrainingSampler()
decoder_cell = tf.keras.layers.LSTMCell(num_units)
projection_layer = tf.keras.layers.Dense(num_outputs)

attention_mechanism = tfa.seq2seq.LuongAttention(num_units, encoder_outputs, memory_sequence_length=encoder_sequence_length)

decoder_cell = tfa.seq2seq.AttentionWrapper(decoder_cell, attention_mechanism, attention_layer_size=num_units, output_attention=False)

decoder = tfa.seq2seq.BasicDecoder(decoder_cell, sampler, output_layer=projection_layer, maximum_iterations=max_out_length)
   
dec_init_state = decoder_cell.get_initial_state(batch_size=batch_size, dtype=tf.float32)

outputs, _, _ = decoder(decoder_emb_inp, initial_state=dec_init_state, sequence_length=decoder_lengths)
       

Getting this error: 

train.py:38 train_step  *
        mel_pred = model(mel_in, mel_target, input_lengths)
    /home/kb/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py:807 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/kb/TF2/v3c/models/tacotron.py:66 call  *
        outputs, _, _ = decoder(decoder_emb_inp, initial_state=dec_init_state, sequence_length=decoder_lengths)
    /home/kb/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py:807 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/kb/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_addons/seq2seq/decoder.py:167 call  *
        return dynamic_decode(
    /home/kb/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_addons/seq2seq/decoder.py:460 dynamic_decode  *
        res = tf.compat.v1.while_loop(
    /home/kb/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py:2675 while_loop
        back_prop=back_prop)
    /home/kb/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/ops/while_v2.py:234 while_loop
        len_orig_loop_vars], expand_composites=True))
    /home/kb/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/ops/while_v2.py:1068 _check_shapes_compat
        "specify a less-specific shape." % (input_t.name, shape, t.shape))

ValueError: Input tensor 'my_taco/AttentionWrapperZeroState/zeros_2:0' enters the loop with shape (32, 128), but has shape (32, 32) after one iteration. To allow the shape to vary across iterations, use the `shape_invariants` argument of tf.while_loop to specify a less-specific shape.

I think it is something in the dec_init_state, but any suggestions welcome...

**Comment by guillaumekln** [comment]
Could you give the full code to reproduce the error?

**Comment by kaushikb258** [comment]
Here it is: 
https://github.com/kaushikb258/voice_seq2seq

I am trying to convert voice using seq2seq with attention. 

Are you aware of any publicly available seq2seq with attention code for any application using Tensorflow 2.0 and addons, specifically with the AttentionWrapper in TF addons?

**Comment by guillaumekln** [comment]
If you can prepare a code snippet like the one above that we can just copy-paste to reproduce the error that would be great. I did not reproduce the issue at this time.

> Are you aware of any publicly available seq2seq with attention code for any application using Tensorflow 2.0 and addons, specifically with the AttentionWrapper in TF addons?

I'm using `AttentionWrapper` [here](https://github.com/OpenNMT/OpenNMT-tf/blob/v2/opennmt/decoders/rnn_decoder.py#L68) but without the decoding implementation of `tfa.seq2seq`.

**Comment by kaushikb258** [comment]
It is in https://github.com/kaushikb258/voice_seq2seq/models/tacotron.py
 
I just followed the decoding implementation from tfa, but looks like something is not right:  
https://github.com/tensorflow/addons/tree/master/tensorflow_addons/seq2seq

I will look into your decoder implementation.

**Comment by guillaumekln** [comment]
I copy-pasted your implementation and used these dummy inputs:

```python
mel_in = tf.random.uniform([4, 7, 16])
mel_targets = tf.random.uniform([4, 7, 16])
input_lengths = tf.constant([7, 6, 5, 6], dtype=tf.int32)
```

It runs fine.

Are you using the latest version of TensorFlow Addons? If yes, could you share the inputs for which the error above is raised?

**Comment by kaushikb258** [comment]
I am using TF addons 0.5. I have a small set of 8 inputs as Numpy arrays now in the following repo. Still getting the same error. Feel free to take a look. Thanks! 
https://github.com/kaushikb258/voice_seq2seq

**Comment by seanpmorgan** [comment]
Link is dead.. please re-open if this is still an issue with a minimal reproducible example
