### ISSUE TITLE
Add bfloat16 support to ops

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/addons#543]
**Describe the feature and the current behavior/state.**
Ops need to support bfloat16 data type which will accelerate model inference and decrease model size.
**Relevant information**
- Are you willing to contribute it (yes/no): yes
- Are you willing to maintain it going forward? (yes/no): yes
- Is there a relevant academic paper? (if so, where): https://en.wikipedia.org/wiki/Bfloat16_floating-point_format
- Is there already an implementation in another framework? (if so, where): tensorflow kernels
- Was it part of tf.contrib? (if so, where):

**Which API type would this fall under (layer, metric, optimizer, etc.)**
all
**Who will benefit with this feature?**
Developers who use bfloat16 data type
**Any other info.**
Do we need to implement bfloat16 kernel particular?

**Comment by WindQAQ** [comment]
I think it would be great if we could support bfloat16 :smiley:

**Comment by bionicles** [comment]
would use (especially if it works on nvidia gpus)

**Comment by WindQAQ** [comment]
I am going to close this as bfloat16 would only be supported for XLA kernels, which is currently not in addons' scope.
