### ISSUE TITLE
Package Addons 0.6

### ISSUE THREAD

**Issue by facaiy** [tensorflow/addons#553]
TensorFlow2.0.0 is out. So it's time to package and release IMO. 

@seanpmorgan @tensorflow/model-maintainers what do you think, all?

**Comment by facaiy** [comment]
Congrats, closed by https://github.com/tensorflow/addons/pull/565 👍

**Comment by facaiy** [comment]
@seanpmorgan Sean, we should bump up 0.7.0 version in master branch.

**Comment by seanpmorgan** [comment]
> @seanpmorgan Sean, we should bump up 0.7.0 version in master branch.

Yes, thanks for the reminder:
https://github.com/tensorflow/addons/pull/568
