### ISSUE TITLE
Record in progress & completed moves to TF-Core

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#560]
Per the discussion in #550 it'd be helpful to record whats is being and has been moved.

Some things that might be worth including:

- Subpackage
- Status
- Last version it was in TFA
- First version it was added to TF
- Relevant PRs

Any opinions on what the document should be named? `GRADUATED.md`? `MIGRATED.md`?

**Comment by AakashKumarNain** [comment]
IMO `MIGRATED.md` makes more sense.
