### ISSUE TITLE
Build doctest to test python docstrings

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/addons#582]
Seems that core TF has already used `doctest` to test python docstring, which having different style with ours, especially for code snippet example usage. To unify the docstring and for better documentation, the doctest should be also built in addons.

See https://www.tensorflow.org/community/contribute/docs_ref for more details.

**Comment by WindQAQ** [comment]
For anyone who what to work on this, these files in core TensorFlow might be helpful.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docs/tf_doctest.py
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docs/BUILD#L13

**Comment by bryanko1** [comment]
I am interested in helping out with this. Do you have any advice for me on where to start? Thanks!

**Comment by seanpmorgan** [comment]
Hi @bryanko1! Welcome to addons. There is already a PR for this:
https://github.com/tensorflow/addons/pull/677

Would you mind giving it a review?

**Comment by bryanko1** [comment]
Yeah, sure thing!

**Comment by yil532** [comment]
Hello friend, I see this issue is not closed yet, do we still need some help here? @seanpmorgan
