### ISSUE TITLE
Can't compile for ppc64le-linux

### ISSUE THREAD

**Issue by fernandocamargoti** [tensorflow/addons#589]
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04 (Docker)
- TensorFlow version and how it was installed: 2.0.0 (compiled from source)
- TensorFlow-Addons version and how it was installed: 0.6.0
- Python version: 3.6
- Is GPU used? yes
- Bazel version: 0.26.1 (same used to compile Tensorflow 2.0.0)

**Describe the bug**

I'm trying to compile tensorflow-addons on a IBM Power 9 (ppc64le-linux) and I'm receiving the following error:

```
ERROR: /root/.cache/bazel/_bazel_root/2c0821a9a5dcbde3bb318f28476d8d57/external/local_config_cuda/crosstool/BUILD:22:1: in cc_toolchain_suite rule @local_config_cuda//crosstool:toolchain: cc_toolchain_suite '@local_config_cuda//crosstool:toolchain' does not contain a toolchain for cpu 'ppc'
ERROR: Analysis of target '//:build_pip_pkg' failed; build aborted: Analysis of target '@local_config_cuda//crosstool:toolchain' failed; build aborted
INFO: Elapsed time: 0.476s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 6 targets configured)
```

**Comment by seanpmorgan** [comment]
Hi @fernandocamargoti . At the moment we don't support ppc64 in our build. There should be no blocker so would be happy to accept a PR for the build but we currently have no infrastructure to test so it'll require community support/verification

**Comment by fernandocamargoti** [comment]
Thanks for the feedback, @seanpmorgan. I don't know much about the Tensorflow's build system, so I tried and failed to fix it. I hope someone else can submit a PR. I'd be happy to help with the verification.

**Comment by seanpmorgan** [comment]
Closed by https://github.com/tensorflow/addons/pull/1672
