### ISSUE TITLE
0.6.0 installs tensorflow-gpu on CPU only environment.

### ISSUE THREAD

**Issue by invencode** [tensorflow/addons#597]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu server 18.04
- TensorFlow version and how it was installed (source or binary): 2.0.0, binary
- TensorFlow-Addons version and how it was installed (source or binary): 0.6.0, binary
- Python version: 3.7.3
- Is GPU used? (yes/no): no

**Describe the bug**

tensorflow-addons 0.6.0 installs tensorflow-gpu on CPU only environment.

**Code to reproduce the issue**

1. Install tensorflow 2.0.0 (cpu only)
`$ pip install tensorflow==2.0.0`

2. Install tensorflow-addons 0.6.0
`$ pip install tensorflow-addons==0.6.0`

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by seanpmorgan** [comment]
Hi @invencode! So `tensorflow-gpu` should work fine on a CPU only machine. Please let us know if you have issue.

Unfortunately, the linking is a bit of an issue at the moment. Once TF 2.1 is released the packages will be considated into a single `tensorflow` package and at that point we'll switch to depending on that.
