### ISSUE TITLE
[F1Score] average should be None by default

### ISSUE THREAD

**Issue by cgarciae** [tensorflow/addons#602]
In the documentation it says that the `average` parameters is `None` by default but the signature has it as a required argument. See this line:

https://github.com/tensorflow/addons/blob/40de2b942c833c6afccd96759f106640b983953b/tensorflow_addons/metrics/f_scores.py#L338

**Comment by Liu-Da** [comment]
I also found the same problem.

**Comment by seanpmorgan** [comment]
Please consider submitting a PR to fix this. Thanks!

**Comment by seanpmorgan** [comment]
Nevermind looks like it was fixed by https://github.com/tensorflow/addons/pull/502. Closing.
