### ISSUE TITLE
Define seq2seq.Sampler and seq2seq.BasicDecoder in __init__.

### ISSUE THREAD

**Issue by npuichigo** [tensorflow/addons#603]
Currently, it's not convenient to define both seq2seq.Sampler and seq2seq.BasicDecoder in __init__, because we usually need to switch to different samplers between training and testing, but the training flag is unavailable in __init__.

```
class Foo(tf.keras.layers.Layer):
  def __init__():
      super(Foo, self).__init__()

  def call(inputs, training=None):
    if training:
      sampler = tfa.seq2seq.TrainingSampler()
    else:
      sampler = tfa.seq2seq.InferenceSampler()

   # Decoder
   decoder_cell = tf.keras.layers.LSTMCell(num_units)
   projection_layer = tf.keras.layers.Dense(num_outputs)
   decoder = tfa.seq2seq.BasicDecoder(
       decoder_cell, sampler, output_layer=projection_layer)

   outputs, _, _ = decoder(
       decoder_emb_inp,
       initial_state=encoder_state,
       sequence_length=decoder_lengths)

   return outputs
```

A workaround is to define a sampler that can both be used during training and inference, with a training flag in its call method.

**Comment by npuichigo** [comment]
@qlzh727 @guillaumekln Can you help to take a look?

**Comment by kazemnejad** [comment]
Another common practice is to create two separate decoders one for training and one for inference inside the `__init__(..)` method, and let the decoder_cell and projection_layer to be shared between them, Here is an example:
```python
class Foo(tf.keras.layers.Layer):
  def __init__():
      super(Foo, self).__init__()

      decoder_cell = tf.keras.layers.LSTMCell(num_units)
      projection_layer = tf.keras.layers.Dense(num_outputs)

      train_sampler = tfa.seq2seq.TrainingSampler()
      self._train_decoder = tfa.seq2seq.BasicDecoder(
                decoder_cell, sampler, output_layer=projection_layer)

      inference_sampler = tfa.seq2seq.TrainingSampler()
      self._inference_decoder = tfa.seq2seq.BasicDecoder(
               decoder_cell, inference_sampler, output_layer=projection_layer)

  def call(...):
      if training is None:
              training = tf.keras.backend.learning_phase()
       
      if training:
             # Training stuff
      else:
             # Inference stuff
```

**Comment by npuichigo** [comment]
@kazemnejad Another question is how can we debug with eager mode? If we place sampler in __init__, we cannot reset decoder inputs for sampler (teacher forcing).

**Comment by kazemnejad** [comment]
The decoder itself re-initializes the sampler upon each invocation. It's also worth mentioning that Neither of `Decoder` or `Sampler` accepts any data input/tensor in the *init* method; instead, they receive the inputs on their *call* method.

**Comment by qlzh727** [comment]
I think the example from @kazemnejad should work nicely. In general, we recommend user to create instance they need in the init() since should the correct context (either eager in v2 or graph in v1). On the otherhand, call() will almost certain executed in graph context, which might lead to some unexpected behavior/error.

By the way, if you want to debug in the eager mode, you could try model.compile(run_eagerly=True), which will then cause all the call() body to be run in eager context. Or you can directly invoke your Foo with the numpy data.

**Comment by npuichigo** [comment]
@qlzh727 @kazemnejad Thank you for your advice! It works now.
