### ISSUE TITLE
windows pip can't get package

### ISSUE THREAD

**Issue by gjxcq** [tensorflow/addons#612]
I want to install it in windows python3.6, but I use pip install tensorflow-addons,can't get the package,
and I see it on pypi only support mac and linux, not find window.

**Comment by Gokkulnath** [comment]
@gjxcq We are tracking this here. https://github.com/tensorflow/addons/issues/173  and https://github.com/tensorflow/custom-op/issues/24 . Meanwhile you try setting it up in WSL
