### ISSUE TITLE
MovingAverage optimizer does not work with tf.keras.callbacks.ReduceLROnPlateau

### ISSUE THREAD

**Issue by artemmavrin** [tensorflow/addons#613]
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow version and how it was installed: 2.0.0, from pip
- TensorFlow-Addons version and how it was installed: 0.6.0, from pip
- Python version: 3.7.4
- Is GPU used? no

**Describe the bug**

Training a `tf.keras.Model` using its `fit` method with a `tfa.optimizers.MovingAverage` optimizer and the `tf.keras.callbacks.ReduceLROnPlateau` callback fails at the end of an epoch because [the callback relies on the model's optimizer to have a `lr` attribute](https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/keras/callbacks.py#L1819). The `MovingAverage` wrapper does not expose the underlying optimizer's `lr` attribute.

Related: #575

**Code to reproduce the issue**

```python
import tensorflow as tf
import tensorflow_addons as tfa

(x, y), *_ = tf.keras.datasets.mnist.load_data()
_, height, width = x.shape
x = tf.image.convert_image_dtype(x, tf.dtypes.float32)

model = tf.keras.Sequential([
    tf.keras.layers.Input((height, width)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(units=10, activation='softmax'),
])
optimizer = tfa.optimizers.MovingAverage('sgd')
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy')

lr_reducer = tf.keras.callbacks.ReduceLROnPlateau(monitor='loss')

model.fit(x, y, callbacks=[lr_reducer])
```

Error (without full traceback):

```
AttributeError: 'MovingAverage' object has no attribute 'lr'
```

**Comment by seanpmorgan** [comment]
Should be fixed from #617
