### ISSUE TITLE
I have a problem about " tfa.text.crf_log_likelihood " API !

### ISSUE THREAD

**Issue by hacker-lin** [tensorflow/addons#615]
Tensorflow2.0 
tfa 0.6.0

part code:  

    with tf.GradientTape() as tp:
        predict = model(data)
        print(predict.shape) # (32, 574)
        print(label.shape)  # (32, 574)
        log_likelihood, transition_params = tfa.text.crf_log_likelihood(
            tf.cast(tf.expand_dims(predict, axis=2), tf.float32),       
            label,            
            maxlen
        )

final error:  

    "ValueError: Shape must be rank 2 but is rank 1 for 'Slice_2' (op: 'Slice') with input shapes: [574], [2], [2]."

I adjust the input shape many times, and it doesnt works~
plz help. thx!

**Comment by WindQAQ** [comment]
Hi, could you provide the minimal runnable code snippet so that we could reproduce the issue? Thanks.

**Comment by hacker-lin** [comment]
> Hi, could you provide the minimal runnable code snippet so that we could reproduce the issue? Thanks.

Thanks!
I only change the arguments's dim, and it works !   

    log_likelihood, transition_params = tfa.text.crf_log_likelihood(
        inputs = tf.expand_dims(predict, axis=2),                  # expand it dim
        tag_indices = label,
        sequence_lengths = tf.expand_dims(maxlen,axis=0),      # expand it dim, too
    )

**Comment by WindQAQ** [comment]
Great! Then I am going to close this issue. Feel free to issue another one if you get something wrong. Thanks!
