### ISSUE TITLE
Feature request: add parametric ELU (PELU) activation function

### ISSUE THREAD

**Issue by carlthome** [tensorflow/addons#625]
# Proposal
The exponential linear unit (ELU) is already in TensorFlow as `tf.nn.elu` which is great. The new parametric version (called PELU) shows very promising experimental results so I wonder if it could be added in to TensorFlow too in order to encourage more widespread experimentation with it by the deep learning community. One problem with it though is that it's stateful (e.g. `tf.Variable`), meaning it's not clear to me where in TensorFlow it fits in.

# Implementation
Here's an implementation of the PELU that I've been using lately (I'm assuming batch_size is the first dimension in `x`):
```python
def pelu(x):
  """Parametric Exponential Linear Unit (https://arxiv.org/abs/1605.09332v1)."""
  with tf.variable_scope(x.op.name + '_activation', initializer=tf.constant_initializer(1.0)):
    shape = x.get_shape().as_list()[1:]
    alpha = tf.get_variable('alpha', shape)
    beta = tf.get_variable('beta', shape)
    positive = tf.nn.relu(x) * alpha / (beta + 1e-9)
    negative = alpha * (tf.exp((-tf.nn.relu(-x)) / (beta + 1e-9)) - 1)
    return negative + positive
```

# Reference
https://arxiv.org/abs/1605.09332v1

**Comment by seanpmorgan** [comment]
My only hesitation would be whether or not PELU is still relevant now that SELU is part of TF-Core. Does anyone in the community still see this as useful and if so could you point to an architecture or experiment that shows value. Thanks!

**Comment by seanpmorgan** [comment]
Seeing as the original author of this issue no longer sees value and there are several alternatives I'm going to close this issue. Happy to have someone re-open it if there is evidence for its usefulness.
