### ISSUE TITLE
[feature] tf.contrib.image.invert

### ISSUE THREAD

**Issue by cancan101** [tensorflow/addons#627]
/CC @ringw 

Along the lines of the other utility functions in [`tf.contrib.image`](https://www.tensorflow.org/api_docs/python/tf/contrib/image), would be great to have a `tf.contrib.image.invert` that takes a transform and returns the inverse transform.

**Comment by seanpmorgan** [comment]
My initial thought is that this could be difficult to maintain if it applied to all of the transforms in `tfa.image`. Seeing as the last comments were in 2017 I'm going to close this issue but happy to re-open and discuss if there is still a desire for this.
