### ISSUE TITLE
Feature request: Keras CRF layer

### ISSUE THREAD

**Issue by ipoletaev** [tensorflow/addons#628]
It will be great if in the `contrib.keras` in the nearest future [linear CRF layer](https://github.com/phipleg/keras/blob/crf/keras/layers/crf.py) (inside the Keras wrapper) will be added.

I think a lot of people will find this very [useful](https://github.com/fchollet/keras/issues/4090).

**Comment by seanpmorgan** [comment]
Thanks for transferring. We have a PR under review for CRF Keras Layer #377. There may be some moves (CRF leaving tfa.text) so the review is taking longer than we'd hope. Will close this issue once we've decided on the path forward and merge.

**Comment by WindQAQ** [comment]
Close the issue as we already had `tfa.layers.CRF`.
