### ISSUE TITLE
Resize image for nd

### ISSUE THREAD

**Issue by ruanxt** [tensorflow/addons#629]
Is there a functionality of resize image for n-d where n > 2? It seems currently tensorflow only support resize images for 2d images (4D tensor). Could you add the functionality?

**Comment by seanpmorgan** [comment]
Hmmm this one I'm less confident in adding to addons as opposed to modifying `tf.image.resize`. There would be no functionality difference only that it would support larger rank tensors. I don't believe this would be adding dimensions, just resizing higher dimensional tensors so I would be interested in hearing why `tf.image.resize` can't be modified before adding a `tfa.image.resize_nd` which esentially does the same thing.

**Comment by seanpmorgan** [comment]
Closing this issue as I do not see it as a separate addition, but rather an extension to `tf.image.resize`. Happy to have someone re-open this and discuss why it should be an addon instead.
