### ISSUE TITLE
Feature Request : PathNorm and PathSGD

### ISSUE THREAD

**Issue by AshishBora** [tensorflow/addons#633]
PathSGD was introduced in [this](https://arxiv.org/abs/1506.02617) paper. Is there existing support for this? If not, this is a feature request for:
- PathNorm computation (Equation 5 in the paper)
- PathSGD using the PathNorm

For the first part, the interface can be to provide a function `path_norm(a, b, p=2)` where `a` and `b` are tensors, `p` is a scalar. The function returns the p-PathNorm for the "path" between the tensors `a` and `b` (assuming that `b` depends on `a` and some weights. If not, there can be an exception or simply return `0`).

**Comment by seanpmorgan** [comment]
This seems like a good fit, but will need to confirm there is still a need from the community.

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
