### ISSUE TITLE
How to use addons in Java/Scala

### ISSUE THREAD

**Issue by maziyarpanahi** [tensorflow/addons#634]
**Describe the feature and the current behavior/state.**
Hi,

We use some `contrib` functions and for using them in Java/Scala we would find the `.so` files generated for each OS (mac, Linux, and windows) and load them with `TensorFlow.loadLibrary`.

I would like to know what should be the procedure in which we can use addons in our Java/Scala project? 

**Relevant information**
- Are you willing to contribute it (yes/no): yes
- Are you willing to maintain it going forward? (yes/no): yes
- Is there a relevant academic paper? (if so, where):
- Is there already an implementation in another framework? (if so, where):
- Was it part of tf.contrib? (if so, where):

**Who will benefit with this feature?**
All the projects using Java/Scala to access generated TF graph files.

**Comment by WindQAQ** [comment]
We currently do not have other language bindings, but you should find the `.so` files after installation under the package. Therefore, it would be in the same procedure like what you've done for contrib. 

https://github.com/tensorflow/addons/blob/master/tensorflow_addons/activations/gelu.py#L25

**Comment by maziyarpanahi** [comment]
@WindQAQ Thank you for your response. I am going to try it and let you know.

**Comment by WindQAQ** [comment]
Great. Then I am going to close this issue. Feel free to re-open it if you have further problem. Thanks.

**Comment by adithya1991** [comment]
@maziyarpanahi 
Where do we find the `.so` files after installation? Any help will be really helpful

**Comment by maziyarpanahi** [comment]
> @maziyarpanahi
> Where do we find the `.so` files after installation? Any help will be really helpful

I don't know the procedure for `addons` as most of the things we need are somehow natively supported by newer TensorFlow. But for the `contrib` or other stuff like `tensorflow-text`, once you install it, you can look for those in the PyPI packages. (keep in mind, those files are OS-based, so you may find .so for linux but you need .dl for Windows)
