### ISSUE TITLE
MacOS unable to load custom_op

### ISSUE THREAD

**Issue by luffywalf** [tensorflow/addons#638]
**System information**
- OS Platform and Distribution : mac  version:10.12.6
- TensorFlow version and how it was installed : tf-cpu = 2.0.0; installed with pip
- TensorFlow-Addons version and how it was installed : addons=0.6.0
- Python version: python==3.6.9 in conda 
- Is GPU used? (yes/no):no

**Describe the bug**
I just installed addons and wanna have a try.
my script is just one line: from tensorflow_addons import seq2seq 
when I use python to run it in Mac , it is like below
and when in linux, it run successfully.
is this a bug in Mac? 
thanks~~

(try-addons-py3.6) localhost:delta didi$ python test_addons.py
Traceback (most recent call last):
  File "test_addons.py", line 1, in <module>
    from tensorflow_addons import seq2seq
  File "/Users/didi/.local/lib/python3.6/site-packages/tensorflow_addons/__init__.py", line 75, in <module>
    from tensorflow_addons import image
  File "/Users/didi/.local/lib/python3.6/site-packages/tensorflow_addons/image/__init__.py", line 22, in <module>
    from tensorflow_addons.image.distance_transform import euclidean_dist_transform
  File "/Users/didi/.local/lib/python3.6/site-packages/tensorflow_addons/image/distance_transform.py", line 26, in <module>
    get_path_to_datafile("custom_ops/image/_image_ops.so"))
  File "/Users/didi/anaconda3/envs/try-addons-py3.6/lib/python3.6/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/didi/.local/lib/python3.6/site-packages/tensorflow_addons/custom_ops/image/_image_ops.so, 6): Library not loaded: @rpath/libtensorflow_framework.so
  Referenced from: /Users/didi/.local/lib/python3.6/site-packages/tensorflow_addons/custom_ops/image/_image_ops.so
  Reason: image not found

**Code to reproduce the issue**
from tensorflow_addons import seq2seq

**Comment by seanpmorgan** [comment]
Hi @luffywalf could you explain what you mean by binary `tf-cpu`? 

I just tried this and could not replicate your issue:
```
(addons-test) Seans-MacBook-Air:~ sean$ python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import tensorflow_addons as tfa
>>> tf.__version__
'2.0.0'
>>> tfa.__version__
'0.6.0'
>>> from tensorflow_addons import seq2seq
>>> 
```

**Comment by seanpmorgan** [comment]
Hi, I'm going to close this for now, but please re-open if this is re-producable / still happening.

**Comment by luffywalf** [comment]
tf-cpu, I mean tensorflow with cpu 
and i still got this error

**Comment by luffywalf** [comment]
I figure out why
this error is because my Mac version is 10.12, so tensorflow-addons0.3.1 was installed
when I update Mac to 10.15(>=10.13 will be fine) I can install tensorflow-addons==0.6.0 as I want

**Comment by seanpmorgan** [comment]
Great that's useful to know! Thanks for troubleshooting

**Comment by luffywalf** [comment]
sure!  ^ ^
