### ISSUE TITLE
Tensorflow 2.0: resampler not available

### ISSUE THREAD

**Issue by ltrottier** [tensorflow/addons#640]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

I would like [tensorflow.contrib.resampler.resampler](https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/contrib/resampler/resampler) to be available in TF 2.0. Or, any alternative that allows to interpolate a 2D grid at real coordinates.

**Will this change the current api? How?**

Yes, it will add a new function.

**Who will benefit with this feature?**

I was using `resampler` to optimize ROIAlign (of Mask-RCNN) with rotated bounding boxes (and masks). Instead of doing rotate -> crop -> resize to pool the rotated masks, I directly fetched it with resampler. It was about 2-3x faster.

So anyone who wants to pool random locations in a 2D grid (mostly for instance segmentation I think) could benefit from it.

**Any Other info.**

**Comment by seanpmorgan** [comment]
This seems like it would fit within `tfa.image`. Happy to review a PR for this feature migrated from:
https://github.com/tensorflow/tensorflow/tree/v1.15.0/tensorflow/contrib/resampler

**Comment by WindQAQ** [comment]
Closes via #662.
