### ISSUE TITLE
Questions about AttentionWrapper

### ISSUE THREAD

**Issue by lishi0927** [tensorflow/addons#647]
tensorflow 1.15 has a function "tf.contrib.seq2seq.AttentionWrapper", but as we know tf.contrib module is no longer available in TensorFlow 2.0. I find "tfa.seq2seq.AttentionWrapper" may replace "tf.contrib.seq2seq.AttentionWrapper", but there are many modified functions. 
For example, zero_state is no longer avaliable, and I want to use "get_initial_state" to replace this function, but there are some bugs.
My plateform is Ubuntu18.04, and i use python3.6, tensorflow 2.0.0;

The error information is shown as follows:
initial_state = decoder_cell.get_initial_state(inputs=None,batch_size = batch_size,  dtype=tf.float32).clone(cell_state=fake_encoder_state)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/rnn_cell_impl.py", line 309, in get_initial_state
    return self.zero_state(batch_size, dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/rnn_cell_wrapper_impl.py", line 199, in zero_state
    return self.cell.zero_state(batch_size, dtype)
AttributeError: 'AttentionWrapper' object has no attribute 'zero_state'

Could you give me some advice?
Thank you.

**Comment by guillaumekln** [comment]
Could you describe a bit more how you are using the `AttentionWrapper` class?

Usage examples can be found in the class [test file](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/attention_wrapper_test.py).

**Comment by lishi0927** [comment]
Thank you for your reply.

source code:

 def decode_outputs(self, target_words_vocab, target_input, batch_size, batched_contexts, valid_mask,
                       is_evaluating=False):
        num_contexts_per_example = tf.compat.v1.count_nonzero(valid_mask, axis=-1)

        start_fill = tf.fill([batch_size],
                             self.target_to_index[Common.SOS])  # (batch, )
        decoder_cell = tf.compat.v1.nn.rnn_cell.MultiRNNCell([
            tf.compat.v1.nn.rnn_cell.LSTMCell(self.config.DECODER_SIZE) for _ in range(self.config.NUM_DECODER_LAYERS)
        ])
        contexts_sum = tf.reduce_sum(batched_contexts * tf.expand_dims(valid_mask, -1),
                                     axis=1)  # (batch_size, dim * 2 + rnn_size)
        contexts_average = tf.compat.v1.divide(contexts_sum, tf.compat.v1.to_float(tf.expand_dims(num_contexts_per_example, -1)))
        fake_encoder_state = tuple(tf.compat.v1.nn.rnn_cell.LSTMStateTuple(contexts_average, contexts_average) for _ in
                                   range(self.config.NUM_DECODER_LAYERS))
        projection_layer = tf.compat.v1.layers.Dense(self.target_vocab_size, use_bias=False)
        if is_evaluating and self.config.BEAM_WIDTH > 0:
            batched_contexts = tfa.seq2seq.tile_batch(batched_contexts, multiplier=self.config.BEAM_WIDTH)
            num_contexts_per_example = tfa.seq2seq.tile_batch(num_contexts_per_example,
                                                                     multiplier=self.config.BEAM_WIDTH)
        attention_mechanism = tfa.seq2seq.LuongAttention(
            units=self.config.DECODER_SIZE,
            memory=batched_contexts
        )
        # TF doesn't support beam search with alignment history
        should_save_alignment_history = is_evaluating and self.config.BEAM_WIDTH == 0
        decoder_cell = tfa.seq2seq.AttentionWrapper(decoder_cell, attention_mechanism,
                                                           attention_layer_size=self.config.DECODER_SIZE,
                                                           alignment_history=should_save_alignment_history)
       decoder_cell = tf.compat.v1.nn.rnn_cell.DropoutWrapper(decoder_cell,
                                                         output_keep_prob=self.config.RNN_DROPOUT_KEEP_PROB)
       target_words_embedding = tf.compat.v1.nn.embedding_lookup(target_words_vocab,
                                                            tf.concat([tf.expand_dims(start_fill, -1), target_input],
                                                                      axis=-1))  # (batch, max_target_parts, dim * 2 + rnn_size)
      inithelper = tfa.seq2seq.TrainingSampler()
      helper = inithelper.initialize(inputs=target_words_embedding,
                                                       sequence_length=tf.ones([batch_size], dtype=tf.int32) * (
                                                           self.config.MAX_TARGET_PARTS + 1))

      initial_state = decoder_cell.get_initial_state(inputs=None, batch_size = batch_size, dtype=tf.float32).clone(cell_state=fake_encoder_state)

      decoder = tfa.seq2seq.BasicDecoder(cell=decoder_cell, helper=helper, initial_state=initial_state,
                                                      output_layer=projection_layer)
     outputs, final_states, final_sequence_lengths = tfa.seq2seq.dynamic_decode(decoder, maximum_iterations=self.config.MAX_TARGET_PARTS + 1)
     return outputs, final_states

**Comment by guillaumekln** [comment]
`tfa.seq2seq.AttentionWrapper` is not expected to work with `tf.compat.v1` modules.

You should try to update your code by using layers from TensorFlow 2.0, e.g.:

* `tf.compat.v1.nn.rnn_cell.LSTMCell` -> `tf.keras.layers.LSTM`
* `tf.compat.v1.nn.rnn_cell.DropoutWrapper` -> `tf.nn.RNNCellDropoutWrapper`
* etc.

**Comment by lishi0927** [comment]
Okay.
Thank you for your reply.

**Comment by lishi0927** [comment]
Thank you.
And what about "tf.nn.bidirectional_dynamic_rnn“ in tensorflow 2.0?

**Comment by WindQAQ** [comment]
> Thank you.
> And what about "tf.nn.bidirectional_dynamic_rnn“ in tensorflow 2.0?

It should be [tf.keras.layers.Bidirectional](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Bidirectional). Remember to mask padding values as stated [here](https://www.tensorflow.org/guide/keras/masking_and_padding).

**Comment by guillaumekln** [comment]
I think the main issue has been addressed. Feel free to reopen if you encounter specific issues in using `tfa.seq2seq`.

**Comment by mukurgupta** [comment]
@guillaumekln 

I made the changes you suggested earlier but now the error is:

> 'LSTM' object has no attribute 'zero_state'

Would appreciate any help.

**Comment by guillaumekln** [comment]
You should replace this method with `get_initial_state`. See https://www.tensorflow.org/api_docs/python/tf/keras/layers/AbstractRNNCell#get_initial_state
