### ISSUE TITLE
Error given while trying to import tensorflow-addons

### ISSUE THREAD

**Issue by pabloduque0** [tensorflow/addons#655]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Description:	Ubuntu 18.04.3 LTS, Release:	18.04
- TensorFlow version and how it was installed (source or binary):  Installed from pip, version: 2.0.0b1
- TensorFlow-Addons version and how it was installed (source or binary): Installed from pip, version 0.6.0
- Python version: 3.6.8
- Is GPU used? (yes/no): no

importing the library gives the following error:

lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid name: Addons>Gelu (Did you use CamelCase?); in OpDef: name: "Addons>Gelu" input_arg { name: "features" type_attr: "T" } output_arg { name: "activations" type_attr: "T" } attr { name: "T" type: "type" allowed_values { list { type: DT_HALF type: DT_FLOAT type: DT_DOUBLE } } } attr { name: "approximate" type: "bool" default_value { b: true } }

**Comment by seanpmorgan** [comment]
v0.6.0 is only compatible with `tensorflow==2.0.0`. The error you're getting is because Op Namespacing wasn't available in beta1.

**Comment by Dahkenangnon** [comment]
How to solve the problem please ?

**Comment by pabloduque0** [comment]
Upgrade to tensorflow 2.0 or greater
