### ISSUE TITLE
Dendrite morphological neural networks

### ISSUE THREAD

**Issue by Ahmad-Masood** [tensorflow/addons#660]
Can you guys also provide an implementation for Dendrite morphological neural networks in tensorflow. 

http://www.sciencedirect.com/science/article/pii/S0925231213010916

**Comment by seanpmorgan** [comment]
Hi, without having read the paper in its entirety does anyone have any information about what aspects of this would fit within TFA (Layers, optimizers, etc.)?

Addons need to be components that fit into the APIs.

**Comment by seanpmorgan** [comment]
Closing. Feel free to re-open with details regarding how this would fit within the Addons API structure.
