### ISSUE TITLE
Missing symbol for Abseil ParseTime Op

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#663]
**Describe the bug**
Since the 20101030 nightly, our library fails when opening the `_parse_time_op.so` because of an undefined symbol error. Typically this occurs when there is an ABI incompatibility between core TensorFlow and our custom-ops. 

```
tensorflow.python.framework.errors_impl.NotFoundError: .../custom_ops/text/_parse_time_op.so: undefined symbol: _ZN4absl9ParseTimeERKSsS1_PNS_4TimeEPSs
```

This particular [custom-op utilizes absl](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/custom_ops/text/cc/kernels/parse_time_kernel.cc#L75) and the mangled symbol name does not match what our compiled operation thinks it should be. I'm not really sure how this would happen since the rest of the TensorFlow library was compiled with a compatible gcc version.

CC'ing some people who may have insight into how this can happen:
@yifeif @r4nt @perfinion @gunan 

I suppose we could make absl a dependency in our TFA build and compile it ourselves but this seems to be going down a bad path.

Failing Log:
https://source.cloud.google.com/results/invocations/a71d103a-ecac-421c-bc53-ef06648fdc9f/targets/tensorflow_addons%2Fubuntu%2Fgpu%2Fpy3%2Fpresubmit/log

**Comment by r4nt** [comment]
@scentini for whether this might be due to us not exporting all symbols from absl any more

**Comment by scentini** [comment]
Yep, seems like it is related to [f58c9f8](https://github.com/tensorflow/tensorflow/commit/f58c9f835c32e02895bdd629c7660567ae011001), which changes what we export, see https://github.com/bazelbuild/bazel/issues/7362.

The absl symbols probably came from [here](https://github.com/tensorflow/addons/blob/c3aba0818b6e74ac3a4341d00242c464584c8b50/tensorflow_addons/tensorflow_addons.bzl#L13), and due to [f58c9f8](https://github.com/tensorflow/tensorflow/commit/f58c9f835c32e02895bdd629c7660567ae011001) we just don't export the symbol anymore.
I think the right way forward is to make [_parse_time_op.so](https://github.com/tensorflow/addons/blob/c3aba0818b6e74ac3a4341d00242c464584c8b50/tensorflow_addons/custom_ops/text/BUILD#L16) depend on absl.

**Comment by seanpmorgan** [comment]
Great thanks that makes sense! cc @helinwang as code owner. 

Helin if you have time could you submit a patch to add absl as a build dependency.

**Comment by scentini** [comment]
After discussion with @r4nt, it might be better to not pass the absl dependency to [_parse_time_op.so](https://github.com/tensorflow/addons/blob/c3aba0818b6e74ac3a4341d00242c464584c8b50/tensorflow_addons/custom_ops/text/BUILD#L16), but rather add `alwayslink = 1` to the `absl` library. (thus make sure that absl symbols are present in [@local_config_tf//:libtensorflow_framework](https://github.com/tensorflow/addons/blob/c3aba0818b6e74ac3a4341d00242c464584c8b50/tensorflow_addons/tensorflow_addons.bzl#L13))

The reason for this is, if we pass `absl` as a dependency, we may end up linking global initializers multiple times.

I can send out a fix for this tomorrow.

**Comment by helinwang** [comment]
Thanks, everyone! If there is anything I can help, please let me know.

**Comment by seanpmorgan** [comment]
Hmmm so it seems whatever has landed in the tf_nightly-2.1.0.dev20191114 nightly has not fixed this build issue:
https://source.cloud.google.com/results/invocations/f7858a66-3ac1-4717-a85a-bf160e754918/targets/tensorflow_addons%2Fubuntu%2Fcpu%2Fpy3%2Fpresubmit/log

I saw there was some issues with merging the patch... can we confirm that the fix landed but didn't solve our issue @scentini @helinwang

**Comment by scentini** [comment]
The PR that fixed this was reverted in [5acf6bd](https://github.com/tensorflow/tensorflow/commit/5acf6bdd2ba4cf1640c983c3b8c3c991715048e9).
An internal PR that'll fix this and similar issues by reverting the change that introduced these errors is in the process of being merged.

**Comment by georgesterpu** [comment]
@seanpmorgan it appears to work now with
```
tf-nightly                2.1.0.dev20191119
tfa-nightly               0.7.0.dev20191119
```

**Comment by seanpmorgan** [comment]
> @seanpmorgan it appears to work now with
> 
> ```
> tf-nightly                2.1.0.dev20191119
> tfa-nightly               0.7.0.dev20191119
> ```

Thanks @georgesterpu! https://github.com/tensorflow/addons/pull/658

**Comment by seanpmorgan** [comment]
> The PR that fixed this was reverted in [5acf6bd](https://github.com/tensorflow/tensorflow/commit/5acf6bdd2ba4cf1640c983c3b8c3c991715048e9).
> An internal PR that'll fix this and similar issues by reverting the change that introduced these errors is in the process of being merged.

@scentini @r4nt Now that the fix has landed do we know if it'll be cherry-picked onto r2.1?

**Comment by scentini** [comment]
Unfortunately this fix caused internal breakages, so we'll be rolling it back. Whatever the solution is, it will be cherrypicked onto r2.1. I'll keep you updated.

**Comment by Squadrick** [comment]
[Failure log](https://source.cloud.google.com/results/invocations/cf194363-d647-4caa-82d2-5e783fc33296/targets/tensorflow_addons%2Fubuntu%2Fgpu%2Fpy2%2Fpresubmit/log). 

Version: `tf_nightly-2.1.0.dev20191120`

Error:
```
tensorflow_addons/custom_ops/text/_parse_time_op.so: undefined symbol: _ZN4absl9ParseTimeERKSsS1_PNS_4TimeEPSs
```

We'll need to pin it to `tf_nightly-2.1.0.dev20191119`.

**Comment by ezzeldinadel** [comment]
still suffering from this in the current nightly build

**Comment by seanpmorgan** [comment]
> still suffering from this in the current nightly build

Hi @ezzeldinadel can you confirm the nightly version you're using. We've dropped the ParseTime Op until a fix has landed in TF-core so there should be no issue with the nightlies:

https://colab.research.google.com/drive/1KV4J4Gs9VrNmxzstXQOhdYufg1BASaVI

**Comment by seanpmorgan** [comment]
#728 is passing so I'm assuming this fix landed in nightly. Can we confirm that it was picked into 2.1?

**Comment by seanpmorgan** [comment]
Hi @scentini so I checked and this build fails on TF2.1rc0 but passes on tf-nightly. Could you point me to the commit that ultimately fixed this so I can request it to be picked into TF2.1? (Assuming that isn't already happening)

**Comment by scentini** [comment]
The commit was https://github.com/tensorflow/tensorflow/commit/c9d1b6dc3ada4aa88e97725b11ffb2371e75f355, I asked for it to be cherrypicked, you can follow https://github.com/tensorflow/tensorflow/pull/34764. Thank you for your patience!

**Comment by seanpmorgan** [comment]
Thanks very much for your help!

**Comment by helinwang** [comment]
Thanks @scentini and @seanpmorgan !
