### ISSUE TITLE
How to use seq2seq attention in eager mode?

### ISSUE THREAD

**Issue by matthen** [tensorflow/addons#670]
**System information**
- OS Platform and Distribution: ubuntu 
- TensorFlow version and how it was installed (source or binary): pip install tensorflow_gpu==2.0.0b1
- TensorFlow-Addons version and how it was installed (source or binary): pip install tfa-nightly (dev20190811)
- Python version: 3.6.8
- Is GPU used? (yes/no): yes

I can't figure out how I am supposed to set up attention with `tfa.seq2seq` in eager mode. Here is the code I am trying:

```python

# create layers, do not feed input data yet
gru_cell = tf.keras.layers.GRUCell(256)
attn_mech = tfa.seq2seq.LuongAttention(128)
attn_cell = tfa.seq2seq.AttentionWrapper(
    cell=gru_cell,
    attention_mechanism=attn_mech,
    alignment_history=True,
)


# in eager mode, feed data through the layers
batch_size = 3
dummy_memory = tf.zeros([batch_size, 12, 128])
attn_mech(dummy_memory, setup_memory=True)
initial_state = attn_cell.get_initial_state(batch_size=batch_size, dtype=tf.float32)
```

this fails at the line creating the `AttentionWrapper`, with the traceback below. It seems to imply that the attention wrapper requires the memory to already be setup.

How am I supposed to do this? 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-e505d2e7f63f> in <module>
     12     cell=gru_cell,
     13     attention_mechanism=attn_mech,
---> 14     alignment_history=True,
     15 )
     16 

~/my-project/venv/lib/python3.6/site-packages/tensorflow_addons/seq2seq/attention_wrapper.py in __init__(self, cell, attention_mechanism, attention_layer_size, alignment_history, cell_input_fn, output_attention, initial_cell_state, name, attention_layer, attention_fn)
   1700             self._attention_layer_size = sum(
   1701                 tf.compat.dimension_value(attention_mechanism.values.shape[-1])
-> 1702                 for attention_mechanism in attention_mechanisms)
   1703 
   1704         if attention_fn is None:

~/my-project/venv/lib/python3.6/site-packages/tensorflow_addons/seq2seq/attention_wrapper.py in <genexpr>(.0)
   1700             self._attention_layer_size = sum(
   1701                 tf.compat.dimension_value(attention_mechanism.values.shape[-1])
-> 1702                 for attention_mechanism in attention_mechanisms)
   1703 
   1704         if attention_fn is None:

AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by matthen** [comment]
I had to upgrade pip to 19, and it installed a more recent nightly build. However that is broken with this error: https://github.com/tensorflow/addons/issues/663

I'm guessing seq2seq in tensorflow 2.0 is not ready yet

**Comment by guillaumekln** [comment]
Did you try with TensorFlow Addons 0.6.0 and TensorFlow 2.0?

**Comment by matthen** [comment]
@guillaumekln aha yes that seems to be working! I think my problem was that I didn't have pip 19.0.0, so I was getting some old buggy version of tf addons. (maybe that requirement should be made more prominent?)

**Comment by seanpmorgan** [comment]
@matthen so the thought on this was that TF2 requires pip 19 as well so users should have had it installed already. I think that may be a bit of a shaky assumption though.

@tensorflow/sig-addons-maintainers Would anyone be opposed to me deleting all manylinux1 whls that should be quite stale at this point.

**Comment by matthen** [comment]
(@seanpmorgan I managed to get tensorflow 2.0.0b with an earlier pip, so I didn't realise the issue initially)
