### ISSUE TITLE
Future Release

### ISSUE THREAD

**Issue by digantamisra98** [tensorflow/addons#683]
Just a small inquiry regarding when the next release with all the recent additions is coming?

**Comment by seanpmorgan** [comment]
Hi @digantamisra98! Since #664 we have a breaking change since that Keras registration API was added after 2.0 release.

2.1 branch was scheduled to be cut this afternoon so most likely within the next few weeks we'll have a release to go alongside it.
https://groups.google.com/a/tensorflow.org/forum/#!topic/developers/DK4QK25ViA4

**Comment by WindQAQ** [comment]
Please note that we also have nightly build, so if you want to try new things/commits, you might also use `pip install tfa-nightly`.

**Comment by qo4on** [comment]
> Please note that we also have nightly build, so if you want to try new things/commits, you might also use `pip install tfa-nightly`.

Do you know how to import `tfa` after `pip install tfa-nightly`?

**Comment by Squadrick** [comment]
> Do you know how to import `tfa` after `pip install tfa-nightly`?

```python
import tensorflow_addons as tfa
```

**Comment by qo4on** [comment]
> ```python
> import tensorflow_addons as tfa
> ```

This doesn't work in Colab:
```
!pip install tfa-nightly
import tensorflow_addons as tfa

NotFoundError                             Traceback (most recent call last)
<ipython-input-1-ab0853e194ea> in <module>()
      1 get_ipython().system('pip install tfa-nightly')
----> 2 import tensorflow_addons as tfa
```

**Comment by seanpmorgan** [comment]
So you'll want to use `tf-nighly` with our `tfa-nightly` as that is what it's built against. Unfortunately, our build is pinned to a slightly old (~week) nightly as we wait for a resolution in #663 

If this is blocking you today you can use the `tf-nightly==2.1.0.dev20191029` version with the latest addons as shown in this notebook:
https://colab.research.google.com/drive/1yW4ZLkIxdo4hGj55RQ4u3GTPF0xX6x7s

Closing but feel free to re-open if there are more issues.
