### ISSUE TITLE
seq2seq - using GRUCell in attention wrapper

### ISSUE THREAD

**Issue by matthen** [tensorflow/addons#684]
**System information**
- OS Platform and Distribution: ubuntu
- TensorFlow version and how it was installed: `pip install tensorflow_gpu==2.0.0` 
- TensorFlow-Addons version and how it was installed (source or binary): `pip install tensorflow_addons==0.6.0`
- Python version: 3.6.8
- Is GPU used? (yes/no): yes

(sorry for reporting yet another stumbling block..!)

```python
attn_mech = tfa.seq2seq.LuongAttention(128)

decoder_cell = tfa.seq2seq.AttentionWrapper(
    cell=tf.keras.layers.GRUCell(128),  # cell=tf.keras.layers.LSTMCell(128)
    attention_mechanism=attn_mech,
    alignment_history=True,
    output_attention=False,
)


sampler = tfa.seq2seq.TrainingSampler()
decode = tfa.seq2seq.BasicDecoder(decoder_cell, sampler)

batch_size = 3

dummy_memory = np.ones([batch_size, 5, 128], dtype=np.float32)
dummy_target = np.ones([batch_size, 7, 128], dtype=np.float32)


attn_mech.setup_memory(dummy_memory, memory_sequence_length=[3, 3, 3])        
initial_state = decoder_cell.get_initial_state(batch_size=batch_size, dtype=tf.float32)        
decoder_outputs, final_decoder_state, _ = decode(
    dummy_target, initial_state=initial_state, sequence_length=[5,6,7])
```

this fails on the last line with:

```
InvalidArgumentError: In[0] is not a matrix. Instead it has shape [128] [Op:MatMul] name: basic_decoder_17/decoder/while/attention_wrapper_22/gru_cell_28/MatMul/
```

If I switch to using `cell=tf.keras.layers.LSTMCell(128)` in the `AttentionWrapper`, then there is no exception raised. But given it fails for `GRUCell`, I am a bit suspicious it is doing the right thing

**Comment by guillaumekln** [comment]
It looks like the `GRUCell` is not compatible with its own initial state. The following example fails with the same error:

```python
import tensorflow as tf
batch_size = 4
cell = tf.keras.layers.GRUCell(20)
initial_state = cell.get_initial_state(batch_size=batch_size, dtype=tf.float32)
output, state = cell(tf.random.uniform([batch_size, 10]), initial_state)
```

The cell expects that `states` is a list (or tuple):

https://github.com/tensorflow/tensorflow/blob/v2.0.0/tensorflow/python/keras/layers/recurrent.py#L1629

@qlzh727 Is this an issue for `tf.keras` or should `tfa.seq2seq` ensure that the state is a Python sequence?

**Comment by guillaumekln** [comment]
I opened the issue there: https://github.com/tensorflow/tensorflow/issues/34789

I believe this should be handled on the TensorFlow side so let me close this issue.
