### ISSUE TITLE
pip install tensorflow-addons depends on tensorflow_gpu?

### ISSUE THREAD

**Issue by valendin** [tensorflow/addons#706]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow version and how it was installed (source or binary): conda install tensorflow
- TensorFlow-Addons version and how it was installed (source or binary): pip install tensorflow-addons
- Python version: 3.7.4
- Is GPU used? (yes/no): no

**Describe the bug**

Note that this is a machine without an NVidia GPU, using cpu version of TF. I would expect that tensorflow-addons do not depend on having a GPU version of TF?

**Code to reproduce the issue**

pip install tensorflow-addons

**Comment by seanpmorgan** [comment]
Hi @valendin tensorflow-gpu should work fine on system without a GPU and simply fallback to CPU. Once TF 2.1 is released the packages will be considated into simply `tensorflow`. At that point we can get rid of our hacky dependencies.

Please let us know if there are still issues. I suspect you're going to run into one by conda installing TF and pip installing TFA. It's a known issue and there's a larger effort to make sure it works: 
https://github.com/tensorflow/community/pulls
