### ISSUE TITLE
Can't import TQDMProgressBar

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/addons#707]
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow version and how it was installed: pip (2.0.0)
- TensorFlow-Addons version and how it was installed: `pip install -q --no-deps tensorflow-addons~=0.6`
- Python version: 3.6.8
- Is GPU used?: yes

**Describe the bug**

I can't import `TQDMProgressBar`.

**Code to reproduce the issue**

```python
import tensorflow_addons as tfa
print(tfa.__version__)
tfa.callbacks.TQDMProgressBar
```

**Other info / logs**
This issue appeared when discussing with @shun-lin , I originally described it in https://github.com/tensorflow/tensorflow/issues/34417, but felt it made more sense to discuss it here.
Apparently I could install from source to try and solve it, but it's not in my priorities right now.

**Comment by shun-lin** [comment]
@seanpmorgan is it because it will be included in the next release but not the current one? Thanks!

**Comment by Squadrick** [comment]
@zaccharieramzi Like @shun-lin mentioned, `TQDMProgressBar` isn't included in `r0.6`. You can either build TFA from source or install `tfa-nightly`.

**Comment by zaccharieramzi** [comment]
Sure makes sense. Probably [the notebook introducing the `TQMProgressBar`](https://github.com/tensorflow/addons/blob/master/docs/tutorials/tqdm_progress_bar.ipynb) needs to be updated to reflect that, because it says that you can use it with 0.6.

**Comment by zaccharieramzi** [comment]
I also have this other error with `tfa-nightly` (without dependencies): `AttributeError: module 'tensorflow_core.keras.utils' has no attribute 'register_keras_serializable'`

If I install with dependencies:
```
NotFoundError: /mypath/tests/venv/lib/python3.6/site-packages/tensorflow_addons/custom_ops/text/_parse_time_op.so: undefined symbol: _ZN4absl9ParseTimeERKSsS1_PNS_4TimeEPSs
```

**Comment by Squadrick** [comment]
We currently have a breakage due to upstream tf-nightly. We're working on resolving it: #709 

In the meantime, you can install `tf-nightly==2.1.0.dev20191119`.
