### ISSUE TITLE
cannot install on windows and ubuntu ???

### ISSUE THREAD

**Issue by bodekjan** [tensorflow/addons#715]
I need to install this package(v 0.6.0) on my computer. 
When i trying to install on Windows10, pip cannot find this package.
When i trying to install on Ubuntu18, pip only can install v0.4.0 , i open pypi.org website and download tensorflow_addons-0.6.0-cp36-cp36m-manylinux2010_x86_64.whl manualy install, and it also failed by message :  xxx.whl is not a supported wheel on this platform.
So please tell me what kind of enviroment does tensorflow-addons==0.6.0 need???

**Comment by seanpmorgan** [comment]
Hi @bodekjan there is currently no release for Windows see #173 .

Ubuntu18 should be fine -- but the pip is packaged as manylinux2010 so you'll need to update your pip version:
```
pip install --upgrade pip
pip install tensorflow-addons==0.6.0
```
