### ISSUE TITLE
tfa.layers.WeightNormalization fails with Assert when called by multiple threads

### ISSUE THREAD

**Issue by dominikroblek** [tensorflow/addons#722]
### Issue description

`tfa.layers.WeightNormalization` fails with the following Tensorflow assert failure when used by multiple threads (e.g., when the same layer wrapped by `tfa.layers.WeightNormalization` is part of two parallel execution flows in a Tensorflow graph while reusing the variables):
```
(0) Invalid argument: assertion failed: [The layer has been initialized.] [Condition x == y did not hold element-wise:] [x (discriminator/discriminator_1/n_layer_discriminator/sequential_21/grouped_conv1d_3/weight_normalization_304/cond/assert_equal_1/ReadVariableOp:0) = ] [1] [y (discriminator/discriminator_1/n_layer_discriminator/sequential_21/grouped_conv1d_3/weight_normalization_304/cond/assert_equal_1/y:0) = ] [0]
[[{{node discriminator/discriminator_1/n_layer_discriminator/sequential_21/grouped_conv1d_3/weight_normalization_304/cond/assert_equal_1/Assert/AssertGuard/Assert}}]]
```

### Proposed solution

Add the following line of code to the `tfa.layers.WeightNormalization.build` function:
```
self._initialized_critical_section = tf.CriticalSection(name='initialized_mutex')
```

Replace `g = tf.cond(self._initialized, _do_nothing, _update_weights)` in the `tfa.layers.WeightNormalization.call` function with the following lines of code:
```
def _get_initialized_weights():
    return tf.cond(self._initialized, _do_nothing, _update_weights)
g = self._initialized_critical_section.execute(_get_initialized_weights)
```

**Comment by WindQAQ** [comment]
Hi @dominikroblek, thanks for the report! Are you willing to fill a PR and add some unittests for it? Thank you again.

**Comment by failure-to-thrive** [comment]
What I see from the assert message (_[The layer has been initialized.]_) - it has nothing to do with the race conditions of parallel execution. It's a "multiple initializations" problem. CriticalSection won't help. Atomic flag (test-and-set lock mechanism) should have been there. And a piece of code to reproduce the problem, in the first place.
