### ISSUE TITLE
Package Addons 0.7 with TF2.1

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#725]
2.1rc has been released:
https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/UAddBVYncLE

There have been a lot of additions and requests for a new package. We can increase minor version as the RC increments. 

This depends on: #719 since 2.1 is built against CUDA 10.1

**Comment by guillaumekln** [comment]
Do you also plan to depend on `tensorflow` instead of `tensorflow-gpu` now that Pip packages are consolidated?

**Comment by seanpmorgan** [comment]
> Do you also plan to depend on `tensorflow` instead of `tensorflow-gpu` now that Pip packages are consolidated?

Yup. Will send a small clean-up PR once #730 gets merged.

**Comment by seanpmorgan** [comment]
Just as an update we'll be waiting for TF2.1-rc1 prior to this release (should be in the very near future). This will allow us to keep ParseTime Op in the release and gives us a little time to see how much work is needed to add a Windows release.

**Comment by seanpmorgan** [comment]
RC1 has been released. Cutting the branch; but may take a couple days due to other priorities

**Comment by veqtor** [comment]
2.1.0 is out!

**Comment by seanpmorgan** [comment]
0.7.0 has been released!
https://github.com/tensorflow/addons/releases/tag/v0.7.0
