### ISSUE TITLE
Add comprehensive tests for group/instance normalization layers

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#731]
As seen in #611 the test coverage validates the result of GroupNormalization by replicating the same procedure (which is to be tested) in numpy. 

We should instead update the test case so that we validate the result against an easily computable tensor. Hardcoding the result for several different axes to be grouped.

**Comment by manda-creator** [comment]
This is an issue that I would like to contribute to.

**Comment by seanpmorgan** [comment]
> This is an issue that I would like to contribute to.

Great! Welcome to addons please let us know if you need any further information to create a PR

**Comment by failure-to-thrive** [comment]
Excuse me, but what's the current state of affairs? Hasn't #766 done that?

**Comment by seanpmorgan** [comment]
@autoih what is the status of #766. Its still marked as WIP

**Comment by autoih** [comment]
Thanks @seanpmorgan for the reminder. I've updated the test.

**Comment by us** [comment]
#766 was merged so I think this issue can be closed.
