### ISSUE TITLE
Publish Python3.8 package

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#744]
TF core is getting very close to being able to package for py3.8. We will follow suit quickly after them: 
https://github.com/tensorflow/tensorflow/issues/33374

**Comment by 372046933** [comment]
Seems that in the process of releasing. But I  can't install with pip right now.

https://github.com/tensorflow/tensorflow/issues/33374#issuecomment-562663993

**Comment by seanpmorgan** [comment]
Version 0.10 includes a python3.8 wheel. Closing.
