### ISSUE TITLE
Adding animated progress bar for tf.keras

### ISSUE THREAD

**Issue by rpalakkal** [tensorflow/addons#749]
Hello,

Currently the tf.keras Progbar and ProgbarLogger classes provide a progress bar for monitoring training but these only measure the progress of the current epoch and are also don't have the capability for fully animated progress bars for notebooks like Google Colab or Jupyter Notebooks/Labs. 

I started developing a tf.keras callback to do this as part of a Google Code-In task. Here is the link to the Google Colab: [Colab](https://colab.research.google.com/drive/1t0gDGQ74OMfbrXE0yX6U4hC-G4e2KTj5#scrollTo=Dh_dQVUHEIU0). The callback has one progress bar tracking which epoch the training is on, as well as child progress bars for each epoch.  I am definitely willing to help contribute and possibly maintain it in the future. I am submitting this to tensorflow/addons because I see this as a nice feature which could make logs interactive and interesting. Is this the right place to bring up this feature, or should I just bring up this feature request in tensorflow/tensorflow?

Thanks.

**Comment by shun-lin** [comment]
Hi,

I have implmented a TQDM progress bar here on Addons not too long ago, would this works for your use case? Also if you want to extend the tqdm progress bar here on Addons feel free to send PR!

Tutorial:
https://github.com/tensorflow/addons/blob/master/docs/tutorials/tqdm_progress_bar.ipynb

**Comment by seanpmorgan** [comment]
Closing, but feel free to ask to re-open if TQDM progress bar does not meet your needs. It will be included in the upcoming 0.7 release
