### ISSUE TITLE
Package Addons for python3.7 

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#75]
Using the current docker image, we're unable to install / build TensorFlow in python3.7 with the following error:
```
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /root/miniconda2/envs/py37/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
```

It seems like we need to compile using Ubuntu 16.04 libs, which will require a bump in the custom-op docker image. @yifeif would it be possible to bump the base image in the container? If so we can rebuild our release as 0.1.1 and include py37.

Alternatively, we could create a new docker image for builds.

**Comment by facaiy** [comment]
@dynamicwebpaige Paige, tf-2.0-preview has supported python 3.7 in https://github.com/tensorflow/tensorflow/issues/25429 . Could you tell us how did you do it?

**Comment by seanpmorgan** [comment]
cc @gunan. Is ubuntu 14.04 being used for the build or some other docker image?

**Comment by gunan** [comment]
For python 3.7, we had to base our builders off of ubuntu 16.04.
Everything else uses ubuntu 14.04

**Comment by yifeif** [comment]
We will definitely need a new image for python3.7.

**Comment by seanpmorgan** [comment]
Addons 0.2.0 has a py37 available on pypi

**Comment by seanpmorgan** [comment]
Bumping to ubuntu16+GCC5 caused issues issues as seen here in the most recent builds of TF:
https://github.com/tensorflow/tensorflow/issues/27067

This will remain unsoved until the manylinux2010 toolchain is finalized. See #119

**Comment by hartikainen** [comment]
What's the ETA for tf addons python 3.7 support?

**Comment by seanpmorgan** [comment]
@perfinion is there an updated build environment and date when TF pip packages will be built in it? Just for reference python 3.8 release is soon.

**Comment by seanpmorgan** [comment]
Looks like this is almost ready:
https://github.com/tensorflow/tensorflow/commit/ec83c8a8292aa881b701928a7ffbe2305cc0e4e5

@av8ramit Could you comment on the above question?

**Comment by av8ramit** [comment]
Ideally worst case within two weeks we will transition over. Waiting on one last issue with GPU custom ops.
