### ISSUE TITLE
Allow passing in a tensor to tfa.optimizers.MovingAverage num_updates

### ISSUE THREAD

**Issue by Hyperparticle** [tensorflow/addons#754]
Currently, `tfa.optimizers.MovingAverage` has an assert that requires `num_updates` to be of type int, [shown here](https://github.com/tensorflow/addons/blob/604a70de563f8797984c9c3f002aff70bef6c90b/tensorflow_addons/optimizers/moving_average.py#L81). This prevents me from passing in an integer tensor that changes with the global step, which is officially supported by `tf.train.ExponentialMovingAverage`.

Can this assert be updated to handle this use case?

**Comment by SSaishruthi** [comment]
@seanpmorgan I was looking at the code and looks like we just need to remove the check for `int`. Is that right? I will create a PR if that is right

**Comment by Hyperparticle** [comment]
Yes, either remove the int check or additionally check if the input is a tensor.

**Comment by SSaishruthi** [comment]
Thanks. Creating PR now

**Comment by guillaumekln** [comment]
Is the `num_updates` argument necessary? Why not using `optimizer.iterations` directly?

**Comment by Hyperparticle** [comment]
It's possible you might want to change the moving average over time with custom behavior and `num_updates` would do that. However, the current code changes have broken this again. It looks like you won't be able to change the moving average ratio every step, only at the beginning.
