### ISSUE TITLE
python rnn GRU/LSTM ops support in addons

### ISSUE THREAD

**Issue by dianjunsun** [tensorflow/addons#756]
In previous TF we have optimized gru/lstm op implementation for CPU and GPU, in TF2.0 kernel we still have these but seems no python interface anymore.

TF 2.0 Kernel:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/kernels/rnn

In contrib TF1.8:
https://github.com/tensorflow/tensorflow/blob/1.8.0/tensorflow/contrib/rnn/python/ops/gru_ops.py

**Comment by seanpmorgan** [comment]
Hi @dianjunsun sorry for the delay../..

In TF2 the recommend way to implement GRU/LSTM ops would be to utilize a Keras layer:
https://www.tensorflow.org/api_docs/python/tf/keras/layers/GRU?version=stable
https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM?version=stable

Does that cover your use-case?

**Comment by seanpmorgan** [comment]
Closing... feel free to ask for a re-open if that doesn't cover it.
