### ISSUE TITLE
Automate Build Process

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#76]
Currently we have no automated process for building Addons across python version and operating systems. Going forward we'll want this process to be automated.. but it may be challenging for us to start builds without access to the Google internal tooling.

We could conceivably use Travis... but if we can keep consistent CI that would be ideal.

**Comment by seanpmorgan** [comment]
Good example that we could adapt. Still need to determine how we can trigger a release build.
https://github.com/apache/arrow/blob/master/python/manylinux1/build_arrow.sh

**Comment by seanpmorgan** [comment]
@karmel @av8ramit I've start working on this as well as #77 and wanted to see if we could discuss our options.

1. Will we be able to use Google infra to build our releases?
2. Would that be something the Addons release team could trigger? Or will it need to be an internal team member.
2. Are there OSX instances we can use?

**Comment by karmel** [comment]
1. We could in theory set up scripts/builds for release building as well as testing.
2. Remind me-- are you able to trigger the testing builds? If so, presumably the same would work for release builds as well. ( @av8ramit to correct me if I'm wrong)
3. Oof. They are really hard to come by-- @av8ramit , do you know the feasibility of doing mac osx builds for addons?

If we can make this work with Travis, that might be preferable long-term insofar as the keys are in your hands; are there blockers to that currently?

CC @ewilderj @martinwicke , FYI

**Comment by av8ramit** [comment]
@seanpmorgan and @karmel 

2. You are correct. If you can trigger them via GitHub labels it should work. 
3. You can do Mac OSX builds for addons via the internal infrastructure we are using for presubmits and ci testing. Someone internally will have to maintain that though.

**Comment by seanpmorgan** [comment]
Thanks for the followup. Yeah we currently trigger tests using the korkoro label which works great, but labels seem a bit clunky for builds/releases.

I've started a branch using travis which will build nightly packages and allow us to trigger releases.
