### ISSUE TITLE
build from source code then reinstall tensorflow

### ISSUE THREAD

**Issue by SmileTM** [tensorflow/addons#775]
cuda 9.0
cudnn 7

I had installed tensorflow2.0-gpu that was bazeled from source code. 
And tf.test.is_gpu_available()  is true

Then I had changed configure.sh 
```
if [[ "$TF_NEED_CUDA" == "1" ]]; then
    write_action_env_to_bazelrc "TF_NEED_CUDA" ${TF_NEED_CUDA}
    write_action_env_to_bazelrc "CUDNN_INSTALL_PATH" "${CUDNN_INSTALL_PATH:=/disk1/lx/cuda/lib64}"
    write_action_env_to_bazelrc "TF_CUDA_VERSION" "9.0"
    write_action_env_to_bazelrc "TF_CUDNN_VERSION" "7"
    write_action_env_to_bazelrc "CUDA_TOOLKIT_PATH" "${CUDA_HOME:=/disk1/lx/cuda}"

```
Then I run ./configure.sh , it will reinstall tf-nightly. 
how to change this dependency ？

**Comment by seanpmorgan** [comment]
Hi @SmileTM, we're working on our build to be more flexible for custom configurations. See https://github.com/tensorflow/addons/issues/770. I suspect this will be completed before the new year. 

If you would like to see if you can get it to work prior to those changes, you'll want to change the requirement in `build_deps`: https://github.com/tensorflow/addons/blob/master/build_deps/requirements.txt so that it requires tf2-gpu instead of the nightly. That way if it exists there will be no installation from `./configure.sh`. No promises that the CUDA build won't fail for CUDA 9.0, but in the near future it should work out of the box

**Comment by SmileTM** [comment]
> Hi @SmileTM, we're working on our build to be more flexible for custom configurations. See #770. I suspect this will be completed before the new year.
> 
> If you would like to see if you can get it to work prior to those changes, you'll want to change the requirement in `build_deps`: https://github.com/tensorflow/addons/blob/master/build_deps/requirements.txt so that it requires tf2-gpu instead of the nightly. That way if it exists there will be no installation from `./configure.sh`. No promises that the CUDA build won't fail for CUDA 9.0, but in the near future it should work out of the box

emm,I try to change https://github.com/tensorflow/addons/blob/master/build_deps/requirements.txt to
```
tensorflow==2.0.0
```
but when I pip install  addons ,it will search tensorflow to install. (I have installed tensorflow-gpu that was named 'tensorflow' not 'tensorflow-gpu')
```
(mk) wxy@sait:/disk1/lx/addons/artifacts$ pip install tensorflow_addons-0.7.0.dev0-cp37-cp37m-linux_x86_64.whl 
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Processing ./tensorflow_addons-0.7.0.dev0-cp37-cp37m-linux_x86_64.whl
Requirement already satisfied: six>=1.10.0 in /disk1/lx/conda/envs/mk/lib/python3.7/site-packages (from tensorflow-addons==0.7.0.dev0) (1.12.0)
Collecting tensorflow>=2.1.0rc1 (from tensorflow-addons==0.7.0.dev0)
  Downloading http://mirrors.aliyun.com/pypi/packages/06/08/1efc1a1e1da34f2b1444695be4b92a273d2cd2f92621321d87486fec0e92/tensorflow-2.1.0rc1-cp37-cp37m-manylinux2010_x86_64.whl (421.8MB)
```

**Comment by SmileTM** [comment]
> Hi @SmileTM, we're working on our build to be more flexible for custom configurations. See #770. I suspect this will be completed before the new year.
> 
> If you would like to see if you can get it to work prior to those changes, you'll want to change the requirement in `build_deps`: https://github.com/tensorflow/addons/blob/master/build_deps/requirements.txt so that it requires tf2-gpu instead of the nightly. That way if it exists there will be no installation from `./configure.sh`. No promises that the CUDA build won't fail for CUDA 9.0, but in the near future it should work out of the box

have a good news to you.
I have successed to bazel and install the addons in cuda 9.0 and cudnn 7.
You can refer
http://s-tm.cn/2019/12/19/tensorflow-addons/
