### ISSUE TITLE
tfa.text.crf.crf_log_likelihood produce log likelihood > 0 for sequences with length 1

### ISSUE THREAD

**Issue by Ghostvv** [tensorflow/addons#778]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `mac os`
- TensorFlow version and how it was installed (source or binary): `2.0` from pip
- TensorFlow-Addons version and how it was installed (source or binary): `0.6.0` from pip
- Python version: `3.7`
- Is GPU used? (yes/no): no

**Describe the bug**

If there an example in a batch, which true sequence length is 1, log-likelihood produced by `tfa.text.crf.crf_log_likelihood` can be positive for these examples.

**Comment by Ghostvv** [comment]
created a fix: https://github.com/tensorflow/addons/pull/779

**Comment by Squadrick** [comment]
@Ghostvv Thanks for the fix!
