### ISSUE TITLE
Build GPU custom Ops for windows

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#784]
Currently we only compile/use the CPU version of custom ops in Addons for windows. Users should still be able to leverage GPU ops from TF-Core but this is something we want to build/enable.

I don't think this is a huge lift since the gpu toolchain works on nix and windows, but needs some testing.

**Comment by allen108108** [comment]
So, we can't use tensorflow-addons in Win10 system  now ,right ?

**Comment by seanpmorgan** [comment]
> So, we can't use tensorflow-addons in Win10 system now ,right ?

You can compile from source. See the README. It will only support CPU addons ops (but thats the majority of them). 

Alternatively we'll have a 0.7 release in the very near future to pip install.

**Comment by allen108108** [comment]
Will you release the GPU version in future ?

**Comment by seanpmorgan** [comment]
Yes that is what this issue is here to track. 

Just to be clear, prior to this issue being completed the addons package will still utilize GPU for underlying TF ops (matmul, etc.). But there will not be GPU implementations for the custom CUDA kernels in this repository... though they'll have CPU fallback.

**Comment by allen108108** [comment]
Thanks for answering ~~~~

**Comment by seanpmorgan** [comment]
This has been unblocked:
https://github.com/tensorflow/custom-op/pull/43#event-2902430632

**Comment by seanpmorgan** [comment]
Given the recent news: https://developer.nvidia.com/cuda/wsl
Is this feature still requested from the community?

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
