### ISSUE TITLE
Investigate why rrelu_test is flaky

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#802]
Example log:
https://source.cloud.google.com/results/invocations/2490d700-0837-4468-916a-0306b1714d87/targets/tensorflow_addons%2Fubuntu%2Fgpu%2Fpy3%2Fpresubmit/log

**Comment by seanpmorgan** [comment]
cc @fsx950223 as code owner

**Comment by fsx950223** [comment]
It seems something has changed with the latest TensorFlow version and GPU kernel doesn't work anymore. The kernel needs to be refracted.
