### ISSUE TITLE
tf.keras.load_model throws error when trained using the tfa.losses.TripletSemiHardLoss

### ISSUE THREAD

**Issue by slala2121** [tensorflow/addons#809]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow version and how it was installed (source or binary): 2.0 -source
- TensorFlow-Addons version and how it was installed (source or binary): 0.6.0; 
- Python version: 3.6
- Is GPU used? (yes/no):yes

I get the following error when running the following command. I get this error when training the network with tfa.losses.TripletSemiHardLoss but do not get this error when training with tf.keras.losses.CategoricalCrossentropy().

Command:
loaded_model=tf.keras.models.load_model(filepath)

Error:
TypeError    
Traceback (most recent call last)
<ipython-input-33-dd68e3d40410> in <module>()
----> 1 loaded_model=tf.keras.models.load_model(filepath)

6 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/losses.py in from_config(cls, config)
    138         A `Loss` instance.
    139     """
--> 140     return cls(**config)
    141 
    142   def get_config(self):

TypeError: __init__() got an unexpected keyword argument 'reduction'

**Comment by seanpmorgan** [comment]
@slala2121 thanks for the bug report! @Squadrick has sent a fix!
