### ISSUE TITLE
Remove API generation from release process

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#856]
As part of our release process we currently generate the API docs on every release branch:
https://github.com/tensorflow/community/blob/master/sigs/addons/RELEASE.md
https://github.com/tensorflow/addons/blob/master/tools/docs/README.md

IIUC the tf-docs team pulls our repo and generates their own files for display on the website. I wanted to confirm that it would be okay for us to remove this.

@MarkDaoust @lamberta

**Comment by lamberta** [comment]
Mark says, "yes"
And just tell us when you want us to update the site.

**Comment by seanpmorgan** [comment]
Great! To clarify... does that mean we can remove all of the code in this directory?
https://github.com/tensorflow/addons/tree/master/tools/docs

Or do you leverage that code?

**Comment by lamberta** [comment]
Yeah, keep that. We still need to use your build_docs.py
