### ISSUE TITLE
Issue regarding Coverage Penalty implementation

### ISSUE THREAD

**Issue by ragnarlbrok** [tensorflow/addons#859]
I am confused regarding coverage penalty implementation in get_scores() function of BeamSearchDecoder in this part of code :

     # Apply coverage penalty to finished predictions.
    coverage_penalty *= tf.cast(finished, tf.float32)
    weighted_coverage_penalty = coverage_penalty * coverage_penalty_weight
    # Reshape from [batch_size, beam_width] to [batch_size, beam_width, 1]
    weighted_coverage_penalty = tf.expand_dims(weighted_coverage_penalty, 2)
    return scores + weighted_coverage_penalty

Why coverage penalty is only applied to finished beams? I am following https://arxiv.org/pdf/1609.08144.pdf paper for coverage penalty reference. Its aim is to reduce over/under translation problem. Shouldn't it be applied for each beam in consideration rather than applying it to only finished beams?

**Comment by seanpmorgan** [comment]
cc @qlzh727 @guillaumekln

**Comment by guillaumekln** [comment]
The paper is not very explicit about when to compute the penalty. In practice, computing the penalty on complete hypothesis should be the correct implementation.

**Comment by guillaumekln** [comment]
Feel free to reopen if you have additional concerns regarding the coverage penalty implementation.
