### ISSUE TITLE
ImageProjectiveTransform should be named ImageProjectiveTransformV2

### ISSUE THREAD

**Issue by andresusanopinto** [tensorflow/addons#86]
**Describe the bug**
- It looks like ImageProjectiveTransform is based on ImageProjectiveTransformV2 present in tf.contrib in TF-1.x.

**Describe the expected behavior**
- Op names should not colide between 1.x and 2.x environments or saved models won't be shareable across them.

**Comment by andresusanopinto** [comment]
Links to ops:

* [tf.contrib.image](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/image/ops/image_ops.cc#L110)
* [tensorflow_addons.image](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/custom_ops/image/cc/ops/image_ops.cc#L95)

Looking at code it really seems that the op "ImageProjectiveTransformV2" from tf.contrib.image was renamed to "ImageProjectiveTransform" (which was a name already taken by other op). I guess this was un-intentional or in an attempt to cleanup the names, but in reality it can break moving models across TF-1.x and TF-2.x.

**Comment by seanpmorgan** [comment]
Thanks @andresusanopinto. I think you are correct that this is a problem even though we don't support 1.x because of saved models.

@karmel @martinwicke Should we maintain all V2 op naming just to be safe?

**Comment by karmel** [comment]
Yes-- we continue to support v1 graphdef/ops in v2, so maintaining separate namespaces will help avoid collisions. Eventually, we will be able to prefix op names with appropriate namespaces (ie, tensorflow_addons:OP_NAME), but we don't do that yet.

**Comment by seanpmorgan** [comment]
Thanks! Adding help wanted, and this bug fix would require reviewing all Ops that we've moved over.

**Comment by jharmsen** [comment]
Looks like there are only three ops in addon so far.

Two match:
- AdjustHsvInYiq [[contrib](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/image/ops/distort_image_ops.cc) | [addon](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/custom_ops/image/cc/ops/distort_image_ops.cc)]
- SkipGramGenerateCandidates [[contrib](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/text/ops/skip_gram_ops.cc) | [addon](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/custom_ops/text/cc/ops/skip_gram_ops.cc)]

As noted, one has a name mismatch:
- ImageProjectiveTransformV2 [[contrib](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/image/ops/image_ops.cc#L110)] became ImageProjectiveTransform [[addon](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/custom_ops/image/cc/ops/image_ops.cc#L95)]

**Comment by jharmsen** [comment]
Going forward is the right thing to rename addon ImageProjectiveTransform to ImageProjectiveTransformV2?

**Comment by martinwicke** [comment]
I think for now, yes -- that'll make sure that people can use the existing
SavedModels, etc.

For the future, we need to figure out proper namespacing.

**Comment by karmel** [comment]
cc @tomerk
