### ISSUE TITLE
Update kokoro tests in order to drop Py2 support

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#863]
The current CI tests ran by kokoro come from these commands:
https://github.com/tensorflow/addons/pull/328#issue-293621981

After #862 merges the only test we'll need from kokoro is (Ubuntu GPU only):
```
bash tools/run_docker.sh -s linux -d gpu -c 'make gpu-unit-test'  # Ubuntu GPU Python3
```
Note: this drops the `-p` parameter which will be removed in #861. And will currently default to python3

**Comment by seanpmorgan** [comment]
@av8ramit would you be able to assist in removing all of the Kokoro tests except for Python3 GPU? 

The py3 GPU script will also need to be updated to match the command above (no `-p` parameter)

**Comment by av8ramit** [comment]
I have sent @karmel an internal change that will only keep the Python3 GPU build and remove the -p parameter.

**Comment by seanpmorgan** [comment]
Looks as though this has been completed. Thanks again!

**Comment by seanpmorgan** [comment]
Related: https://github.com/tensorflow/addons/issues/743
