### ISSUE TITLE
Behaviour change in deserialization since 0.6

### ISSUE THREAD

**Issue by RomainBrault** [tensorflow/addons#868]
**System information**
- OS Platform and Distribution (Ubuntu 19.04):
- TensorFlow version and how it was installed (pip==2.1.0):
- TensorFlow-Addons version and how it was installed (pip==0.7.0):
- Python version: 3.7
- Is GPU used? (yes):

**Describe the bug**

Registered activation cannot be retrieved using tf.keras.activations.get

**Code to reproduce the issue**

```python

import tensorflow as tf
import tensorflow_addons as tf

tf.keras.activations.get('lisht')
```

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-ca08aaadf661> in <module>
----> 1 tf.keras.activations.get('lisht')

~/miniconda3/envs/xxxxx/lib/python3.7/site-packages/tensorflow_core/python/keras/activations.py in get(identifier)
    443   if isinstance(identifier, six.string_types):
    444     identifier = str(identifier)
--> 445     return deserialize(identifier)
    446   elif callable(identifier):
    447     return identifier

~/miniconda3/envs/xxxxxlib/python3.7/site-packages/tensorflow_core/python/keras/activations.py in deserialize(name, custom_objects)
    405       module_objects=globals(),
    406       custom_objects=custom_objects,
--> 407       printable_module_name='activation function')
    408 
    409 

~/miniconda3/envs/xxxxx/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    320       obj = module_objects.get(object_name)
    321       if obj is None:
--> 322         raise ValueError('Unknown ' + printable_module_name + ':' + object_name)
    323     # Classes passed by name are instantiated with no args, functions are
    324     # returned as-is.

ValueError: Unknown activation function:lisht
```

**Other info / logs**

It was working under 0.6.0. Is this behaviour expected in the new version?

**Comment by RomainBrault** [comment]
Ok, I need to do

```python
tf.keras.activations.get('Addons>lisht')
```

Maybe this should be stated explicitly somewhere?

**Comment by WindQAQ** [comment]
This is due to #438. We could update the release note actually. @tensorflow/sig-addons-maintainers what do you think about this?

**Comment by seanpmorgan** [comment]
Agree this should be better explained in the release note. There is a bullet: `Keras subclasses now use the public registration decorator as package Addons`

But I think an example of that impact is important.

**Comment by WindQAQ** [comment]
I update one more bullet:
> The prefix of registration name is Addons>. For example, users should change the serialization from tf.keras.activations.get('gelu') to tf.keras.activations.get('Addons>gelu')

Feel free to reopen the issue if you get further questions. Thank you!
