### ISSUE TITLE
build against CUDA 10.0 fails - incorrect path to libcublas library

### ISSUE THREAD

**Issue by lebedov** [tensorflow/addons#877]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.3
- TensorFlow version and how it was installed (source or binary): binary (Anaconda package tensorflow-2.0.0-gpu_py37h768510d_0)
- TensorFlow-Addons version and how it was installed (source or binary): source (a1a1e4c)
- Python version: 3.7.6
- Is GPU used? (yes/no): yes

**Describe the bug**

Attempting to build against CUDA 10.0 (which is installed in `/usr/local/cuda`) by entering "10.0" when prompted for the desired CUDA version by `configure.sh` and modifying `requirements.txt` to contain `tensorflow>=2.0.0` results in the following exception when `bazel build build_pip_pkg` is run:

```
ERROR: Analysis of target '//:build_pip_pkg' failed; build aborted: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "/home/lebedov/tensorflow-addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 1047
                _create_local_cuda_repository(<1 more arguments>)
        File "/home/lebedov/tensorflow-addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 869, in _create_local_cuda_repository
                _find_libs(repository_ctx, <1 more arguments>)
        File "/home/lebedov/tensorflow-addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 568, in _find_libs
                _find_cuda_lib("cublas", <4 more arguments>)
        File "/home/lebedov/tensorflow-addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 529, in _find_cuda_lib
                find_lib(repository_ctx, <2 more arguments>)
        File "/home/lebedov/tensorflow-addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 507, in find_lib
                auto_configure_fail(<1 more arguments>)
        File "/home/lebedov/tensorflow-addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 261, in auto_configure_fail
                fail(<1 more arguments>)

Cuda Configuration Error: No library found under: /usr/local/cuda/lib64/libcublas.so.10
```

This is because CUDA 10.0 contains the lib symlinks `/usr/local/cuda/lib64/libcublas.so` and `/usr/local/cuda/lib64/libcublas.so.10.0`, but not `/usr/local/cuda/lib64/libcublas.so.10`. I'm specifically interested in using addons with tensorflow 2.0.0 because that is the latest version of the GPU-enabled packages provided by Anaconda as of today.
 
**Code to reproduce the issue**

See above.

**Other info / logs**

**Comment by seanpmorgan** [comment]
Hi @lebedov! Yes this is related to completing https://github.com/tensorflow/addons/issues/770

I'm about to take off on a vacation otherwise I'd say it could be done in the near term. Basically requires tweaking the bazel build a bit to support prior-to-10.1 & 10.1-forward. The necessary parts are actually in the git history of those files. E.g:
https://github.com/tensorflow/addons/commit/6fd4580281270d877c4b750222ff7d4a531eea85#diff-bb478b5f9059862fc4414c796ace6c64

Marking as help wanted.. but it will be accomplished sooner or later.

Does `addons-0.6.0` work for you (compatible with 10.0+TF2) or is it a new addition your interested in using?

**Comment by seanpmorgan** [comment]
There was a breaking change of using the public Keras serialization (came out after 2.0):
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/layers/gelu.py#L25

So you'll have issues using addons regardless of the build when using TF2.0. It's possible we could have (and still can) provide better backwards compatibility for that.

**Comment by lebedov** [comment]
@seanpmorgan I was able to build 0.6.0 against CUDA 10.0 with bazel 2.0.0 successfully, although I had to tweak `build_deps/toolchains/gpu/cuda_configure.bzl` to suppress the following exception:

```
ERROR: Analysis of target '//:build_pip_pkg' failed; build aborted: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "/home/lebedov/tensorflow-addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 1329
                _create_local_cuda_repository(<1 more arguments>)
        File "/home/lebedov/tensorflow-addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 1231, in _create_local_cuda_repository
                _host_compiler_includes(<2 more arguments>)
        File "/home/lebedov/tensorflow-addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 357, in _host_compiler_includes
                get_cxx_inc_directories(<2 more arguments>)
        File "/home/lebedov/tensorflow-addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 336, in get_cxx_inc_directories
                inc not in includes_cpp_set
argument of type 'depset' is not iterable. in operator only works on lists, tuples, dicts and strings.
```

I'm specifically interested in using the seq2seq code - as the seq2seq unit tests in 0.6.0 seem to pass with my custom build, I'm hoping that whatever remaining tf 2.0 compatibility issues still exist will not be a concern.

**Comment by seanpmorgan** [comment]
Great! Closing as this is a duplicate issue, but feel free to continue discussion if you run into issues.

**Comment by cecabert** [comment]
I add the exact same error while trying to build for older cuda version (i.e. 9.2). I solve the issue by replacing `cuda_config.cuda_major_version` to `cuda_config.cuda_version` on the lines `573, 580, 587, 594` in the `build_deps/toolchains/gpu/cuda_configure.bzl` file, because the cuda library are named <_libname_>.so.<_Major_>.<_Minor_> and not <_libname_>.so.<_Major_>.
