### ISSUE TITLE
Windows nightly is broken

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/addons#909]
Seems to be an upstream issue that GitHub deployed to the VMs yesterday.

https://github.com/numworks/setup-msys2/issues/26
https://github.com/actions/virtual-environments/issues/282

**Comment by gabrieldemarmiesse** [comment]
One solution could be to avoid using msys2 and use bash instead. It's possible to select it as the shell in github actions instead of cmd.

**Comment by WindQAQ** [comment]
For tracking, #910.

**Comment by eine** [comment]
FTR, MSYS2 is only required if you need to use `pacman`, which is not available in the bash (MINGW) included in `windows-latest`. If all you need is a shell, MSYS2 is not required, as @gabrieldemarmiesse said.

**Comment by WindQAQ** [comment]
> FTR, MSYS2 is only required if you need to use `pacman` to install additional packages, which is not available in the bash (MINGW) included in `windows-latest`. If all you need is a shell, MSYS2 is not required, as @gabrieldemarmiesse said.

Thanks for clarification!
