### ISSUE TITLE
[Feature] Add MultiHeadAttention Layer

### ISSUE THREAD

**Issue by cgarciae** [tensorflow/addons#951]
Currently `tf.keras.layers` doesn't have a `MultiHeadAttention` module which is a bit odd given the popularity Transformers have today and that Attention is All You Need and BERT came out of Google. Maybe this layer could be added to this repo initially at least and maybe migrate to the official in the future. 

I have an implementation based on the code in the BERT repo I could share which I tweaked a little bit to make it easier to use if you are open to it. Either way, it would be good for the community to have easy access to this layer.

**Comment by Squadrick** [comment]
@cgarciae Thanks for bringing this up, and it would great if you could create a PR with your implementation.

**Comment by cgarciae** [comment]
@Squadrick WIll do.

**Comment by bhack** [comment]
@cgarciae Just cause your are interested in the topic, take a look at https://github.com/Nandan91/ULSAM

**Comment by seanpmorgan** [comment]
This was merged. Closing but feel free to keep discussion going in this issue.
