### ISSUE TITLE
pip install downloads tensorflow 2.1.0 when I already have tensorflow-gpu 2.1.0

### ISSUE THREAD

**Issue by saravanabalagi** [tensorflow/addons#952]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS (from Docker image)
- TensorFlow version and how it was installed (source or binary): Binary (from Docker image)
- TensorFlow-Addons version and how it was installed (source or binary): Binary 0.7.1 (pip latest)
- Python version: 3.6.9 (from Docker image)
- Docker Image Tag: 2.1.0-gpu-py3 (from tensorflow/tensorflow dockerhub)
- Is GPU used? (yes/no): Yes

**Describe the bug**

`pip install tensorflow_addons` automatically downloads `tensorflow>=2.1.0`

**Code to reproduce the issue**

Download docker image from tensorflow/tensorflow with tag 2.1.0-gpu-py3
Install tensorflow_addons using pip
While installing tensorflow_addons, it download tensorflow

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**

```
+ pip install tensorflow_addons
Collecting tensorflow_addons
  Downloading tensorflow_addons-0.7.1-cp36-cp36m-manylinux2010_x86_64.whl (986 kB)
     |################################| 986 kB 11.2 MB/s
Collecting tensorflow>=2.1.0
  Downloading tensorflow-2.1.0-cp36-cp36m-manylinux2010_x86_64.whl (421.8 MB)
     |################################| 421.8 MB 92 kB/s
Requirement already satisfied: gast==0.2.2 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.1.0->tensorflow_addons) (0.2.2)
Requirement already satisfied: tensorboard<2.2.0,>=2.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.1.0->tensorflow_addons) (2.1.0)
Requirement already satisfied: keras-preprocessing>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow>=2.1.0->tensorflow_addons) (1.1.0)
```

After installation,

```
> pip list | grep tensor
tensorboard                       2.1.0
tensorflow                        2.1.0
tensorflow-addons                 0.7.1
tensorflow-estimator              2.1.0
tensorflow-gpu                    2.1.0
```

Note that I have both tensorflow and tensorflow-gpu after installation.

**Expected Behaviour**

tensorflow-addons get installed without installing tensorflow 2.1.0 (in presence of tensorflow-gpu 2.1.0)

**Comment by saravanabalagi** [comment]
Similar to #864 but that's with `tensorflow-cpu`. As a workaround I'm using
```
pip install --no-deps tensorflow_addons
```

**Comment by seanpmorgan** [comment]
Hi @saravanabalagi! Yes as you mentioned this is the same issue that is going on in #864. For the time being your workaround is the recommended way to install.

For the 0.8 release we will remove the hard dependency on `tensorflow`. Thanks for creating this to help future users with issues. I'm going to close for the time being but will try to update this issue once the fixed dependency is removed.

**Comment by seanpmorgan** [comment]
TFA Nightlies starting tomorrow will have no pip dependency. 0.8 release is upcoming and will also be dependency free
