### ISSUE TITLE
TimeStopping Callback fail in verbose mode

### ISSUE THREAD

**Issue by RomainBrault** [tensorflow/addons#964]
**System information**

OS Platform and Distribution (Ubuntu 19.04):
TensorFlow version and how it was installed (pip==2.1.0):
TensorFlow-Addons version and how it was installed (pip==0.7.0):
Python version: 3.7
Is GPU used? (yes):

**Describe the bug**

When the fit method stop before the timer, it raises with

```AttributeError: 'TimeStopping' object has no attribute 'stopped_epoch'```

**Code to reproduce the issue**

Use tqdm callback

**Other info / logs**

Proposed fix

```python
...

    def on_epoch_end(self, epoch, logs={}):
        self.stopped_epoch = epoch
        if time.time() >= self.stopping_time:
            self.model.stop_training = True

...

    def on_train_end(self, logs=None):
        if self.verbose > 0:
            formatted_time = datetime.timedelta(seconds=self.seconds)
            msg = "Stopping at epoch {} after training for {}".format(
                self.stopped_epoch + 1, formatted_time
            )
            print(msg)
...

```

**Comment by shun-lin** [comment]
Hi @RomainBrault thank you so much for catching the bug! I apologize I forgot to consider the obvious case where training stopped before proposed time, your proposed fix looks good to me (putting `self.stopped_epoch = epoch`) outside of `'if` statement in `on_epoch_end` method. If you have time, may you submit a simple PR for it? (If not I can do it) Thank you so much for your contribution!

**Comment by failure-to-thrive** [comment]
I would recommend some kind of flag to distinguish whether `on_train_end` was called due to the "timeout" or by any other reason.  @RomainBrault, it will fix your "cosmetic problem", too. If no one doesn't mind, I can get down to this.

**Comment by shun-lin** [comment]
> I would recommend some kind of flag to distinguish whether `on_train_end` was called due to the "timeout" or by any other reason. @RomainBrault, it will fix your "cosmetic problem", too. If no one doesn't mind, I can get down to this.

Hi @failure-to-thrive, great idea and I think it would be helpful! I think one thing to consider is to see what `EarlyStopping` Callback is doing in similar case (training finished regularly without `EarlyStopping` effect took place and `verbose` was set to `1`), so when we handle that case here it's similar. @failure-to-thrive thanks for your contribution in advance!

**Comment by failure-to-thrive** [comment]
Here it is. https://github.com/failure-to-thrive/addons/commit/bc99311646a92a1099021ea767c489e033fa61ed#diff-dbab0e9de0d8f25e76e13d3906e105a5
If it is OK I will PR.
`EarlyStopping` utilizes the same technique.

**Comment by shun-lin** [comment]
Looks good to me but just a small NIT, instead of setting `self.stop_epochs` to `None` set it to `0` and check if it's above 0 in `at_train_end`, so the implementation is more consistent w/ `EarlyStopping`, also may you also added `on_train_begin` and reset `self.stop_epochs` so it's re-usable? Thanks for your contribution!

**Comment by failure-to-thrive** [comment]
> Looks good to me but just a small NIT, instead of setting `self.stop_epochs` to `None` set it to `0` and check if it's above 0 in `at_train_end`, so the implementation is more consistent w/ `EarlyStopping`

Sorry, we may not do it. What if the first epoch (epoch == 0) turns out to be too long? In that case verbose output in the `at_train_end` will be missed. Possible the same issue in the `EarlyStopping`, by the way.

> also may you also added on_train_begin and reset self.stop_epochs so it's re-usable?

Sure. I just was trying to make it consistent with `EarlyStopping`.

**Comment by shun-lin** [comment]
@failure-to-thrive , you got a great point, in the current implementation, we always let an epoch finish, even if it goes over time (we check at the end of each epochs  instead of each batch, thus if the first epoch turns out to be too long we will still finish it and then stop). I think it's better this way than stopping in the middle of epoch. Therefore we can assume that the first epoch will finish (this isn't a problem for `EarlyStopping` because they are comparing metrics and some of them are aggregated at the end of epochs). What you think?

**Comment by failure-to-thrive** [comment]
> I think it's better this way than stopping in the middle of epoch.

Me, too. I suspect a model will be left in the some kind of inconsistent state.

> What you think?

My offer still stands. The only think that I would change is the allowing the object (`TimeStopping`) to be reused. However, it might come into the code inconsistency with other Callbacks. Moreover, what if Callbacks are not supposed to be reused in the first place? I'm not a project maintainer, I may not make such decisions. It's up to you.

**Comment by seanpmorgan** [comment]
https://github.com/tensorflow/addons/pull/967 has merged and fixed the bug I believe. Do we want to keep this open for @failure-to-thrive s implementation or close and start a new one?

**Comment by failure-to-thrive** [comment]
> #967 has merged and fixed the bug I believe. Do we want to keep this open for @failure-to-thrive s implementation or close and start a new one?

#967 is a quick workaround to avoid crashes. It does its job very well but now we should move forward to a comprehensive solution, because for example https://github.com/tensorflow/addons/pull/967#issuecomment-579628853. It's still #964, I think we should stay here.

**Comment by shun-lin** [comment]
@failure-to-thrive @seanpmorgan ya I think we should keep this one open for @failure-to-thrive's PR. @failure-to-thrive let me know if you have any more questions/confusions :)

**Comment by failure-to-thrive** [comment]
> @failure-to-thrive let me know if you have any more questions/confusions :)

They are here https://github.com/tensorflow/addons/issues/964#issuecomment-580596414.

But... Honestly, it's a not big deal that justify putting so much of our time and efforts into it. Let us just https://github.com/tensorflow/addons/issues/964#issuecomment-579914295. We can always get back to this issue anytime in the future.

**Comment by shun-lin** [comment]
@failure-to-thrive sounds good, thanks!

**Comment by shun-lin** [comment]
Closing this issue as @failure-to-thrive's PR has been merged, thanks!
