### ISSUE TITLE
Difficult to use tensorflow-addons with tf-nightly builds

### ISSUE THREAD

**Issue by ghop02** [tensorflow/addons#965]
It's a bit tricky to use the tf-nightly builds and have a dependency on tensorflow addons because of the pinned tensorflow version.  

Is there a way to have the setup.py file for the nightly builds be slightly more lenient as to the version? It's a bit tricky because tf-nightly is an entirely different package.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
- TensorFlow version and how it was installed (source or binary): tensorflow nightly (pip)
- TensorFlow-Addons version and how it was installed (source or binary): (0.7.1)
- Python version: 3.7

**Code to reproduce the issue**
```
pip install tf-nightly
pip install tfa-nightly (or tensorflow-addons)
# installs tensorflow 2.1.0 which downgrades gast
```

**Comment by seanpmorgan** [comment]
Hi @ghop02! Thanks for reporting. So we should have a soon incoming solution to this which is to remove the hard installation dependencies:
https://github.com/tensorflow/addons/issues/864
https://github.com/tensorflow/addons/issues/952

I plan to work on this later today when I have some time to rework the builds. If you need to unblock today you can `pip install tfa-nightly --no-deps`

**Comment by ghop02** [comment]
Great, figured there was something in the works!

And never knew about `--no-deps`, will probably abuse this now for many carefully constructed brittle python environments 😄

**Comment by seanpmorgan** [comment]
TFA Nightlies starting tomorrow will have no pip dependency. 0.8 release is upcoming and will also be dependency free
