### ISSUE TITLE
Cannot use AttentionWrapper in Graph Mode

### ISSUE THREAD

**Issue by Taggotty** [tensorflow/addons#970]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu
- TensorFlow version and how it was installed (source or binary): 2.0.0
- TensorFlow-Addons version and how it was installed (source or binary): 0.6.0
- Python version: 3.7.5
- Is GPU used? (yes/no): yes

**Describe the bug**

In graph mode the state of the attention wrapper cannot be updated. 

**Code to reproduce the issue**

I am having the same issue...I have built a minimum example and ralized the error only occured in graph mode.
```
import tensorflow as tf
import tensorflow_addons as tfa

sequence_length = (5, 5)

# embedding
vocab_size = 5
word_embedding = tf.keras.layers.Embedding(input_dim=5, output_dim=512)

# decoder
lstm_cell_1 = tf.keras.layers.LSTMCell(units=512)
lstm_cell_2 = tf.keras.layers.LSTMCell(units=512)

stacked_cell = tf.keras.layers.StackedRNNCells([lstm_cell_1, lstm_cell_2,])
zero_state = stacked_cell.get_initial_state(batch_size=2, dtype=tf.float32)

# attention
sampler = tfa.seq2seq.sampler.TrainingSampler()
projection_layer = tf.keras.layers.Dense(10)

attention_mechanism = tfa.seq2seq.LuongAttention(units=512)
wrapper = tfa.seq2seq.AttentionWrapper(stacked_cell, attention_mechanism, attention_layer_size=512, output_attention=False)

decoder = tfa.seq2seq.BasicDecoder(wrapper, sampler, output_layer=projection_layer, maximum_iterations=50)

# training

image_features = tf.random.uniform((2, 1024), dtype=tf.float32)
image_captions = tf.random.uniform((2, 5), 0, vocab_size, dtype=tf.int64) \
            * tf.constant([[1, 1, 1, 0, 0], [1, 1, 1, 1, 1]], dtype=tf.int64)

@tf.function
def train_step(features, captions):
    value, states = stacked_cell(features, states=zero_state)
    attention_mechanism.setup_memory(value)
    dec_init_state = wrapper.get_initial_state(batch_size=tf.constant(2, dtype=tf.int32), dtype=tf.float32)
    dec_init_state.clone(cell_state=states)

    emb_inp = word_embedding(captions)
    outputs, _, _ = decoder(emb_inp, initial_state=dec_init_state, sequence_length=sequence_length)
    return outputs.rnn_output


train_step(image_features, image_captions)
```

**Other info / logs**

  File "recurrent_test.py", line 43, in <module>
    train_step(image_features, image_captions)
  File "/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 503, in _call
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 408, in _initialize
    *args, **kwds))
  File "/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 905, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:

    recurrent_test.py:39 train_step  *
        outputs, _, _ = decoder(emb_inp, initial_state=dec_init_state, sequence_length=sequence_length)
    /lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py:847 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /lib/python3.7/site-packages/tensorflow_addons/seq2seq/decoder.py:162 call  *
        return dynamic_decode(
    /lib/python3.7/site-packages/tensorflow_addons/seq2seq/decoder.py:463 dynamic_decode  *
        res = tf.while_loop(
    /lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py:2478 while_loop_v2
        return_same_structure=True)
    /lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py:2675 while_loop
        back_prop=back_prop)
    /lib/python3.7/site-packages/tensorflow_core/python/ops/while_v2.py:234 while_loop
        len_orig_loop_vars], expand_composites=True))
    /lib/python3.7/site-packages/tensorflow_core/python/ops/while_v2.py:1068 _check_shapes_compat
        "specify a less-specific shape." % (input_t.name, shape, t.shape))

    ValueError: Input tensor 'AttentionWrapperZeroState/zeros_4:0' enters the loop with shape (2, 512), but has shape (2, 2) after one iteration. To allow the shape to vary across iterations, use the `shape_invariants` argument of tf.while_loop to specify a less-specific shape.

**Comment by seanpmorgan** [comment]
cc @qlzh727 @guillaumekln

**Comment by guillaumekln** [comment]
The value that you are passing to `attention_mechanism.setup_memory` is incorrect. As per the [documentation](https://www.tensorflow.org/addons/api_docs/python/tfa/seq2seq/LuongAttention#setup_memory), it should be a tensor of shape `[batch_size, max_time, ...]` while yours have shape `[batch_size, ...]`.

**Comment by seanpmorgan** [comment]
Closing. Please feel free to ask for a re-open if there is still confusion.
