### ISSUE TITLE
triplet loss tutorial colab broken?

### ISSUE THREAD

**Issue by shun-lin** [tensorflow/addons#983]
I got an error when going to triplet loss's tutorial on Tensorflow doc https://www.tensorflow.org/addons/tutorials/losses_triplet and click "Run in Google Colab". 

When I try to access the triplet loss's tutorial on github it looks like it cannot be loaded either
https://github.com/tensorflow/addons/blob/master/docs/tutorials/losses_triplet.ipynb

**Comment by seanpmorgan** [comment]
Good catch. Really have no idea how that could happen though.

**Comment by shun-lin** [comment]
fixed!
