### ISSUE TITLE
tfa.seq2seq decoder implementation problem

### ISSUE THREAD

**Issue by Om-Pandey** [tensorflow/addons#986]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version and how it was installed (source or binary): tf 2.1.0
- TensorFlow-Addons version and how it was installed (source or binary): tf_addons 0.7.1
- Python version: 3.6
- Is GPU used? (yes/no): no

**Describe the bug**
I do not understand how the decoder function is working as in what should be the input to the sequence_length. I did what I could decipher from the code. Here, embedding and embedding1 are embedding of two different languages in NMT and fr_vocab_size, en_vocab_size are the lengths of respective tokenizers.

**Code to reproduce the issue**
```
@tf.function
def train_step(source_seq, target_seq_in, target_seq_out):
    with tf.GradientTape() as tape:
        encoder_outputs, state_h, state_c = encoder(embedding(source_seq))
        encoder_state = [state_h, state_c]
        sampler = tfa.seq2seq.sampler.TrainingSampler()
        projection_layer = tf.keras.layers.Dense(fr_vocab_size)
        decoder = tfa.seq2seq.BasicDecoder(
            decoder_cell, sampler, output_layer=projection_layer)

        outputs,_,_= decoder(
            embedding1(target_seq_in),
            initial_state=encoder_state,
            sequence_length=[fr_vocab_size])
        logits = outputs.rnn_output
        loss = loss_func(target_seq_out, logits)

    variables = encoder.trainable_variables + decoder.trainable_variables
    gradients = tape.gradient(loss, variables)
    optimizer.apply_gradients(zip(gradients, variables))

    return loss

```
**Other info / logs**
ValueError: in converted code:

    <ipython-input-32-11e809516a8d>:12 train_step  *
        outputs,_,_= decoder(
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py:778 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_addons/seq2seq/decoder.py:162 call  *
        return dynamic_decode(
    /usr/local/lib/python3.6/dist-packages/tensorflow_addons/seq2seq/decoder.py:393 body  *
        (next_outputs, decoder_state, next_inputs,
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py:2478 while_loop_v2
        return_same_structure=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow_addons/seq2seq/basic_decoder.py:126 step  *
        cell_outputs = self.output_layer(cell_outputs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py:748 __call__
        self._maybe_build(inputs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py:2116 _maybe_build
        self.build(input_shapes)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/core.py:1113 build
        trainable=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py:446 add_weight
        caching_device=caching_device)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/tracking/base.py:744 _add_variable_with_custom_getter
        **kwargs_for_getter)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer_utils.py:142 make_variable
        shape=variable_shape if variable_shape else None)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/variables.py:258 __call__
        return cls._variable_v1_call(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/variables.py:219 _variable_v1_call
        shape=shape)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/variables.py:65 getter
        return captured_getter(captured_previous, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py:502 invalid_creator_scope
        "tf.function-decorated function tried to create "

    ValueError: tf.function-decorated function tried to create variables on non-first call.

**Comment by guillaumekln** [comment]
The error you reported is not related to `tfa.seq2seq` but to how `tf.function` should be used, see the [documentation](https://www.tensorflow.org/api_docs/python/tf/function). In particular, you should create stateful layers such as `tf.keras.layers.Dense` outside the `tf.function`.

**Comment by Om-Pandey** [comment]
@guillaumekln yeah .. I had actually declared it above the function.. 😅 .. I think .. It got in the way while I was debugging... This is the actual error:
```
InvalidArgumentError:  Trying to access element 76 in a list with 76 elements.
	 [[{{node basic_decoder/decoder/while/body/_10/cond/else/_619/TensorArrayV2Read/TensorListGetItem}}]] [Op:__inference_train_step_40940]
```
Why do you think this may be ?

**Comment by Om-Pandey** [comment]
Ohhhkkkk .. I got my mistake .. Thanks!
