### ISSUE TITLE
Custom Op Linux ABI Incompatibility: Undefined Symbol

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#987]
Creating this issue to consolidate the information. As seen in https://github.com/tensorflow/addons/issues/676 https://github.com/tensorflow/addons/issues/574

## Overview:
The TF C++ API for kernel implementations are not ABI stable. Because of this we compile our pip package to be manylinux2010 compatible with GCC 7.3.1. This means that TF-Addons custom ops will work on pip installed TF, but are not guaranteed to work with TF built from source or installed from conda

This should not affect our macOS and Windows versions.

## Temporary "fixes"
We implemented a lazy loading of custom-ops so majority of TFA functionality is not affected by this issue:
https://github.com/tensorflow/addons/pull/869

## Long term solution
[RFC 133](https://github.com/tensorflow/community/pull/133) is in the works to make a stable C ABI.

**Comment by whatdhack** [comment]
I am seeing the undefined symbol problem with a custom built TF 1.14 python whl.  What  bazel build option should I use beside  --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"  ? How do I specify compatibility with manylinux2010 compatible with GCC 7.3.1

**Comment by seanpmorgan** [comment]
> I am seeing the undefined symbol problem with a custom built TF 1.14 python whl. What bazel build option should I use beside --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" ? How do I specify compatibility with manylinux2010 and GCC 7.3.1

TensorFlow Addons only supports TF2.x. We have an issue for build from source compatibility but it would still only support TF2+ https://github.com/tensorflow/addons/issues/770

**Comment by whatdhack** [comment]
Addons are similar to CustomOps in 1.x , right ?  So has the same issue.
