### ISSUE TITLE
Complete black formatting

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#988]
We made the transition to utilize `black` for its strict standard and easy of use (while being able to remove a ton of formatting code and maintainer burden from TFA). 

To do this gracefully we excluded several modules which were under active development so as to minimize impact on active PRs. We need to remove those modules from the exclusion list as they become no longer worked on and format them appropriately.

Exclusion list:
https://github.com/tensorflow/addons/blob/master/pyproject.toml#L18-L67

**Comment by seanpmorgan** [comment]
@gabrieldemarmiesse could you please post a snippet to show how you checked which modules were under active development.

**Comment by gabrieldemarmiesse** [comment]
pip install pygithub

```python
from github import Github
g = Github('my_pretty_token')
repo = g.get_repo('tensorflow/addons')
list_files = set()
for pull in repo.get_pulls():
    for file in pull.get_files():
    list_files.add(file.filename)
print(list_files)
```

**Comment by seanpmorgan** [comment]
One last thing.. there remains some `pylint` and `yapf` comments in these files. Those should be removed as well as they no longer do anything.
