### ISSUE TITLE
Complete typing

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#989]
Since python2 support was dropped we've begun typing TFA. 

To do this gracefully we excluded several modules which were under active development so as to minimize impact on active PRs. We need to remove those modules from the exclusion list as they become no longer worked on and type them appropriately.

Exclusion list:
https://github.com/tensorflow/addons/blob/master/tools/ci_build/verify/check_typing_info.py#L27-L135

**Comment by seanpmorgan** [comment]
Big thank you to @autoih for many PRs working towards this.

**Comment by AakashKumarNain** [comment]
We need to include this in the `contribution` guidelines.

**Comment by gabrieldemarmiesse** [comment]
@AakashKumarNain  See https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#about-type-hints

**Comment by AakashKumarNain** [comment]
LGTM! Can we add a simple example as well? Like a class with the constructor signature only.

**Comment by gabrieldemarmiesse** [comment]
For more info about all this: 

I opened an issue in the tensorflow repository about the autograph bug:

https://github.com/tensorflow/tensorflow/issues/36462


List of pull requests linked to this issue:
#894 
#925 
#928 
#929 
#931 
#971
#972 
#975 
#978 
#981
#995
#999
#1007
#1002
#1015 
#1016 
#1019

**Comment by gabrieldemarmiesse** [comment]
Yay! It's finished! Big thanks to @autoih who worked extra hard on this!

If some people are interested, we want to do the same with autokeras! See the link just above.

**Comment by seanpmorgan** [comment]
Thanks so much for the great contributions @autoih
