### ISSUE TITLE
Refactor Sanity Check

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#991]
The term sanity check is a bit legacy from the TF core repo. In the past month we've done some major revamping our of repo and it's time to update this to align.

At the moment we break out flake8, black, and typing into separate CI tests:
https://github.com/tensorflow/addons/blob/master/.github/workflows/ci_test.yml#L60-L102

Personally I like this from a PR perspective because it limits the logs you need to read through to find your problem. I did want to discuss this though since it does make this list of test cases in PRs quite lengthy.

If we do keep this setup, I think it makes sense to break up the sanity check into its respective tests:
* C++ code format
* Bazel code format / no-build test
* Python check filename test

An alternative option would be to consolidate Lint tests under a single github action. For example we could add black and flake8 to https://github.com/tensorflow/addons/blob/master/tools/ci_build/code_format.sh

I think there is a number of ways to go about this so opening this issue to discuss and then we can implement.

**Comment by gabrieldemarmiesse** [comment]
For the CI, I believe that fast feedback is very important for the developer's experience. Black action takes  around 15s to run, flake8 too, the typing check takes 40s and I also agree with @seanpmorgan about logs clarity which is important for first contributors to addons.

I'd be in favor of a tool that we can run and do all the checks at once locally, but in the CI, those checks should stay separate to improve the time it takes to do a cycle of push/fix.

**Comment by gabrieldemarmiesse** [comment]
I've made 4 pull requests to extract the 4 checks from the sanity check. Once they are all merged, I'll work on the tool to run them locally (docker + git hook).

**Comment by gabrieldemarmiesse** [comment]
Can we completely assume that users have access to docker locally? It would make the pre-commit hook and local testing much easier to implement.

**Comment by seanpmorgan** [comment]
> Can we completely assume that users have access to docker locally? It would make the pre-commit hook and local testing much easier to implement.

Yes I think we can safely assume this for developers.

**Comment by gabrieldemarmiesse** [comment]
Ho yeah, fasten your seat belts it's going to awesome really fast!
