### ISSUE TITLE
tfa-nightly missing ensure_tf_install

### ISSUE THREAD

**Issue by ghop02** [tensorflow/addons#996]
```
> import tensorflow_addons
ModuleNotFoundError: No module named 'tensorflow_addons.utils.ensure_tf_install'
```
Getting this error when installing the latest version of tfa-nightly (`tfa-nightly-0.8.0.dev20200131`).

Looks like it was added yesterday. Not 100% sure how, but looks like `ensure_tf_install.py` wasn't included in the wheel?

**Comment by seanpmorgan** [comment]
@ghop02 Thank you very much for the report. PR submitted to fix

**Comment by ghop02** [comment]
Definitely, thanks for the quick response/fix!
